/* completion_provider.c generated by valac UNKNOWN, the Vala compiler
 * generated from completion_provider.vala, do not modify */

#include <glib-object.h>
#include <gtksourceview/gtksource.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <vala.h>
#include <valagee.h>
#include <gtk/gtk.h>
#include <gdk-pixbuf/gdk-pixbuf.h>

#define VALA_DEVELOP_TYPE_VALA_COMPLETION_PROVIDER (vala_develop_vala_completion_provider_get_type ())
#define VALA_DEVELOP_VALA_COMPLETION_PROVIDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_VALA_COMPLETION_PROVIDER, valaDevelopValaCompletionProvider))
#define VALA_DEVELOP_VALA_COMPLETION_PROVIDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_VALA_COMPLETION_PROVIDER, valaDevelopValaCompletionProviderClass))
#define VALA_DEVELOP_IS_VALA_COMPLETION_PROVIDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_VALA_COMPLETION_PROVIDER))
#define VALA_DEVELOP_IS_VALA_COMPLETION_PROVIDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_VALA_COMPLETION_PROVIDER))
#define VALA_DEVELOP_VALA_COMPLETION_PROVIDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_VALA_COMPLETION_PROVIDER, valaDevelopValaCompletionProviderClass))

typedef struct _valaDevelopValaCompletionProvider valaDevelopValaCompletionProvider;
typedef struct _valaDevelopValaCompletionProviderClass valaDevelopValaCompletionProviderClass;
typedef struct _valaDevelopValaCompletionProviderPrivate valaDevelopValaCompletionProviderPrivate;

#define VALA_DEVELOP_TYPE_SYMBOL_FINDER (vala_develop_symbol_finder_get_type ())
#define VALA_DEVELOP_SYMBOL_FINDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_SYMBOL_FINDER, valaDevelopSymbolFinder))
#define VALA_DEVELOP_SYMBOL_FINDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_SYMBOL_FINDER, valaDevelopSymbolFinderClass))
#define VALA_DEVELOP_IS_SYMBOL_FINDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_SYMBOL_FINDER))
#define VALA_DEVELOP_IS_SYMBOL_FINDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_SYMBOL_FINDER))
#define VALA_DEVELOP_SYMBOL_FINDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_SYMBOL_FINDER, valaDevelopSymbolFinderClass))

typedef struct _valaDevelopSymbolFinder valaDevelopSymbolFinder;
typedef struct _valaDevelopSymbolFinderClass valaDevelopSymbolFinderClass;
enum  {
	VALA_DEVELOP_VALA_COMPLETION_PROVIDER_0_PROPERTY,
	VALA_DEVELOP_VALA_COMPLETION_PROVIDER_NUM_PROPERTIES
};
static GParamSpec* vala_develop_vala_completion_provider_properties[VALA_DEVELOP_VALA_COMPLETION_PROVIDER_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _vala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (vala_code_node_unref (var), NULL)))
#define _vala_iterable_unref0(var) ((var == NULL) ? NULL : (var = (vala_iterable_unref (var), NULL)))
#define _vala_map_unref0(var) ((var == NULL) ? NULL : (var = (vala_map_unref (var), NULL)))
#define _vala_iterator_unref0(var) ((var == NULL) ? NULL : (var = (vala_iterator_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _valaDevelopSymbolFinderPrivate valaDevelopSymbolFinderPrivate;

struct _valaDevelopValaCompletionProvider {
	GObject parent_instance;
	valaDevelopValaCompletionProviderPrivate * priv;
};

struct _valaDevelopValaCompletionProviderClass {
	GObjectClass parent_class;
};

struct _valaDevelopValaCompletionProviderPrivate {
	valaDevelopSymbolFinder* _symbol_finder;
	gchar* _fullpath;
	ValaSymbol* current_symbol;
	GList* proposals;
	gint c;
};

struct _valaDevelopSymbolFinder {
	GObject parent_instance;
	valaDevelopSymbolFinderPrivate * priv;
	ValaHashSet* _sources;
	ValaHashSet* _packages;
	gboolean need_update;
};

struct _valaDevelopSymbolFinderClass {
	GObjectClass parent_class;
};

static gint valaDevelopValaCompletionProvider_private_offset;
static gpointer vala_develop_vala_completion_provider_parent_class = NULL;
static GtkSourceCompletionProviderIface * vala_develop_vala_completion_provider_gtk_source_completion_provider_parent_iface = NULL;

GType vala_develop_vala_completion_provider_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (valaDevelopValaCompletionProvider, g_object_unref)
GType vala_develop_symbol_finder_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (valaDevelopSymbolFinder, g_object_unref)
static void _g_object_unref0_ (gpointer var);
static inline void _g_list_free__g_object_unref0_ (GList* self);
valaDevelopValaCompletionProvider* vala_develop_vala_completion_provider_new (const gchar* fullpath,
                                                                              valaDevelopSymbolFinder* symbol_finder);
valaDevelopValaCompletionProvider* vala_develop_vala_completion_provider_construct (GType object_type,
                                                                                    const gchar* fullpath,
                                                                                    valaDevelopSymbolFinder* symbol_finder);
static void vala_develop_vala_completion_provider_real_populate (GtkSourceCompletionProvider* base,
                                                          GtkSourceCompletionContext* context);
static void ___lambda54_ (valaDevelopValaCompletionProvider* self,
                   GtkSourceCompletionItem* element);
static void ____lambda54__gfunc (gconstpointer data,
                          gpointer self);
static gboolean vala_develop_vala_completion_provider_real_match (GtkSourceCompletionProvider* base,
                                                           GtkSourceCompletionContext* context);
gchar* vala_develop_globals_get_word_at_iter (GtkSourceBuffer* buffer,
                                              GtkTextIter* iter);
void vala_develop_symbol_finder_Update (valaDevelopSymbolFinder* self,
                                        const gchar* file,
                                        const gchar* content);
gchar* vala_develop_globals_get_text_from_buffer (GtkTextBuffer* buffer,
                                                  gboolean include_hidden_chars);
ValaSymbol* vala_develop_symbol_finder_find_symbol_by_name (valaDevelopSymbolFinder* self,
                                                            const gchar* word,
                                                            const gchar* file,
                                                            const gchar* content,
                                                            gint line,
                                                            gint col);
static gint vala_develop_vala_completion_provider_real_get_priority (GtkSourceCompletionProvider* base);
static GdkPixbuf* vala_develop_vala_completion_provider_real_get_icon (GtkSourceCompletionProvider* base);
static gchar* vala_develop_vala_completion_provider_real_get_name (GtkSourceCompletionProvider* base);
static void vala_develop_vala_completion_provider_finalize (GObject * obj);

static inline gpointer
vala_develop_vala_completion_provider_get_instance_private (valaDevelopValaCompletionProvider* self)
{
	return G_STRUCT_MEMBER_P (self, valaDevelopValaCompletionProvider_private_offset);
}

static void
_g_object_unref0_ (gpointer var)
{
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
}

static inline void
_g_list_free__g_object_unref0_ (GList* self)
{
	g_list_free_full (self, (GDestroyNotify) _g_object_unref0_);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

valaDevelopValaCompletionProvider*
vala_develop_vala_completion_provider_construct (GType object_type,
                                                 const gchar* fullpath,
                                                 valaDevelopSymbolFinder* symbol_finder)
{
	valaDevelopValaCompletionProvider * self = NULL;
	valaDevelopSymbolFinder* _tmp0_;
	gchar* _tmp1_;
	g_return_val_if_fail (fullpath != NULL, NULL);
	g_return_val_if_fail (symbol_finder != NULL, NULL);
	self = (valaDevelopValaCompletionProvider*) g_object_new (object_type, NULL);
	_tmp0_ = _g_object_ref0 (symbol_finder);
	_g_object_unref0 (self->priv->_symbol_finder);
	self->priv->_symbol_finder = _tmp0_;
	_tmp1_ = g_strdup (fullpath);
	_g_free0 (self->priv->_fullpath);
	self->priv->_fullpath = _tmp1_;
	(self->priv->proposals == NULL) ? NULL : (self->priv->proposals = (_g_list_free__g_object_unref0_ (self->priv->proposals), NULL));
	self->priv->proposals = NULL;
	return self;
}

valaDevelopValaCompletionProvider*
vala_develop_vala_completion_provider_new (const gchar* fullpath,
                                           valaDevelopSymbolFinder* symbol_finder)
{
	return vala_develop_vala_completion_provider_construct (VALA_DEVELOP_TYPE_VALA_COMPLETION_PROVIDER, fullpath, symbol_finder);
}

static void
___lambda54_ (valaDevelopValaCompletionProvider* self,
              GtkSourceCompletionItem* element)
{
	g_return_if_fail (element != NULL);
	self->priv->proposals = g_list_remove (self->priv->proposals, element);
}

static void
____lambda54__gfunc (gconstpointer data,
                     gpointer self)
{
	___lambda54_ ((valaDevelopValaCompletionProvider*) self, (GtkSourceCompletionItem*) data);
}

static gpointer
_vala_code_node_ref0 (gpointer self)
{
	return self ? vala_code_node_ref (self) : NULL;
}

static void
vala_develop_vala_completion_provider_real_populate (GtkSourceCompletionProvider* base,
                                                     GtkSourceCompletionContext* context)
{
	valaDevelopValaCompletionProvider * self;
	ValaSymbol* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	ValaSymbol* _tmp3_;
	GList* _tmp77_;
	self = (valaDevelopValaCompletionProvider*) base;
	g_return_if_fail (context != NULL);
	_tmp0_ = self->priv->current_symbol;
	_tmp1_ = vala_code_node_get_type_name ((ValaCodeNode*) _tmp0_);
	_tmp2_ = _tmp1_;
	g_print ("popuate %s\n", _tmp2_);
	_tmp3_ = self->priv->current_symbol;
	if (_tmp3_ != NULL) {
		GList* _tmp4_;
		ValaTypeSymbol* type_symbol = NULL;
		ValaSymbol* _tmp5_;
		_tmp4_ = self->priv->proposals;
		g_list_foreach (_tmp4_, ____lambda54__gfunc, self);
		type_symbol = NULL;
		_tmp5_ = self->priv->current_symbol;
		if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp5_, VALA_TYPE_VARIABLE)) {
			ValaSymbol* _tmp6_;
			ValaDataType* _tmp7_;
			ValaDataType* _tmp8_;
			ValaTypeSymbol* _tmp9_;
			ValaTypeSymbol* _tmp10_;
			ValaTypeSymbol* _tmp11_;
			_tmp6_ = self->priv->current_symbol;
			_tmp7_ = vala_variable_get_variable_type (G_TYPE_CHECK_INSTANCE_TYPE (_tmp6_, VALA_TYPE_VARIABLE) ? ((ValaVariable*) _tmp6_) : NULL);
			_tmp8_ = _tmp7_;
			_tmp9_ = vala_data_type_get_data_type (_tmp8_);
			_tmp10_ = _tmp9_;
			_tmp11_ = _vala_code_node_ref0 (_tmp10_);
			_vala_code_node_unref0 (type_symbol);
			type_symbol = _tmp11_;
		} else {
			ValaSymbol* _tmp12_;
			_tmp12_ = self->priv->current_symbol;
			if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp12_, VALA_TYPE_PROPERTY)) {
				ValaSymbol* _tmp13_;
				ValaDataType* _tmp14_;
				ValaDataType* _tmp15_;
				ValaTypeSymbol* _tmp16_;
				ValaTypeSymbol* _tmp17_;
				ValaTypeSymbol* _tmp18_;
				_tmp13_ = self->priv->current_symbol;
				_tmp14_ = vala_property_get_property_type (G_TYPE_CHECK_INSTANCE_TYPE (_tmp13_, VALA_TYPE_PROPERTY) ? ((ValaProperty*) _tmp13_) : NULL);
				_tmp15_ = _tmp14_;
				_tmp16_ = vala_data_type_get_data_type (_tmp15_);
				_tmp17_ = _tmp16_;
				_tmp18_ = _vala_code_node_ref0 (_tmp17_);
				_vala_code_node_unref0 (type_symbol);
				type_symbol = _tmp18_;
			} else {
				ValaSymbol* _tmp19_;
				_tmp19_ = self->priv->current_symbol;
				if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp19_, VALA_TYPE_CALLABLE)) {
					ValaSymbol* _tmp20_;
					ValaDataType* _tmp21_;
					ValaDataType* _tmp22_;
					ValaTypeSymbol* _tmp23_;
					ValaTypeSymbol* _tmp24_;
					ValaTypeSymbol* _tmp25_;
					_tmp20_ = self->priv->current_symbol;
					_tmp21_ = vala_callable_get_return_type (G_TYPE_CHECK_INSTANCE_TYPE (_tmp20_, VALA_TYPE_CALLABLE) ? ((ValaCallable*) _tmp20_) : NULL);
					_tmp22_ = _tmp21_;
					_tmp23_ = vala_data_type_get_data_type (_tmp22_);
					_tmp24_ = _tmp23_;
					_tmp25_ = _vala_code_node_ref0 (_tmp24_);
					_vala_code_node_unref0 (type_symbol);
					type_symbol = _tmp25_;
				} else {
					ValaSymbol* _tmp26_;
					_tmp26_ = self->priv->current_symbol;
					if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp26_, VALA_TYPE_OBJECT_TYPE_SYMBOL)) {
						ValaSymbol* _tmp27_;
						ValaObjectType* _tmp28_;
						ValaObjectType* _tmp29_;
						ValaTypeSymbol* _tmp30_;
						ValaTypeSymbol* _tmp31_;
						ValaTypeSymbol* _tmp32_;
						_tmp27_ = self->priv->current_symbol;
						_tmp28_ = vala_object_type_symbol_get_this_type (G_TYPE_CHECK_INSTANCE_TYPE (_tmp27_, VALA_TYPE_OBJECT_TYPE_SYMBOL) ? ((ValaObjectTypeSymbol*) _tmp27_) : NULL);
						_tmp29_ = _tmp28_;
						_tmp30_ = vala_data_type_get_data_type ((ValaDataType*) _tmp29_);
						_tmp31_ = _tmp30_;
						_tmp32_ = _vala_code_node_ref0 (_tmp31_);
						_vala_code_node_unref0 (type_symbol);
						type_symbol = _tmp32_;
						_vala_code_node_unref0 (_tmp29_);
					}
				}
			}
		}
		while (TRUE) {
			ValaTypeSymbol* _tmp33_;
			ValaTypeSymbol* _tmp68_;
			_tmp33_ = type_symbol;
			if (!(_tmp33_ != NULL)) {
				break;
			}
			{
				ValaIterator* _sym_it = NULL;
				ValaTypeSymbol* _tmp34_;
				ValaScope* _tmp35_;
				ValaScope* _tmp36_;
				ValaMap* _tmp37_;
				ValaMap* _tmp38_;
				ValaCollection* _tmp39_;
				ValaCollection* _tmp40_;
				ValaIterator* _tmp41_;
				ValaIterator* _tmp42_;
				_tmp34_ = type_symbol;
				_tmp35_ = vala_symbol_get_scope ((ValaSymbol*) _tmp34_);
				_tmp36_ = _tmp35_;
				_tmp37_ = vala_scope_get_symbol_table (_tmp36_);
				_tmp38_ = _tmp37_;
				_tmp39_ = vala_map_get_values (_tmp38_);
				_tmp40_ = _tmp39_;
				_tmp41_ = vala_iterable_iterator ((ValaIterable*) _tmp40_);
				_tmp42_ = _tmp41_;
				_vala_iterable_unref0 (_tmp40_);
				_vala_map_unref0 (_tmp38_);
				_sym_it = _tmp42_;
				while (TRUE) {
					ValaIterator* _tmp43_;
					ValaSymbol* sym = NULL;
					ValaIterator* _tmp44_;
					gpointer _tmp45_;
					gboolean _tmp46_ = FALSE;
					ValaSymbol* _tmp47_;
					ValaSymbolAccessibility _tmp48_;
					ValaSymbolAccessibility _tmp49_;
					_tmp43_ = _sym_it;
					if (!vala_iterator_next (_tmp43_)) {
						break;
					}
					_tmp44_ = _sym_it;
					_tmp45_ = vala_iterator_get (_tmp44_);
					sym = (ValaSymbol*) _tmp45_;
					_tmp47_ = sym;
					_tmp48_ = vala_symbol_get_access (_tmp47_);
					_tmp49_ = _tmp48_;
					if (_tmp49_ != VALA_SYMBOL_ACCESSIBILITY_PRIVATE) {
						ValaSymbol* _tmp50_;
						const gchar* _tmp51_;
						const gchar* _tmp52_;
						_tmp50_ = sym;
						_tmp51_ = vala_symbol_get_name (_tmp50_);
						_tmp52_ = _tmp51_;
						_tmp46_ = g_strcmp0 (_tmp52_, ".new") != 0;
					} else {
						_tmp46_ = FALSE;
					}
					if (_tmp46_) {
						GtkSourceCompletionItem* item = NULL;
						GtkSourceCompletionItem* _tmp53_;
						GtkSourceCompletionItem* _tmp54_;
						ValaSymbol* _tmp55_;
						const gchar* _tmp56_;
						const gchar* _tmp57_;
						GtkSourceCompletionItem* _tmp58_;
						ValaSymbol* _tmp59_;
						const gchar* _tmp60_;
						const gchar* _tmp61_;
						GtkSourceCompletionItem* _tmp62_;
						ValaSymbol* _tmp63_;
						gchar* _tmp64_;
						gchar* _tmp65_;
						GtkSourceCompletionItem* _tmp66_;
						GtkSourceCompletionItem* _tmp67_;
						_tmp53_ = gtk_source_completion_item_new2 ();
						item = _tmp53_;
						_tmp54_ = item;
						_tmp55_ = sym;
						_tmp56_ = vala_symbol_get_name (_tmp55_);
						_tmp57_ = _tmp56_;
						gtk_source_completion_item_set_label (_tmp54_, _tmp57_);
						_tmp58_ = item;
						_tmp59_ = sym;
						_tmp60_ = vala_symbol_get_name (_tmp59_);
						_tmp61_ = _tmp60_;
						gtk_source_completion_item_set_text (_tmp58_, _tmp61_);
						_tmp62_ = item;
						_tmp63_ = sym;
						_tmp64_ = vala_code_node_to_string ((ValaCodeNode*) _tmp63_);
						_tmp65_ = _tmp64_;
						gtk_source_completion_item_set_info (_tmp62_, _tmp65_);
						_g_free0 (_tmp65_);
						_tmp66_ = item;
						_tmp67_ = _g_object_ref0 (_tmp66_);
						self->priv->proposals = g_list_append (self->priv->proposals, _tmp67_);
						_g_object_unref0 (item);
					}
					_vala_code_node_unref0 (sym);
				}
				_vala_iterator_unref0 (_sym_it);
			}
			_tmp68_ = type_symbol;
			if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp68_, VALA_TYPE_CLASS)) {
				ValaTypeSymbol* _tmp69_;
				ValaClass* _tmp70_;
				ValaClass* _tmp71_;
				ValaObjectType* _tmp72_;
				ValaObjectType* _tmp73_;
				ValaTypeSymbol* _tmp74_;
				ValaTypeSymbol* _tmp75_;
				ValaTypeSymbol* _tmp76_;
				_tmp69_ = type_symbol;
				_tmp70_ = vala_class_get_base_class (G_TYPE_CHECK_INSTANCE_TYPE (_tmp69_, VALA_TYPE_CLASS) ? ((ValaClass*) _tmp69_) : NULL);
				_tmp71_ = _tmp70_;
				_tmp72_ = vala_object_type_symbol_get_this_type ((ValaObjectTypeSymbol*) _tmp71_);
				_tmp73_ = _tmp72_;
				_tmp74_ = vala_data_type_get_data_type ((ValaDataType*) _tmp73_);
				_tmp75_ = _tmp74_;
				_tmp76_ = _vala_code_node_ref0 (_tmp75_);
				_vala_code_node_unref0 (type_symbol);
				type_symbol = _tmp76_;
				_vala_code_node_unref0 (_tmp73_);
			} else {
				_vala_code_node_unref0 (type_symbol);
				type_symbol = NULL;
			}
		}
		_vala_code_node_unref0 (type_symbol);
	}
	_tmp77_ = self->priv->proposals;
	gtk_source_completion_context_add_proposals (context, (GtkSourceCompletionProvider*) self, _tmp77_, TRUE);
}

static gchar*
g_unichar_to_string (gunichar self)
{
	gchar* result = NULL;
	gchar* str = NULL;
	gchar* _tmp0_;
	const gchar* _tmp1_;
	_tmp0_ = g_new0 (gchar, 7);
	str = (gchar*) _tmp0_;
	_tmp1_ = str;
	g_unichar_to_utf8 (self, _tmp1_);
	result = str;
	return result;
}

static gchar*
string_strip (const gchar* self)
{
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_;
	const gchar* _tmp1_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	_tmp1_ = _result_;
	g_strstrip (_tmp1_);
	result = _result_;
	return result;
}

static gboolean
vala_develop_vala_completion_provider_real_match (GtkSourceCompletionProvider* base,
                                                  GtkSourceCompletionContext* context)
{
	valaDevelopValaCompletionProvider * self;
	gboolean result = FALSE;
	GtkTextIter currentIter = {0};
	GtkTextIter* _tmp0_;
	GtkTextIter* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gboolean _tmp4_;
	GError* _inner_error0_ = NULL;
	self = (valaDevelopValaCompletionProvider*) base;
	g_return_val_if_fail (context != NULL, FALSE);
	result = FALSE;
	return result;
	self->priv->c = 0;
	g_object_get (context, "iter", &_tmp0_, NULL);
	_tmp1_ = _tmp0_;
	currentIter = *_tmp1_;
	gtk_text_iter_backward_char (&currentIter);
	_tmp2_ = g_unichar_to_string (gtk_text_iter_get_char (&currentIter));
	_tmp3_ = _tmp2_;
	_tmp4_ = g_strcmp0 (_tmp3_, ".") == 0;
	_g_free0 (_tmp3_);
	if (_tmp4_) {
		gchar* word = NULL;
		gchar* _tmp5_;
		const gchar* _tmp11_;
		gchar* _tmp12_;
		gchar* _tmp13_;
		gboolean _tmp14_;
		_tmp5_ = g_strdup ("");
		word = _tmp5_;
		{
			gchar* _tmp6_;
			gchar* _tmp7_;
			GtkTextBuffer* _tmp8_;
			gchar* _tmp9_;
			_tmp6_ = g_unichar_to_string (gtk_text_iter_get_char (&currentIter));
			_tmp7_ = _tmp6_;
			g_print ("[ITER]%s %d,%d\n", _tmp7_, gtk_text_iter_get_line (&currentIter), gtk_text_iter_get_line_offset (&currentIter));
			_g_free0 (_tmp7_);
			gtk_text_iter_backward_char (&currentIter);
			_tmp8_ = gtk_text_iter_get_buffer (&currentIter);
			_tmp9_ = vala_develop_globals_get_word_at_iter (G_TYPE_CHECK_INSTANCE_CAST (_tmp8_, gtk_source_buffer_get_type (), GtkSourceBuffer), &currentIter);
			_g_free0 (word);
			word = _tmp9_;
		}
		goto __finally24;
		__catch24_g_error:
		{
			GError* e = NULL;
			e = _inner_error0_;
			_inner_error0_ = NULL;
			result = FALSE;
			_g_error_free0 (e);
			_g_free0 (word);
			return result;
		}
		__finally24:
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			gboolean _tmp10_ = FALSE;
			_g_free0 (word);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return _tmp10_;
		}
		_tmp11_ = word;
		_tmp12_ = string_strip (_tmp11_);
		_tmp13_ = _tmp12_;
		_tmp14_ = g_strcmp0 (_tmp13_, "") == 0;
		_g_free0 (_tmp13_);
		if (_tmp14_) {
			result = FALSE;
			_g_free0 (word);
			return result;
		}
		{
			GtkSourceSearchSettings* searchSettings = NULL;
			GtkSourceSearchSettings* _tmp15_;
			GtkSourceSearchSettings* _tmp16_;
			GtkSourceSearchSettings* _tmp17_;
			const gchar* _tmp18_;
			GtkSourceSearchContext* searchContext = NULL;
			GtkTextIter* _tmp19_;
			GtkTextIter* _tmp20_;
			GtkTextBuffer* _tmp21_;
			GtkSourceSearchSettings* _tmp22_;
			GtkSourceSearchContext* _tmp23_;
			GtkSourceSearchContext* _tmp24_;
			GtkTextIter matchStart = {0};
			GtkTextIter matchEnd = {0};
			gboolean wrapped = FALSE;
			GtkTextIter iter = {0};
			GtkTextIter* _tmp25_;
			GtkTextIter* _tmp26_;
			const gchar* _tmp27_;
			gint _tmp28_;
			gint _tmp29_;
			GtkSourceSearchContext* _tmp30_;
			GtkTextIter _tmp31_;
			GtkTextIter _tmp32_ = {0};
			GtkTextIter _tmp33_ = {0};
			gboolean _tmp34_ = FALSE;
			gboolean _tmp35_;
			_tmp15_ = gtk_source_search_settings_new ();
			searchSettings = _tmp15_;
			_tmp16_ = searchSettings;
			gtk_source_search_settings_set_wrap_around (_tmp16_, FALSE);
			_tmp17_ = searchSettings;
			_tmp18_ = word;
			gtk_source_search_settings_set_search_text (_tmp17_, _tmp18_);
			g_object_get (context, "iter", &_tmp19_, NULL);
			_tmp20_ = _tmp19_;
			_tmp21_ = gtk_text_iter_get_buffer (_tmp20_);
			_tmp22_ = searchSettings;
			_tmp23_ = gtk_source_search_context_new (G_TYPE_CHECK_INSTANCE_CAST (_tmp21_, gtk_source_buffer_get_type (), GtkSourceBuffer), _tmp22_);
			searchContext = _tmp23_;
			_tmp24_ = searchContext;
			gtk_source_search_context_set_highlight (_tmp24_, FALSE);
			g_object_get (context, "iter", &_tmp25_, NULL);
			_tmp26_ = _tmp25_;
			iter = *_tmp26_;
			_tmp27_ = word;
			_tmp28_ = strlen (_tmp27_);
			_tmp29_ = _tmp28_;
			gtk_text_iter_backward_chars (&iter, _tmp29_);
			_tmp30_ = searchContext;
			_tmp31_ = iter;
			_tmp35_ = gtk_source_search_context_backward2 (_tmp30_, &_tmp31_, &_tmp32_, &_tmp33_, &_tmp34_);
			matchStart = _tmp32_;
			matchEnd = _tmp33_;
			wrapped = _tmp34_;
			if (_tmp35_) {
				valaDevelopSymbolFinder* _tmp36_;
				valaDevelopSymbolFinder* _tmp42_;
				const gchar* _tmp43_;
				const gchar* _tmp44_;
				GtkTextBuffer* _tmp45_;
				gchar* _tmp46_;
				gchar* _tmp47_;
				ValaSymbol* _tmp48_;
				ValaSymbol* _tmp49_;
				_tmp36_ = self->priv->_symbol_finder;
				if (_tmp36_->need_update) {
					valaDevelopSymbolFinder* _tmp37_;
					const gchar* _tmp38_;
					GtkTextBuffer* _tmp39_;
					gchar* _tmp40_;
					gchar* _tmp41_;
					_tmp37_ = self->priv->_symbol_finder;
					_tmp38_ = self->priv->_fullpath;
					_tmp39_ = gtk_text_iter_get_buffer (&matchStart);
					_tmp40_ = vala_develop_globals_get_text_from_buffer (_tmp39_, TRUE);
					_tmp41_ = _tmp40_;
					vala_develop_symbol_finder_Update (_tmp37_, _tmp38_, _tmp41_);
					_g_free0 (_tmp41_);
				}
				_tmp42_ = self->priv->_symbol_finder;
				_tmp43_ = word;
				_tmp44_ = self->priv->_fullpath;
				_tmp45_ = gtk_text_iter_get_buffer (&matchStart);
				_tmp46_ = vala_develop_globals_get_text_from_buffer (_tmp45_, TRUE);
				_tmp47_ = _tmp46_;
				_tmp48_ = vala_develop_symbol_finder_find_symbol_by_name (_tmp42_, _tmp43_, _tmp44_, _tmp47_, gtk_text_iter_get_line (&matchStart) + 1, gtk_text_iter_get_line_offset (&matchStart));
				_vala_code_node_unref0 (self->priv->current_symbol);
				self->priv->current_symbol = _tmp48_;
				_g_free0 (_tmp47_);
				_tmp49_ = self->priv->current_symbol;
				if (_tmp49_ != NULL) {
					const gchar* _tmp50_;
					_tmp50_ = word;
					g_print ("[WORD match] '%s' %d,%d\n", _tmp50_, gtk_text_iter_get_line (&matchStart) + 1, gtk_text_iter_get_line_offset (&matchStart));
					result = TRUE;
					_g_object_unref0 (searchContext);
					_g_object_unref0 (searchSettings);
					_g_free0 (word);
					return result;
				}
			} else {
				valaDevelopSymbolFinder* _tmp51_;
				const gchar* _tmp52_;
				const gchar* _tmp53_;
				GtkTextIter* _tmp54_;
				GtkTextIter* _tmp55_;
				GtkTextBuffer* _tmp56_;
				gchar* _tmp57_;
				gchar* _tmp58_;
				ValaSymbol* _tmp59_;
				ValaSymbol* _tmp60_;
				_tmp51_ = self->priv->_symbol_finder;
				_tmp52_ = word;
				_tmp53_ = self->priv->_fullpath;
				g_object_get (context, "iter", &_tmp54_, NULL);
				_tmp55_ = _tmp54_;
				_tmp56_ = gtk_text_iter_get_buffer (_tmp55_);
				_tmp57_ = vala_develop_globals_get_text_from_buffer (_tmp56_, TRUE);
				_tmp58_ = _tmp57_;
				_tmp59_ = vala_develop_symbol_finder_find_symbol_by_name (_tmp51_, _tmp52_, _tmp53_, _tmp58_, 0, 0);
				_vala_code_node_unref0 (self->priv->current_symbol);
				self->priv->current_symbol = _tmp59_;
				_g_free0 (_tmp58_);
				_tmp60_ = self->priv->current_symbol;
				if (_tmp60_ != NULL) {
					const gchar* _tmp61_;
					_tmp61_ = word;
					g_print ("[WORD match] '%s' %d,%d\n", _tmp61_, 0, 0);
					result = TRUE;
					_g_object_unref0 (searchContext);
					_g_object_unref0 (searchSettings);
					_g_free0 (word);
					return result;
				}
			}
			_g_object_unref0 (searchContext);
			_g_object_unref0 (searchSettings);
		}
		goto __finally25;
		__catch25_g_error:
		{
			GError* e = NULL;
			GError* _tmp62_;
			const gchar* _tmp63_;
			e = _inner_error0_;
			_inner_error0_ = NULL;
			_tmp62_ = e;
			_tmp63_ = _tmp62_->message;
			g_log (NULL, G_LOG_LEVEL_ERROR, "completion_provider.vala:124: %s", _tmp63_);
			_g_error_free0 (e);
		}
		__finally25:
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			gboolean _tmp64_ = FALSE;
			_g_free0 (word);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return _tmp64_;
		}
		_g_free0 (word);
	}
	result = TRUE;
	return result;
}

static gint
vala_develop_vala_completion_provider_real_get_priority (GtkSourceCompletionProvider* base)
{
	valaDevelopValaCompletionProvider * self;
	gint result = 0;
	self = (valaDevelopValaCompletionProvider*) base;
	result = 1;
	return result;
}

static GdkPixbuf*
vala_develop_vala_completion_provider_real_get_icon (GtkSourceCompletionProvider* base)
{
	valaDevelopValaCompletionProvider * self;
	GdkPixbuf* result = NULL;
	self = (valaDevelopValaCompletionProvider*) base;
	result = NULL;
	return result;
}

static gchar*
vala_develop_vala_completion_provider_real_get_name (GtkSourceCompletionProvider* base)
{
	valaDevelopValaCompletionProvider * self;
	gchar* result = NULL;
	gchar* _tmp0_;
	self = (valaDevelopValaCompletionProvider*) base;
	_tmp0_ = g_strdup ("valaDevelopCompletionProvider");
	result = _tmp0_;
	return result;
}

static void
vala_develop_vala_completion_provider_class_init (valaDevelopValaCompletionProviderClass * klass,
                                                  gpointer klass_data)
{
	vala_develop_vala_completion_provider_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &valaDevelopValaCompletionProvider_private_offset);
	G_OBJECT_CLASS (klass)->finalize = vala_develop_vala_completion_provider_finalize;
}

static void
vala_develop_vala_completion_provider_gtk_source_completion_provider_interface_init (GtkSourceCompletionProviderIface * iface,
                                                                                     gpointer iface_data)
{
	vala_develop_vala_completion_provider_gtk_source_completion_provider_parent_iface = g_type_interface_peek_parent (iface);
	iface->populate = (void (*) (GtkSourceCompletionProvider*, GtkSourceCompletionContext*)) vala_develop_vala_completion_provider_real_populate;
	iface->match = (gboolean (*) (GtkSourceCompletionProvider*, GtkSourceCompletionContext*)) vala_develop_vala_completion_provider_real_match;
	iface->get_priority = (gint (*) (GtkSourceCompletionProvider*)) vala_develop_vala_completion_provider_real_get_priority;
	iface->get_icon = (GdkPixbuf* (*) (GtkSourceCompletionProvider*)) vala_develop_vala_completion_provider_real_get_icon;
	iface->get_name = (gchar* (*) (GtkSourceCompletionProvider*)) vala_develop_vala_completion_provider_real_get_name;
}

static void
vala_develop_vala_completion_provider_instance_init (valaDevelopValaCompletionProvider * self,
                                                     gpointer klass)
{
	self->priv = vala_develop_vala_completion_provider_get_instance_private (self);
	self->priv->c = 0;
}

static void
vala_develop_vala_completion_provider_finalize (GObject * obj)
{
	valaDevelopValaCompletionProvider * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALA_DEVELOP_TYPE_VALA_COMPLETION_PROVIDER, valaDevelopValaCompletionProvider);
	_g_object_unref0 (self->priv->_symbol_finder);
	_g_free0 (self->priv->_fullpath);
	_vala_code_node_unref0 (self->priv->current_symbol);
	(self->priv->proposals == NULL) ? NULL : (self->priv->proposals = (_g_list_free__g_object_unref0_ (self->priv->proposals), NULL));
	G_OBJECT_CLASS (vala_develop_vala_completion_provider_parent_class)->finalize (obj);
}

GType
vala_develop_vala_completion_provider_get_type (void)
{
	static volatile gsize vala_develop_vala_completion_provider_type_id__volatile = 0;
	if (g_once_init_enter (&vala_develop_vala_completion_provider_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (valaDevelopValaCompletionProviderClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_develop_vala_completion_provider_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (valaDevelopValaCompletionProvider), 0, (GInstanceInitFunc) vala_develop_vala_completion_provider_instance_init, NULL };
		static const GInterfaceInfo gtk_source_completion_provider_info = { (GInterfaceInitFunc) vala_develop_vala_completion_provider_gtk_source_completion_provider_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType vala_develop_vala_completion_provider_type_id;
		vala_develop_vala_completion_provider_type_id = g_type_register_static (G_TYPE_OBJECT, "valaDevelopValaCompletionProvider", &g_define_type_info, 0);
		g_type_add_interface_static (vala_develop_vala_completion_provider_type_id, gtk_source_completion_provider_get_type (), &gtk_source_completion_provider_info);
		valaDevelopValaCompletionProvider_private_offset = g_type_add_instance_private (vala_develop_vala_completion_provider_type_id, sizeof (valaDevelopValaCompletionProviderPrivate));
		g_once_init_leave (&vala_develop_vala_completion_provider_type_id__volatile, vala_develop_vala_completion_provider_type_id);
	}
	return vala_develop_vala_completion_provider_type_id__volatile;
}

