/* item_options.c generated by valac 0.44.0, the Vala compiler
 * generated from item_options.vala, do not modify */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>

#define VALA_DEVELOP_TYPE_IOPTION_WIDGET (vala_develop_ioption_widget_get_type ())
#define VALA_DEVELOP_IOPTION_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_IOPTION_WIDGET, valaDevelopIOptionWidget))
#define VALA_DEVELOP_IS_IOPTION_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_IOPTION_WIDGET))
#define VALA_DEVELOP_IOPTION_WIDGET_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), VALA_DEVELOP_TYPE_IOPTION_WIDGET, valaDevelopIOptionWidgetIface))

typedef struct _valaDevelopIOptionWidget valaDevelopIOptionWidget;
typedef struct _valaDevelopIOptionWidgetIface valaDevelopIOptionWidgetIface;

#define VALA_DEVELOP_TYPE_ITEM_OPTIONS (vala_develop_item_options_get_type ())
#define VALA_DEVELOP_ITEM_OPTIONS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_ITEM_OPTIONS, valaDevelopItemOptions))
#define VALA_DEVELOP_ITEM_OPTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_ITEM_OPTIONS, valaDevelopItemOptionsClass))
#define VALA_DEVELOP_IS_ITEM_OPTIONS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_ITEM_OPTIONS))
#define VALA_DEVELOP_IS_ITEM_OPTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_ITEM_OPTIONS))
#define VALA_DEVELOP_ITEM_OPTIONS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_ITEM_OPTIONS, valaDevelopItemOptionsClass))

typedef struct _valaDevelopItemOptions valaDevelopItemOptions;
typedef struct _valaDevelopItemOptionsClass valaDevelopItemOptionsClass;
typedef struct _valaDevelopItemOptionsPrivate valaDevelopItemOptionsPrivate;

#define VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE (vala_develop_overview_tree_store_get_type ())
#define VALA_DEVELOP_OVERVIEW_TREE_STORE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE, valaDevelopOverviewTreeStore))
#define VALA_DEVELOP_OVERVIEW_TREE_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE, valaDevelopOverviewTreeStoreClass))
#define VALA_DEVELOP_IS_OVERVIEW_TREE_STORE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE))
#define VALA_DEVELOP_IS_OVERVIEW_TREE_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE))
#define VALA_DEVELOP_OVERVIEW_TREE_STORE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE, valaDevelopOverviewTreeStoreClass))

typedef struct _valaDevelopOverviewTreeStore valaDevelopOverviewTreeStore;
typedef struct _valaDevelopOverviewTreeStoreClass valaDevelopOverviewTreeStoreClass;
enum  {
	VALA_DEVELOP_ITEM_OPTIONS_0_PROPERTY,
	VALA_DEVELOP_ITEM_OPTIONS_NUM_PROPERTIES
};
static GParamSpec* vala_develop_item_options_properties[VALA_DEVELOP_ITEM_OPTIONS_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef enum  {
	VALA_DEVELOP_ITEM_TYPE_None = 0,
	VALA_DEVELOP_ITEM_TYPE_Solution = 1,
	VALA_DEVELOP_ITEM_TYPE_Project = 2,
	VALA_DEVELOP_ITEM_TYPE_Resource = 4,
	VALA_DEVELOP_ITEM_TYPE_Source = 8,
	VALA_DEVELOP_ITEM_TYPE_Package = 16,
	VALA_DEVELOP_ITEM_TYPE_Directory = 32,
	VALA_DEVELOP_ITEM_TYPE_Vapi = 64
} valaDevelopItemType;

#define VALA_DEVELOP_TYPE_ITEM_TYPE (vala_develop_item_type_get_type ())
typedef enum  {
	VALA_DEVELOP_ITEM_BUILD_TYPE_None,
	VALA_DEVELOP_ITEM_BUILD_TYPE_Compile,
	VALA_DEVELOP_ITEM_BUILD_TYPE_Resource,
	VALA_DEVELOP_ITEM_BUILD_TYPE_Package,
	VALA_DEVELOP_ITEM_BUILD_TYPE_Executable,
	VALA_DEVELOP_ITEM_BUILD_TYPE_SharedObject
} valaDevelopItemBuildType;

#define VALA_DEVELOP_TYPE_ITEM_BUILD_TYPE (vala_develop_item_build_type_get_type ())
#define _g_free0(var) (var = (g_free (var), NULL))

struct _valaDevelopIOptionWidgetIface {
	GTypeInterface parent_iface;
	void (*get_iter) (valaDevelopIOptionWidget* self, GtkTreeIter * value);
	void (*set_iter) (valaDevelopIOptionWidget* self, GtkTreeIter * value);
};

struct _valaDevelopItemOptions {
	GtkBox parent_instance;
	valaDevelopItemOptionsPrivate * priv;
};

struct _valaDevelopItemOptionsClass {
	GtkBoxClass parent_class;
};

struct _valaDevelopItemOptionsPrivate {
	GtkEntry* fileName;
	GtkEntry* fileRoot;
	GtkEntry* fileType;
	GtkCheckButton* build;
	GtkEntry* fileResourceId;
	GtkEntry* fileAlias;
	GtkCheckButton* compress;
	GtkCheckButton* stripblanks;
	GtkSeparator* separator;
	GtkBox* optionBox;
	GtkBox* aliasBox;
	GtkBox* resBox;
	valaDevelopOverviewTreeStore* _model;
	GtkTreeIter _iter;
};

static gint valaDevelopItemOptions_private_offset;
static gpointer vala_develop_item_options_parent_class = NULL;
static valaDevelopIOptionWidgetIface * vala_develop_item_options_vala_develop_ioption_widget_parent_iface = NULL;

GType vala_develop_ioption_widget_get_type (void) G_GNUC_CONST;
GType vala_develop_item_options_get_type (void) G_GNUC_CONST;
GType vala_develop_overview_tree_store_get_type (void) G_GNUC_CONST;
valaDevelopItemOptions* vala_develop_item_options_new (valaDevelopOverviewTreeStore* model,
                                                       GtkTreeIter* iter);
valaDevelopItemOptions* vala_develop_item_options_construct (GType object_type,
                                                             valaDevelopOverviewTreeStore* model,
                                                             GtkTreeIter* iter);
void vala_develop_ioption_widget_set_iter (valaDevelopIOptionWidget* self,
                                           GtkTreeIter * value);
static void vala_develop_item_options_Compress_Toggled (valaDevelopItemOptions* self);
void vala_develop_overview_tree_store_set_item_resource_compress (valaDevelopOverviewTreeStore* self,
                                                                  GtkTreeIter* iter,
                                                                  gboolean resourceCompress);
gboolean vala_develop_overview_tree_store_save_project (valaDevelopOverviewTreeStore* self,
                                                        GtkTreeIter* iter);
static void vala_develop_item_options_Stripblanks_Toggled (valaDevelopItemOptions* self);
void vala_develop_overview_tree_store_set_item_resource_stripblanks (valaDevelopOverviewTreeStore* self,
                                                                     GtkTreeIter* iter,
                                                                     gboolean resourceStripBlanks);
static void vala_develop_item_options_FileAlias_Changed (valaDevelopItemOptions* self);
void vala_develop_overview_tree_store_set_item_resource_alias (valaDevelopOverviewTreeStore* self,
                                                               GtkTreeIter* iter,
                                                               const gchar* resourceAlias);
static void vala_develop_item_options_Build_Toggled (valaDevelopItemOptions* self);
gint vala_develop_overview_tree_store_get_item_type (valaDevelopOverviewTreeStore* self,
                                                     GtkTreeIter* iter);
GType vala_develop_item_type_get_type (void) G_GNUC_CONST;
GType vala_develop_item_build_type_get_type (void) G_GNUC_CONST;
void vala_develop_overview_tree_store_set_item_buildtype (valaDevelopOverviewTreeStore* self,
                                                          GtkTreeIter* iter,
                                                          gint itemBuildType);
static void _vala_develop_item_options_Build_Toggled_gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                                                         gpointer self);
static void _vala_develop_item_options_Compress_Toggled_gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                                                            gpointer self);
static void _vala_develop_item_options_Stripblanks_Toggled_gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                                                               gpointer self);
static void _vala_develop_item_options_FileAlias_Changed_gtk_editable_changed (GtkEditable* _sender,
                                                                        gpointer self);
gchar* vala_develop_overview_tree_store_get_item_name (valaDevelopOverviewTreeStore* self,
                                                       GtkTreeIter* iter);
gchar* vala_develop_overview_tree_store_get_item_path (valaDevelopOverviewTreeStore* self,
                                                       GtkTreeIter* iter);
gchar* vala_develop_overview_tree_store_get_item_resource_id (valaDevelopOverviewTreeStore* self,
                                                              GtkTreeIter* iter);
gchar* vala_develop_overview_tree_store_get_item_mimetype (valaDevelopOverviewTreeStore* self,
                                                           GtkTreeIter* iter);
gint vala_develop_overview_tree_store_get_item_buildtype (valaDevelopOverviewTreeStore* self,
                                                          GtkTreeIter* iter);
gboolean vala_develop_overview_tree_store_get_item_resource_compress (valaDevelopOverviewTreeStore* self,
                                                                      GtkTreeIter* iter);
gboolean vala_develop_overview_tree_store_get_item_resource_stripblanks (valaDevelopOverviewTreeStore* self,
                                                                         GtkTreeIter* iter);
gchar* vala_develop_overview_tree_store_get_item_resource_alias (valaDevelopOverviewTreeStore* self,
                                                                 GtkTreeIter* iter);
static void vala_develop_item_options_finalize (GObject * obj);
static void _vala_vala_develop_item_options_get_property (GObject * object,
                                                   guint property_id,
                                                   GValue * value,
                                                   GParamSpec * pspec);
static void _vala_vala_develop_item_options_set_property (GObject * object,
                                                   guint property_id,
                                                   const GValue * value,
                                                   GParamSpec * pspec);

static inline gpointer
vala_develop_item_options_get_instance_private (valaDevelopItemOptions* self)
{
	return G_STRUCT_MEMBER_P (self, valaDevelopItemOptions_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

valaDevelopItemOptions*
vala_develop_item_options_construct (GType object_type,
                                     valaDevelopOverviewTreeStore* model,
                                     GtkTreeIter* iter)
{
	valaDevelopItemOptions * self = NULL;
	valaDevelopOverviewTreeStore* _tmp0_;
	GtkTreeIter _tmp1_;
	g_return_val_if_fail (model != NULL, NULL);
	g_return_val_if_fail (iter != NULL, NULL);
	self = (valaDevelopItemOptions*) g_object_new (object_type, NULL);
	_tmp0_ = _g_object_ref0 (model);
	_g_object_unref0 (self->priv->_model);
	self->priv->_model = _tmp0_;
	_tmp1_ = *iter;
	vala_develop_ioption_widget_set_iter ((valaDevelopIOptionWidget*) self, &_tmp1_);
	return self;
}

valaDevelopItemOptions*
vala_develop_item_options_new (valaDevelopOverviewTreeStore* model,
                               GtkTreeIter* iter)
{
	return vala_develop_item_options_construct (VALA_DEVELOP_TYPE_ITEM_OPTIONS, model, iter);
}

static void
vala_develop_item_options_Compress_Toggled (valaDevelopItemOptions* self)
{
	valaDevelopOverviewTreeStore* _tmp0_;
	GtkTreeIter _tmp1_;
	GtkCheckButton* _tmp2_;
	gboolean _tmp3_;
	gboolean _tmp4_;
	valaDevelopOverviewTreeStore* _tmp5_;
	GtkTreeIter _tmp6_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_model;
	_tmp1_ = self->priv->_iter;
	_tmp2_ = self->priv->compress;
	_tmp3_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp2_);
	_tmp4_ = _tmp3_;
	vala_develop_overview_tree_store_set_item_resource_compress (_tmp0_, &_tmp1_, _tmp4_);
	_tmp5_ = self->priv->_model;
	_tmp6_ = self->priv->_iter;
	vala_develop_overview_tree_store_save_project (_tmp5_, &_tmp6_);
}

static void
vala_develop_item_options_Stripblanks_Toggled (valaDevelopItemOptions* self)
{
	valaDevelopOverviewTreeStore* _tmp0_;
	GtkTreeIter _tmp1_;
	GtkCheckButton* _tmp2_;
	gboolean _tmp3_;
	gboolean _tmp4_;
	valaDevelopOverviewTreeStore* _tmp5_;
	GtkTreeIter _tmp6_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_model;
	_tmp1_ = self->priv->_iter;
	_tmp2_ = self->priv->stripblanks;
	_tmp3_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp2_);
	_tmp4_ = _tmp3_;
	vala_develop_overview_tree_store_set_item_resource_stripblanks (_tmp0_, &_tmp1_, _tmp4_);
	_tmp5_ = self->priv->_model;
	_tmp6_ = self->priv->_iter;
	vala_develop_overview_tree_store_save_project (_tmp5_, &_tmp6_);
}

static void
vala_develop_item_options_FileAlias_Changed (valaDevelopItemOptions* self)
{
	valaDevelopOverviewTreeStore* _tmp0_;
	GtkTreeIter _tmp1_;
	GtkEntry* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	valaDevelopOverviewTreeStore* _tmp5_;
	GtkTreeIter _tmp6_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_model;
	_tmp1_ = self->priv->_iter;
	_tmp2_ = self->priv->fileAlias;
	_tmp3_ = gtk_entry_get_text (_tmp2_);
	_tmp4_ = _tmp3_;
	vala_develop_overview_tree_store_set_item_resource_alias (_tmp0_, &_tmp1_, _tmp4_);
	_tmp5_ = self->priv->_model;
	_tmp6_ = self->priv->_iter;
	vala_develop_overview_tree_store_save_project (_tmp5_, &_tmp6_);
}

static void
vala_develop_item_options_Build_Toggled (valaDevelopItemOptions* self)
{
	gint itemType = 0;
	valaDevelopOverviewTreeStore* _tmp0_;
	GtkTreeIter _tmp1_;
	valaDevelopOverviewTreeStore* _tmp14_;
	GtkTreeIter _tmp15_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_model;
	_tmp1_ = self->priv->_iter;
	itemType = vala_develop_overview_tree_store_get_item_type (_tmp0_, &_tmp1_);
	if (itemType == ((gint) VALA_DEVELOP_ITEM_TYPE_Resource)) {
		valaDevelopItemBuildType _tmp2_ = 0;
		GtkCheckButton* _tmp3_;
		gboolean _tmp4_;
		gboolean _tmp5_;
		valaDevelopOverviewTreeStore* _tmp6_;
		GtkTreeIter _tmp7_;
		_tmp3_ = self->priv->build;
		_tmp4_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp3_);
		_tmp5_ = _tmp4_;
		if (_tmp5_) {
			_tmp2_ = VALA_DEVELOP_ITEM_BUILD_TYPE_Resource;
		} else {
			_tmp2_ = VALA_DEVELOP_ITEM_BUILD_TYPE_None;
		}
		_tmp6_ = self->priv->_model;
		_tmp7_ = self->priv->_iter;
		vala_develop_overview_tree_store_set_item_buildtype (_tmp6_, &_tmp7_, (gint) _tmp2_);
	} else {
		if (itemType == ((gint) VALA_DEVELOP_ITEM_TYPE_Source)) {
			valaDevelopItemBuildType _tmp8_ = 0;
			GtkCheckButton* _tmp9_;
			gboolean _tmp10_;
			gboolean _tmp11_;
			valaDevelopOverviewTreeStore* _tmp12_;
			GtkTreeIter _tmp13_;
			_tmp9_ = self->priv->build;
			_tmp10_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp9_);
			_tmp11_ = _tmp10_;
			if (_tmp11_) {
				_tmp8_ = VALA_DEVELOP_ITEM_BUILD_TYPE_Compile;
			} else {
				_tmp8_ = VALA_DEVELOP_ITEM_BUILD_TYPE_None;
			}
			_tmp12_ = self->priv->_model;
			_tmp13_ = self->priv->_iter;
			vala_develop_overview_tree_store_set_item_buildtype (_tmp12_, &_tmp13_, (gint) _tmp8_);
		}
	}
	_tmp14_ = self->priv->_model;
	_tmp15_ = self->priv->_iter;
	vala_develop_overview_tree_store_save_project (_tmp14_, &_tmp15_);
}

static void
vala_develop_item_options_real_get_iter (valaDevelopIOptionWidget* base,
                                         GtkTreeIter * result)
{
	valaDevelopItemOptions* self;
	GtkTreeIter _tmp0_;
	self = (valaDevelopItemOptions*) base;
	_tmp0_ = self->priv->_iter;
	*result = _tmp0_;
	return;
}

static void
_vala_develop_item_options_Build_Toggled_gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                                                    gpointer self)
{
	vala_develop_item_options_Build_Toggled ((valaDevelopItemOptions*) self);
}

static void
_vala_develop_item_options_Compress_Toggled_gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                                                       gpointer self)
{
	vala_develop_item_options_Compress_Toggled ((valaDevelopItemOptions*) self);
}

static void
_vala_develop_item_options_Stripblanks_Toggled_gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                                                          gpointer self)
{
	vala_develop_item_options_Stripblanks_Toggled ((valaDevelopItemOptions*) self);
}

static void
_vala_develop_item_options_FileAlias_Changed_gtk_editable_changed (GtkEditable* _sender,
                                                                   gpointer self)
{
	vala_develop_item_options_FileAlias_Changed ((valaDevelopItemOptions*) self);
}

static void
vala_develop_item_options_real_set_iter (valaDevelopIOptionWidget* base,
                                         GtkTreeIter * value)
{
	valaDevelopItemOptions* self;
	GtkTreeIter _tmp0_;
	GtkCheckButton* _tmp1_;
	guint _tmp2_;
	GtkCheckButton* _tmp3_;
	guint _tmp4_;
	GtkCheckButton* _tmp5_;
	guint _tmp6_;
	GtkEntry* _tmp7_;
	guint _tmp8_;
	gint itemType = 0;
	valaDevelopOverviewTreeStore* _tmp9_;
	GtkTreeIter _tmp10_;
	GtkEntry* _tmp21_;
	valaDevelopOverviewTreeStore* _tmp22_;
	GtkTreeIter _tmp23_;
	gchar* _tmp24_;
	gchar* _tmp25_;
	GtkTreeIter parentIter = {0};
	valaDevelopOverviewTreeStore* _tmp26_;
	GtkTreeIter _tmp27_;
	GtkTreeIter _tmp28_ = {0};
	GtkEntry* _tmp29_;
	valaDevelopOverviewTreeStore* _tmp30_;
	GtkTreeIter _tmp31_;
	gchar* _tmp32_;
	gchar* _tmp33_;
	GtkEntry* _tmp34_;
	valaDevelopOverviewTreeStore* _tmp35_;
	GtkTreeIter _tmp36_;
	gchar* _tmp37_;
	gchar* _tmp38_;
	GtkEntry* _tmp39_;
	valaDevelopOverviewTreeStore* _tmp40_;
	GtkTreeIter _tmp41_;
	gchar* _tmp42_;
	gchar* _tmp43_;
	gint itemBuildType = 0;
	valaDevelopOverviewTreeStore* _tmp44_;
	GtkTreeIter _tmp45_;
	GtkCheckButton* _tmp46_;
	GtkCheckButton* _tmp59_;
	GtkCheckButton* _tmp60_;
	GtkCheckButton* _tmp61_;
	GtkEntry* _tmp62_;
	self = (valaDevelopItemOptions*) base;
	_tmp0_ = *value;
	self->priv->_iter = _tmp0_;
	_tmp1_ = self->priv->build;
	g_signal_parse_name ("toggled", gtk_toggle_button_get_type (), &_tmp2_, NULL, FALSE);
	g_signal_handlers_disconnect_matched ((GtkToggleButton*) _tmp1_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp2_, 0, NULL, (GCallback) _vala_develop_item_options_Build_Toggled_gtk_toggle_button_toggled, self);
	_tmp3_ = self->priv->compress;
	g_signal_parse_name ("toggled", gtk_toggle_button_get_type (), &_tmp4_, NULL, FALSE);
	g_signal_handlers_disconnect_matched ((GtkToggleButton*) _tmp3_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp4_, 0, NULL, (GCallback) _vala_develop_item_options_Compress_Toggled_gtk_toggle_button_toggled, self);
	_tmp5_ = self->priv->stripblanks;
	g_signal_parse_name ("toggled", gtk_toggle_button_get_type (), &_tmp6_, NULL, FALSE);
	g_signal_handlers_disconnect_matched ((GtkToggleButton*) _tmp5_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp6_, 0, NULL, (GCallback) _vala_develop_item_options_Stripblanks_Toggled_gtk_toggle_button_toggled, self);
	_tmp7_ = self->priv->fileAlias;
	g_signal_parse_name ("changed", gtk_editable_get_type (), &_tmp8_, NULL, FALSE);
	g_signal_handlers_disconnect_matched ((GtkEditable*) _tmp7_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp8_, 0, NULL, (GCallback) _vala_develop_item_options_FileAlias_Changed_gtk_editable_changed, self);
	_tmp9_ = self->priv->_model;
	_tmp10_ = self->priv->_iter;
	itemType = vala_develop_overview_tree_store_get_item_type (_tmp9_, &_tmp10_);
	if (itemType == ((gint) VALA_DEVELOP_ITEM_TYPE_Resource)) {
		GtkCheckButton* _tmp11_;
		GtkSeparator* _tmp12_;
		GtkBox* _tmp13_;
		GtkBox* _tmp14_;
		GtkBox* _tmp15_;
		_tmp11_ = self->priv->build;
		gtk_button_set_label ((GtkButton*) _tmp11_, _ ("Embed resource"));
		_tmp12_ = self->priv->separator;
		gtk_widget_set_visible ((GtkWidget*) _tmp12_, TRUE);
		_tmp13_ = self->priv->optionBox;
		gtk_widget_set_visible ((GtkWidget*) _tmp13_, TRUE);
		_tmp14_ = self->priv->aliasBox;
		gtk_widget_set_visible ((GtkWidget*) _tmp14_, TRUE);
		_tmp15_ = self->priv->resBox;
		gtk_widget_set_visible ((GtkWidget*) _tmp15_, TRUE);
	} else {
		if (itemType == ((gint) VALA_DEVELOP_ITEM_TYPE_Source)) {
			GtkCheckButton* _tmp16_;
			GtkSeparator* _tmp17_;
			GtkBox* _tmp18_;
			GtkBox* _tmp19_;
			GtkBox* _tmp20_;
			_tmp16_ = self->priv->build;
			gtk_button_set_label ((GtkButton*) _tmp16_, _ ("Compile"));
			_tmp17_ = self->priv->separator;
			gtk_widget_set_visible ((GtkWidget*) _tmp17_, FALSE);
			_tmp18_ = self->priv->optionBox;
			gtk_widget_set_visible ((GtkWidget*) _tmp18_, FALSE);
			_tmp19_ = self->priv->aliasBox;
			gtk_widget_set_visible ((GtkWidget*) _tmp19_, FALSE);
			_tmp20_ = self->priv->resBox;
			gtk_widget_set_visible ((GtkWidget*) _tmp20_, FALSE);
		}
	}
	_tmp21_ = self->priv->fileName;
	_tmp22_ = self->priv->_model;
	_tmp23_ = self->priv->_iter;
	_tmp24_ = vala_develop_overview_tree_store_get_item_name (_tmp22_, &_tmp23_);
	_tmp25_ = _tmp24_;
	gtk_entry_set_text (_tmp21_, _tmp25_);
	_g_free0 (_tmp25_);
	_tmp26_ = self->priv->_model;
	_tmp27_ = self->priv->_iter;
	gtk_tree_model_iter_parent ((GtkTreeModel*) _tmp26_, &_tmp28_, &_tmp27_);
	parentIter = _tmp28_;
	_tmp29_ = self->priv->fileRoot;
	_tmp30_ = self->priv->_model;
	_tmp31_ = parentIter;
	_tmp32_ = vala_develop_overview_tree_store_get_item_path (_tmp30_, &_tmp31_);
	_tmp33_ = _tmp32_;
	gtk_entry_set_text (_tmp29_, _tmp33_);
	_g_free0 (_tmp33_);
	_tmp34_ = self->priv->fileResourceId;
	_tmp35_ = self->priv->_model;
	_tmp36_ = self->priv->_iter;
	_tmp37_ = vala_develop_overview_tree_store_get_item_resource_id (_tmp35_, &_tmp36_);
	_tmp38_ = _tmp37_;
	gtk_entry_set_text (_tmp34_, _tmp38_);
	_g_free0 (_tmp38_);
	_tmp39_ = self->priv->fileType;
	_tmp40_ = self->priv->_model;
	_tmp41_ = self->priv->_iter;
	_tmp42_ = vala_develop_overview_tree_store_get_item_mimetype (_tmp40_, &_tmp41_);
	_tmp43_ = _tmp42_;
	gtk_entry_set_text (_tmp39_, _tmp43_);
	_g_free0 (_tmp43_);
	_tmp44_ = self->priv->_model;
	_tmp45_ = self->priv->_iter;
	itemBuildType = vala_develop_overview_tree_store_get_item_buildtype (_tmp44_, &_tmp45_);
	_tmp46_ = self->priv->build;
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp46_, itemBuildType != ((gint) VALA_DEVELOP_ITEM_BUILD_TYPE_None));
	if (itemBuildType == ((gint) VALA_DEVELOP_ITEM_BUILD_TYPE_Compile)) {
		GtkCheckButton* _tmp47_;
		_tmp47_ = self->priv->build;
		gtk_widget_set_sensitive ((GtkWidget*) _tmp47_, TRUE);
	} else {
		if (itemBuildType == ((gint) VALA_DEVELOP_ITEM_BUILD_TYPE_Resource)) {
			GtkCheckButton* _tmp48_;
			valaDevelopOverviewTreeStore* _tmp49_;
			GtkTreeIter _tmp50_;
			GtkCheckButton* _tmp51_;
			valaDevelopOverviewTreeStore* _tmp52_;
			GtkTreeIter _tmp53_;
			GtkEntry* _tmp54_;
			valaDevelopOverviewTreeStore* _tmp55_;
			GtkTreeIter _tmp56_;
			gchar* _tmp57_;
			gchar* _tmp58_;
			_tmp48_ = self->priv->compress;
			_tmp49_ = self->priv->_model;
			_tmp50_ = self->priv->_iter;
			gtk_toggle_button_set_active ((GtkToggleButton*) _tmp48_, vala_develop_overview_tree_store_get_item_resource_compress (_tmp49_, &_tmp50_));
			_tmp51_ = self->priv->stripblanks;
			_tmp52_ = self->priv->_model;
			_tmp53_ = self->priv->_iter;
			gtk_toggle_button_set_active ((GtkToggleButton*) _tmp51_, vala_develop_overview_tree_store_get_item_resource_stripblanks (_tmp52_, &_tmp53_));
			_tmp54_ = self->priv->fileAlias;
			_tmp55_ = self->priv->_model;
			_tmp56_ = self->priv->_iter;
			_tmp57_ = vala_develop_overview_tree_store_get_item_resource_alias (_tmp55_, &_tmp56_);
			_tmp58_ = _tmp57_;
			gtk_entry_set_text (_tmp54_, _tmp58_);
			_g_free0 (_tmp58_);
		}
	}
	_tmp59_ = self->priv->build;
	g_signal_connect_object ((GtkToggleButton*) _tmp59_, "toggled", (GCallback) _vala_develop_item_options_Build_Toggled_gtk_toggle_button_toggled, self, 0);
	_tmp60_ = self->priv->compress;
	g_signal_connect_object ((GtkToggleButton*) _tmp60_, "toggled", (GCallback) _vala_develop_item_options_Compress_Toggled_gtk_toggle_button_toggled, self, 0);
	_tmp61_ = self->priv->stripblanks;
	g_signal_connect_object ((GtkToggleButton*) _tmp61_, "toggled", (GCallback) _vala_develop_item_options_Stripblanks_Toggled_gtk_toggle_button_toggled, self, 0);
	_tmp62_ = self->priv->fileAlias;
	g_signal_connect_object ((GtkEditable*) _tmp62_, "changed", (GCallback) _vala_develop_item_options_FileAlias_Changed_gtk_editable_changed, self, 0);
}

static void
vala_develop_item_options_class_init (valaDevelopItemOptionsClass * klass,
                                      gpointer klass_data)
{
	vala_develop_item_options_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &valaDevelopItemOptions_private_offset);
	G_OBJECT_CLASS (klass)->get_property = _vala_vala_develop_item_options_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_vala_develop_item_options_set_property;
	G_OBJECT_CLASS (klass)->finalize = vala_develop_item_options_finalize;
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/valaDevelop/itemoptions.glade");
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "fileName", FALSE, valaDevelopItemOptions_private_offset + G_STRUCT_OFFSET (valaDevelopItemOptionsPrivate, fileName));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "fileRoot", FALSE, valaDevelopItemOptions_private_offset + G_STRUCT_OFFSET (valaDevelopItemOptionsPrivate, fileRoot));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "fileType", FALSE, valaDevelopItemOptions_private_offset + G_STRUCT_OFFSET (valaDevelopItemOptionsPrivate, fileType));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "build", FALSE, valaDevelopItemOptions_private_offset + G_STRUCT_OFFSET (valaDevelopItemOptionsPrivate, build));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "fileResourceId", FALSE, valaDevelopItemOptions_private_offset + G_STRUCT_OFFSET (valaDevelopItemOptionsPrivate, fileResourceId));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "fileAlias", FALSE, valaDevelopItemOptions_private_offset + G_STRUCT_OFFSET (valaDevelopItemOptionsPrivate, fileAlias));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "compress", FALSE, valaDevelopItemOptions_private_offset + G_STRUCT_OFFSET (valaDevelopItemOptionsPrivate, compress));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "stripblanks", FALSE, valaDevelopItemOptions_private_offset + G_STRUCT_OFFSET (valaDevelopItemOptionsPrivate, stripblanks));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "separator", FALSE, valaDevelopItemOptions_private_offset + G_STRUCT_OFFSET (valaDevelopItemOptionsPrivate, separator));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "optionBox", FALSE, valaDevelopItemOptions_private_offset + G_STRUCT_OFFSET (valaDevelopItemOptionsPrivate, optionBox));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "aliasBox", FALSE, valaDevelopItemOptions_private_offset + G_STRUCT_OFFSET (valaDevelopItemOptionsPrivate, aliasBox));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "resBox", FALSE, valaDevelopItemOptions_private_offset + G_STRUCT_OFFSET (valaDevelopItemOptionsPrivate, resBox));
}

static void
vala_develop_item_options_vala_develop_ioption_widget_interface_init (valaDevelopIOptionWidgetIface * iface,
                                                                      gpointer iface_data)
{
	vala_develop_item_options_vala_develop_ioption_widget_parent_iface = g_type_interface_peek_parent (iface);
	iface->get_iter = vala_develop_item_options_real_get_iter;
	iface->set_iter = vala_develop_item_options_real_set_iter;
}

static void
vala_develop_item_options_instance_init (valaDevelopItemOptions * self,
                                         gpointer klass)
{
	self->priv = vala_develop_item_options_get_instance_private (self);
	gtk_widget_init_template (GTK_WIDGET (self));
}

static void
vala_develop_item_options_finalize (GObject * obj)
{
	valaDevelopItemOptions * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALA_DEVELOP_TYPE_ITEM_OPTIONS, valaDevelopItemOptions);
	_g_object_unref0 (self->priv->fileName);
	_g_object_unref0 (self->priv->fileRoot);
	_g_object_unref0 (self->priv->fileType);
	_g_object_unref0 (self->priv->build);
	_g_object_unref0 (self->priv->fileResourceId);
	_g_object_unref0 (self->priv->fileAlias);
	_g_object_unref0 (self->priv->compress);
	_g_object_unref0 (self->priv->stripblanks);
	_g_object_unref0 (self->priv->separator);
	_g_object_unref0 (self->priv->optionBox);
	_g_object_unref0 (self->priv->aliasBox);
	_g_object_unref0 (self->priv->resBox);
	_g_object_unref0 (self->priv->_model);
	G_OBJECT_CLASS (vala_develop_item_options_parent_class)->finalize (obj);
}

GType
vala_develop_item_options_get_type (void)
{
	static volatile gsize vala_develop_item_options_type_id__volatile = 0;
	if (g_once_init_enter (&vala_develop_item_options_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (valaDevelopItemOptionsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_develop_item_options_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (valaDevelopItemOptions), 0, (GInstanceInitFunc) vala_develop_item_options_instance_init, NULL };
		static const GInterfaceInfo vala_develop_ioption_widget_info = { (GInterfaceInitFunc) vala_develop_item_options_vala_develop_ioption_widget_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType vala_develop_item_options_type_id;
		vala_develop_item_options_type_id = g_type_register_static (gtk_box_get_type (), "valaDevelopItemOptions", &g_define_type_info, 0);
		g_type_add_interface_static (vala_develop_item_options_type_id, VALA_DEVELOP_TYPE_IOPTION_WIDGET, &vala_develop_ioption_widget_info);
		valaDevelopItemOptions_private_offset = g_type_add_instance_private (vala_develop_item_options_type_id, sizeof (valaDevelopItemOptionsPrivate));
		g_once_init_leave (&vala_develop_item_options_type_id__volatile, vala_develop_item_options_type_id);
	}
	return vala_develop_item_options_type_id__volatile;
}

static void
_vala_vala_develop_item_options_get_property (GObject * object,
                                              guint property_id,
                                              GValue * value,
                                              GParamSpec * pspec)
{
	valaDevelopItemOptions * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, VALA_DEVELOP_TYPE_ITEM_OPTIONS, valaDevelopItemOptions);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_vala_develop_item_options_set_property (GObject * object,
                                              guint property_id,
                                              const GValue * value,
                                              GParamSpec * pspec)
{
	valaDevelopItemOptions * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, VALA_DEVELOP_TYPE_ITEM_OPTIONS, valaDevelopItemOptions);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

