/* main.c generated by valac UNKNOWN, the Vala compiler
 * generated from main.vala, do not modify */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <locale.h>
#include <glib/gi18n-lib.h>
#include <gdk/gdk.h>

#define VALA_DEVELOP_TYPE_VALA_DEVELOP (vala_develop_vala_develop_get_type ())
#define VALA_DEVELOP_VALA_DEVELOP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_VALA_DEVELOP, valaDevelopvalaDevelop))
#define VALA_DEVELOP_VALA_DEVELOP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_VALA_DEVELOP, valaDevelopvalaDevelopClass))
#define VALA_DEVELOP_IS_VALA_DEVELOP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_VALA_DEVELOP))
#define VALA_DEVELOP_IS_VALA_DEVELOP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_VALA_DEVELOP))
#define VALA_DEVELOP_VALA_DEVELOP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_VALA_DEVELOP, valaDevelopvalaDevelopClass))

typedef struct _valaDevelopvalaDevelop valaDevelopvalaDevelop;
typedef struct _valaDevelopvalaDevelopClass valaDevelopvalaDevelopClass;
typedef struct _valaDevelopvalaDevelopPrivate valaDevelopvalaDevelopPrivate;
enum  {
	VALA_DEVELOP_VALA_DEVELOP_0_PROPERTY,
	VALA_DEVELOP_VALA_DEVELOP_NUM_PROPERTIES
};
static GParamSpec* vala_develop_vala_develop_properties[VALA_DEVELOP_VALA_DEVELOP_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define VALA_DEVELOP_TYPE_MAIN_WINDOW (vala_develop_main_window_get_type ())
#define VALA_DEVELOP_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_MAIN_WINDOW, valaDevelopmainWindow))
#define VALA_DEVELOP_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_MAIN_WINDOW, valaDevelopmainWindowClass))
#define VALA_DEVELOP_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_MAIN_WINDOW))
#define VALA_DEVELOP_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_MAIN_WINDOW))
#define VALA_DEVELOP_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_MAIN_WINDOW, valaDevelopmainWindowClass))

typedef struct _valaDevelopmainWindow valaDevelopmainWindow;
typedef struct _valaDevelopmainWindowClass valaDevelopmainWindowClass;
typedef struct _Block22Data Block22Data;

#define VALA_DEVELOP_TYPE_SETTINGS (vala_develop_settings_get_type ())
#define VALA_DEVELOP_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_SETTINGS, valaDevelopSettings))
#define VALA_DEVELOP_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_SETTINGS, valaDevelopSettingsClass))
#define VALA_DEVELOP_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_SETTINGS))
#define VALA_DEVELOP_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_SETTINGS))
#define VALA_DEVELOP_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_SETTINGS, valaDevelopSettingsClass))

typedef struct _valaDevelopSettings valaDevelopSettings;
typedef struct _valaDevelopSettingsClass valaDevelopSettingsClass;
typedef struct _Block23Data Block23Data;

struct _valaDevelopvalaDevelop {
	GtkApplication parent_instance;
	valaDevelopvalaDevelopPrivate * priv;
};

struct _valaDevelopvalaDevelopClass {
	GtkApplicationClass parent_class;
};

struct _Block22Data {
	int _ref_count_;
	valaDevelopvalaDevelop* self;
	valaDevelopmainWindow* window;
	GFile** files;
	gint files_length1;
};

struct _Block23Data {
	int _ref_count_;
	valaDevelopvalaDevelop* self;
	valaDevelopmainWindow* window;
};

static gpointer vala_develop_vala_develop_parent_class = NULL;
extern gchar* vala_develop_vala_develop_package_suffix;
gchar* vala_develop_vala_develop_package_suffix = NULL;
extern gchar* vala_develop_vala_develop_package_datadir;
gchar* vala_develop_vala_develop_package_datadir = NULL;

GType vala_develop_vala_develop_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (valaDevelopvalaDevelop, g_object_unref)
gint vala_develop_vala_develop_main (gchar** args,
                                     gint args_length1);
valaDevelopvalaDevelop* vala_develop_vala_develop_new (void);
valaDevelopvalaDevelop* vala_develop_vala_develop_construct (GType object_type);
static void vala_develop_vala_develop_real_startup (GApplication* base);
void vala_develop_xml_configuration_load (void);
static void vala_develop_vala_develop_real_open (GApplication* base,
                                          GFile** files,
                                          gint files_length1,
                                          const gchar* hint);
GType vala_develop_main_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (valaDevelopmainWindow, g_object_unref)
static Block22Data* block22_data_ref (Block22Data* _data22_);
static void block22_data_unref (void * _userdata_);
valaDevelopmainWindow* vala_develop_main_window_new (GtkApplication* application);
valaDevelopmainWindow* vala_develop_main_window_construct (GType object_type,
                                                           GtkApplication* application);
static void __lambda14_ (Block22Data* _data22_);
gpointer vala_develop_settings_ref (gpointer instance);
void vala_develop_settings_unref (gpointer instance);
GParamSpec* vala_develop_param_spec_settings (const gchar* name,
                                              const gchar* nick,
                                              const gchar* blurb,
                                              GType object_type,
                                              GParamFlags flags);
void vala_develop_value_set_settings (GValue* value,
                                      gpointer v_object);
void vala_develop_value_take_settings (GValue* value,
                                       gpointer v_object);
gpointer vala_develop_value_get_settings (const GValue* value);
GType vala_develop_settings_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (valaDevelopSettings, vala_develop_settings_unref)
valaDevelopSettings* vala_develop_xml_configuration_get_Setting (void);
gchar* vala_develop_settings_get (valaDevelopSettings* self,
                                  const gchar* key);
void vala_develop_main_window_LoadSolution (valaDevelopmainWindow* self,
                                            const gchar* vsln);
static void ___lambda14__gtk_widget_realize (GtkWidget* _sender,
                                      gpointer self);
static void vala_develop_vala_develop_real_activate (GApplication* base);
static Block23Data* block23_data_ref (Block23Data* _data23_);
static void block23_data_unref (void * _userdata_);
static void __lambda18_ (Block23Data* _data23_);
static void ___lambda18__gtk_widget_realize (GtkWidget* _sender,
                                      gpointer self);
static void vala_develop_vala_develop_finalize (GObject * obj);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);

/** Application entry point */
static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}

static gchar*
string_replace (const gchar* self,
                const gchar* old,
                const gchar* replacement)
{
	gchar* result = NULL;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	GError* _inner_error0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	if ((*((gchar*) self)) == '\0') {
		_tmp1_ = TRUE;
	} else {
		_tmp1_ = (*((gchar*) old)) == '\0';
	}
	if (_tmp1_) {
		_tmp0_ = TRUE;
	} else {
		_tmp0_ = g_strcmp0 (old, replacement) == 0;
	}
	if (_tmp0_) {
		gchar* _tmp2_;
		_tmp2_ = g_strdup (self);
		result = _tmp2_;
		return result;
	}
	{
		GRegex* regex = NULL;
		gchar* _tmp3_;
		gchar* _tmp4_;
		GRegex* _tmp5_;
		GRegex* _tmp6_;
		gchar* _tmp7_ = NULL;
		GRegex* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		_tmp3_ = g_regex_escape_string (old, -1);
		_tmp4_ = _tmp3_;
		_tmp5_ = g_regex_new (_tmp4_, 0, 0, &_inner_error0_);
		_tmp6_ = _tmp5_;
		_g_free0 (_tmp4_);
		regex = _tmp6_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			if (_inner_error0_->domain == G_REGEX_ERROR) {
				goto __catch45_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return NULL;
		}
		_tmp8_ = regex;
		_tmp9_ = g_regex_replace_literal (_tmp8_, self, (gssize) -1, 0, replacement, 0, &_inner_error0_);
		_tmp7_ = _tmp9_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_regex_unref0 (regex);
			if (_inner_error0_->domain == G_REGEX_ERROR) {
				goto __catch45_g_regex_error;
			}
			_g_regex_unref0 (regex);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return NULL;
		}
		_tmp10_ = _tmp7_;
		_tmp7_ = NULL;
		result = _tmp10_;
		_g_free0 (_tmp7_);
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally45;
	__catch45_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		g_assert_not_reached ();
		_g_error_free0 (e);
	}
	__finally45:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return NULL;
	}
}

gint
vala_develop_vala_develop_main (gchar** args,
                                gint args_length1)
{
	gint result = 0;
	gchar** spawn_args = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar** _tmp2_;
	gint spawn_args_length1;
	gint _spawn_args_size_;
	gchar** spawn_env = NULL;
	gchar** _tmp3_;
	gchar** _tmp4_;
	gint spawn_env_length1;
	gint _spawn_env_size_;
	gchar* ls_stdout = NULL;
	gchar* ls_stderr = NULL;
	gint ls_status = 0;
	gchar** _tmp5_;
	gint _tmp5__length1;
	gchar** _tmp6_;
	gint _tmp6__length1;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	gchar** lines = NULL;
	const gchar* _tmp11_;
	gchar** _tmp12_;
	gchar** _tmp13_;
	gint lines_length1;
	gint _lines_size_;
	gchar* valaversion = NULL;
	gchar* _tmp14_;
	gchar** _tmp15_;
	gint _tmp15__length1;
	gchar* _tmp40_;
	gchar* _tmp41_;
	const gchar* _tmp42_;
	gchar* _tmp43_;
	gchar** _tmp44_;
	gchar** _tmp45_;
	gint _tmp45__length1;
	gchar** _tmp46_;
	gint _tmp46__length1;
	gchar* _tmp47_ = NULL;
	gchar* _tmp48_ = NULL;
	gint _tmp49_ = 0;
	const gchar* _tmp51_;
	gchar* _tmp52_;
	gchar* _tmp53_;
	gchar* _tmp54_;
	valaDevelopvalaDevelop* app = NULL;
	valaDevelopvalaDevelop* _tmp55_;
	valaDevelopvalaDevelop* _tmp56_;
	GError* _inner_error0_ = NULL;
	setlocale (LC_ALL, "");
	bindtextdomain ("valaDevelop", "/usr/share/locale");
	bind_textdomain_codeset ("valaDevelop", "UTF-8");
	textdomain ("valaDevelop");
	g_set_application_name ("valaDevelop");
	_tmp0_ = g_strdup ("dpkg-query");
	_tmp1_ = g_strdup ("-W");
	_tmp2_ = g_new0 (gchar*, 2 + 1);
	_tmp2_[0] = _tmp0_;
	_tmp2_[1] = _tmp1_;
	spawn_args = _tmp2_;
	spawn_args_length1 = 2;
	_spawn_args_size_ = spawn_args_length1;
	_tmp4_ = _tmp3_ = g_get_environ ();
	spawn_env = _tmp4_;
	spawn_env_length1 = _vala_array_length (_tmp3_);
	_spawn_env_size_ = spawn_env_length1;
	_tmp5_ = spawn_args;
	_tmp5__length1 = spawn_args_length1;
	_tmp6_ = spawn_env;
	_tmp6__length1 = spawn_env_length1;
	g_spawn_sync (".", _tmp5_, _tmp6_, G_SPAWN_SEARCH_PATH, NULL, NULL, &_tmp7_, &_tmp8_, &_tmp9_, &_inner_error0_);
	_g_free0 (ls_stdout);
	ls_stdout = _tmp7_;
	_g_free0 (ls_stderr);
	ls_stderr = _tmp8_;
	ls_status = _tmp9_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		gint _tmp10_ = -1;
		_g_free0 (ls_stderr);
		_g_free0 (ls_stdout);
		spawn_env = (_vala_array_free (spawn_env, spawn_env_length1, (GDestroyNotify) g_free), NULL);
		spawn_args = (_vala_array_free (spawn_args, spawn_args_length1, (GDestroyNotify) g_free), NULL);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return _tmp10_;
	}
	_tmp11_ = ls_stdout;
	_tmp13_ = _tmp12_ = g_strsplit (_tmp11_, "\n", 0);
	lines = _tmp13_;
	lines_length1 = _vala_array_length (_tmp12_);
	_lines_size_ = lines_length1;
	_tmp14_ = g_strdup ("libvala-0");
	valaversion = _tmp14_;
	_tmp15_ = lines;
	_tmp15__length1 = lines_length1;
	{
		gchar** line_collection = NULL;
		gint line_collection_length1 = 0;
		gint _line_collection_size_ = 0;
		gint line_it = 0;
		line_collection = _tmp15_;
		line_collection_length1 = _tmp15__length1;
		for (line_it = 0; line_it < _tmp15__length1; line_it = line_it + 1) {
			gchar* _tmp16_;
			gchar* line = NULL;
			_tmp16_ = g_strdup (line_collection[line_it]);
			line = _tmp16_;
			{
				gchar** names = NULL;
				const gchar* _tmp17_;
				gchar** _tmp18_;
				gchar** _tmp19_;
				gint names_length1;
				gint _names_size_;
				gboolean _tmp20_ = FALSE;
				gchar** _tmp21_;
				gint _tmp21__length1;
				const gchar* _tmp22_;
				_tmp17_ = line;
				_tmp19_ = _tmp18_ = g_strsplit (_tmp17_, ":", 0);
				names = _tmp19_;
				names_length1 = _vala_array_length (_tmp18_);
				_names_size_ = names_length1;
				_tmp21_ = names;
				_tmp21__length1 = names_length1;
				_tmp22_ = _tmp21_[0];
				if (g_str_has_prefix (_tmp22_, "libvala-")) {
					gchar** _tmp23_;
					gint _tmp23__length1;
					const gchar* _tmp24_;
					_tmp23_ = names;
					_tmp23__length1 = names_length1;
					_tmp24_ = _tmp23_[0];
					_tmp20_ = !g_str_has_suffix (_tmp24_, "-dev");
				} else {
					_tmp20_ = FALSE;
				}
				if (_tmp20_) {
					gchar** tmp = NULL;
					gchar** _tmp25_;
					gint _tmp25__length1;
					const gchar* _tmp26_;
					gchar** _tmp27_;
					gchar** _tmp28_;
					gint tmp_length1;
					gint _tmp_size_;
					gchar** _tmp29_;
					gint _tmp29__length1;
					const gchar* _tmp30_;
					const gchar* _tmp31_;
					gchar* _tmp32_;
					gchar** _tmp33_;
					gint _tmp33__length1;
					const gchar* _tmp34_;
					const gchar* _tmp35_;
					gchar** _tmp36_;
					gint _tmp36__length1;
					const gchar* _tmp37_;
					const gchar* _tmp38_;
					gchar* _tmp39_;
					_tmp25_ = names;
					_tmp25__length1 = names_length1;
					_tmp26_ = _tmp25_[0];
					_tmp28_ = _tmp27_ = g_strsplit (_tmp26_, "-", 0);
					tmp = _tmp28_;
					tmp_length1 = _vala_array_length (_tmp27_);
					_tmp_size_ = tmp_length1;
					_tmp29_ = tmp;
					_tmp29__length1 = tmp_length1;
					_tmp30_ = _tmp29_[1];
					_tmp31_ = string_to_string (_tmp30_);
					_tmp32_ = g_strconcat ("-", _tmp31_, NULL);
					_g_free0 (vala_develop_vala_develop_package_suffix);
					vala_develop_vala_develop_package_suffix = _tmp32_;
					_tmp33_ = tmp;
					_tmp33__length1 = tmp_length1;
					_tmp34_ = _tmp33_[0];
					_tmp35_ = string_to_string (_tmp34_);
					_tmp36_ = tmp;
					_tmp36__length1 = tmp_length1;
					_tmp37_ = _tmp36_[1];
					_tmp38_ = string_to_string (_tmp37_);
					_tmp39_ = g_strconcat (_tmp35_, "-", _tmp38_, NULL);
					_g_free0 (valaversion);
					valaversion = _tmp39_;
					tmp = (_vala_array_free (tmp, tmp_length1, (GDestroyNotify) g_free), NULL);
					names = (_vala_array_free (names, names_length1, (GDestroyNotify) g_free), NULL);
					_g_free0 (line);
					break;
				}
				names = (_vala_array_free (names, names_length1, (GDestroyNotify) g_free), NULL);
				_g_free0 (line);
			}
		}
	}
	_tmp40_ = g_strdup ("pkg-config");
	_tmp41_ = g_strdup ("--variable=vapidir");
	_tmp42_ = valaversion;
	_tmp43_ = g_strdup (_tmp42_);
	_tmp44_ = g_new0 (gchar*, 3 + 1);
	_tmp44_[0] = _tmp40_;
	_tmp44_[1] = _tmp41_;
	_tmp44_[2] = _tmp43_;
	spawn_args = (_vala_array_free (spawn_args, spawn_args_length1, (GDestroyNotify) g_free), NULL);
	spawn_args = _tmp44_;
	spawn_args_length1 = 3;
	_spawn_args_size_ = spawn_args_length1;
	_tmp45_ = spawn_args;
	_tmp45__length1 = spawn_args_length1;
	_tmp46_ = spawn_env;
	_tmp46__length1 = spawn_env_length1;
	g_spawn_sync (".", _tmp45_, _tmp46_, G_SPAWN_SEARCH_PATH, NULL, NULL, &_tmp47_, &_tmp48_, &_tmp49_, &_inner_error0_);
	_g_free0 (ls_stdout);
	ls_stdout = _tmp47_;
	_g_free0 (ls_stderr);
	ls_stderr = _tmp48_;
	ls_status = _tmp49_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		gint _tmp50_ = -1;
		_g_free0 (valaversion);
		lines = (_vala_array_free (lines, lines_length1, (GDestroyNotify) g_free), NULL);
		_g_free0 (ls_stderr);
		_g_free0 (ls_stdout);
		spawn_env = (_vala_array_free (spawn_env, spawn_env_length1, (GDestroyNotify) g_free), NULL);
		spawn_args = (_vala_array_free (spawn_args, spawn_args_length1, (GDestroyNotify) g_free), NULL);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return _tmp50_;
	}
	_tmp51_ = ls_stdout;
	_tmp52_ = string_replace (_tmp51_, "/vapi", "");
	_tmp53_ = _tmp52_;
	_tmp54_ = string_replace (_tmp53_, "\n", "");
	_g_free0 (vala_develop_vala_develop_package_datadir);
	vala_develop_vala_develop_package_datadir = _tmp54_;
	_g_free0 (_tmp53_);
	_tmp55_ = vala_develop_vala_develop_new ();
	app = _tmp55_;
	_tmp56_ = app;
	result = g_application_run ((GApplication*) _tmp56_, (gint) args_length1, args);
	_g_object_unref0 (app);
	_g_free0 (valaversion);
	lines = (_vala_array_free (lines, lines_length1, (GDestroyNotify) g_free), NULL);
	_g_free0 (ls_stderr);
	_g_free0 (ls_stdout);
	spawn_env = (_vala_array_free (spawn_env, spawn_env_length1, (GDestroyNotify) g_free), NULL);
	spawn_args = (_vala_array_free (spawn_args, spawn_args_length1, (GDestroyNotify) g_free), NULL);
	return result;
}

int
main (int argc,
      char ** argv)
{
	return vala_develop_vala_develop_main (argv, argc);
}

valaDevelopvalaDevelop*
vala_develop_vala_develop_construct (GType object_type)
{
	valaDevelopvalaDevelop * self = NULL;
	self = (valaDevelopvalaDevelop*) g_object_new (object_type, "application-id", "valaDevelop.valaDevelop", "flags", G_APPLICATION_NON_UNIQUE | G_APPLICATION_HANDLES_OPEN, NULL);
	return self;
}

valaDevelopvalaDevelop*
vala_develop_vala_develop_new (void)
{
	return vala_develop_vala_develop_construct (VALA_DEVELOP_TYPE_VALA_DEVELOP);
}

static void
vala_develop_vala_develop_real_startup (GApplication* base)
{
	valaDevelopvalaDevelop * self;
	self = (valaDevelopvalaDevelop*) base;
	G_APPLICATION_CLASS (vala_develop_vala_develop_parent_class)->startup ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_application_get_type (), GtkApplication));
	vala_develop_xml_configuration_load ();
}

static Block22Data*
block22_data_ref (Block22Data* _data22_)
{
	g_atomic_int_inc (&_data22_->_ref_count_);
	return _data22_;
}

static void
block22_data_unref (void * _userdata_)
{
	Block22Data* _data22_;
	_data22_ = (Block22Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data22_->_ref_count_)) {
		valaDevelopvalaDevelop* self;
		self = _data22_->self;
		_g_object_unref0 (_data22_->window);
		_g_object_unref0 (self);
		g_slice_free (Block22Data, _data22_);
	}
}

static void
__lambda14_ (Block22Data* _data22_)
{
	valaDevelopvalaDevelop* self;
	gchar* _tmp0_ = NULL;
	valaDevelopSettings* _tmp1_;
	valaDevelopSettings* _tmp2_;
	gchar* _tmp3_;
	gint x = 0;
	gchar* _tmp5_ = NULL;
	valaDevelopSettings* _tmp6_;
	valaDevelopSettings* _tmp7_;
	gchar* _tmp8_;
	gint y = 0;
	gchar* _tmp10_ = NULL;
	valaDevelopSettings* _tmp11_;
	valaDevelopSettings* _tmp12_;
	gchar* _tmp13_;
	gint width = 0;
	gchar* _tmp15_ = NULL;
	valaDevelopSettings* _tmp16_;
	valaDevelopSettings* _tmp17_;
	gchar* _tmp18_;
	gint height = 0;
	gchar* _tmp20_ = NULL;
	valaDevelopSettings* _tmp21_;
	valaDevelopSettings* _tmp22_;
	gchar* _tmp23_;
	GdkWindowState state = 0U;
	GdkWindowState _tmp25_;
	GFile* _tmp27_;
	gchar* _tmp28_;
	gchar* _tmp29_;
	self = _data22_->self;
	_tmp1_ = vala_develop_xml_configuration_get_Setting ();
	_tmp2_ = _tmp1_;
	_tmp3_ = vala_develop_settings_get (_tmp2_, "xpos");
	_tmp0_ = _tmp3_;
	if (_tmp0_ == NULL) {
		gchar* _tmp4_;
		_tmp4_ = g_strdup ("0");
		_g_free0 (_tmp0_);
		_tmp0_ = _tmp4_;
	}
	x = atoi (_tmp0_);
	_tmp6_ = vala_develop_xml_configuration_get_Setting ();
	_tmp7_ = _tmp6_;
	_tmp8_ = vala_develop_settings_get (_tmp7_, "ypos");
	_tmp5_ = _tmp8_;
	if (_tmp5_ == NULL) {
		gchar* _tmp9_;
		_tmp9_ = g_strdup ("0");
		_g_free0 (_tmp5_);
		_tmp5_ = _tmp9_;
	}
	y = atoi (_tmp5_);
	gtk_window_move ((GtkWindow*) _data22_->window, x, y);
	_tmp11_ = vala_develop_xml_configuration_get_Setting ();
	_tmp12_ = _tmp11_;
	_tmp13_ = vala_develop_settings_get (_tmp12_, "width");
	_tmp10_ = _tmp13_;
	if (_tmp10_ == NULL) {
		gchar* _tmp14_;
		_tmp14_ = g_strdup ("800");
		_g_free0 (_tmp10_);
		_tmp10_ = _tmp14_;
	}
	width = atoi (_tmp10_);
	_tmp16_ = vala_develop_xml_configuration_get_Setting ();
	_tmp17_ = _tmp16_;
	_tmp18_ = vala_develop_settings_get (_tmp17_, "height");
	_tmp15_ = _tmp18_;
	if (_tmp15_ == NULL) {
		gchar* _tmp19_;
		_tmp19_ = g_strdup ("600");
		_g_free0 (_tmp15_);
		_tmp15_ = _tmp19_;
	}
	height = atoi (_tmp15_);
	gtk_window_resize ((GtkWindow*) _data22_->window, width, height);
	_tmp21_ = vala_develop_xml_configuration_get_Setting ();
	_tmp22_ = _tmp21_;
	_tmp23_ = vala_develop_settings_get (_tmp22_, "state");
	_tmp20_ = _tmp23_;
	if (_tmp20_ == NULL) {
		gchar* _tmp24_;
		_tmp24_ = g_strdup ("43908");
		_g_free0 (_tmp20_);
		_tmp20_ = _tmp24_;
	}
	state = (GdkWindowState) atoi (_tmp20_);
	_tmp25_ = state;
	if ((_tmp25_ & GDK_WINDOW_STATE_FULLSCREEN) != 0) {
		gtk_window_fullscreen ((GtkWindow*) _data22_->window);
	} else {
		GdkWindowState _tmp26_;
		_tmp26_ = state;
		if ((_tmp26_ & GDK_WINDOW_STATE_MAXIMIZED) != 0) {
			gtk_window_maximize ((GtkWindow*) _data22_->window);
		}
	}
	_tmp27_ = _data22_->files[0];
	_tmp28_ = g_file_get_path (_tmp27_);
	_tmp29_ = _tmp28_;
	vala_develop_main_window_LoadSolution (_data22_->window, _tmp29_);
	_g_free0 (_tmp29_);
	_g_free0 (_tmp20_);
	_g_free0 (_tmp15_);
	_g_free0 (_tmp10_);
	_g_free0 (_tmp5_);
	_g_free0 (_tmp0_);
}

static void
___lambda14__gtk_widget_realize (GtkWidget* _sender,
                                 gpointer self)
{
	__lambda14_ (self);
}

static void
vala_develop_vala_develop_real_open (GApplication* base,
                                     GFile** files,
                                     gint files_length1,
                                     const gchar* hint)
{
	valaDevelopvalaDevelop * self;
	Block22Data* _data22_;
	valaDevelopmainWindow* _tmp0_;
	self = (valaDevelopvalaDevelop*) base;
	g_return_if_fail (hint != NULL);
	_data22_ = g_slice_new0 (Block22Data);
	_data22_->_ref_count_ = 1;
	_data22_->self = g_object_ref (self);
	_data22_->files = files;
	_data22_->files_length1 = files_length1;
	_tmp0_ = vala_develop_main_window_new ((GtkApplication*) self);
	g_object_ref_sink (_tmp0_);
	_data22_->window = _tmp0_;
	g_signal_connect_data ((GtkWidget*) _data22_->window, "realize", (GCallback) ___lambda14__gtk_widget_realize, block22_data_ref (_data22_), (GClosureNotify) block22_data_unref, 0);
	gtk_widget_show_all ((GtkWidget*) _data22_->window);
	block22_data_unref (_data22_);
	_data22_ = NULL;
}

static Block23Data*
block23_data_ref (Block23Data* _data23_)
{
	g_atomic_int_inc (&_data23_->_ref_count_);
	return _data23_;
}

static void
block23_data_unref (void * _userdata_)
{
	Block23Data* _data23_;
	_data23_ = (Block23Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data23_->_ref_count_)) {
		valaDevelopvalaDevelop* self;
		self = _data23_->self;
		_g_object_unref0 (_data23_->window);
		_g_object_unref0 (self);
		g_slice_free (Block23Data, _data23_);
	}
}

static void
__lambda18_ (Block23Data* _data23_)
{
	valaDevelopvalaDevelop* self;
	gchar* _tmp0_ = NULL;
	valaDevelopSettings* _tmp1_;
	valaDevelopSettings* _tmp2_;
	gchar* _tmp3_;
	gint x = 0;
	gchar* _tmp5_ = NULL;
	valaDevelopSettings* _tmp6_;
	valaDevelopSettings* _tmp7_;
	gchar* _tmp8_;
	gint y = 0;
	gchar* _tmp10_ = NULL;
	valaDevelopSettings* _tmp11_;
	valaDevelopSettings* _tmp12_;
	gchar* _tmp13_;
	gint width = 0;
	gchar* _tmp15_ = NULL;
	valaDevelopSettings* _tmp16_;
	valaDevelopSettings* _tmp17_;
	gchar* _tmp18_;
	gint height = 0;
	gchar* _tmp20_ = NULL;
	valaDevelopSettings* _tmp21_;
	valaDevelopSettings* _tmp22_;
	gchar* _tmp23_;
	GdkWindowState state = 0U;
	GdkWindowState _tmp25_;
	self = _data23_->self;
	_tmp1_ = vala_develop_xml_configuration_get_Setting ();
	_tmp2_ = _tmp1_;
	_tmp3_ = vala_develop_settings_get (_tmp2_, "xpos");
	_tmp0_ = _tmp3_;
	if (_tmp0_ == NULL) {
		gchar* _tmp4_;
		_tmp4_ = g_strdup ("0");
		_g_free0 (_tmp0_);
		_tmp0_ = _tmp4_;
	}
	x = atoi (_tmp0_);
	_tmp6_ = vala_develop_xml_configuration_get_Setting ();
	_tmp7_ = _tmp6_;
	_tmp8_ = vala_develop_settings_get (_tmp7_, "ypos");
	_tmp5_ = _tmp8_;
	if (_tmp5_ == NULL) {
		gchar* _tmp9_;
		_tmp9_ = g_strdup ("0");
		_g_free0 (_tmp5_);
		_tmp5_ = _tmp9_;
	}
	y = atoi (_tmp5_);
	gtk_window_move ((GtkWindow*) _data23_->window, x, y);
	_tmp11_ = vala_develop_xml_configuration_get_Setting ();
	_tmp12_ = _tmp11_;
	_tmp13_ = vala_develop_settings_get (_tmp12_, "width");
	_tmp10_ = _tmp13_;
	if (_tmp10_ == NULL) {
		gchar* _tmp14_;
		_tmp14_ = g_strdup ("800");
		_g_free0 (_tmp10_);
		_tmp10_ = _tmp14_;
	}
	width = atoi (_tmp10_);
	_tmp16_ = vala_develop_xml_configuration_get_Setting ();
	_tmp17_ = _tmp16_;
	_tmp18_ = vala_develop_settings_get (_tmp17_, "height");
	_tmp15_ = _tmp18_;
	if (_tmp15_ == NULL) {
		gchar* _tmp19_;
		_tmp19_ = g_strdup ("600");
		_g_free0 (_tmp15_);
		_tmp15_ = _tmp19_;
	}
	height = atoi (_tmp15_);
	gtk_window_resize ((GtkWindow*) _data23_->window, width, height);
	_tmp21_ = vala_develop_xml_configuration_get_Setting ();
	_tmp22_ = _tmp21_;
	_tmp23_ = vala_develop_settings_get (_tmp22_, "state");
	_tmp20_ = _tmp23_;
	if (_tmp20_ == NULL) {
		gchar* _tmp24_;
		_tmp24_ = g_strdup ("43908");
		_g_free0 (_tmp20_);
		_tmp20_ = _tmp24_;
	}
	state = (GdkWindowState) atoi (_tmp20_);
	_tmp25_ = state;
	if ((_tmp25_ & GDK_WINDOW_STATE_FULLSCREEN) != 0) {
		gtk_window_fullscreen ((GtkWindow*) _data23_->window);
	} else {
		GdkWindowState _tmp26_;
		_tmp26_ = state;
		if ((_tmp26_ & GDK_WINDOW_STATE_MAXIMIZED) != 0) {
			gtk_window_maximize ((GtkWindow*) _data23_->window);
		}
	}
	_g_free0 (_tmp20_);
	_g_free0 (_tmp15_);
	_g_free0 (_tmp10_);
	_g_free0 (_tmp5_);
	_g_free0 (_tmp0_);
}

static void
___lambda18__gtk_widget_realize (GtkWidget* _sender,
                                 gpointer self)
{
	__lambda18_ (self);
}

static void
vala_develop_vala_develop_real_activate (GApplication* base)
{
	valaDevelopvalaDevelop * self;
	Block23Data* _data23_;
	valaDevelopmainWindow* _tmp0_;
	self = (valaDevelopvalaDevelop*) base;
	_data23_ = g_slice_new0 (Block23Data);
	_data23_->_ref_count_ = 1;
	_data23_->self = g_object_ref (self);
	_tmp0_ = vala_develop_main_window_new ((GtkApplication*) self);
	g_object_ref_sink (_tmp0_);
	_data23_->window = _tmp0_;
	g_signal_connect_data ((GtkWidget*) _data23_->window, "realize", (GCallback) ___lambda18__gtk_widget_realize, block23_data_ref (_data23_), (GClosureNotify) block23_data_unref, 0);
	gtk_widget_show_all ((GtkWidget*) _data23_->window);
	block23_data_unref (_data23_);
	_data23_ = NULL;
}

static void
vala_develop_vala_develop_class_init (valaDevelopvalaDevelopClass * klass,
                                      gpointer klass_data)
{
	vala_develop_vala_develop_parent_class = g_type_class_peek_parent (klass);
	((GApplicationClass *) klass)->startup = (void (*) (GApplication*)) vala_develop_vala_develop_real_startup;
	((GApplicationClass *) klass)->open = (void (*) (GApplication*, GFile**, gint, const gchar*)) vala_develop_vala_develop_real_open;
	((GApplicationClass *) klass)->activate = (void (*) (GApplication*)) vala_develop_vala_develop_real_activate;
	G_OBJECT_CLASS (klass)->finalize = vala_develop_vala_develop_finalize;
}

static void
vala_develop_vala_develop_instance_init (valaDevelopvalaDevelop * self,
                                         gpointer klass)
{
}

static void
vala_develop_vala_develop_finalize (GObject * obj)
{
	valaDevelopvalaDevelop * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALA_DEVELOP_TYPE_VALA_DEVELOP, valaDevelopvalaDevelop);
	G_OBJECT_CLASS (vala_develop_vala_develop_parent_class)->finalize (obj);
}

/**
     * Application
     */
GType
vala_develop_vala_develop_get_type (void)
{
	static volatile gsize vala_develop_vala_develop_type_id__volatile = 0;
	if (g_once_init_enter (&vala_develop_vala_develop_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (valaDevelopvalaDevelopClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_develop_vala_develop_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (valaDevelopvalaDevelop), 0, (GInstanceInitFunc) vala_develop_vala_develop_instance_init, NULL };
		GType vala_develop_vala_develop_type_id;
		vala_develop_vala_develop_type_id = g_type_register_static (gtk_application_get_type (), "valaDevelopvalaDevelop", &g_define_type_info, 0);
		g_once_init_leave (&vala_develop_vala_develop_type_id__volatile, vala_develop_vala_develop_type_id);
	}
	return vala_develop_vala_develop_type_id__volatile;
}

static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

static gint
_vala_array_length (gpointer array)
{
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}

