/* project_options.c generated by valac UNKNOWN, the Vala compiler
 * generated from project_options.vala, do not modify */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <glib.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <stdlib.h>
#include <string.h>

#define VALA_DEVELOP_TYPE_IOPTION_WIDGET (vala_develop_ioption_widget_get_type ())
#define VALA_DEVELOP_IOPTION_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_IOPTION_WIDGET, valaDevelopIOptionWidget))
#define VALA_DEVELOP_IS_IOPTION_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_IOPTION_WIDGET))
#define VALA_DEVELOP_IOPTION_WIDGET_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), VALA_DEVELOP_TYPE_IOPTION_WIDGET, valaDevelopIOptionWidgetIface))

typedef struct _valaDevelopIOptionWidget valaDevelopIOptionWidget;
typedef struct _valaDevelopIOptionWidgetIface valaDevelopIOptionWidgetIface;

#define VALA_DEVELOP_TYPE_PROJECT_OPTIONS (vala_develop_project_options_get_type ())
#define VALA_DEVELOP_PROJECT_OPTIONS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_PROJECT_OPTIONS, valaDevelopProjectOptions))
#define VALA_DEVELOP_PROJECT_OPTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_PROJECT_OPTIONS, valaDevelopProjectOptionsClass))
#define VALA_DEVELOP_IS_PROJECT_OPTIONS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_PROJECT_OPTIONS))
#define VALA_DEVELOP_IS_PROJECT_OPTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_PROJECT_OPTIONS))
#define VALA_DEVELOP_PROJECT_OPTIONS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_PROJECT_OPTIONS, valaDevelopProjectOptionsClass))

typedef struct _valaDevelopProjectOptions valaDevelopProjectOptions;
typedef struct _valaDevelopProjectOptionsClass valaDevelopProjectOptionsClass;
typedef struct _valaDevelopProjectOptionsPrivate valaDevelopProjectOptionsPrivate;
enum  {
	VALA_DEVELOP_PROJECT_OPTIONS_0_PROPERTY,
	VALA_DEVELOP_PROJECT_OPTIONS_NUM_PROPERTIES
};
static GParamSpec* vala_develop_project_options_properties[VALA_DEVELOP_PROJECT_OPTIONS_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE (vala_develop_overview_tree_store_get_type ())
#define VALA_DEVELOP_OVERVIEW_TREE_STORE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE, valaDevelopOverviewTreeStore))
#define VALA_DEVELOP_OVERVIEW_TREE_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE, valaDevelopOverviewTreeStoreClass))
#define VALA_DEVELOP_IS_OVERVIEW_TREE_STORE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE))
#define VALA_DEVELOP_IS_OVERVIEW_TREE_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE))
#define VALA_DEVELOP_OVERVIEW_TREE_STORE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE, valaDevelopOverviewTreeStoreClass))

typedef struct _valaDevelopOverviewTreeStore valaDevelopOverviewTreeStore;
typedef struct _valaDevelopOverviewTreeStoreClass valaDevelopOverviewTreeStoreClass;
typedef enum  {
	VALA_DEVELOP_ITEM_BUILD_TYPE_None,
	VALA_DEVELOP_ITEM_BUILD_TYPE_Compile,
	VALA_DEVELOP_ITEM_BUILD_TYPE_Resource,
	VALA_DEVELOP_ITEM_BUILD_TYPE_Package,
	VALA_DEVELOP_ITEM_BUILD_TYPE_Executable,
	VALA_DEVELOP_ITEM_BUILD_TYPE_SharedObject
} valaDevelopItemBuildType;

#define VALA_DEVELOP_TYPE_ITEM_BUILD_TYPE (vala_develop_item_build_type_get_type ())
#define _g_free0(var) (var = (g_free (var), NULL))

struct _valaDevelopIOptionWidgetIface {
	GTypeInterface parent_iface;
	void (*get_iter) (valaDevelopIOptionWidget* self, GtkTreeIter * value);
	void (*set_iter) (valaDevelopIOptionWidget* self, GtkTreeIter * value);
};

struct _valaDevelopProjectOptions {
	GtkBox parent_instance;
	valaDevelopProjectOptionsPrivate * priv;
};

struct _valaDevelopProjectOptionsClass {
	GtkBoxClass parent_class;
};

struct _valaDevelopProjectOptionsPrivate {
	GtkEntry* fileName;
	GtkEntry* defaultnamespace;
	GtkEntry* fileRoot;
	GtkRadioButton* executable;
	GtkRadioButton* shared;
	GtkCheckButton* vapi;
	GtkTreeIter _iter;
};

static gint valaDevelopProjectOptions_private_offset;
static gpointer vala_develop_project_options_parent_class = NULL;
extern valaDevelopOverviewTreeStore* vala_develop_main_paned_overviewTreeModel;
static valaDevelopIOptionWidgetIface * vala_develop_project_options_vala_develop_ioption_widget_parent_iface = NULL;

GType vala_develop_ioption_widget_get_type (void) G_GNUC_CONST;
GType vala_develop_project_options_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (valaDevelopProjectOptions, g_object_unref)
valaDevelopProjectOptions* vala_develop_project_options_new (GtkTreeIter* iter);
valaDevelopProjectOptions* vala_develop_project_options_construct (GType object_type,
                                                                   GtkTreeIter* iter);
void vala_develop_ioption_widget_set_iter (valaDevelopIOptionWidget* self,
                                           GtkTreeIter * value);
GType vala_develop_overview_tree_store_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (valaDevelopOverviewTreeStore, g_object_unref)
static void vala_develop_project_options_Model_RowChanged (valaDevelopProjectOptions* self,
                                                    GtkTreePath* path,
                                                    GtkTreeIter* iter);
static void _vala_develop_project_options_Model_RowChanged_gtk_tree_model_row_changed (GtkTreeModel* _sender,
                                                                                GtkTreePath* path,
                                                                                GtkTreeIter* iter,
                                                                                gpointer self);
static void vala_develop_project_options_Executable_Toggled (valaDevelopProjectOptions* self);
GType vala_develop_item_build_type_get_type (void) G_GNUC_CONST;
void vala_develop_overview_tree_store_set_item_buildtype (valaDevelopOverviewTreeStore* self,
                                                          GtkTreeIter* iter,
                                                          gint itemBuildType);
void vala_develop_overview_tree_store_set_item_pixbuf (valaDevelopOverviewTreeStore* self,
                                                       GtkTreeIter* iter,
                                                       GdkPixbuf* itemPixbuf);
gboolean vala_develop_overview_tree_store_save_project (valaDevelopOverviewTreeStore* self,
                                                        GtkTreeIter* iter);
static void vala_develop_project_options_Vapi_Toggled (valaDevelopProjectOptions* self);
void vala_develop_overview_tree_store_set_item_withvapi (valaDevelopOverviewTreeStore* self,
                                                         GtkTreeIter* iter,
                                                         gboolean withVapi);
static void vala_develop_project_options_Shared_Toggled (valaDevelopProjectOptions* self);
static gboolean _gtk_tree_iter_equal (const GtkTreeIter * s1,
                               const GtkTreeIter * s2);
gchar* vala_develop_overview_tree_store_get_item_name (valaDevelopOverviewTreeStore* self,
                                                       GtkTreeIter* iter);
gchar* vala_develop_overview_tree_store_get_item_namespace (valaDevelopOverviewTreeStore* self,
                                                            GtkTreeIter* iter);
gchar* vala_develop_overview_tree_store_get_item_path (valaDevelopOverviewTreeStore* self,
                                                       GtkTreeIter* iter);
gint vala_develop_overview_tree_store_get_item_buildtype (valaDevelopOverviewTreeStore* self,
                                                          GtkTreeIter* iter);
gboolean vala_develop_overview_tree_store_get_item_withvapi (valaDevelopOverviewTreeStore* self,
                                                             GtkTreeIter* iter);
static void _vala_develop_project_options_Executable_Toggled_gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                                                                 gpointer self);
static void _vala_develop_project_options_Vapi_Toggled_gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                                                           gpointer self);
static void _vala_develop_project_options_Shared_Toggled_gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                                                             gpointer self);
static void vala_develop_project_options_finalize (GObject * obj);
static void _vala_vala_develop_project_options_get_property (GObject * object,
                                                      guint property_id,
                                                      GValue * value,
                                                      GParamSpec * pspec);
static void _vala_vala_develop_project_options_set_property (GObject * object,
                                                      guint property_id,
                                                      const GValue * value,
                                                      GParamSpec * pspec);

static inline gpointer
vala_develop_project_options_get_instance_private (valaDevelopProjectOptions* self)
{
	return G_STRUCT_MEMBER_P (self, valaDevelopProjectOptions_private_offset);
}

static void
_vala_develop_project_options_Model_RowChanged_gtk_tree_model_row_changed (GtkTreeModel* _sender,
                                                                           GtkTreePath* path,
                                                                           GtkTreeIter* iter,
                                                                           gpointer self)
{
#line 18 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	vala_develop_project_options_Model_RowChanged ((valaDevelopProjectOptions*) self, path, iter);
#line 162 "project_options.c"
}

valaDevelopProjectOptions*
vala_develop_project_options_construct (GType object_type,
                                        GtkTreeIter* iter)
{
	valaDevelopProjectOptions * self = NULL;
	GtkTreeIter _tmp0_;
	valaDevelopOverviewTreeStore* _tmp1_;
#line 15 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	g_return_val_if_fail (iter != NULL, NULL);
#line 15 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	self = (valaDevelopProjectOptions*) g_object_new (object_type, NULL);
#line 17 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp0_ = *iter;
#line 17 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	vala_develop_ioption_widget_set_iter ((valaDevelopIOptionWidget*) self, &_tmp0_);
#line 18 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp1_ = vala_develop_main_paned_overviewTreeModel;
#line 18 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	g_signal_connect_object ((GtkTreeModel*) _tmp1_, "row-changed", (GCallback) _vala_develop_project_options_Model_RowChanged_gtk_tree_model_row_changed, self, 0);
#line 15 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	return self;
#line 186 "project_options.c"
}

valaDevelopProjectOptions*
vala_develop_project_options_new (GtkTreeIter* iter)
{
#line 15 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	return vala_develop_project_options_construct (VALA_DEVELOP_TYPE_PROJECT_OPTIONS, iter);
#line 194 "project_options.c"
}

static void
vala_develop_project_options_Executable_Toggled (valaDevelopProjectOptions* self)
{
	valaDevelopItemBuildType _tmp0_ = 0;
	GtkRadioButton* _tmp1_;
	gboolean _tmp2_;
	gboolean _tmp3_;
	valaDevelopOverviewTreeStore* _tmp4_;
	GtkTreeIter _tmp5_;
	GtkRadioButton* _tmp6_;
	gboolean _tmp7_;
	gboolean _tmp8_;
	valaDevelopOverviewTreeStore* _tmp21_;
	GtkTreeIter _tmp22_;
	GError* _inner_error0_ = NULL;
#line 51 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	g_return_if_fail (self != NULL);
#line 53 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp1_ = self->priv->executable;
#line 53 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp2_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp1_);
#line 53 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp3_ = _tmp2_;
#line 53 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	if (_tmp3_) {
#line 53 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp0_ = VALA_DEVELOP_ITEM_BUILD_TYPE_Executable;
#line 224 "project_options.c"
	} else {
#line 53 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp0_ = VALA_DEVELOP_ITEM_BUILD_TYPE_SharedObject;
#line 228 "project_options.c"
	}
#line 53 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp4_ = vala_develop_main_paned_overviewTreeModel;
#line 53 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp5_ = self->priv->_iter;
#line 53 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	vala_develop_overview_tree_store_set_item_buildtype (_tmp4_, &_tmp5_, (gint) _tmp0_);
#line 54 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp6_ = self->priv->executable;
#line 54 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp7_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp6_);
#line 54 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp8_ = _tmp7_;
#line 54 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	if (_tmp8_) {
#line 244 "project_options.c"
		GdkPixbuf* _tmp9_ = NULL;
		GdkPixbuf* _tmp10_;
		valaDevelopOverviewTreeStore* _tmp11_;
		GtkTreeIter _tmp12_;
		GdkPixbuf* _tmp13_;
		GdkPixbuf* _tmp14_;
#line 55 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp10_ = gdk_pixbuf_new_from_resource ("/valaDevelop/project.svg.png", &_inner_error0_);
#line 55 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp9_ = _tmp10_;
#line 55 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 55 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 55 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
			g_clear_error (&_inner_error0_);
#line 55 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
			return;
#line 263 "project_options.c"
		}
#line 55 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp11_ = vala_develop_main_paned_overviewTreeModel;
#line 55 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp12_ = self->priv->_iter;
#line 55 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp13_ = gdk_pixbuf_scale_simple (_tmp9_, 16, 16, GDK_INTERP_BILINEAR);
#line 55 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp14_ = _tmp13_;
#line 55 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		vala_develop_overview_tree_store_set_item_pixbuf (_tmp11_, &_tmp12_, _tmp14_);
#line 55 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_g_object_unref0 (_tmp14_);
#line 54 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_g_object_unref0 (_tmp9_);
#line 279 "project_options.c"
	} else {
		GdkPixbuf* _tmp15_ = NULL;
		GdkPixbuf* _tmp16_;
		valaDevelopOverviewTreeStore* _tmp17_;
		GtkTreeIter _tmp18_;
		GdkPixbuf* _tmp19_;
		GdkPixbuf* _tmp20_;
#line 57 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp16_ = gdk_pixbuf_new_from_resource ("/valaDevelop/sharedobject.svg.png", &_inner_error0_);
#line 57 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp15_ = _tmp16_;
#line 57 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 57 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 57 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
			g_clear_error (&_inner_error0_);
#line 57 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
			return;
#line 299 "project_options.c"
		}
#line 57 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp17_ = vala_develop_main_paned_overviewTreeModel;
#line 57 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp18_ = self->priv->_iter;
#line 57 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp19_ = gdk_pixbuf_scale_simple (_tmp15_, 16, 16, GDK_INTERP_BILINEAR);
#line 57 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp20_ = _tmp19_;
#line 57 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		vala_develop_overview_tree_store_set_item_pixbuf (_tmp17_, &_tmp18_, _tmp20_);
#line 57 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_g_object_unref0 (_tmp20_);
#line 54 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_g_object_unref0 (_tmp15_);
#line 315 "project_options.c"
	}
#line 58 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp21_ = vala_develop_main_paned_overviewTreeModel;
#line 58 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp22_ = self->priv->_iter;
#line 58 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	vala_develop_overview_tree_store_save_project (_tmp21_, &_tmp22_);
#line 323 "project_options.c"
}

static void
vala_develop_project_options_Vapi_Toggled (valaDevelopProjectOptions* self)
{
	valaDevelopOverviewTreeStore* _tmp0_;
	GtkTreeIter _tmp1_;
	GtkCheckButton* _tmp2_;
	gboolean _tmp3_;
	gboolean _tmp4_;
	valaDevelopOverviewTreeStore* _tmp5_;
	GtkTreeIter _tmp6_;
#line 61 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	g_return_if_fail (self != NULL);
#line 63 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp0_ = vala_develop_main_paned_overviewTreeModel;
#line 63 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp1_ = self->priv->_iter;
#line 63 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp2_ = self->priv->vapi;
#line 63 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp3_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp2_);
#line 63 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp4_ = _tmp3_;
#line 63 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	vala_develop_overview_tree_store_set_item_withvapi (_tmp0_, &_tmp1_, _tmp4_);
#line 64 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp5_ = vala_develop_main_paned_overviewTreeModel;
#line 64 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp6_ = self->priv->_iter;
#line 64 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	vala_develop_overview_tree_store_save_project (_tmp5_, &_tmp6_);
#line 356 "project_options.c"
}

static void
vala_develop_project_options_Shared_Toggled (valaDevelopProjectOptions* self)
{
	valaDevelopItemBuildType _tmp0_ = 0;
	GtkRadioButton* _tmp1_;
	gboolean _tmp2_;
	gboolean _tmp3_;
	valaDevelopOverviewTreeStore* _tmp4_;
	GtkTreeIter _tmp5_;
	GtkRadioButton* _tmp6_;
	gboolean _tmp7_;
	gboolean _tmp8_;
	GtkCheckButton* _tmp21_;
	GtkRadioButton* _tmp22_;
	gboolean _tmp23_;
	gboolean _tmp24_;
	valaDevelopOverviewTreeStore* _tmp25_;
	GtkTreeIter _tmp26_;
	GError* _inner_error0_ = NULL;
#line 67 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	g_return_if_fail (self != NULL);
#line 69 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp1_ = self->priv->shared;
#line 69 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp2_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp1_);
#line 69 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp3_ = _tmp2_;
#line 69 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	if (_tmp3_) {
#line 69 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp0_ = VALA_DEVELOP_ITEM_BUILD_TYPE_SharedObject;
#line 390 "project_options.c"
	} else {
#line 69 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp0_ = VALA_DEVELOP_ITEM_BUILD_TYPE_Executable;
#line 394 "project_options.c"
	}
#line 69 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp4_ = vala_develop_main_paned_overviewTreeModel;
#line 69 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp5_ = self->priv->_iter;
#line 69 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	vala_develop_overview_tree_store_set_item_buildtype (_tmp4_, &_tmp5_, (gint) _tmp0_);
#line 70 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp6_ = self->priv->shared;
#line 70 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp7_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp6_);
#line 70 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp8_ = _tmp7_;
#line 70 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	if (_tmp8_) {
#line 410 "project_options.c"
		GdkPixbuf* _tmp9_ = NULL;
		GdkPixbuf* _tmp10_;
		valaDevelopOverviewTreeStore* _tmp11_;
		GtkTreeIter _tmp12_;
		GdkPixbuf* _tmp13_;
		GdkPixbuf* _tmp14_;
#line 71 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp10_ = gdk_pixbuf_new_from_resource ("/valaDevelop/sharedobject.svg.png", &_inner_error0_);
#line 71 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp9_ = _tmp10_;
#line 71 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 71 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 71 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
			g_clear_error (&_inner_error0_);
#line 71 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
			return;
#line 429 "project_options.c"
		}
#line 71 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp11_ = vala_develop_main_paned_overviewTreeModel;
#line 71 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp12_ = self->priv->_iter;
#line 71 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp13_ = gdk_pixbuf_scale_simple (_tmp9_, 16, 16, GDK_INTERP_BILINEAR);
#line 71 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp14_ = _tmp13_;
#line 71 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		vala_develop_overview_tree_store_set_item_pixbuf (_tmp11_, &_tmp12_, _tmp14_);
#line 71 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_g_object_unref0 (_tmp14_);
#line 70 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_g_object_unref0 (_tmp9_);
#line 445 "project_options.c"
	} else {
		GdkPixbuf* _tmp15_ = NULL;
		GdkPixbuf* _tmp16_;
		valaDevelopOverviewTreeStore* _tmp17_;
		GtkTreeIter _tmp18_;
		GdkPixbuf* _tmp19_;
		GdkPixbuf* _tmp20_;
#line 73 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp16_ = gdk_pixbuf_new_from_resource ("/valaDevelop/project.svg.png", &_inner_error0_);
#line 73 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp15_ = _tmp16_;
#line 73 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 73 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 73 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
			g_clear_error (&_inner_error0_);
#line 73 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
			return;
#line 465 "project_options.c"
		}
#line 73 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp17_ = vala_develop_main_paned_overviewTreeModel;
#line 73 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp18_ = self->priv->_iter;
#line 73 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp19_ = gdk_pixbuf_scale_simple (_tmp15_, 16, 16, GDK_INTERP_BILINEAR);
#line 73 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp20_ = _tmp19_;
#line 73 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		vala_develop_overview_tree_store_set_item_pixbuf (_tmp17_, &_tmp18_, _tmp20_);
#line 73 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_g_object_unref0 (_tmp20_);
#line 70 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_g_object_unref0 (_tmp15_);
#line 481 "project_options.c"
	}
#line 74 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp21_ = self->priv->vapi;
#line 74 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp22_ = self->priv->shared;
#line 74 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp23_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp22_);
#line 74 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp24_ = _tmp23_;
#line 74 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp21_, _tmp24_);
#line 75 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp25_ = vala_develop_main_paned_overviewTreeModel;
#line 75 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp26_ = self->priv->_iter;
#line 75 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	vala_develop_overview_tree_store_save_project (_tmp25_, &_tmp26_);
#line 499 "project_options.c"
}

static gboolean
_gtk_tree_iter_equal (const GtkTreeIter * s1,
                      const GtkTreeIter * s2)
{
#line 80 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	if (s1 == s2) {
#line 80 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		return TRUE;
#line 510 "project_options.c"
	}
#line 80 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	if (s1 == NULL) {
#line 80 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		return FALSE;
#line 516 "project_options.c"
	}
#line 80 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	if (s2 == NULL) {
#line 80 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		return FALSE;
#line 522 "project_options.c"
	}
#line 80 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	if (s1->stamp != s2->stamp) {
#line 80 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		return FALSE;
#line 528 "project_options.c"
	}
#line 80 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	if (s1->user_data != s2->user_data) {
#line 80 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		return FALSE;
#line 534 "project_options.c"
	}
#line 80 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	if (s1->user_data2 != s2->user_data2) {
#line 80 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		return FALSE;
#line 540 "project_options.c"
	}
#line 80 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	if (s1->user_data3 != s2->user_data3) {
#line 80 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		return FALSE;
#line 546 "project_options.c"
	}
#line 80 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	return TRUE;
#line 550 "project_options.c"
}

static void
vala_develop_project_options_Model_RowChanged (valaDevelopProjectOptions* self,
                                               GtkTreePath* path,
                                               GtkTreeIter* iter)
{
	GtkTreeIter _tmp0_;
	GtkTreeIter _tmp1_;
#line 78 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	g_return_if_fail (self != NULL);
#line 78 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	g_return_if_fail (path != NULL);
#line 78 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	g_return_if_fail (iter != NULL);
#line 80 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp0_ = *iter;
#line 80 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp1_ = self->priv->_iter;
#line 80 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	if (_gtk_tree_iter_equal (&_tmp0_, &_tmp1_) == TRUE) {
#line 572 "project_options.c"
		GtkEntry* _tmp2_;
		valaDevelopOverviewTreeStore* _tmp3_;
		GtkTreeIter _tmp4_;
		gchar* _tmp5_;
		gchar* _tmp6_;
		GtkEntry* _tmp7_;
		valaDevelopOverviewTreeStore* _tmp8_;
		GtkTreeIter _tmp9_;
		gchar* _tmp10_;
		gchar* _tmp11_;
		GtkEntry* _tmp12_;
		valaDevelopOverviewTreeStore* _tmp13_;
		GtkTreeIter _tmp14_;
		gchar* _tmp15_;
		gchar* _tmp16_;
		GtkRadioButton* _tmp17_;
		valaDevelopOverviewTreeStore* _tmp18_;
		GtkTreeIter _tmp19_;
		GtkRadioButton* _tmp20_;
		valaDevelopOverviewTreeStore* _tmp21_;
		GtkTreeIter _tmp22_;
		GtkCheckButton* _tmp23_;
		valaDevelopOverviewTreeStore* _tmp24_;
		GtkTreeIter _tmp25_;
#line 82 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp2_ = self->priv->fileName;
#line 82 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp3_ = vala_develop_main_paned_overviewTreeModel;
#line 82 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp4_ = *iter;
#line 82 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp5_ = vala_develop_overview_tree_store_get_item_name (_tmp3_, &_tmp4_);
#line 82 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp6_ = _tmp5_;
#line 82 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		gtk_entry_set_text (_tmp2_, _tmp6_);
#line 82 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_g_free0 (_tmp6_);
#line 83 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp7_ = self->priv->defaultnamespace;
#line 83 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp8_ = vala_develop_main_paned_overviewTreeModel;
#line 83 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp9_ = *iter;
#line 83 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp10_ = vala_develop_overview_tree_store_get_item_namespace (_tmp8_, &_tmp9_);
#line 83 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp11_ = _tmp10_;
#line 83 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		gtk_entry_set_text (_tmp7_, _tmp11_);
#line 83 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_g_free0 (_tmp11_);
#line 84 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp12_ = self->priv->fileRoot;
#line 84 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp13_ = vala_develop_main_paned_overviewTreeModel;
#line 84 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp14_ = *iter;
#line 84 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp15_ = vala_develop_overview_tree_store_get_item_path (_tmp13_, &_tmp14_);
#line 84 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp16_ = _tmp15_;
#line 84 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		gtk_entry_set_text (_tmp12_, _tmp16_);
#line 84 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_g_free0 (_tmp16_);
#line 85 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp17_ = self->priv->executable;
#line 85 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp18_ = vala_develop_main_paned_overviewTreeModel;
#line 85 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp19_ = *iter;
#line 85 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		gtk_toggle_button_set_active ((GtkToggleButton*) _tmp17_, vala_develop_overview_tree_store_get_item_buildtype (_tmp18_, &_tmp19_) == ((gint) VALA_DEVELOP_ITEM_BUILD_TYPE_Executable));
#line 86 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp20_ = self->priv->shared;
#line 86 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp21_ = vala_develop_main_paned_overviewTreeModel;
#line 86 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp22_ = *iter;
#line 86 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		gtk_toggle_button_set_active ((GtkToggleButton*) _tmp20_, vala_develop_overview_tree_store_get_item_buildtype (_tmp21_, &_tmp22_) == ((gint) VALA_DEVELOP_ITEM_BUILD_TYPE_SharedObject));
#line 87 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp23_ = self->priv->vapi;
#line 87 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp24_ = vala_develop_main_paned_overviewTreeModel;
#line 87 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		_tmp25_ = *iter;
#line 87 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		gtk_toggle_button_set_active ((GtkToggleButton*) _tmp23_, vala_develop_overview_tree_store_get_item_withvapi (_tmp24_, &_tmp25_));
#line 663 "project_options.c"
	}
}

static void
vala_develop_project_options_real_get_iter (valaDevelopIOptionWidget* base,
                                            GtkTreeIter * result)
{
	valaDevelopProjectOptions* self;
	GtkTreeIter _tmp0_;
#line 28 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	self = (valaDevelopProjectOptions*) base;
#line 28 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp0_ = self->priv->_iter;
#line 28 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	*result = _tmp0_;
#line 28 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	return;
#line 681 "project_options.c"
}

static void
_vala_develop_project_options_Executable_Toggled_gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                                                            gpointer self)
{
#line 32 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	vala_develop_project_options_Executable_Toggled ((valaDevelopProjectOptions*) self);
#line 690 "project_options.c"
}

static void
_vala_develop_project_options_Vapi_Toggled_gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                                                      gpointer self)
{
#line 33 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	vala_develop_project_options_Vapi_Toggled ((valaDevelopProjectOptions*) self);
#line 699 "project_options.c"
}

static void
_vala_develop_project_options_Shared_Toggled_gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                                                        gpointer self)
{
#line 34 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	vala_develop_project_options_Shared_Toggled ((valaDevelopProjectOptions*) self);
#line 708 "project_options.c"
}

static void
vala_develop_project_options_real_set_iter (valaDevelopIOptionWidget* base,
                                            GtkTreeIter * value)
{
	valaDevelopProjectOptions* self;
	GtkTreeIter _tmp0_;
	GtkRadioButton* _tmp1_;
	guint _tmp2_;
	GtkCheckButton* _tmp3_;
	guint _tmp4_;
	GtkRadioButton* _tmp5_;
	guint _tmp6_;
	GtkEntry* _tmp7_;
	valaDevelopOverviewTreeStore* _tmp8_;
	GtkTreeIter _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	GtkEntry* _tmp12_;
	valaDevelopOverviewTreeStore* _tmp13_;
	GtkTreeIter _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	GtkEntry* _tmp17_;
	valaDevelopOverviewTreeStore* _tmp18_;
	GtkTreeIter _tmp19_;
	gchar* _tmp20_;
	gchar* _tmp21_;
	gint itemBuildType = 0;
	valaDevelopOverviewTreeStore* _tmp22_;
	GtkTreeIter _tmp23_;
	GtkRadioButton* _tmp24_;
	GtkRadioButton* _tmp25_;
	GtkCheckButton* _tmp26_;
	valaDevelopOverviewTreeStore* _tmp27_;
	GtkTreeIter _tmp28_;
	GtkCheckButton* _tmp29_;
	GtkRadioButton* _tmp30_;
	gboolean _tmp31_;
	gboolean _tmp32_;
	GtkRadioButton* _tmp33_;
	GtkCheckButton* _tmp34_;
	GtkRadioButton* _tmp35_;
#line 29 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	self = (valaDevelopProjectOptions*) base;
#line 31 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp0_ = *value;
#line 31 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	self->priv->_iter = _tmp0_;
#line 32 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp1_ = self->priv->executable;
#line 32 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	g_signal_parse_name ("toggled", gtk_toggle_button_get_type (), &_tmp2_, NULL, FALSE);
#line 32 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	g_signal_handlers_disconnect_matched ((GtkToggleButton*) _tmp1_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp2_, 0, NULL, (GCallback) _vala_develop_project_options_Executable_Toggled_gtk_toggle_button_toggled, self);
#line 33 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp3_ = self->priv->vapi;
#line 33 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	g_signal_parse_name ("toggled", gtk_toggle_button_get_type (), &_tmp4_, NULL, FALSE);
#line 33 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	g_signal_handlers_disconnect_matched ((GtkToggleButton*) _tmp3_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp4_, 0, NULL, (GCallback) _vala_develop_project_options_Vapi_Toggled_gtk_toggle_button_toggled, self);
#line 34 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp5_ = self->priv->shared;
#line 34 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	g_signal_parse_name ("toggled", gtk_toggle_button_get_type (), &_tmp6_, NULL, FALSE);
#line 34 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	g_signal_handlers_disconnect_matched ((GtkToggleButton*) _tmp5_, G_SIGNAL_MATCH_ID | G_SIGNAL_MATCH_FUNC | G_SIGNAL_MATCH_DATA, _tmp6_, 0, NULL, (GCallback) _vala_develop_project_options_Shared_Toggled_gtk_toggle_button_toggled, self);
#line 36 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp7_ = self->priv->fileName;
#line 36 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp8_ = vala_develop_main_paned_overviewTreeModel;
#line 36 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp9_ = self->priv->_iter;
#line 36 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp10_ = vala_develop_overview_tree_store_get_item_name (_tmp8_, &_tmp9_);
#line 36 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp11_ = _tmp10_;
#line 36 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	gtk_entry_set_text (_tmp7_, _tmp11_);
#line 36 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_g_free0 (_tmp11_);
#line 37 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp12_ = self->priv->defaultnamespace;
#line 37 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp13_ = vala_develop_main_paned_overviewTreeModel;
#line 37 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp14_ = self->priv->_iter;
#line 37 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp15_ = vala_develop_overview_tree_store_get_item_namespace (_tmp13_, &_tmp14_);
#line 37 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp16_ = _tmp15_;
#line 37 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	gtk_entry_set_text (_tmp12_, _tmp16_);
#line 37 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_g_free0 (_tmp16_);
#line 38 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp17_ = self->priv->fileRoot;
#line 38 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp18_ = vala_develop_main_paned_overviewTreeModel;
#line 38 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp19_ = self->priv->_iter;
#line 38 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp20_ = vala_develop_overview_tree_store_get_item_path (_tmp18_, &_tmp19_);
#line 38 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp21_ = _tmp20_;
#line 38 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	gtk_entry_set_text (_tmp17_, _tmp21_);
#line 38 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_g_free0 (_tmp21_);
#line 39 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp22_ = vala_develop_main_paned_overviewTreeModel;
#line 39 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp23_ = self->priv->_iter;
#line 39 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	itemBuildType = vala_develop_overview_tree_store_get_item_buildtype (_tmp22_, &_tmp23_);
#line 40 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp24_ = self->priv->executable;
#line 40 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp24_, itemBuildType == ((gint) VALA_DEVELOP_ITEM_BUILD_TYPE_Executable));
#line 41 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp25_ = self->priv->shared;
#line 41 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp25_, itemBuildType == ((gint) VALA_DEVELOP_ITEM_BUILD_TYPE_SharedObject));
#line 42 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp26_ = self->priv->vapi;
#line 42 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp27_ = vala_develop_main_paned_overviewTreeModel;
#line 42 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp28_ = self->priv->_iter;
#line 42 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp26_, vala_develop_overview_tree_store_get_item_withvapi (_tmp27_, &_tmp28_));
#line 43 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp29_ = self->priv->vapi;
#line 43 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp30_ = self->priv->shared;
#line 43 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp31_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp30_);
#line 43 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp32_ = _tmp31_;
#line 43 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	gtk_widget_set_sensitive ((GtkWidget*) _tmp29_, _tmp32_);
#line 45 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp33_ = self->priv->executable;
#line 45 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	g_signal_connect_object ((GtkToggleButton*) _tmp33_, "toggled", (GCallback) _vala_develop_project_options_Executable_Toggled_gtk_toggle_button_toggled, self, 0);
#line 46 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp34_ = self->priv->vapi;
#line 46 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	g_signal_connect_object ((GtkToggleButton*) _tmp34_, "toggled", (GCallback) _vala_develop_project_options_Vapi_Toggled_gtk_toggle_button_toggled, self, 0);
#line 47 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_tmp35_ = self->priv->shared;
#line 47 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	g_signal_connect_object ((GtkToggleButton*) _tmp35_, "toggled", (GCallback) _vala_develop_project_options_Shared_Toggled_gtk_toggle_button_toggled, self, 0);
#line 863 "project_options.c"
}

static void
vala_develop_project_options_class_init (valaDevelopProjectOptionsClass * klass,
                                         gpointer klass_data)
{
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	vala_develop_project_options_parent_class = g_type_class_peek_parent (klass);
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	g_type_class_adjust_private_offset (klass, &valaDevelopProjectOptions_private_offset);
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_vala_develop_project_options_get_property;
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_vala_develop_project_options_set_property;
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	G_OBJECT_CLASS (klass)->finalize = vala_develop_project_options_finalize;
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/valaDevelop/projectoptions.glade");
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "fileName", FALSE, valaDevelopProjectOptions_private_offset + G_STRUCT_OFFSET (valaDevelopProjectOptionsPrivate, fileName));
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "defaultnamespace", FALSE, valaDevelopProjectOptions_private_offset + G_STRUCT_OFFSET (valaDevelopProjectOptionsPrivate, defaultnamespace));
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "fileRoot", FALSE, valaDevelopProjectOptions_private_offset + G_STRUCT_OFFSET (valaDevelopProjectOptionsPrivate, fileRoot));
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "executable", FALSE, valaDevelopProjectOptions_private_offset + G_STRUCT_OFFSET (valaDevelopProjectOptionsPrivate, executable));
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "shared", FALSE, valaDevelopProjectOptions_private_offset + G_STRUCT_OFFSET (valaDevelopProjectOptionsPrivate, shared));
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "vapi", FALSE, valaDevelopProjectOptions_private_offset + G_STRUCT_OFFSET (valaDevelopProjectOptionsPrivate, vapi));
#line 894 "project_options.c"
}

static void
vala_develop_project_options_vala_develop_ioption_widget_interface_init (valaDevelopIOptionWidgetIface * iface,
                                                                         gpointer iface_data)
{
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	vala_develop_project_options_vala_develop_ioption_widget_parent_iface = g_type_interface_peek_parent (iface);
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	iface->get_iter = vala_develop_project_options_real_get_iter;
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	iface->set_iter = vala_develop_project_options_real_set_iter;
#line 907 "project_options.c"
}

static void
vala_develop_project_options_instance_init (valaDevelopProjectOptions * self,
                                            gpointer klass)
{
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	self->priv = vala_develop_project_options_get_instance_private (self);
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 918 "project_options.c"
}

static void
vala_develop_project_options_finalize (GObject * obj)
{
	valaDevelopProjectOptions * self;
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALA_DEVELOP_TYPE_PROJECT_OPTIONS, valaDevelopProjectOptions);
#line 8 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_g_object_unref0 (self->priv->fileName);
#line 9 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_g_object_unref0 (self->priv->defaultnamespace);
#line 10 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_g_object_unref0 (self->priv->fileRoot);
#line 11 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_g_object_unref0 (self->priv->executable);
#line 12 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_g_object_unref0 (self->priv->shared);
#line 13 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	_g_object_unref0 (self->priv->vapi);
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	G_OBJECT_CLASS (vala_develop_project_options_parent_class)->finalize (obj);
#line 941 "project_options.c"
}

GType
vala_develop_project_options_get_type (void)
{
	static volatile gsize vala_develop_project_options_type_id__volatile = 0;
	if (g_once_init_enter (&vala_develop_project_options_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (valaDevelopProjectOptionsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_develop_project_options_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (valaDevelopProjectOptions), 0, (GInstanceInitFunc) vala_develop_project_options_instance_init, NULL };
		static const GInterfaceInfo vala_develop_ioption_widget_info = { (GInterfaceInitFunc) vala_develop_project_options_vala_develop_ioption_widget_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType vala_develop_project_options_type_id;
		vala_develop_project_options_type_id = g_type_register_static (gtk_box_get_type (), "valaDevelopProjectOptions", &g_define_type_info, 0);
		g_type_add_interface_static (vala_develop_project_options_type_id, VALA_DEVELOP_TYPE_IOPTION_WIDGET, &vala_develop_ioption_widget_info);
		valaDevelopProjectOptions_private_offset = g_type_add_instance_private (vala_develop_project_options_type_id, sizeof (valaDevelopProjectOptionsPrivate));
		g_once_init_leave (&vala_develop_project_options_type_id__volatile, vala_develop_project_options_type_id);
	}
	return vala_develop_project_options_type_id__volatile;
}

static void
_vala_vala_develop_project_options_get_property (GObject * object,
                                                 guint property_id,
                                                 GValue * value,
                                                 GParamSpec * pspec)
{
	valaDevelopProjectOptions * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, VALA_DEVELOP_TYPE_PROJECT_OPTIONS, valaDevelopProjectOptions);
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	switch (property_id) {
#line 970 "project_options.c"
		default:
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		break;
#line 976 "project_options.c"
	}
}

static void
_vala_vala_develop_project_options_set_property (GObject * object,
                                                 guint property_id,
                                                 const GValue * value,
                                                 GParamSpec * pspec)
{
	valaDevelopProjectOptions * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, VALA_DEVELOP_TYPE_PROJECT_OPTIONS, valaDevelopProjectOptions);
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
	switch (property_id) {
#line 990 "project_options.c"
		default:
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 6 "/home/wolfgang/Projekte/vDevelop/valaDevelop/OptionWidgets/project_options.vala"
		break;
#line 996 "project_options.c"
	}
}

