/* rename_folder_dialog.c generated by valac UNKNOWN, the Vala compiler
 * generated from rename_folder_dialog.vala, do not modify */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib/gi18n-lib.h>
#include <gio/gio.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gtksourceview/gtksource.h>

#define VALA_DEVELOP_TYPE_RENAME (vala_develop_rename_get_type ())
#define VALA_DEVELOP_RENAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_RENAME, valaDevelopRename))
#define VALA_DEVELOP_RENAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_RENAME, valaDevelopRenameClass))
#define VALA_DEVELOP_IS_RENAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_RENAME))
#define VALA_DEVELOP_IS_RENAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_RENAME))
#define VALA_DEVELOP_RENAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_RENAME, valaDevelopRenameClass))

typedef struct _valaDevelopRename valaDevelopRename;
typedef struct _valaDevelopRenameClass valaDevelopRenameClass;
typedef struct _valaDevelopRenamePrivate valaDevelopRenamePrivate;
typedef enum  {
	VALA_DEVELOP_ITEM_TYPE_None = 0,
	VALA_DEVELOP_ITEM_TYPE_Solution = 1,
	VALA_DEVELOP_ITEM_TYPE_Project = 2,
	VALA_DEVELOP_ITEM_TYPE_Resource = 4,
	VALA_DEVELOP_ITEM_TYPE_Source = 8,
	VALA_DEVELOP_ITEM_TYPE_Package = 16,
	VALA_DEVELOP_ITEM_TYPE_Directory = 32,
	VALA_DEVELOP_ITEM_TYPE_Vapi = 64
} valaDevelopItemType;

#define VALA_DEVELOP_TYPE_ITEM_TYPE (vala_develop_item_type_get_type ())

#define VALA_DEVELOP_TYPE_MAIN_PANED (vala_develop_main_paned_get_type ())
#define VALA_DEVELOP_MAIN_PANED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_MAIN_PANED, valaDevelopMainPaned))
#define VALA_DEVELOP_MAIN_PANED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_MAIN_PANED, valaDevelopMainPanedClass))
#define VALA_DEVELOP_IS_MAIN_PANED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_MAIN_PANED))
#define VALA_DEVELOP_IS_MAIN_PANED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_MAIN_PANED))
#define VALA_DEVELOP_MAIN_PANED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_MAIN_PANED, valaDevelopMainPanedClass))

typedef struct _valaDevelopMainPaned valaDevelopMainPaned;
typedef struct _valaDevelopMainPanedClass valaDevelopMainPanedClass;
enum  {
	VALA_DEVELOP_RENAME_0_PROPERTY,
	VALA_DEVELOP_RENAME_NUM_PROPERTIES
};
static GParamSpec* vala_develop_rename_properties[VALA_DEVELOP_RENAME_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE (vala_develop_overview_tree_store_get_type ())
#define VALA_DEVELOP_OVERVIEW_TREE_STORE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE, valaDevelopOverviewTreeStore))
#define VALA_DEVELOP_OVERVIEW_TREE_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE, valaDevelopOverviewTreeStoreClass))
#define VALA_DEVELOP_IS_OVERVIEW_TREE_STORE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE))
#define VALA_DEVELOP_IS_OVERVIEW_TREE_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE))
#define VALA_DEVELOP_OVERVIEW_TREE_STORE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE, valaDevelopOverviewTreeStoreClass))

typedef struct _valaDevelopOverviewTreeStore valaDevelopOverviewTreeStore;
typedef struct _valaDevelopOverviewTreeStoreClass valaDevelopOverviewTreeStoreClass;
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _valaDevelopMainPanedPrivate valaDevelopMainPanedPrivate;

#define VALA_DEVELOP_TYPE_STATUS_LIST (vala_develop_status_list_get_type ())
#define VALA_DEVELOP_STATUS_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_STATUS_LIST, valaDevelopStatusList))
#define VALA_DEVELOP_STATUS_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_STATUS_LIST, valaDevelopStatusListClass))
#define VALA_DEVELOP_IS_STATUS_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_STATUS_LIST))
#define VALA_DEVELOP_IS_STATUS_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_STATUS_LIST))
#define VALA_DEVELOP_STATUS_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_STATUS_LIST, valaDevelopStatusListClass))

typedef struct _valaDevelopStatusList valaDevelopStatusList;
typedef struct _valaDevelopStatusListClass valaDevelopStatusListClass;

#define VALA_DEVELOP_TYPE_ITEM_OPTIONS (vala_develop_item_options_get_type ())
#define VALA_DEVELOP_ITEM_OPTIONS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_ITEM_OPTIONS, valaDevelopItemOptions))
#define VALA_DEVELOP_ITEM_OPTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_ITEM_OPTIONS, valaDevelopItemOptionsClass))
#define VALA_DEVELOP_IS_ITEM_OPTIONS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_ITEM_OPTIONS))
#define VALA_DEVELOP_IS_ITEM_OPTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_ITEM_OPTIONS))
#define VALA_DEVELOP_ITEM_OPTIONS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_ITEM_OPTIONS, valaDevelopItemOptionsClass))

typedef struct _valaDevelopItemOptions valaDevelopItemOptions;
typedef struct _valaDevelopItemOptionsClass valaDevelopItemOptionsClass;

#define VALA_DEVELOP_TYPE_MAIN_WINDOW (vala_develop_main_window_get_type ())
#define VALA_DEVELOP_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_MAIN_WINDOW, valaDevelopmainWindow))
#define VALA_DEVELOP_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_MAIN_WINDOW, valaDevelopmainWindowClass))
#define VALA_DEVELOP_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_MAIN_WINDOW))
#define VALA_DEVELOP_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_MAIN_WINDOW))
#define VALA_DEVELOP_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_MAIN_WINDOW, valaDevelopmainWindowClass))

typedef struct _valaDevelopmainWindow valaDevelopmainWindow;
typedef struct _valaDevelopmainWindowClass valaDevelopmainWindowClass;

#define VALA_DEVELOP_TYPE_IOPTION_WIDGET (vala_develop_ioption_widget_get_type ())
#define VALA_DEVELOP_IOPTION_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_IOPTION_WIDGET, valaDevelopIOptionWidget))
#define VALA_DEVELOP_IS_IOPTION_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_IOPTION_WIDGET))
#define VALA_DEVELOP_IOPTION_WIDGET_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), VALA_DEVELOP_TYPE_IOPTION_WIDGET, valaDevelopIOptionWidgetIface))

typedef struct _valaDevelopIOptionWidget valaDevelopIOptionWidget;
typedef struct _valaDevelopIOptionWidgetIface valaDevelopIOptionWidgetIface;

struct _valaDevelopRename {
	GtkDialog parent_instance;
	valaDevelopRenamePrivate * priv;
};

struct _valaDevelopRenameClass {
	GtkDialogClass parent_class;
};

struct _valaDevelopRenamePrivate {
	GtkEntry* itemname;
	GtkButton* rename;
	GtkTreeIter _overviewTreeIter;
	valaDevelopItemType _itemType;
	gchar* _orgName;
	valaDevelopMainPaned* _parent;
};

struct _valaDevelopMainPaned {
	GtkBox parent_instance;
	valaDevelopMainPanedPrivate * priv;
	GtkTreeView* solutionTreeView;
	GtkBox* optionWindow;
	GtkBox* solutionWindow;
	GtkBox* toolWindow;
	GtkBox* statusWindow;
	GtkPaned* mainPaned;
	GtkPaned* childPaned;
	GtkPaned* infoPaned;
	GtkImage* closeOverview;
	GtkImage* closeOptions;
	GtkImage* closeStatus;
	GtkImage* expandOverview;
	GtkEventBox* solutionCaption;
	GtkNotebook* documentTab;
	GtkNotebook* infoTab;
	GtkCheckButton* showerrors;
	GtkCheckButton* showwarnings;
	GtkTextView* buildTextView;
	GtkTreeView* searchList;
	GtkTreeView* breakPoints;
	GtkTreeView* callStack;
	GtkTreeView* localSymbols;
	GtkTextView* appOutput;
	valaDevelopStatusList* statusList;
	GtkSwitch* statusSwitch;
	GtkStack* statusStack;
	GtkBox* resolveSymbolsBox;
	GtkButton* resolveSymbols;
	GtkTreeView* symbolTree;
	GtkTreeStore* symbolTreeModel;
	valaDevelopItemOptions* _itemOptions;
	GtkAccelGroup* accelGroup;
	valaDevelopmainWindow* _parentClass;
	GtkSourceStyleSchemeManager* _styleSchemeManager;
};

struct _valaDevelopMainPanedClass {
	GtkBoxClass parent_class;
};

struct _valaDevelopIOptionWidgetIface {
	GTypeInterface parent_iface;
	void (*get_iter) (valaDevelopIOptionWidget* self, GtkTreeIter * value);
	void (*set_iter) (valaDevelopIOptionWidget* self, GtkTreeIter * value);
};

static gint valaDevelopRename_private_offset;
static gpointer vala_develop_rename_parent_class = NULL;
extern valaDevelopOverviewTreeStore* vala_develop_main_paned_overviewTreeModel;

GType vala_develop_rename_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (valaDevelopRename, g_object_unref)
GType vala_develop_item_type_get_type (void) G_GNUC_CONST;
GType vala_develop_main_paned_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (valaDevelopMainPaned, g_object_unref)
valaDevelopRename* vala_develop_rename_new (GtkWidget* parent,
                                            GtkTreeIter* iter,
                                            valaDevelopItemType itemType);
valaDevelopRename* vala_develop_rename_construct (GType object_type,
                                                  GtkWidget* parent,
                                                  GtkTreeIter* iter,
                                                  valaDevelopItemType itemType);
static void __lambda83_ (valaDevelopRename* self);
static void ___lambda83__gtk_editable_changed (GtkEditable* _sender,
                                        gpointer self);
GType vala_develop_overview_tree_store_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (valaDevelopOverviewTreeStore, g_object_unref)
gchar* vala_develop_overview_tree_store_get_item_name (valaDevelopOverviewTreeStore* self,
                                                       GtkTreeIter* iter);
static void vala_develop_rename_OnAccept (valaDevelopRename* self);
gchar* vala_develop_overview_tree_store_get_item_path (valaDevelopOverviewTreeStore* self,
                                                       GtkTreeIter* iter);
gchar* vala_develop_overview_tree_store_get_project_path (valaDevelopOverviewTreeStore* self,
                                                          GtkTreeIter* iter);
void vala_develop_overview_tree_store_set_item_name (valaDevelopOverviewTreeStore* self,
                                                     GtkTreeIter* iter,
                                                     const gchar* name);
void vala_develop_overview_tree_store_set_item_path (valaDevelopOverviewTreeStore* self,
                                                     GtkTreeIter* iter,
                                                     const gchar* path);
gboolean vala_develop_overview_tree_store_save_project (valaDevelopOverviewTreeStore* self,
                                                        GtkTreeIter* iter);
GtkTreeIter* vala_develop_overview_tree_store_get_project_iter_by_iter (valaDevelopOverviewTreeStore* self,
                                                                        GtkTreeIter* iter);
gchar* vala_develop_overview_tree_store_get_item_relative_path (valaDevelopOverviewTreeStore* self,
                                                                GtkTreeIter* iter);
gchar* vala_develop_overview_tree_store_get_item_resource_id (valaDevelopOverviewTreeStore* self,
                                                              GtkTreeIter* iter);
void vala_develop_overview_tree_store_set_item_resource_id (valaDevelopOverviewTreeStore* self,
                                                            GtkTreeIter* iter,
                                                            const gchar* resourceId);
void vala_develop_overview_tree_store_set_item_mimetype (valaDevelopOverviewTreeStore* self,
                                                         GtkTreeIter* iter,
                                                         const gchar* mimeType);
void vala_develop_overview_tree_store_set_item_pixbuf (valaDevelopOverviewTreeStore* self,
                                                       GtkTreeIter* iter,
                                                       GdkPixbuf* itemPixbuf);
GType vala_develop_status_list_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (valaDevelopStatusList, g_object_unref)
GType vala_develop_item_options_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (valaDevelopItemOptions, g_object_unref)
GType vala_develop_main_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (valaDevelopmainWindow, g_object_unref)
GType vala_develop_ioption_widget_get_type (void) G_GNUC_CONST;
void vala_develop_ioption_widget_set_iter (valaDevelopIOptionWidget* self,
                                           GtkTreeIter * value);
static void _vala_develop_rename_OnAccept_gtk_button_clicked (GtkButton* _sender,
                                                       gpointer self);
static void vala_develop_rename_OnCancel (valaDevelopRename* self);
static void _vala_develop_rename_OnCancel_gtk_button_clicked (GtkButton* _sender,
                                                       gpointer self);
static void vala_develop_rename_finalize (GObject * obj);

static inline gpointer
vala_develop_rename_get_instance_private (valaDevelopRename* self)
{
	return G_STRUCT_MEMBER_P (self, valaDevelopRename_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static void
__lambda83_ (valaDevelopRename* self)
{
	GtkButton* _tmp0_;
	GtkEntry* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	_tmp0_ = self->priv->rename;
	_tmp1_ = self->priv->itemname;
	_tmp2_ = gtk_entry_get_text (_tmp1_);
	_tmp3_ = _tmp2_;
	gtk_widget_set_sensitive ((GtkWidget*) _tmp0_, g_strcmp0 (_tmp3_, "") != 0);
}

static void
___lambda83__gtk_editable_changed (GtkEditable* _sender,
                                   gpointer self)
{
	__lambda83_ ((valaDevelopRename*) self);
}

valaDevelopRename*
vala_develop_rename_construct (GType object_type,
                               GtkWidget* parent,
                               GtkTreeIter* iter,
                               valaDevelopItemType itemType)
{
	valaDevelopRename * self = NULL;
	GtkWidget* _tmp0_;
	valaDevelopMainPaned* _tmp1_;
	const gchar* _tmp2_ = NULL;
	GtkTreeIter _tmp4_;
	GtkEntry* _tmp5_;
	valaDevelopOverviewTreeStore* _tmp6_;
	GtkTreeIter _tmp7_;
	gchar* _tmp8_;
	GtkEntry* _tmp9_;
	const gchar* _tmp10_;
	g_return_val_if_fail (parent != NULL, NULL);
	g_return_val_if_fail (iter != NULL, NULL);
	self = (valaDevelopRename*) g_object_new (object_type, NULL);
	_tmp0_ = gtk_widget_get_toplevel (parent);
	gtk_window_set_transient_for ((GtkWindow*) self, G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, gtk_window_get_type (), GtkWindow));
	_tmp1_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (parent, VALA_DEVELOP_TYPE_MAIN_PANED) ? ((valaDevelopMainPaned*) parent) : NULL);
	_g_object_unref0 (self->priv->_parent);
	self->priv->_parent = _tmp1_;
	if ((itemType & VALA_DEVELOP_ITEM_TYPE_Directory) == VALA_DEVELOP_ITEM_TYPE_Directory) {
		_tmp2_ = _ ("Rename folder");
	} else {
		const gchar* _tmp3_ = NULL;
		if (itemType == VALA_DEVELOP_ITEM_TYPE_Resource) {
			_tmp3_ = _ ("Rename resource (Resource-Id will be changed)");
		} else {
			_tmp3_ = _ ("Rename item");
		}
		_tmp2_ = _tmp3_;
	}
	gtk_window_set_title ((GtkWindow*) self, _tmp2_);
	gtk_dialog_set_default_response ((GtkDialog*) self, (gint) GTK_RESPONSE_ACCEPT);
	_tmp4_ = *iter;
	self->priv->_overviewTreeIter = _tmp4_;
	self->priv->_itemType = itemType;
	_tmp5_ = self->priv->itemname;
	g_signal_connect_object ((GtkEditable*) _tmp5_, "changed", (GCallback) ___lambda83__gtk_editable_changed, self, 0);
	_tmp6_ = vala_develop_main_paned_overviewTreeModel;
	_tmp7_ = self->priv->_overviewTreeIter;
	_tmp8_ = vala_develop_overview_tree_store_get_item_name (_tmp6_, &_tmp7_);
	_g_free0 (self->priv->_orgName);
	self->priv->_orgName = _tmp8_;
	_tmp9_ = self->priv->itemname;
	_tmp10_ = self->priv->_orgName;
	gtk_entry_set_text (_tmp9_, _tmp10_);
	gtk_widget_show_all ((GtkWidget*) self);
	return self;
}

valaDevelopRename*
vala_develop_rename_new (GtkWidget* parent,
                         GtkTreeIter* iter,
                         valaDevelopItemType itemType)
{
	return vala_develop_rename_construct (VALA_DEVELOP_TYPE_RENAME, parent, iter, itemType);
}

static gchar*
string_replace (const gchar* self,
                const gchar* old,
                const gchar* replacement)
{
	gchar* result = NULL;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	GError* _inner_error0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	if ((*((gchar*) self)) == '\0') {
		_tmp1_ = TRUE;
	} else {
		_tmp1_ = (*((gchar*) old)) == '\0';
	}
	if (_tmp1_) {
		_tmp0_ = TRUE;
	} else {
		_tmp0_ = g_strcmp0 (old, replacement) == 0;
	}
	if (_tmp0_) {
		gchar* _tmp2_;
		_tmp2_ = g_strdup (self);
		result = _tmp2_;
		return result;
	}
	{
		GRegex* regex = NULL;
		gchar* _tmp3_;
		gchar* _tmp4_;
		GRegex* _tmp5_;
		GRegex* _tmp6_;
		gchar* _tmp7_ = NULL;
		GRegex* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		_tmp3_ = g_regex_escape_string (old, -1);
		_tmp4_ = _tmp3_;
		_tmp5_ = g_regex_new (_tmp4_, 0, 0, &_inner_error0_);
		_tmp6_ = _tmp5_;
		_g_free0 (_tmp4_);
		regex = _tmp6_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			if (_inner_error0_->domain == G_REGEX_ERROR) {
				goto __catch1_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return NULL;
		}
		_tmp8_ = regex;
		_tmp9_ = g_regex_replace_literal (_tmp8_, self, (gssize) -1, 0, replacement, 0, &_inner_error0_);
		_tmp7_ = _tmp9_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_regex_unref0 (regex);
			if (_inner_error0_->domain == G_REGEX_ERROR) {
				goto __catch1_g_regex_error;
			}
			_g_regex_unref0 (regex);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return NULL;
		}
		_tmp10_ = _tmp7_;
		_tmp7_ = NULL;
		result = _tmp10_;
		_g_free0 (_tmp7_);
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally1;
	__catch1_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		g_assert_not_reached ();
		_g_error_free0 (e);
	}
	__finally1:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return NULL;
	}
}

static void
vala_develop_rename_OnAccept (valaDevelopRename* self)
{
	GError* _inner_error0_ = NULL;
	g_return_if_fail (self != NULL);
	{
		GtkTreeIter solutionIter = {0};
		valaDevelopOverviewTreeStore* _tmp0_;
		GtkTreeIter _tmp1_ = {0};
		gchar* solutionPath = NULL;
		valaDevelopOverviewTreeStore* _tmp2_;
		GtkTreeIter _tmp3_;
		gchar* _tmp4_;
		valaDevelopItemType _tmp5_;
		valaDevelopMainPaned* _tmp145_;
		_tmp0_ = vala_develop_main_paned_overviewTreeModel;
		gtk_tree_model_get_iter_first ((GtkTreeModel*) _tmp0_, &_tmp1_);
		solutionIter = _tmp1_;
		_tmp2_ = vala_develop_main_paned_overviewTreeModel;
		_tmp3_ = solutionIter;
		_tmp4_ = vala_develop_overview_tree_store_get_item_path (_tmp2_, &_tmp3_);
		solutionPath = _tmp4_;
		_tmp5_ = self->priv->_itemType;
		if ((_tmp5_ & VALA_DEVELOP_ITEM_TYPE_Directory) == VALA_DEVELOP_ITEM_TYPE_Directory) {
			gchar* projectPath = NULL;
			valaDevelopOverviewTreeStore* _tmp6_;
			GtkTreeIter _tmp7_;
			gchar* _tmp8_;
			gchar* folderPath = NULL;
			valaDevelopOverviewTreeStore* _tmp9_;
			GtkTreeIter _tmp10_;
			gchar* _tmp11_;
			GFile* fullOldPath = NULL;
			const gchar* _tmp12_;
			GFile* _tmp13_;
			GFile* _tmp14_;
			const gchar* _tmp15_;
			GFile* _tmp16_;
			GFile* _tmp17_;
			GFile* fullNewPath = NULL;
			const gchar* _tmp18_;
			GFile* _tmp19_;
			GFile* _tmp20_;
			const gchar* _tmp21_;
			GFile* _tmp22_;
			GFile* _tmp23_;
			GtkEntry* _tmp24_;
			const gchar* _tmp25_;
			const gchar* _tmp26_;
			GFile* _tmp27_;
			GFile* _tmp28_;
			gboolean _tmp29_ = FALSE;
			GFile* _tmp30_;
			GFile* _tmp31_;
			_tmp6_ = vala_develop_main_paned_overviewTreeModel;
			_tmp7_ = self->priv->_overviewTreeIter;
			_tmp8_ = vala_develop_overview_tree_store_get_project_path (_tmp6_, &_tmp7_);
			projectPath = _tmp8_;
			_tmp9_ = vala_develop_main_paned_overviewTreeModel;
			_tmp10_ = self->priv->_overviewTreeIter;
			_tmp11_ = vala_develop_overview_tree_store_get_item_path (_tmp9_, &_tmp10_);
			folderPath = _tmp11_;
			_tmp12_ = solutionPath;
			_tmp13_ = g_file_new_for_path (_tmp12_);
			_tmp14_ = _tmp13_;
			_tmp15_ = folderPath;
			_tmp16_ = g_file_get_child (_tmp14_, _tmp15_);
			_tmp17_ = _tmp16_;
			_g_object_unref0 (_tmp14_);
			fullOldPath = _tmp17_;
			_tmp18_ = solutionPath;
			_tmp19_ = g_file_new_for_path (_tmp18_);
			_tmp20_ = _tmp19_;
			_tmp21_ = projectPath;
			_tmp22_ = g_file_get_child (_tmp20_, _tmp21_);
			_tmp23_ = _tmp22_;
			_tmp24_ = self->priv->itemname;
			_tmp25_ = gtk_entry_get_text (_tmp24_);
			_tmp26_ = _tmp25_;
			_tmp27_ = g_file_get_child (_tmp23_, _tmp26_);
			_tmp28_ = _tmp27_;
			_g_object_unref0 (_tmp23_);
			_g_object_unref0 (_tmp20_);
			fullNewPath = _tmp28_;
			_tmp30_ = fullOldPath;
			_tmp31_ = fullNewPath;
			_tmp29_ = g_file_move (_tmp30_, _tmp31_, G_FILE_COPY_NONE, NULL, NULL, NULL, &_inner_error0_);
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
				_g_object_unref0 (fullNewPath);
				_g_object_unref0 (fullOldPath);
				_g_free0 (folderPath);
				_g_free0 (projectPath);
				_g_free0 (solutionPath);
				goto __catch0_g_error;
			}
			if (_tmp29_) {
				valaDevelopOverviewTreeStore* _tmp32_;
				GtkTreeIter _tmp33_;
				GtkEntry* _tmp34_;
				const gchar* _tmp35_;
				const gchar* _tmp36_;
				valaDevelopOverviewTreeStore* _tmp37_;
				GtkTreeIter _tmp38_;
				const gchar* _tmp39_;
				const gchar* _tmp40_;
				GtkEntry* _tmp41_;
				const gchar* _tmp42_;
				const gchar* _tmp43_;
				gchar* _tmp44_;
				gchar* _tmp45_;
				valaDevelopOverviewTreeStore* _tmp46_;
				valaDevelopOverviewTreeStore* _tmp47_;
				GtkTreeIter _tmp48_;
				GtkTreeIter* _tmp49_;
				GtkTreeIter* _tmp50_;
				GtkTreeIter _tmp51_;
				_tmp32_ = vala_develop_main_paned_overviewTreeModel;
				_tmp33_ = self->priv->_overviewTreeIter;
				_tmp34_ = self->priv->itemname;
				_tmp35_ = gtk_entry_get_text (_tmp34_);
				_tmp36_ = _tmp35_;
				vala_develop_overview_tree_store_set_item_name (_tmp32_, &_tmp33_, _tmp36_);
				_tmp37_ = vala_develop_main_paned_overviewTreeModel;
				_tmp38_ = self->priv->_overviewTreeIter;
				_tmp39_ = folderPath;
				_tmp40_ = self->priv->_orgName;
				_tmp41_ = self->priv->itemname;
				_tmp42_ = gtk_entry_get_text (_tmp41_);
				_tmp43_ = _tmp42_;
				_tmp44_ = string_replace (_tmp39_, _tmp40_, _tmp43_);
				_tmp45_ = _tmp44_;
				vala_develop_overview_tree_store_set_item_path (_tmp37_, &_tmp38_, _tmp45_);
				_g_free0 (_tmp45_);
				_tmp46_ = vala_develop_main_paned_overviewTreeModel;
				_tmp47_ = vala_develop_main_paned_overviewTreeModel;
				_tmp48_ = self->priv->_overviewTreeIter;
				_tmp49_ = vala_develop_overview_tree_store_get_project_iter_by_iter (_tmp47_, &_tmp48_);
				_tmp50_ = _tmp49_;
				_tmp51_ = *_tmp50_;
				vala_develop_overview_tree_store_save_project (_tmp46_, &_tmp51_);
				_g_free0 (_tmp50_);
			}
			_g_object_unref0 (fullNewPath);
			_g_object_unref0 (fullOldPath);
			_g_free0 (folderPath);
			_g_free0 (projectPath);
		} else {
			gchar* orgPathName = NULL;
			valaDevelopOverviewTreeStore* _tmp52_;
			GtkTreeIter _tmp53_;
			gchar* _tmp54_;
			GFile* fullOldPath = NULL;
			const gchar* _tmp55_;
			GFile* _tmp56_;
			GFile* _tmp57_;
			const gchar* _tmp58_;
			GFile* _tmp59_;
			GFile* _tmp60_;
			GFile* fullNewPath = NULL;
			const gchar* _tmp61_;
			GFile* _tmp62_;
			GFile* _tmp63_;
			const gchar* _tmp64_;
			const gchar* _tmp65_;
			GtkEntry* _tmp66_;
			const gchar* _tmp67_;
			const gchar* _tmp68_;
			gchar* _tmp69_;
			gchar* _tmp70_;
			GFile* _tmp71_;
			GFile* _tmp72_;
			gboolean _tmp73_ = FALSE;
			GFile* _tmp74_;
			GFile* _tmp75_;
			_tmp52_ = vala_develop_main_paned_overviewTreeModel;
			_tmp53_ = self->priv->_overviewTreeIter;
			_tmp54_ = vala_develop_overview_tree_store_get_item_relative_path (_tmp52_, &_tmp53_);
			orgPathName = _tmp54_;
			_tmp55_ = solutionPath;
			_tmp56_ = g_file_new_for_path (_tmp55_);
			_tmp57_ = _tmp56_;
			_tmp58_ = orgPathName;
			_tmp59_ = g_file_get_child (_tmp57_, _tmp58_);
			_tmp60_ = _tmp59_;
			_g_object_unref0 (_tmp57_);
			fullOldPath = _tmp60_;
			_tmp61_ = solutionPath;
			_tmp62_ = g_file_new_for_path (_tmp61_);
			_tmp63_ = _tmp62_;
			_tmp64_ = orgPathName;
			_tmp65_ = self->priv->_orgName;
			_tmp66_ = self->priv->itemname;
			_tmp67_ = gtk_entry_get_text (_tmp66_);
			_tmp68_ = _tmp67_;
			_tmp69_ = string_replace (_tmp64_, _tmp65_, _tmp68_);
			_tmp70_ = _tmp69_;
			_tmp71_ = g_file_get_child (_tmp63_, _tmp70_);
			_tmp72_ = _tmp71_;
			_g_free0 (_tmp70_);
			_g_object_unref0 (_tmp63_);
			fullNewPath = _tmp72_;
			_tmp74_ = fullOldPath;
			_tmp75_ = fullNewPath;
			_tmp73_ = g_file_move (_tmp74_, _tmp75_, G_FILE_COPY_NONE, NULL, NULL, NULL, &_inner_error0_);
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
				_g_object_unref0 (fullNewPath);
				_g_object_unref0 (fullOldPath);
				_g_free0 (orgPathName);
				_g_free0 (solutionPath);
				goto __catch0_g_error;
			}
			if (_tmp73_) {
				valaDevelopOverviewTreeStore* _tmp76_;
				GtkTreeIter _tmp77_;
				GtkEntry* _tmp78_;
				const gchar* _tmp79_;
				const gchar* _tmp80_;
				valaDevelopItemType _tmp81_;
				gchar* cType = NULL;
				GFile* _tmp94_;
				gchar* _tmp95_;
				gchar* _tmp96_;
				gchar* _tmp97_;
				gchar* _tmp98_;
				valaDevelopOverviewTreeStore* _tmp99_;
				GtkTreeIter _tmp100_;
				const gchar* _tmp101_;
				GdkPixbuf* itemPixbuf = NULL;
				gchar* itemName = NULL;
				GFile* _tmp102_;
				gchar* _tmp103_;
				gboolean _tmp104_ = FALSE;
				const gchar* _tmp105_;
				GdkPixbuf* _tmp130_;
				valaDevelopOverviewTreeStore* _tmp134_;
				GtkTreeIter _tmp135_;
				GtkEntry* _tmp136_;
				const gchar* _tmp137_;
				const gchar* _tmp138_;
				valaDevelopOverviewTreeStore* _tmp139_;
				valaDevelopOverviewTreeStore* _tmp140_;
				GtkTreeIter _tmp141_;
				GtkTreeIter* _tmp142_;
				GtkTreeIter* _tmp143_;
				GtkTreeIter _tmp144_;
				_tmp76_ = vala_develop_main_paned_overviewTreeModel;
				_tmp77_ = self->priv->_overviewTreeIter;
				_tmp78_ = self->priv->itemname;
				_tmp79_ = gtk_entry_get_text (_tmp78_);
				_tmp80_ = _tmp79_;
				vala_develop_overview_tree_store_set_item_name (_tmp76_, &_tmp77_, _tmp80_);
				_tmp81_ = self->priv->_itemType;
				if (_tmp81_ == VALA_DEVELOP_ITEM_TYPE_Resource) {
					gchar* old_resource_id = NULL;
					valaDevelopOverviewTreeStore* _tmp82_;
					GtkTreeIter _tmp83_;
					gchar* _tmp84_;
					valaDevelopOverviewTreeStore* _tmp85_;
					GtkTreeIter _tmp86_;
					const gchar* _tmp87_;
					const gchar* _tmp88_;
					GtkEntry* _tmp89_;
					const gchar* _tmp90_;
					const gchar* _tmp91_;
					gchar* _tmp92_;
					gchar* _tmp93_;
					_tmp82_ = vala_develop_main_paned_overviewTreeModel;
					_tmp83_ = self->priv->_overviewTreeIter;
					_tmp84_ = vala_develop_overview_tree_store_get_item_resource_id (_tmp82_, &_tmp83_);
					old_resource_id = _tmp84_;
					_tmp85_ = vala_develop_main_paned_overviewTreeModel;
					_tmp86_ = self->priv->_overviewTreeIter;
					_tmp87_ = old_resource_id;
					_tmp88_ = self->priv->_orgName;
					_tmp89_ = self->priv->itemname;
					_tmp90_ = gtk_entry_get_text (_tmp89_);
					_tmp91_ = _tmp90_;
					_tmp92_ = string_replace (_tmp87_, _tmp88_, _tmp91_);
					_tmp93_ = _tmp92_;
					vala_develop_overview_tree_store_set_item_resource_id (_tmp85_, &_tmp86_, _tmp93_);
					_g_free0 (_tmp93_);
					_g_free0 (old_resource_id);
				}
				_tmp94_ = fullNewPath;
				_tmp95_ = g_file_get_path (_tmp94_);
				_tmp96_ = _tmp95_;
				_tmp97_ = g_content_type_guess (_tmp96_, NULL, (gsize) 0, NULL);
				_tmp98_ = _tmp97_;
				_g_free0 (_tmp96_);
				cType = _tmp98_;
				_tmp99_ = vala_develop_main_paned_overviewTreeModel;
				_tmp100_ = self->priv->_overviewTreeIter;
				_tmp101_ = cType;
				vala_develop_overview_tree_store_set_item_mimetype (_tmp99_, &_tmp100_, _tmp101_);
				itemPixbuf = NULL;
				_tmp102_ = fullNewPath;
				_tmp103_ = g_file_get_path (_tmp102_);
				itemName = _tmp103_;
				_tmp105_ = itemName;
				if (g_str_has_suffix (_tmp105_, ".glade")) {
					_tmp104_ = TRUE;
				} else {
					const gchar* _tmp106_;
					_tmp106_ = itemName;
					_tmp104_ = g_str_has_suffix (_tmp106_, ".ui");
				}
				if (_tmp104_) {
					GdkPixbuf* _tmp107_ = NULL;
					GdkPixbuf* _tmp108_;
					GdkPixbuf* _tmp109_;
					_tmp108_ = gdk_pixbuf_new_from_resource ("/valaDevelop/glade.svg.png", &_inner_error0_);
					_tmp107_ = _tmp108_;
					if (G_UNLIKELY (_inner_error0_ != NULL)) {
						_g_free0 (itemName);
						_g_object_unref0 (itemPixbuf);
						_g_free0 (cType);
						_g_object_unref0 (fullNewPath);
						_g_object_unref0 (fullOldPath);
						_g_free0 (orgPathName);
						_g_free0 (solutionPath);
						goto __catch0_g_error;
					}
					_tmp109_ = gdk_pixbuf_scale_simple (_tmp107_, 16, 16, GDK_INTERP_BILINEAR);
					_g_object_unref0 (itemPixbuf);
					itemPixbuf = _tmp109_;
					_g_object_unref0 (_tmp107_);
				} else {
					gboolean _tmp110_ = FALSE;
					const gchar* _tmp111_;
					_tmp111_ = itemName;
					if (g_str_has_suffix (_tmp111_, ".xml")) {
						_tmp110_ = TRUE;
					} else {
						const gchar* _tmp112_;
						_tmp112_ = itemName;
						_tmp110_ = g_str_has_suffix (_tmp112_, ".css");
					}
					if (_tmp110_) {
						GdkPixbuf* _tmp113_ = NULL;
						GdkPixbuf* _tmp114_;
						GdkPixbuf* _tmp115_;
						_tmp114_ = gdk_pixbuf_new_from_resource ("/valaDevelop/xml.svg.png", &_inner_error0_);
						_tmp113_ = _tmp114_;
						if (G_UNLIKELY (_inner_error0_ != NULL)) {
							_g_free0 (itemName);
							_g_object_unref0 (itemPixbuf);
							_g_free0 (cType);
							_g_object_unref0 (fullNewPath);
							_g_object_unref0 (fullOldPath);
							_g_free0 (orgPathName);
							_g_free0 (solutionPath);
							goto __catch0_g_error;
						}
						_tmp115_ = gdk_pixbuf_scale_simple (_tmp113_, 16, 16, GDK_INTERP_BILINEAR);
						_g_object_unref0 (itemPixbuf);
						itemPixbuf = _tmp115_;
						_g_object_unref0 (_tmp113_);
					} else {
						gboolean _tmp116_ = FALSE;
						const gchar* _tmp117_;
						_tmp117_ = itemName;
						if (g_str_has_suffix (_tmp117_, ".png")) {
							_tmp116_ = TRUE;
						} else {
							const gchar* _tmp118_;
							_tmp118_ = itemName;
							_tmp116_ = g_str_has_suffix (_tmp118_, ".svg");
						}
						if (_tmp116_) {
							GdkPixbuf* _tmp119_ = NULL;
							GdkPixbuf* _tmp120_;
							GdkPixbuf* _tmp121_;
							_tmp120_ = gdk_pixbuf_new_from_resource ("/valaDevelop/picture.svg.png", &_inner_error0_);
							_tmp119_ = _tmp120_;
							if (G_UNLIKELY (_inner_error0_ != NULL)) {
								_g_free0 (itemName);
								_g_object_unref0 (itemPixbuf);
								_g_free0 (cType);
								_g_object_unref0 (fullNewPath);
								_g_object_unref0 (fullOldPath);
								_g_free0 (orgPathName);
								_g_free0 (solutionPath);
								goto __catch0_g_error;
							}
							_tmp121_ = gdk_pixbuf_scale_simple (_tmp119_, 16, 16, GDK_INTERP_BILINEAR);
							_g_object_unref0 (itemPixbuf);
							itemPixbuf = _tmp121_;
							_g_object_unref0 (_tmp119_);
						} else {
							gboolean _tmp122_ = FALSE;
							gboolean _tmp123_ = FALSE;
							const gchar* _tmp124_;
							_tmp124_ = itemName;
							if (g_str_has_suffix (_tmp124_, ".vala")) {
								_tmp123_ = TRUE;
							} else {
								const gchar* _tmp125_;
								_tmp125_ = itemName;
								_tmp123_ = g_str_has_suffix (_tmp125_, ".vapi");
							}
							if (_tmp123_) {
								_tmp122_ = TRUE;
							} else {
								const gchar* _tmp126_;
								_tmp126_ = itemName;
								_tmp122_ = g_str_has_suffix (_tmp126_, ".c");
							}
							if (_tmp122_) {
								GdkPixbuf* _tmp127_ = NULL;
								GdkPixbuf* _tmp128_;
								GdkPixbuf* _tmp129_;
								_tmp128_ = gdk_pixbuf_new_from_resource ("/valaDevelop/source.svg.png", &_inner_error0_);
								_tmp127_ = _tmp128_;
								if (G_UNLIKELY (_inner_error0_ != NULL)) {
									_g_free0 (itemName);
									_g_object_unref0 (itemPixbuf);
									_g_free0 (cType);
									_g_object_unref0 (fullNewPath);
									_g_object_unref0 (fullOldPath);
									_g_free0 (orgPathName);
									_g_free0 (solutionPath);
									goto __catch0_g_error;
								}
								_tmp129_ = gdk_pixbuf_scale_simple (_tmp127_, 16, 16, GDK_INTERP_BILINEAR);
								_g_object_unref0 (itemPixbuf);
								itemPixbuf = _tmp129_;
								_g_object_unref0 (_tmp127_);
							}
						}
					}
				}
				_tmp130_ = itemPixbuf;
				if (_tmp130_ != NULL) {
					valaDevelopOverviewTreeStore* _tmp131_;
					GtkTreeIter _tmp132_;
					GdkPixbuf* _tmp133_;
					_tmp131_ = vala_develop_main_paned_overviewTreeModel;
					_tmp132_ = self->priv->_overviewTreeIter;
					_tmp133_ = itemPixbuf;
					vala_develop_overview_tree_store_set_item_pixbuf (_tmp131_, &_tmp132_, _tmp133_);
				}
				_tmp134_ = vala_develop_main_paned_overviewTreeModel;
				_tmp135_ = self->priv->_overviewTreeIter;
				_tmp136_ = self->priv->itemname;
				_tmp137_ = gtk_entry_get_text (_tmp136_);
				_tmp138_ = _tmp137_;
				vala_develop_overview_tree_store_set_item_name (_tmp134_, &_tmp135_, _tmp138_);
				_tmp139_ = vala_develop_main_paned_overviewTreeModel;
				_tmp140_ = vala_develop_main_paned_overviewTreeModel;
				_tmp141_ = self->priv->_overviewTreeIter;
				_tmp142_ = vala_develop_overview_tree_store_get_project_iter_by_iter (_tmp140_, &_tmp141_);
				_tmp143_ = _tmp142_;
				_tmp144_ = *_tmp143_;
				vala_develop_overview_tree_store_save_project (_tmp139_, &_tmp144_);
				_g_free0 (_tmp143_);
				_g_free0 (itemName);
				_g_object_unref0 (itemPixbuf);
				_g_free0 (cType);
			}
			_g_object_unref0 (fullNewPath);
			_g_object_unref0 (fullOldPath);
			_g_free0 (orgPathName);
		}
		_tmp145_ = self->priv->_parent;
		if (_tmp145_ != NULL) {
			valaDevelopMainPaned* _tmp146_;
			GtkBox* _tmp147_;
			GList* _tmp148_;
			GList* _tmp149_;
			gconstpointer _tmp150_;
			GtkWidget* _tmp151_;
			GtkTreeIter _tmp152_;
			_tmp146_ = self->priv->_parent;
			_tmp147_ = _tmp146_->toolWindow;
			_tmp148_ = gtk_container_get_children ((GtkContainer*) _tmp147_);
			_tmp149_ = _tmp148_;
			_tmp150_ = g_list_nth_data (_tmp149_, (guint) 0);
			_tmp151_ = (GtkWidget*) _tmp150_;
			_tmp152_ = self->priv->_overviewTreeIter;
			vala_develop_ioption_widget_set_iter (G_TYPE_CHECK_INSTANCE_TYPE (_tmp151_, VALA_DEVELOP_TYPE_IOPTION_WIDGET) ? ((valaDevelopIOptionWidget*) _tmp151_) : NULL, &_tmp152_);
			(_tmp149_ == NULL) ? NULL : (_tmp149_ = (g_list_free (_tmp149_), NULL));
		}
		_g_free0 (solutionPath);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GtkMessageDialog* messagedialog = NULL;
		GError* _tmp153_;
		const gchar* _tmp154_;
		GtkMessageDialog* _tmp155_;
		GtkMessageDialog* _tmp156_;
		GtkMessageDialog* _tmp157_;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp153_ = e;
		_tmp154_ = _tmp153_->message;
		_tmp155_ = (GtkMessageDialog*) gtk_message_dialog_new ((GtkWindow*) self, GTK_DIALOG_MODAL, GTK_MESSAGE_ERROR, GTK_BUTTONS_OK, "%s", _tmp154_);
		g_object_ref_sink (_tmp155_);
		messagedialog = _tmp155_;
		_tmp156_ = messagedialog;
		gtk_dialog_run ((GtkDialog*) _tmp156_);
		_tmp157_ = messagedialog;
		gtk_widget_destroy ((GtkWidget*) _tmp157_);
		_g_object_unref0 (messagedialog);
		_g_error_free0 (e);
		return;
	}
	__finally0:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	gtk_dialog_response ((GtkDialog*) self, (gint) GTK_RESPONSE_ACCEPT);
}

static void
_vala_develop_rename_OnAccept_gtk_button_clicked (GtkButton* _sender,
                                                  gpointer self)
{
	vala_develop_rename_OnAccept ((valaDevelopRename*) self);
}

static void
vala_develop_rename_OnCancel (valaDevelopRename* self)
{
	g_return_if_fail (self != NULL);
	gtk_dialog_response ((GtkDialog*) self, (gint) GTK_RESPONSE_CANCEL);
}

static void
_vala_develop_rename_OnCancel_gtk_button_clicked (GtkButton* _sender,
                                                  gpointer self)
{
	vala_develop_rename_OnCancel ((valaDevelopRename*) self);
}

static void
vala_develop_rename_class_init (valaDevelopRenameClass * klass,
                                gpointer klass_data)
{
	vala_develop_rename_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &valaDevelopRename_private_offset);
	G_OBJECT_CLASS (klass)->finalize = vala_develop_rename_finalize;
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/valaDevelop/rename.glade");
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "itemname", FALSE, valaDevelopRename_private_offset + G_STRUCT_OFFSET (valaDevelopRenamePrivate, itemname));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "rename", FALSE, valaDevelopRename_private_offset + G_STRUCT_OFFSET (valaDevelopRenamePrivate, rename));
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "OnAccept", G_CALLBACK(_vala_develop_rename_OnAccept_gtk_button_clicked));
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "OnCancel", G_CALLBACK(_vala_develop_rename_OnCancel_gtk_button_clicked));
}

static void
vala_develop_rename_instance_init (valaDevelopRename * self,
                                   gpointer klass)
{
	self->priv = vala_develop_rename_get_instance_private (self);
	gtk_widget_init_template (GTK_WIDGET (self));
}

static void
vala_develop_rename_finalize (GObject * obj)
{
	valaDevelopRename * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALA_DEVELOP_TYPE_RENAME, valaDevelopRename);
	_g_object_unref0 (self->priv->itemname);
	_g_object_unref0 (self->priv->rename);
	_g_free0 (self->priv->_orgName);
	_g_object_unref0 (self->priv->_parent);
	G_OBJECT_CLASS (vala_develop_rename_parent_class)->finalize (obj);
}

GType
vala_develop_rename_get_type (void)
{
	static volatile gsize vala_develop_rename_type_id__volatile = 0;
	if (g_once_init_enter (&vala_develop_rename_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (valaDevelopRenameClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_develop_rename_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (valaDevelopRename), 0, (GInstanceInitFunc) vala_develop_rename_instance_init, NULL };
		GType vala_develop_rename_type_id;
		vala_develop_rename_type_id = g_type_register_static (gtk_dialog_get_type (), "valaDevelopRename", &g_define_type_info, 0);
		valaDevelopRename_private_offset = g_type_add_instance_private (vala_develop_rename_type_id, sizeof (valaDevelopRenamePrivate));
		g_once_init_leave (&vala_develop_rename_type_id__volatile, vala_develop_rename_type_id);
	}
	return vala_develop_rename_type_id__volatile;
}

