/* reporter.c generated by valac 0.44.0, the Vala compiler
 * generated from reporter.vala, do not modify */

#include <glib-object.h>
#include <vala.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gee.h>

typedef enum  {
	REPORT_TYPE_ERROR = 1 << 0,
	REPORT_TYPE_WARNING = 1 << 1,
	REPORT_TYPE_DEPRECATED = 1 << 2,
	REPORT_TYPE_EXPERIMENTAL = 1 << 3,
	REPORT_TYPE_NOTE = 1 << 4
} ReportType;

#define TYPE_REPORT_TYPE (report_type_get_type ())

#define TYPE_REPORT_ERROR (report_error_get_type ())
#define REPORT_ERROR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_REPORT_ERROR, ReportError))
#define REPORT_ERROR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_REPORT_ERROR, ReportErrorClass))
#define IS_REPORT_ERROR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_REPORT_ERROR))
#define IS_REPORT_ERROR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_REPORT_ERROR))
#define REPORT_ERROR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_REPORT_ERROR, ReportErrorClass))

typedef struct _ReportError ReportError;
typedef struct _ReportErrorClass ReportErrorClass;
typedef struct _ReportErrorPrivate ReportErrorPrivate;
enum  {
	REPORT_ERROR_0_PROPERTY,
	REPORT_ERROR_NUM_PROPERTIES
};
static GParamSpec* report_error_properties[REPORT_ERROR_NUM_PROPERTIES];
#define _vala_source_reference_unref0(var) ((var == NULL) ? NULL : (var = (vala_source_reference_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define VALA_DEVELOP_TYPE_REPORTER (vala_develop_reporter_get_type ())
#define VALA_DEVELOP_REPORTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_REPORTER, valaDevelopReporter))
#define VALA_DEVELOP_REPORTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_REPORTER, valaDevelopReporterClass))
#define VALA_DEVELOP_IS_REPORTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_REPORTER))
#define VALA_DEVELOP_IS_REPORTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_REPORTER))
#define VALA_DEVELOP_REPORTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_REPORTER, valaDevelopReporterClass))

typedef struct _valaDevelopReporter valaDevelopReporter;
typedef struct _valaDevelopReporterClass valaDevelopReporterClass;
typedef struct _valaDevelopReporterPrivate valaDevelopReporterPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _ReportError {
	GObject parent_instance;
	ReportErrorPrivate * priv;
	ValaSourceReference* source;
	gchar* message;
	ReportType type;
};

struct _ReportErrorClass {
	GObjectClass parent_class;
};

struct _valaDevelopReporter {
	ValaReport parent_instance;
	valaDevelopReporterPrivate * priv;
};

struct _valaDevelopReporterClass {
	ValaReportClass parent_class;
};

struct _valaDevelopReporterPrivate {
	GeeArrayList* _error_list;
};

static gpointer report_error_parent_class = NULL;
static gint valaDevelopReporter_private_offset;
static gpointer vala_develop_reporter_parent_class = NULL;

GType report_type_get_type (void) G_GNUC_CONST;
GType report_error_get_type (void) G_GNUC_CONST;
ReportError* report_error_new (ValaSourceReference* source,
                               const gchar* message,
                               ReportType type);
ReportError* report_error_construct (GType object_type,
                                     ValaSourceReference* source,
                                     const gchar* message,
                                     ReportType type);
static void report_error_finalize (GObject * obj);
GType vala_develop_reporter_get_type (void) G_GNUC_CONST;
valaDevelopReporter* vala_develop_reporter_new (void);
valaDevelopReporter* vala_develop_reporter_construct (GType object_type);
static void vala_develop_reporter_set_error_list (valaDevelopReporter* self,
                                           GeeArrayList* value);
void vala_develop_reporter_reset (valaDevelopReporter* self);
GeeArrayList* vala_develop_reporter_get_error_list (valaDevelopReporter* self);
static void vala_develop_reporter_real_note (ValaReport* base,
                                      ValaSourceReference* source,
                                      const gchar* message);
static void vala_develop_reporter_real_depr (ValaReport* base,
                                      ValaSourceReference* source,
                                      const gchar* message);
static void vala_develop_reporter_real_warn (ValaReport* base,
                                      ValaSourceReference* source,
                                      const gchar* message);
static void vala_develop_reporter_real_err (ValaReport* base,
                                     ValaSourceReference* source,
                                     const gchar* message);
static void vala_develop_reporter_finalize (ValaReport * obj);

GType
report_type_get_type (void)
{
	static volatile gsize report_type_type_id__volatile = 0;
	if (g_once_init_enter (&report_type_type_id__volatile)) {
		static const GFlagsValue values[] = {{REPORT_TYPE_ERROR, "REPORT_TYPE_ERROR", "error"}, {REPORT_TYPE_WARNING, "REPORT_TYPE_WARNING", "warning"}, {REPORT_TYPE_DEPRECATED, "REPORT_TYPE_DEPRECATED", "deprecated"}, {REPORT_TYPE_EXPERIMENTAL, "REPORT_TYPE_EXPERIMENTAL", "experimental"}, {REPORT_TYPE_NOTE, "REPORT_TYPE_NOTE", "note"}, {0, NULL, NULL}};
		GType report_type_type_id;
		report_type_type_id = g_flags_register_static ("ReportType", values);
		g_once_init_leave (&report_type_type_id__volatile, report_type_type_id);
	}
	return report_type_type_id__volatile;
}

static gpointer
_vala_source_reference_ref0 (gpointer self)
{
	return self ? vala_source_reference_ref (self) : NULL;
}

ReportError*
report_error_construct (GType object_type,
                        ValaSourceReference* source,
                        const gchar* message,
                        ReportType type)
{
	ReportError * self = NULL;
	ValaSourceReference* _tmp0_;
	gchar* _tmp1_;
	g_return_val_if_fail (message != NULL, NULL);
	self = (ReportError*) g_object_new (object_type, NULL);
	_tmp0_ = _vala_source_reference_ref0 (source);
	_vala_source_reference_unref0 (self->source);
	self->source = _tmp0_;
	_tmp1_ = g_strdup (message);
	_g_free0 (self->message);
	self->message = _tmp1_;
	self->type = type;
	return self;
}

ReportError*
report_error_new (ValaSourceReference* source,
                  const gchar* message,
                  ReportType type)
{
	return report_error_construct (TYPE_REPORT_ERROR, source, message, type);
}

static void
report_error_class_init (ReportErrorClass * klass,
                         gpointer klass_data)
{
	report_error_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = report_error_finalize;
}

static void
report_error_instance_init (ReportError * self,
                            gpointer klass)
{
}

static void
report_error_finalize (GObject * obj)
{
	ReportError * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_REPORT_ERROR, ReportError);
	_vala_source_reference_unref0 (self->source);
	_g_free0 (self->message);
	G_OBJECT_CLASS (report_error_parent_class)->finalize (obj);
}

GType
report_error_get_type (void)
{
	static volatile gsize report_error_type_id__volatile = 0;
	if (g_once_init_enter (&report_error_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ReportErrorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) report_error_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ReportError), 0, (GInstanceInitFunc) report_error_instance_init, NULL };
		GType report_error_type_id;
		report_error_type_id = g_type_register_static (G_TYPE_OBJECT, "ReportError", &g_define_type_info, 0);
		g_once_init_leave (&report_error_type_id__volatile, report_error_type_id);
	}
	return report_error_type_id__volatile;
}

static inline gpointer
vala_develop_reporter_get_instance_private (valaDevelopReporter* self)
{
	return G_STRUCT_MEMBER_P (self, valaDevelopReporter_private_offset);
}

valaDevelopReporter*
vala_develop_reporter_construct (GType object_type)
{
	valaDevelopReporter* self = NULL;
	GeeArrayList* _tmp0_;
	GeeArrayList* _tmp1_;
	self = (valaDevelopReporter*) vala_report_construct (object_type);
	_tmp0_ = gee_array_list_new (TYPE_REPORT_ERROR, (GBoxedCopyFunc) g_object_ref, (GDestroyNotify) g_object_unref, NULL, NULL, NULL);
	_tmp1_ = _tmp0_;
	vala_develop_reporter_set_error_list (self, _tmp1_);
	_g_object_unref0 (_tmp1_);
	return self;
}

valaDevelopReporter*
vala_develop_reporter_new (void)
{
	return vala_develop_reporter_construct (VALA_DEVELOP_TYPE_REPORTER);
}

void
vala_develop_reporter_reset (valaDevelopReporter* self)
{
	GeeArrayList* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_error_list;
	gee_abstract_collection_clear ((GeeAbstractCollection*) _tmp0_);
	((ValaReport*) self)->errors = 0;
	((ValaReport*) self)->warnings = 0;
}

static void
vala_develop_reporter_real_note (ValaReport* base,
                                 ValaSourceReference* source,
                                 const gchar* message)
{
	valaDevelopReporter * self;
	gint _tmp0_;
	GeeArrayList* _tmp1_;
	ReportError* _tmp2_;
	ReportError* _tmp3_;
	self = (valaDevelopReporter*) base;
	g_return_if_fail (message != NULL);
	_tmp0_ = ((ValaReport*) self)->warnings;
	((ValaReport*) self)->warnings = _tmp0_ + 1;
	if (source == NULL) {
		return;
	}
	_tmp1_ = self->priv->_error_list;
	_tmp2_ = report_error_new (source, message, REPORT_TYPE_NOTE);
	_tmp3_ = _tmp2_;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp1_, _tmp3_);
	_g_object_unref0 (_tmp3_);
}

static void
vala_develop_reporter_real_depr (ValaReport* base,
                                 ValaSourceReference* source,
                                 const gchar* message)
{
	valaDevelopReporter * self;
	gint _tmp0_;
	GeeArrayList* _tmp1_;
	ReportError* _tmp2_;
	ReportError* _tmp3_;
	self = (valaDevelopReporter*) base;
	g_return_if_fail (message != NULL);
	_tmp0_ = ((ValaReport*) self)->warnings;
	((ValaReport*) self)->warnings = _tmp0_ + 1;
	if (source == NULL) {
		return;
	}
	_tmp1_ = self->priv->_error_list;
	_tmp2_ = report_error_new (source, message, REPORT_TYPE_DEPRECATED);
	_tmp3_ = _tmp2_;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp1_, _tmp3_);
	_g_object_unref0 (_tmp3_);
}

static void
vala_develop_reporter_real_warn (ValaReport* base,
                                 ValaSourceReference* source,
                                 const gchar* message)
{
	valaDevelopReporter * self;
	gint _tmp0_;
	ReportType type = 0;
	GeeArrayList* _tmp1_;
	ReportType _tmp2_;
	ReportError* _tmp3_;
	ReportError* _tmp4_;
	self = (valaDevelopReporter*) base;
	g_return_if_fail (message != NULL);
	_tmp0_ = ((ValaReport*) self)->warnings;
	((ValaReport*) self)->warnings = _tmp0_ + 1;
	if (source == NULL) {
		return;
	}
	if (g_str_has_suffix (message, "are experimental")) {
		type = REPORT_TYPE_EXPERIMENTAL;
	} else {
		type = REPORT_TYPE_WARNING;
	}
	_tmp1_ = self->priv->_error_list;
	_tmp2_ = type;
	_tmp3_ = report_error_new (source, message, _tmp2_);
	_tmp4_ = _tmp3_;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp1_, _tmp4_);
	_g_object_unref0 (_tmp4_);
}

static void
vala_develop_reporter_real_err (ValaReport* base,
                                ValaSourceReference* source,
                                const gchar* message)
{
	valaDevelopReporter * self;
	gint _tmp0_;
	GeeArrayList* _tmp1_;
	ReportError* _tmp2_;
	ReportError* _tmp3_;
	self = (valaDevelopReporter*) base;
	g_return_if_fail (message != NULL);
	_tmp0_ = ((ValaReport*) self)->errors;
	((ValaReport*) self)->errors = _tmp0_ + 1;
	if (source == NULL) {
		return;
	}
	_tmp1_ = self->priv->_error_list;
	_tmp2_ = report_error_new (source, message, REPORT_TYPE_ERROR);
	_tmp3_ = _tmp2_;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp1_, _tmp3_);
	_g_object_unref0 (_tmp3_);
}

GeeArrayList*
vala_develop_reporter_get_error_list (valaDevelopReporter* self)
{
	GeeArrayList* result;
	GeeArrayList* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_error_list;
	result = _tmp0_;
	return result;
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static void
vala_develop_reporter_set_error_list (valaDevelopReporter* self,
                                      GeeArrayList* value)
{
	GeeArrayList* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = _g_object_ref0 (value);
	_g_object_unref0 (self->priv->_error_list);
	self->priv->_error_list = _tmp0_;
}

static void
vala_develop_reporter_class_init (valaDevelopReporterClass * klass,
                                  gpointer klass_data)
{
	vala_develop_reporter_parent_class = g_type_class_peek_parent (klass);
	((ValaReportClass *) klass)->finalize = vala_develop_reporter_finalize;
	g_type_class_adjust_private_offset (klass, &valaDevelopReporter_private_offset);
	((ValaReportClass *) klass)->note = (void (*) (ValaReport*, ValaSourceReference*, const gchar*)) vala_develop_reporter_real_note;
	((ValaReportClass *) klass)->depr = (void (*) (ValaReport*, ValaSourceReference*, const gchar*)) vala_develop_reporter_real_depr;
	((ValaReportClass *) klass)->warn = (void (*) (ValaReport*, ValaSourceReference*, const gchar*)) vala_develop_reporter_real_warn;
	((ValaReportClass *) klass)->err = (void (*) (ValaReport*, ValaSourceReference*, const gchar*)) vala_develop_reporter_real_err;
}

static void
vala_develop_reporter_instance_init (valaDevelopReporter * self,
                                     gpointer klass)
{
	self->priv = vala_develop_reporter_get_instance_private (self);
}

static void
vala_develop_reporter_finalize (ValaReport * obj)
{
	valaDevelopReporter * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALA_DEVELOP_TYPE_REPORTER, valaDevelopReporter);
	_g_object_unref0 (self->priv->_error_list);
	VALA_REPORT_CLASS (vala_develop_reporter_parent_class)->finalize (obj);
}

GType
vala_develop_reporter_get_type (void)
{
	static volatile gsize vala_develop_reporter_type_id__volatile = 0;
	if (g_once_init_enter (&vala_develop_reporter_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (valaDevelopReporterClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_develop_reporter_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (valaDevelopReporter), 0, (GInstanceInitFunc) vala_develop_reporter_instance_init, NULL };
		GType vala_develop_reporter_type_id;
		vala_develop_reporter_type_id = g_type_register_static (VALA_TYPE_REPORT, "valaDevelopReporter", &g_define_type_info, 0);
		valaDevelopReporter_private_offset = g_type_add_instance_private (vala_develop_reporter_type_id, sizeof (valaDevelopReporterPrivate));
		g_once_init_leave (&vala_develop_reporter_type_id__volatile, vala_develop_reporter_type_id);
	}
	return vala_develop_reporter_type_id__volatile;
}

