/* search_and_replace.c generated by valac 0.44.0, the Vala compiler
 * generated from search_and_replace.vala, do not modify */

#include <glib-object.h>
#include <gtk/gtk.h>
#include <gtksourceview/gtksource.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>
#include <float.h>
#include <math.h>
#include <gio/gio.h>
#include <glib/gi18n-lib.h>

typedef enum  {
	VALA_DEVELOP_SEARCH_TYPE_ENUM_Find,
	VALA_DEVELOP_SEARCH_TYPE_ENUM_Replace,
	VALA_DEVELOP_SEARCH_TYPE_ENUM_Goto
} valaDevelopSearchTypeEnum;

#define VALA_DEVELOP_TYPE_SEARCH_TYPE_ENUM (vala_develop_search_type_enum_get_type ())

#define VALA_DEVELOP_TYPE_SEARCH_AND_REPLACE (vala_develop_search_and_replace_get_type ())
#define VALA_DEVELOP_SEARCH_AND_REPLACE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_SEARCH_AND_REPLACE, valaDevelopSearchAndReplace))
#define VALA_DEVELOP_SEARCH_AND_REPLACE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_SEARCH_AND_REPLACE, valaDevelopSearchAndReplaceClass))
#define VALA_DEVELOP_IS_SEARCH_AND_REPLACE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_SEARCH_AND_REPLACE))
#define VALA_DEVELOP_IS_SEARCH_AND_REPLACE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_SEARCH_AND_REPLACE))
#define VALA_DEVELOP_SEARCH_AND_REPLACE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_SEARCH_AND_REPLACE, valaDevelopSearchAndReplaceClass))

typedef struct _valaDevelopSearchAndReplace valaDevelopSearchAndReplace;
typedef struct _valaDevelopSearchAndReplaceClass valaDevelopSearchAndReplaceClass;
typedef struct _valaDevelopSearchAndReplacePrivate valaDevelopSearchAndReplacePrivate;
enum  {
	VALA_DEVELOP_SEARCH_AND_REPLACE_0_PROPERTY,
	VALA_DEVELOP_SEARCH_AND_REPLACE_SEARCH_TYPE_PROPERTY,
	VALA_DEVELOP_SEARCH_AND_REPLACE_NUM_PROPERTIES
};
static GParamSpec* vala_develop_search_and_replace_properties[VALA_DEVELOP_SEARCH_AND_REPLACE_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define VALA_DEVELOP_TYPE_SETTINGS (vala_develop_settings_get_type ())
#define VALA_DEVELOP_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_SETTINGS, valaDevelopSettings))
#define VALA_DEVELOP_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_SETTINGS, valaDevelopSettingsClass))
#define VALA_DEVELOP_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_SETTINGS))
#define VALA_DEVELOP_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_SETTINGS))
#define VALA_DEVELOP_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_SETTINGS, valaDevelopSettingsClass))

typedef struct _valaDevelopSettings valaDevelopSettings;
typedef struct _valaDevelopSettingsClass valaDevelopSettingsClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _Block2Data Block2Data;

struct _valaDevelopSearchAndReplace {
	GtkBox parent_instance;
	valaDevelopSearchAndReplacePrivate * priv;
	GtkEntry* searchText;
	GtkEntry* replaceText;
	GtkEntry* gotoText;
	GtkLabel* text;
	GtkMenu* menu;
	GtkCheckMenuItem* caseSensitive;
	GtkCheckMenuItem* regexSearch;
	GtkCheckMenuItem* selectionSearch;
	GtkCheckMenuItem* wholeWord;
	GtkEventBox* prevResult;
	GtkEventBox* nextResult;
	GtkEventBox* gotoEventBox;
	GtkEventBox* replaceEventBox;
	GtkEventBox* replaceAllEventBox;
	GtkFrame* search;
	GtkFrame* replace;
	GtkFrame* gotoLine;
};

struct _valaDevelopSearchAndReplaceClass {
	GtkBoxClass parent_class;
};

struct _valaDevelopSearchAndReplacePrivate {
	GtkImage* closeImage;
	GtkImage* downImage;
	GtkImage* upImage;
	GtkSourceView* _view;
	GtkSourceBuffer* _buffer;
	GtkSourceSearchSettings* _searchSettings;
	GtkSourceSearchContext* _searchContext;
	GRecMutex __lock__searchContext;
	valaDevelopSearchTypeEnum _searchType;
};

struct _Block2Data {
	int _ref_count_;
	valaDevelopSearchAndReplace* self;
	GtkTextIter matchStart;
};

static gint valaDevelopSearchAndReplace_private_offset;
static gpointer vala_develop_search_and_replace_parent_class = NULL;

GType vala_develop_search_type_enum_get_type (void) G_GNUC_CONST;
GType vala_develop_search_and_replace_get_type (void) G_GNUC_CONST;
valaDevelopSearchAndReplace* vala_develop_search_and_replace_new (valaDevelopSearchTypeEnum searchType,
                                                                  GtkSourceView* view,
                                                                  GtkSourceBuffer* buffer);
valaDevelopSearchAndReplace* vala_develop_search_and_replace_construct (GType object_type,
                                                                        valaDevelopSearchTypeEnum searchType,
                                                                        GtkSourceView* view,
                                                                        GtkSourceBuffer* buffer);
void vala_develop_search_and_replace_set_SearchType (valaDevelopSearchAndReplace* self,
                                                     valaDevelopSearchTypeEnum value);
gpointer vala_develop_settings_ref (gpointer instance);
void vala_develop_settings_unref (gpointer instance);
GParamSpec* vala_develop_param_spec_settings (const gchar* name,
                                              const gchar* nick,
                                              const gchar* blurb,
                                              GType object_type,
                                              GParamFlags flags);
void vala_develop_value_set_settings (GValue* value,
                                      gpointer v_object);
void vala_develop_value_take_settings (GValue* value,
                                       gpointer v_object);
gpointer vala_develop_value_get_settings (const GValue* value);
GType vala_develop_settings_get_type (void) G_GNUC_CONST;
valaDevelopSettings* vala_develop_xml_configuration_get_Setting (void);
gchar* vala_develop_settings_get (valaDevelopSettings* self,
                                  const gchar* key);
static void __lambda77_ (valaDevelopSearchAndReplace* self);
static void ___lambda77__gtk_widget_hide (GtkWidget* _sender,
                                   gpointer self);
static void __lambda78_ (valaDevelopSearchAndReplace* self,
                  GObject* sender,
                  GParamSpec* property);
void vala_develop_search_and_replace_UpdateResult (valaDevelopSearchAndReplace* self,
                                                   gboolean withForward);
static void ___lambda78__g_object_notify (GObject* _sender,
                                   GParamSpec* pspec,
                                   gpointer self);
static gboolean vala_develop_search_and_replace_on_key_press_event (valaDevelopSearchAndReplace* self,
                                                             GtkWidget* sender,
                                                             GdkEventKey* event);
static gboolean _vala_develop_search_and_replace_on_key_press_event_gtk_widget_key_press_event (GtkWidget* _sender,
                                                                                         GdkEventKey* event,
                                                                                         gpointer self);
static gboolean vala_develop_search_and_replace_OnGoto (valaDevelopSearchAndReplace* self);
static gboolean _vala_develop_search_and_replace_OnGoto_gtk_widget_button_release_event (GtkWidget* _sender,
                                                                                  GdkEventButton* event,
                                                                                  gpointer self);
static gboolean vala_develop_search_and_replace_OnClearEntry (valaDevelopSearchAndReplace* self,
                                                       GtkWidget* widget,
                                                       GdkEventButton* event);
static gboolean _vala_develop_search_and_replace_OnClearEntry_gtk_widget_button_release_event (GtkWidget* _sender,
                                                                                        GdkEventButton* event,
                                                                                        gpointer self);
static void vala_develop_search_and_replace_OnNextActivate (valaDevelopSearchAndReplace* self,
                                                     GtkEntry* entry);
gboolean vala_develop_search_and_replace_OnSelectNext (valaDevelopSearchAndReplace* self);
static void _vala_develop_search_and_replace_OnNextActivate_gtk_entry_activate (GtkEntry* _sender,
                                                                         gpointer self);
static gboolean vala_develop_search_and_replace_OnSearchClose (valaDevelopSearchAndReplace* self,
                                                        GtkWidget* widget,
                                                        GdkEventButton* event);
static gboolean _vala_develop_search_and_replace_OnSearchClose_gtk_widget_button_release_event (GtkWidget* _sender,
                                                                                         GdkEventButton* event,
                                                                                         gpointer self);
static void vala_develop_search_and_replace_OnGoToActivate (valaDevelopSearchAndReplace* self,
                                                     GtkWidget* widget);
static void _vala_develop_search_and_replace_OnGoToActivate_gtk_entry_activate (GtkEntry* _sender,
                                                                         gpointer self);
static void vala_develop_search_and_replace_OnIconRelease (valaDevelopSearchAndReplace* self,
                                                    GtkEntryIconPosition icon_pos,
                                                    GdkEventButton* event);
static void _vala_develop_search_and_replace_OnIconRelease_gtk_entry_icon_release (GtkEntry* _sender,
                                                                            GtkEntryIconPosition icon_pos,
                                                                            GdkEventButton* event,
                                                                            gpointer self);
static void vala_develop_search_and_replace_CaseSensitiveToggle (valaDevelopSearchAndReplace* self,
                                                          GtkCheckMenuItem* menuItem);
static void vala_develop_search_and_replace_SearchForwardAsync (valaDevelopSearchAndReplace* self);
void vala_develop_settings_set (valaDevelopSettings* self,
                                const gchar* key,
                                const gchar* val);
static void _vala_develop_search_and_replace_CaseSensitiveToggle_gtk_check_menu_item_toggled (GtkCheckMenuItem* _sender,
                                                                                       gpointer self);
static void vala_develop_search_and_replace_RegexSearchToggle (valaDevelopSearchAndReplace* self,
                                                        GtkCheckMenuItem* menuItem);
static void _vala_develop_search_and_replace_RegexSearchToggle_gtk_check_menu_item_toggled (GtkCheckMenuItem* _sender,
                                                                                     gpointer self);
static void vala_develop_search_and_replace_SearchSelectionToggle (valaDevelopSearchAndReplace* self);
static void _vala_develop_search_and_replace_SearchSelectionToggle_gtk_check_menu_item_toggled (GtkCheckMenuItem* _sender,
                                                                                         gpointer self);
static void vala_develop_search_and_replace_WholeWordToggle (valaDevelopSearchAndReplace* self,
                                                      GtkCheckMenuItem* menuItem);
static void _vala_develop_search_and_replace_WholeWordToggle_gtk_check_menu_item_toggled (GtkCheckMenuItem* _sender,
                                                                                   gpointer self);
static void vala_develop_search_and_replace_OnReplaceChanged (valaDevelopSearchAndReplace* self);
static void _vala_develop_search_and_replace_OnReplaceChanged_gtk_editable_changed (GtkEditable* _sender,
                                                                             gpointer self);
static void vala_develop_search_and_replace_OnTextChanged (valaDevelopSearchAndReplace* self);
static void _vala_develop_search_and_replace_OnTextChanged_gtk_editable_changed (GtkEditable* _sender,
                                                                          gpointer self);
static void __lambda79_ (valaDevelopSearchAndReplace* self,
                  GObject* source_object,
                  GAsyncResult* res);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
static gboolean ___lambda80_ (Block2Data* _data2_);
static gboolean ____lambda80__gsource_func (gpointer self);
static void ___lambda79__gasync_ready_callback (GObject* source_object,
                                         GAsyncResult* res,
                                         gpointer self);
void vala_develop_search_and_replace_entry_grab_focus (valaDevelopSearchAndReplace* self);
gboolean vala_develop_search_and_replace_OnSelectPrev (valaDevelopSearchAndReplace* self);
static gboolean _vala_develop_search_and_replace_OnSelectPrev_gtk_widget_button_release_event (GtkWidget* _sender,
                                                                                        GdkEventButton* event,
                                                                                        gpointer self);
static gboolean _vala_develop_search_and_replace_OnSelectNext_gtk_widget_button_release_event (GtkWidget* _sender,
                                                                                        GdkEventButton* event,
                                                                                        gpointer self);
static gboolean vala_develop_search_and_replace_OnReplace (valaDevelopSearchAndReplace* self,
                                                    GtkWidget* widget,
                                                    GdkEventButton* event);
static gboolean _vala_develop_search_and_replace_OnReplace_gtk_widget_button_release_event (GtkWidget* _sender,
                                                                                     GdkEventButton* event,
                                                                                     gpointer self);
static gboolean vala_develop_search_and_replace_OnReplaceAll (valaDevelopSearchAndReplace* self,
                                                       GtkWidget* widget,
                                                       GdkEventButton* event);
static gboolean _vala_develop_search_and_replace_OnReplaceAll_gtk_widget_button_release_event (GtkWidget* _sender,
                                                                                        GdkEventButton* event,
                                                                                        gpointer self);
valaDevelopSearchTypeEnum vala_develop_search_and_replace_get_SearchType (valaDevelopSearchAndReplace* self);
static void vala_develop_search_and_replace_finalize (GObject * obj);
static void _vala_vala_develop_search_and_replace_get_property (GObject * object,
                                                         guint property_id,
                                                         GValue * value,
                                                         GParamSpec * pspec);
static void _vala_vala_develop_search_and_replace_set_property (GObject * object,
                                                         guint property_id,
                                                         const GValue * value,
                                                         GParamSpec * pspec);

GType
vala_develop_search_type_enum_get_type (void)
{
	static volatile gsize vala_develop_search_type_enum_type_id__volatile = 0;
	if (g_once_init_enter (&vala_develop_search_type_enum_type_id__volatile)) {
		static const GEnumValue values[] = {{VALA_DEVELOP_SEARCH_TYPE_ENUM_Find, "VALA_DEVELOP_SEARCH_TYPE_ENUM_Find", "find"}, {VALA_DEVELOP_SEARCH_TYPE_ENUM_Replace, "VALA_DEVELOP_SEARCH_TYPE_ENUM_Replace", "replace"}, {VALA_DEVELOP_SEARCH_TYPE_ENUM_Goto, "VALA_DEVELOP_SEARCH_TYPE_ENUM_Goto", "goto"}, {0, NULL, NULL}};
		GType vala_develop_search_type_enum_type_id;
		vala_develop_search_type_enum_type_id = g_enum_register_static ("valaDevelopSearchTypeEnum", values);
		g_once_init_leave (&vala_develop_search_type_enum_type_id__volatile, vala_develop_search_type_enum_type_id);
	}
	return vala_develop_search_type_enum_type_id__volatile;
}

static inline gpointer
vala_develop_search_and_replace_get_instance_private (valaDevelopSearchAndReplace* self)
{
	return G_STRUCT_MEMBER_P (self, valaDevelopSearchAndReplace_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static gboolean
bool_parse (const gchar* str)
{
	gboolean result = FALSE;
	g_return_val_if_fail (str != NULL, FALSE);
	if (g_strcmp0 (str, "true") == 0) {
		result = TRUE;
		return result;
	} else {
		result = FALSE;
		return result;
	}
}

static void
__lambda77_ (valaDevelopSearchAndReplace* self)
{
	GtkSourceSearchContext* _tmp0_;
	_tmp0_ = self->priv->_searchContext;
	gtk_source_search_context_set_highlight (_tmp0_, FALSE);
}

static void
___lambda77__gtk_widget_hide (GtkWidget* _sender,
                              gpointer self)
{
	__lambda77_ ((valaDevelopSearchAndReplace*) self);
}

static void
__lambda78_ (valaDevelopSearchAndReplace* self,
             GObject* sender,
             GParamSpec* property)
{
	const gchar* _tmp0_;
	g_return_if_fail (sender != NULL);
	g_return_if_fail (property != NULL);
	_tmp0_ = property->name;
	if (g_strcmp0 (_tmp0_, "occurrences_count") == 0) {
		GtkSourceSearchContext* _tmp1_;
		gint _tmp2_;
		gint _tmp3_;
		_tmp1_ = self->priv->_searchContext;
		_tmp2_ = gtk_source_search_context_get_occurrences_count (_tmp1_);
		_tmp3_ = _tmp2_;
		if (_tmp3_ > 0) {
			vala_develop_search_and_replace_UpdateResult (self, FALSE);
		}
	}
}

static void
___lambda78__g_object_notify (GObject* _sender,
                              GParamSpec* pspec,
                              gpointer self)
{
	__lambda78_ ((valaDevelopSearchAndReplace*) self, _sender, pspec);
}

valaDevelopSearchAndReplace*
vala_develop_search_and_replace_construct (GType object_type,
                                           valaDevelopSearchTypeEnum searchType,
                                           GtkSourceView* view,
                                           GtkSourceBuffer* buffer)
{
	valaDevelopSearchAndReplace * self = NULL;
	GtkSourceView* _tmp0_;
	GtkSourceBuffer* _tmp1_;
	GdkPixbuf* _tmp2_ = NULL;
	GdkPixbuf* _tmp3_;
	GtkImage* _tmp4_;
	GdkPixbuf* _tmp5_;
	GdkPixbuf* _tmp6_;
	GdkPixbuf* _tmp7_ = NULL;
	GdkPixbuf* _tmp8_;
	GtkImage* _tmp9_;
	GdkPixbuf* _tmp10_;
	GdkPixbuf* _tmp11_;
	GdkPixbuf* _tmp12_ = NULL;
	GdkPixbuf* _tmp13_;
	GtkImage* _tmp14_;
	GdkPixbuf* _tmp15_;
	GdkPixbuf* _tmp16_;
	GtkSourceSearchSettings* _tmp17_;
	GtkSourceSearchSettings* _tmp18_;
	GtkSourceBuffer* _tmp19_;
	GtkSourceSearchSettings* _tmp20_;
	GtkSourceSearchContext* _tmp21_;
	GtkSourceSearchContext* _tmp22_;
	gboolean _tmp23_ = FALSE;
	GtkFrame* _tmp24_;
	GtkFrame* _tmp25_;
	GtkFrame* _tmp26_;
	gchar* _tmp27_ = NULL;
	valaDevelopSettings* _tmp28_;
	valaDevelopSettings* _tmp29_;
	gchar* _tmp30_;
	GtkSourceSearchSettings* _tmp32_;
	gchar* _tmp33_ = NULL;
	valaDevelopSettings* _tmp34_;
	valaDevelopSettings* _tmp35_;
	gchar* _tmp36_;
	GtkSourceSearchSettings* _tmp38_;
	gchar* _tmp39_ = NULL;
	valaDevelopSettings* _tmp40_;
	valaDevelopSettings* _tmp41_;
	gchar* _tmp42_;
	GtkSourceSearchSettings* _tmp44_;
	GtkCheckMenuItem* _tmp45_;
	GtkSourceSearchSettings* _tmp46_;
	gboolean _tmp47_;
	gboolean _tmp48_;
	GtkCheckMenuItem* _tmp49_;
	GtkSourceSearchSettings* _tmp50_;
	gboolean _tmp51_;
	gboolean _tmp52_;
	GtkCheckMenuItem* _tmp53_;
	GtkSourceSearchSettings* _tmp54_;
	gboolean _tmp55_;
	gboolean _tmp56_;
	GtkSourceSearchContext* _tmp57_;
	GError* _inner_error0_ = NULL;
	g_return_val_if_fail (view != NULL, NULL);
	g_return_val_if_fail (buffer != NULL, NULL);
	self = (valaDevelopSearchAndReplace*) g_object_new (object_type, NULL);
	_tmp0_ = _g_object_ref0 (view);
	_g_object_unref0 (self->priv->_view);
	self->priv->_view = _tmp0_;
	_tmp1_ = _g_object_ref0 (buffer);
	_g_object_unref0 (self->priv->_buffer);
	self->priv->_buffer = _tmp1_;
	vala_develop_search_and_replace_set_SearchType (self, searchType);
	_tmp3_ = gdk_pixbuf_new_from_resource ("/valaDevelop/close.svg.png", &_inner_error0_);
	_tmp2_ = _tmp3_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return NULL;
	}
	_tmp4_ = self->priv->closeImage;
	_tmp5_ = gdk_pixbuf_scale_simple (_tmp2_, 16, 16, GDK_INTERP_BILINEAR);
	_tmp6_ = _tmp5_;
	g_object_set (_tmp4_, "pixbuf", _tmp6_, NULL);
	_g_object_unref0 (_tmp6_);
	_tmp8_ = gdk_pixbuf_new_from_resource ("/valaDevelop/down.svg.png", &_inner_error0_);
	_tmp7_ = _tmp8_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_object_unref0 (_tmp2_);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return NULL;
	}
	_tmp9_ = self->priv->downImage;
	_tmp10_ = gdk_pixbuf_scale_simple (_tmp7_, 16, 16, GDK_INTERP_BILINEAR);
	_tmp11_ = _tmp10_;
	g_object_set (_tmp9_, "pixbuf", _tmp11_, NULL);
	_g_object_unref0 (_tmp11_);
	_tmp13_ = gdk_pixbuf_new_from_resource ("/valaDevelop/up.svg.png", &_inner_error0_);
	_tmp12_ = _tmp13_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		_g_object_unref0 (_tmp7_);
		_g_object_unref0 (_tmp2_);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return NULL;
	}
	_tmp14_ = self->priv->upImage;
	_tmp15_ = gdk_pixbuf_scale_simple (_tmp12_, 16, 16, GDK_INTERP_BILINEAR);
	_tmp16_ = _tmp15_;
	g_object_set (_tmp14_, "pixbuf", _tmp16_, NULL);
	_g_object_unref0 (_tmp16_);
	_tmp17_ = gtk_source_search_settings_new ();
	_g_object_unref0 (self->priv->_searchSettings);
	self->priv->_searchSettings = _tmp17_;
	_tmp18_ = self->priv->_searchSettings;
	gtk_source_search_settings_set_wrap_around (_tmp18_, TRUE);
	_tmp19_ = self->priv->_buffer;
	_tmp20_ = self->priv->_searchSettings;
	_tmp21_ = gtk_source_search_context_new (_tmp19_, _tmp20_);
	_g_object_unref0 (self->priv->_searchContext);
	self->priv->_searchContext = _tmp21_;
	_tmp22_ = self->priv->_searchContext;
	gtk_source_search_context_set_highlight (_tmp22_, TRUE);
	if (searchType == VALA_DEVELOP_SEARCH_TYPE_ENUM_Find) {
		_tmp23_ = TRUE;
	} else {
		_tmp23_ = searchType == VALA_DEVELOP_SEARCH_TYPE_ENUM_Replace;
	}
	_tmp24_ = self->search;
	gtk_widget_set_visible ((GtkWidget*) _tmp24_, _tmp23_);
	_tmp25_ = self->replace;
	gtk_widget_set_visible ((GtkWidget*) _tmp25_, searchType == VALA_DEVELOP_SEARCH_TYPE_ENUM_Replace);
	_tmp26_ = self->gotoLine;
	gtk_widget_set_visible ((GtkWidget*) _tmp26_, searchType == VALA_DEVELOP_SEARCH_TYPE_ENUM_Goto);
	_tmp28_ = vala_develop_xml_configuration_get_Setting ();
	_tmp29_ = _tmp28_;
	_tmp30_ = vala_develop_settings_get (_tmp29_, "case_sensitive");
	_tmp27_ = _tmp30_;
	if (_tmp27_ == NULL) {
		gchar* _tmp31_;
		_tmp31_ = g_strdup ("false");
		_g_free0 (_tmp27_);
		_tmp27_ = _tmp31_;
	}
	_tmp32_ = self->priv->_searchSettings;
	gtk_source_search_settings_set_case_sensitive (_tmp32_, bool_parse (_tmp27_));
	_tmp34_ = vala_develop_xml_configuration_get_Setting ();
	_tmp35_ = _tmp34_;
	_tmp36_ = vala_develop_settings_get (_tmp35_, "regex_enabled");
	_tmp33_ = _tmp36_;
	if (_tmp33_ == NULL) {
		gchar* _tmp37_;
		_tmp37_ = g_strdup ("false");
		_g_free0 (_tmp33_);
		_tmp33_ = _tmp37_;
	}
	_tmp38_ = self->priv->_searchSettings;
	gtk_source_search_settings_set_regex_enabled (_tmp38_, bool_parse (_tmp33_));
	_tmp40_ = vala_develop_xml_configuration_get_Setting ();
	_tmp41_ = _tmp40_;
	_tmp42_ = vala_develop_settings_get (_tmp41_, "at_word_boundaries");
	_tmp39_ = _tmp42_;
	if (_tmp39_ == NULL) {
		gchar* _tmp43_;
		_tmp43_ = g_strdup ("false");
		_g_free0 (_tmp39_);
		_tmp39_ = _tmp43_;
	}
	_tmp44_ = self->priv->_searchSettings;
	gtk_source_search_settings_set_at_word_boundaries (_tmp44_, bool_parse (_tmp39_));
	_tmp45_ = self->caseSensitive;
	_tmp46_ = self->priv->_searchSettings;
	_tmp47_ = gtk_source_search_settings_get_case_sensitive (_tmp46_);
	_tmp48_ = _tmp47_;
	gtk_check_menu_item_set_active (_tmp45_, _tmp48_);
	_tmp49_ = self->regexSearch;
	_tmp50_ = self->priv->_searchSettings;
	_tmp51_ = gtk_source_search_settings_get_regex_enabled (_tmp50_);
	_tmp52_ = _tmp51_;
	gtk_check_menu_item_set_active (_tmp49_, _tmp52_);
	_tmp53_ = self->wholeWord;
	_tmp54_ = self->priv->_searchSettings;
	_tmp55_ = gtk_source_search_settings_get_at_word_boundaries (_tmp54_);
	_tmp56_ = _tmp55_;
	gtk_check_menu_item_set_active (_tmp53_, _tmp56_);
	g_signal_connect_object ((GtkWidget*) self, "hide", (GCallback) ___lambda77__gtk_widget_hide, self, 0);
	_tmp57_ = self->priv->_searchContext;
	g_signal_connect_object ((GObject*) _tmp57_, "notify", (GCallback) ___lambda78__g_object_notify, self, 0);
	_g_free0 (_tmp39_);
	_g_free0 (_tmp33_);
	_g_free0 (_tmp27_);
	_g_object_unref0 (_tmp12_);
	_g_object_unref0 (_tmp7_);
	_g_object_unref0 (_tmp2_);
	return self;
}

valaDevelopSearchAndReplace*
vala_develop_search_and_replace_new (valaDevelopSearchTypeEnum searchType,
                                     GtkSourceView* view,
                                     GtkSourceBuffer* buffer)
{
	return vala_develop_search_and_replace_construct (VALA_DEVELOP_TYPE_SEARCH_AND_REPLACE, searchType, view, buffer);
}

static gboolean
vala_develop_search_and_replace_on_key_press_event (valaDevelopSearchAndReplace* self,
                                                    GtkWidget* sender,
                                                    GdkEventKey* event)
{
	gboolean result = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (sender != NULL, FALSE);
	g_return_val_if_fail (event != NULL, FALSE);
	if (event->keyval == GDK_KEY_Escape) {
		GtkSourceView* _tmp0_;
		_tmp0_ = self->priv->_view;
		gtk_widget_grab_focus ((GtkWidget*) _tmp0_);
		gtk_widget_destroy ((GtkWidget*) self);
		result = TRUE;
		return result;
	}
	result = FALSE;
	return result;
}

static gboolean
_vala_develop_search_and_replace_on_key_press_event_gtk_widget_key_press_event (GtkWidget* _sender,
                                                                                GdkEventKey* event,
                                                                                gpointer self)
{
	gboolean result;
	result = vala_develop_search_and_replace_on_key_press_event ((valaDevelopSearchAndReplace*) self, _sender, event);
	return result;
}

static gboolean
int64_try_parse (const gchar* str,
                 gint64* _result_,
                 const gchar* * unparsed)
{
	gint64 _vala__result_ = 0LL;
	const gchar* _vala_unparsed = NULL;
	gboolean result = FALSE;
	gchar* endptr = NULL;
	gchar* _tmp0_ = NULL;
	gint64 _tmp1_;
	gchar* _tmp2_;
	gint _tmp3_;
	gint _tmp4_;
	g_return_val_if_fail (str != NULL, FALSE);
	_tmp1_ = g_ascii_strtoll (str, &_tmp0_, (guint) 0);
	endptr = _tmp0_;
	_vala__result_ = _tmp1_;
	_tmp2_ = endptr;
	_tmp3_ = strlen (str);
	_tmp4_ = _tmp3_;
	if (_tmp2_ == (((gchar*) str) + _tmp4_)) {
		_vala_unparsed = "";
		result = TRUE;
		if (_result_) {
			*_result_ = _vala__result_;
		}
		if (unparsed) {
			*unparsed = _vala_unparsed;
		}
		return result;
	} else {
		gchar* _tmp5_;
		_tmp5_ = endptr;
		_vala_unparsed = (const gchar*) _tmp5_;
		result = FALSE;
		if (_result_) {
			*_result_ = _vala__result_;
		}
		if (unparsed) {
			*unparsed = _vala_unparsed;
		}
		return result;
	}
	if (_result_) {
		*_result_ = _vala__result_;
	}
	if (unparsed) {
		*unparsed = _vala_unparsed;
	}
}

static gboolean
vala_develop_search_and_replace_OnGoto (valaDevelopSearchAndReplace* self)
{
	gboolean result = FALSE;
	gint64 line = 0LL;
	GtkEntry* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	gint64 _tmp3_ = 0LL;
	gboolean _tmp4_;
	GtkTextIter iter = {0};
	GtkSourceBuffer* _tmp5_;
	GtkTextIter _tmp6_ = {0};
	GtkSourceBuffer* _tmp7_;
	GtkTextIter _tmp8_;
	GtkSourceView* _tmp9_;
	GtkTextIter _tmp10_;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->gotoText;
	_tmp1_ = gtk_entry_get_text (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp4_ = int64_try_parse (_tmp2_, &_tmp3_, NULL);
	line = _tmp3_;
	if (!_tmp4_) {
		result = TRUE;
		return result;
	}
	_tmp5_ = self->priv->_buffer;
	gtk_text_buffer_get_start_iter ((GtkTextBuffer*) _tmp5_, &_tmp6_);
	iter = _tmp6_;
	gtk_text_iter_set_line (&iter, ((gint) line) - 1);
	_tmp7_ = self->priv->_buffer;
	_tmp8_ = iter;
	gtk_text_buffer_place_cursor ((GtkTextBuffer*) _tmp7_, &_tmp8_);
	_tmp9_ = self->priv->_view;
	_tmp10_ = iter;
	gtk_text_view_scroll_to_iter ((GtkTextView*) _tmp9_, &_tmp10_, (gdouble) 0, TRUE, 0.5, 0.5);
	result = FALSE;
	return result;
}

static gboolean
_vala_develop_search_and_replace_OnGoto_gtk_widget_button_release_event (GtkWidget* _sender,
                                                                         GdkEventButton* event,
                                                                         gpointer self)
{
	gboolean result;
	result = vala_develop_search_and_replace_OnGoto ((valaDevelopSearchAndReplace*) self);
	return result;
}

static gboolean
vala_develop_search_and_replace_OnClearEntry (valaDevelopSearchAndReplace* self,
                                              GtkWidget* widget,
                                              GdkEventButton* event)
{
	gboolean result = FALSE;
	GtkEntry* _tmp0_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (widget != NULL, FALSE);
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = self->searchText;
	gtk_entry_set_text (_tmp0_, "");
	vala_develop_search_and_replace_UpdateResult (self, FALSE);
	result = FALSE;
	return result;
}

static gboolean
_vala_develop_search_and_replace_OnClearEntry_gtk_widget_button_release_event (GtkWidget* _sender,
                                                                               GdkEventButton* event,
                                                                               gpointer self)
{
	gboolean result;
	result = vala_develop_search_and_replace_OnClearEntry ((valaDevelopSearchAndReplace*) self, _sender, event);
	return result;
}

static void
vala_develop_search_and_replace_OnNextActivate (valaDevelopSearchAndReplace* self,
                                                GtkEntry* entry)
{
	g_return_if_fail (self != NULL);
	g_return_if_fail (entry != NULL);
	vala_develop_search_and_replace_OnSelectNext (self);
}

static void
_vala_develop_search_and_replace_OnNextActivate_gtk_entry_activate (GtkEntry* _sender,
                                                                    gpointer self)
{
	vala_develop_search_and_replace_OnNextActivate ((valaDevelopSearchAndReplace*) self, _sender);
}

static gboolean
vala_develop_search_and_replace_OnSearchClose (valaDevelopSearchAndReplace* self,
                                               GtkWidget* widget,
                                               GdkEventButton* event)
{
	gboolean result = FALSE;
	GtkSourceView* _tmp0_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (widget != NULL, FALSE);
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = self->priv->_view;
	gtk_widget_grab_focus ((GtkWidget*) _tmp0_);
	gtk_widget_destroy ((GtkWidget*) self);
	result = FALSE;
	return result;
}

static gboolean
_vala_develop_search_and_replace_OnSearchClose_gtk_widget_button_release_event (GtkWidget* _sender,
                                                                                GdkEventButton* event,
                                                                                gpointer self)
{
	gboolean result;
	result = vala_develop_search_and_replace_OnSearchClose ((valaDevelopSearchAndReplace*) self, _sender, event);
	return result;
}

static void
vala_develop_search_and_replace_OnGoToActivate (valaDevelopSearchAndReplace* self,
                                                GtkWidget* widget)
{
	g_return_if_fail (self != NULL);
	g_return_if_fail (widget != NULL);
	vala_develop_search_and_replace_OnGoto (self);
}

static void
_vala_develop_search_and_replace_OnGoToActivate_gtk_entry_activate (GtkEntry* _sender,
                                                                    gpointer self)
{
	vala_develop_search_and_replace_OnGoToActivate ((valaDevelopSearchAndReplace*) self, _sender);
}

static void
vala_develop_search_and_replace_OnIconRelease (valaDevelopSearchAndReplace* self,
                                               GtkEntryIconPosition icon_pos,
                                               GdkEventButton* event)
{
	GtkMenu* _tmp0_;
	GtkMenu* _tmp1_;
	GtkEntry* _tmp2_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (event != NULL);
	if (icon_pos != GTK_ENTRY_ICON_PRIMARY) {
		return;
	}
	_tmp0_ = self->menu;
	gtk_widget_show_all ((GtkWidget*) _tmp0_);
	_tmp1_ = self->menu;
	_tmp2_ = self->searchText;
	gtk_menu_popup_at_widget (_tmp1_, (GtkWidget*) _tmp2_, GDK_GRAVITY_SOUTH_WEST, GDK_GRAVITY_NORTH_WEST, (GdkEvent*) event);
}

static void
_vala_develop_search_and_replace_OnIconRelease_gtk_entry_icon_release (GtkEntry* _sender,
                                                                       GtkEntryIconPosition icon_pos,
                                                                       GdkEventButton* event,
                                                                       gpointer self)
{
	vala_develop_search_and_replace_OnIconRelease ((valaDevelopSearchAndReplace*) self, icon_pos, event);
}

static gchar*
bool_to_string (gboolean self)
{
	gchar* result = NULL;
	if (self) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup ("true");
		result = _tmp0_;
		return result;
	} else {
		gchar* _tmp1_;
		_tmp1_ = g_strdup ("false");
		result = _tmp1_;
		return result;
	}
}

static void
vala_develop_search_and_replace_CaseSensitiveToggle (valaDevelopSearchAndReplace* self,
                                                     GtkCheckMenuItem* menuItem)
{
	GtkSourceSearchSettings* _tmp0_;
	gboolean _tmp1_;
	gboolean _tmp2_;
	valaDevelopSettings* _tmp3_;
	valaDevelopSettings* _tmp4_;
	GtkSourceSearchSettings* _tmp5_;
	gboolean _tmp6_;
	gboolean _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (menuItem != NULL);
	_tmp0_ = self->priv->_searchSettings;
	_tmp1_ = gtk_check_menu_item_get_active (menuItem);
	_tmp2_ = _tmp1_;
	gtk_source_search_settings_set_case_sensitive (_tmp0_, _tmp2_);
	vala_develop_search_and_replace_SearchForwardAsync (self);
	_tmp3_ = vala_develop_xml_configuration_get_Setting ();
	_tmp4_ = _tmp3_;
	_tmp5_ = self->priv->_searchSettings;
	_tmp6_ = gtk_source_search_settings_get_case_sensitive (_tmp5_);
	_tmp7_ = _tmp6_;
	_tmp8_ = bool_to_string (_tmp7_);
	_tmp9_ = _tmp8_;
	vala_develop_settings_set (_tmp4_, "case_sensitive", _tmp9_);
	_g_free0 (_tmp9_);
	vala_develop_search_and_replace_UpdateResult (self, FALSE);
}

static void
_vala_develop_search_and_replace_CaseSensitiveToggle_gtk_check_menu_item_toggled (GtkCheckMenuItem* _sender,
                                                                                  gpointer self)
{
	vala_develop_search_and_replace_CaseSensitiveToggle ((valaDevelopSearchAndReplace*) self, _sender);
}

static void
vala_develop_search_and_replace_RegexSearchToggle (valaDevelopSearchAndReplace* self,
                                                   GtkCheckMenuItem* menuItem)
{
	GtkSourceSearchSettings* _tmp0_;
	gboolean _tmp1_;
	gboolean _tmp2_;
	valaDevelopSettings* _tmp3_;
	valaDevelopSettings* _tmp4_;
	GtkSourceSearchSettings* _tmp5_;
	gboolean _tmp6_;
	gboolean _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (menuItem != NULL);
	_tmp0_ = self->priv->_searchSettings;
	_tmp1_ = gtk_check_menu_item_get_active (menuItem);
	_tmp2_ = _tmp1_;
	gtk_source_search_settings_set_regex_enabled (_tmp0_, _tmp2_);
	vala_develop_search_and_replace_SearchForwardAsync (self);
	_tmp3_ = vala_develop_xml_configuration_get_Setting ();
	_tmp4_ = _tmp3_;
	_tmp5_ = self->priv->_searchSettings;
	_tmp6_ = gtk_source_search_settings_get_regex_enabled (_tmp5_);
	_tmp7_ = _tmp6_;
	_tmp8_ = bool_to_string (_tmp7_);
	_tmp9_ = _tmp8_;
	vala_develop_settings_set (_tmp4_, "regex_enabled", _tmp9_);
	_g_free0 (_tmp9_);
	vala_develop_search_and_replace_UpdateResult (self, FALSE);
}

static void
_vala_develop_search_and_replace_RegexSearchToggle_gtk_check_menu_item_toggled (GtkCheckMenuItem* _sender,
                                                                                gpointer self)
{
	vala_develop_search_and_replace_RegexSearchToggle ((valaDevelopSearchAndReplace*) self, _sender);
}

static void
vala_develop_search_and_replace_SearchSelectionToggle (valaDevelopSearchAndReplace* self)
{
	g_return_if_fail (self != NULL);
	vala_develop_search_and_replace_UpdateResult (self, FALSE);
}

static void
_vala_develop_search_and_replace_SearchSelectionToggle_gtk_check_menu_item_toggled (GtkCheckMenuItem* _sender,
                                                                                    gpointer self)
{
	vala_develop_search_and_replace_SearchSelectionToggle ((valaDevelopSearchAndReplace*) self);
}

static void
vala_develop_search_and_replace_WholeWordToggle (valaDevelopSearchAndReplace* self,
                                                 GtkCheckMenuItem* menuItem)
{
	GtkSourceSearchSettings* _tmp0_;
	gboolean _tmp1_;
	gboolean _tmp2_;
	valaDevelopSettings* _tmp3_;
	valaDevelopSettings* _tmp4_;
	GtkSourceSearchSettings* _tmp5_;
	gboolean _tmp6_;
	gboolean _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (menuItem != NULL);
	_tmp0_ = self->priv->_searchSettings;
	_tmp1_ = gtk_check_menu_item_get_active (menuItem);
	_tmp2_ = _tmp1_;
	gtk_source_search_settings_set_at_word_boundaries (_tmp0_, _tmp2_);
	vala_develop_search_and_replace_SearchForwardAsync (self);
	_tmp3_ = vala_develop_xml_configuration_get_Setting ();
	_tmp4_ = _tmp3_;
	_tmp5_ = self->priv->_searchSettings;
	_tmp6_ = gtk_source_search_settings_get_at_word_boundaries (_tmp5_);
	_tmp7_ = _tmp6_;
	_tmp8_ = bool_to_string (_tmp7_);
	_tmp9_ = _tmp8_;
	vala_develop_settings_set (_tmp4_, "at_word_boundaries", _tmp9_);
	_g_free0 (_tmp9_);
	vala_develop_search_and_replace_UpdateResult (self, FALSE);
}

static void
_vala_develop_search_and_replace_WholeWordToggle_gtk_check_menu_item_toggled (GtkCheckMenuItem* _sender,
                                                                              gpointer self)
{
	vala_develop_search_and_replace_WholeWordToggle ((valaDevelopSearchAndReplace*) self, _sender);
}

static void
vala_develop_search_and_replace_OnReplaceChanged (valaDevelopSearchAndReplace* self)
{
	g_return_if_fail (self != NULL);
	vala_develop_search_and_replace_UpdateResult (self, FALSE);
}

static void
_vala_develop_search_and_replace_OnReplaceChanged_gtk_editable_changed (GtkEditable* _sender,
                                                                        gpointer self)
{
	vala_develop_search_and_replace_OnReplaceChanged ((valaDevelopSearchAndReplace*) self);
}

static gchar*
string_replace (const gchar* self,
                const gchar* old,
                const gchar* replacement)
{
	gchar* result = NULL;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	GError* _inner_error0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	if ((*((gchar*) self)) == '\0') {
		_tmp1_ = TRUE;
	} else {
		_tmp1_ = (*((gchar*) old)) == '\0';
	}
	if (_tmp1_) {
		_tmp0_ = TRUE;
	} else {
		_tmp0_ = g_strcmp0 (old, replacement) == 0;
	}
	if (_tmp0_) {
		gchar* _tmp2_;
		_tmp2_ = g_strdup (self);
		result = _tmp2_;
		return result;
	}
	{
		GRegex* regex = NULL;
		gchar* _tmp3_;
		gchar* _tmp4_;
		GRegex* _tmp5_;
		GRegex* _tmp6_;
		gchar* _tmp7_ = NULL;
		GRegex* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		_tmp3_ = g_regex_escape_string (old, -1);
		_tmp4_ = _tmp3_;
		_tmp5_ = g_regex_new (_tmp4_, 0, 0, &_inner_error0_);
		_tmp6_ = _tmp5_;
		_g_free0 (_tmp4_);
		regex = _tmp6_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			if (_inner_error0_->domain == G_REGEX_ERROR) {
				goto __catch7_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return NULL;
		}
		_tmp8_ = regex;
		_tmp9_ = g_regex_replace_literal (_tmp8_, self, (gssize) -1, 0, replacement, 0, &_inner_error0_);
		_tmp7_ = _tmp9_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_regex_unref0 (regex);
			if (_inner_error0_->domain == G_REGEX_ERROR) {
				goto __catch7_g_regex_error;
			}
			_g_regex_unref0 (regex);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return NULL;
		}
		_tmp10_ = _tmp7_;
		_tmp7_ = NULL;
		result = _tmp10_;
		_g_free0 (_tmp7_);
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally7;
	__catch7_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		g_assert_not_reached ();
		_g_error_free0 (e);
	}
	__finally7:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return NULL;
	}
}

static void
vala_develop_search_and_replace_OnTextChanged (valaDevelopSearchAndReplace* self)
{
	GtkSourceSearchSettings* _tmp0_;
	GtkEntry* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_searchSettings;
	_tmp1_ = self->searchText;
	_tmp2_ = gtk_entry_get_text (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = string_replace (_tmp3_, "\\t", "\t");
	_tmp5_ = _tmp4_;
	gtk_source_search_settings_set_search_text (_tmp0_, _tmp5_);
	_g_free0 (_tmp5_);
	vala_develop_search_and_replace_SearchForwardAsync (self);
}

static void
_vala_develop_search_and_replace_OnTextChanged_gtk_editable_changed (GtkEditable* _sender,
                                                                     gpointer self)
{
	vala_develop_search_and_replace_OnTextChanged ((valaDevelopSearchAndReplace*) self);
}

static Block2Data*
block2_data_ref (Block2Data* _data2_)
{
	g_atomic_int_inc (&_data2_->_ref_count_);
	return _data2_;
}

static void
block2_data_unref (void * _userdata_)
{
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
		valaDevelopSearchAndReplace* self;
		self = _data2_->self;
		_g_object_unref0 (self);
		g_slice_free (Block2Data, _data2_);
	}
}

static gboolean
___lambda80_ (Block2Data* _data2_)
{
	valaDevelopSearchAndReplace* self;
	gboolean result = FALSE;
	GtkSourceView* _tmp0_;
	GtkTextIter _tmp1_;
	self = _data2_->self;
	_tmp0_ = self->priv->_view;
	_tmp1_ = _data2_->matchStart;
	if (gtk_text_view_scroll_to_iter ((GtkTextView*) _tmp0_, &_tmp1_, (gdouble) 0, TRUE, 0.5, 0.5)) {
		result = FALSE;
		return result;
	}
	result = TRUE;
	return result;
}

static gboolean
____lambda80__gsource_func (gpointer self)
{
	gboolean result;
	result = ___lambda80_ (self);
	return result;
}

static void
__lambda79_ (valaDevelopSearchAndReplace* self,
             GObject* source_object,
             GAsyncResult* res)
{
	Block2Data* _data2_;
	GtkTextIter matchEnd = {0};
	gboolean wrapped = FALSE;
	gboolean _tmp0_ = FALSE;
	GtkTextIter _tmp1_ = {0};
	GtkTextIter _tmp2_ = {0};
	gboolean _tmp3_ = FALSE;
	gboolean _tmp4_;
	GError* _inner_error0_ = NULL;
	g_return_if_fail (res != NULL);
	_data2_ = g_slice_new0 (Block2Data);
	_data2_->_ref_count_ = 1;
	_data2_->self = g_object_ref (self);
	_tmp4_ = gtk_source_search_context_forward_finish2 (G_TYPE_CHECK_INSTANCE_TYPE (source_object, gtk_source_search_context_get_type ()) ? ((GtkSourceSearchContext*) source_object) : NULL, res, &_tmp1_, &_tmp2_, &_tmp3_, &_inner_error0_);
	_data2_->matchStart = _tmp1_;
	matchEnd = _tmp2_;
	wrapped = _tmp3_;
	_tmp0_ = _tmp4_;
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		block2_data_unref (_data2_);
		_data2_ = NULL;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
	if (_tmp0_) {
		GtkSourceBuffer* _tmp5_;
		GtkTextIter _tmp6_;
		GtkTextIter _tmp7_;
		_tmp5_ = self->priv->_buffer;
		_tmp6_ = _data2_->matchStart;
		_tmp7_ = matchEnd;
		gtk_text_buffer_select_range ((GtkTextBuffer*) _tmp5_, &_tmp6_, &_tmp7_);
		g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, ____lambda80__gsource_func, block2_data_ref (_data2_), block2_data_unref);
	}
	vala_develop_search_and_replace_UpdateResult (self, FALSE);
	block2_data_unref (_data2_);
	_data2_ = NULL;
}

static void
___lambda79__gasync_ready_callback (GObject* source_object,
                                    GAsyncResult* res,
                                    gpointer self)
{
	__lambda79_ ((valaDevelopSearchAndReplace*) self, source_object, res);
	g_object_unref (self);
}

static void
vala_develop_search_and_replace_SearchForwardAsync (valaDevelopSearchAndReplace* self)
{
	GtkTextIter currentIter = {0};
	GtkSourceBuffer* _tmp0_;
	GtkSourceBuffer* _tmp1_;
	GtkTextMark* _tmp2_;
	GtkTextIter _tmp3_ = {0};
	GtkSourceSearchContext* _tmp4_;
	GtkTextIter _tmp5_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_buffer;
	_tmp1_ = self->priv->_buffer;
	_tmp2_ = gtk_text_buffer_get_insert ((GtkTextBuffer*) _tmp1_);
	gtk_text_buffer_get_iter_at_mark ((GtkTextBuffer*) _tmp0_, &_tmp3_, _tmp2_);
	currentIter = _tmp3_;
	_tmp4_ = self->priv->_searchContext;
	_tmp5_ = currentIter;
	gtk_source_search_context_forward_async (_tmp4_, &_tmp5_, NULL, ___lambda79__gasync_ready_callback, g_object_ref (self));
}

void
vala_develop_search_and_replace_entry_grab_focus (valaDevelopSearchAndReplace* self)
{
	valaDevelopSearchTypeEnum _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_searchType;
	switch (_tmp0_) {
		case VALA_DEVELOP_SEARCH_TYPE_ENUM_Find:
		case VALA_DEVELOP_SEARCH_TYPE_ENUM_Replace:
		{
			GtkEntry* _tmp1_;
			_tmp1_ = self->searchText;
			gtk_widget_grab_focus ((GtkWidget*) _tmp1_);
			break;
		}
		case VALA_DEVELOP_SEARCH_TYPE_ENUM_Goto:
		{
			GtkEntry* _tmp2_;
			_tmp2_ = self->gotoText;
			gtk_widget_grab_focus ((GtkWidget*) _tmp2_);
			break;
		}
		default:
		break;
	}
}

gboolean
vala_develop_search_and_replace_OnSelectPrev (valaDevelopSearchAndReplace* self)
{
	gboolean result = FALSE;
	GtkTextIter start = {0};
	GtkTextIter end = {0};
	GtkSourceBuffer* _tmp0_;
	GtkTextIter _tmp1_ = {0};
	GtkTextIter _tmp2_ = {0};
	gboolean _tmp3_;
	GtkTextIter matchStart = {0};
	GtkTextIter matchEnd = {0};
	gboolean wrapped = FALSE;
	GError* _inner_error0_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_buffer;
	_tmp3_ = gtk_text_buffer_get_selection_bounds ((GtkTextBuffer*) _tmp0_, &_tmp1_, &_tmp2_);
	start = _tmp1_;
	end = _tmp2_;
	if (!_tmp3_) {
		GtkSourceBuffer* _tmp4_;
		GtkSourceBuffer* _tmp5_;
		GtkTextMark* _tmp6_;
		GtkTextIter _tmp7_ = {0};
		_tmp4_ = self->priv->_buffer;
		_tmp5_ = self->priv->_buffer;
		_tmp6_ = gtk_text_buffer_get_insert ((GtkTextBuffer*) _tmp5_);
		gtk_text_buffer_get_iter_at_mark ((GtkTextBuffer*) _tmp4_, &_tmp7_, _tmp6_);
		start = _tmp7_;
	}
	{
		GtkSourceSearchContext* _tmp8_;
		_tmp8_ = self->priv->_searchContext;
		g_rec_mutex_lock (&self->priv->__lock__searchContext);
		{
			GtkSourceSearchContext* _tmp9_;
			GtkTextIter _tmp10_;
			GtkTextIter _tmp11_ = {0};
			GtkTextIter _tmp12_ = {0};
			gboolean _tmp13_ = FALSE;
			gboolean _tmp14_;
			_tmp9_ = self->priv->_searchContext;
			_tmp10_ = start;
			_tmp14_ = gtk_source_search_context_backward2 (_tmp9_, &_tmp10_, &_tmp11_, &_tmp12_, &_tmp13_);
			matchStart = _tmp11_;
			matchEnd = _tmp12_;
			wrapped = _tmp13_;
			if (_tmp14_) {
				GtkSourceBuffer* _tmp15_;
				GtkTextIter _tmp16_;
				GtkTextIter _tmp17_;
				GtkSourceView* _tmp18_;
				GtkTextIter _tmp19_;
				_tmp15_ = self->priv->_buffer;
				_tmp16_ = matchStart;
				_tmp17_ = matchEnd;
				gtk_text_buffer_select_range ((GtkTextBuffer*) _tmp15_, &_tmp16_, &_tmp17_);
				vala_develop_search_and_replace_UpdateResult (self, FALSE);
				_tmp18_ = self->priv->_view;
				_tmp19_ = matchStart;
				gtk_text_view_scroll_to_iter ((GtkTextView*) _tmp18_, &_tmp19_, (gdouble) 0, TRUE, 0.5, 0.5);
			}
		}
		__finally8:
		{
			GtkSourceSearchContext* _tmp20_;
			_tmp20_ = self->priv->_searchContext;
			g_rec_mutex_unlock (&self->priv->__lock__searchContext);
		}
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			gboolean _tmp21_ = FALSE;
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return _tmp21_;
		}
	}
	result = FALSE;
	return result;
}

static gboolean
_vala_develop_search_and_replace_OnSelectPrev_gtk_widget_button_release_event (GtkWidget* _sender,
                                                                               GdkEventButton* event,
                                                                               gpointer self)
{
	gboolean result;
	result = vala_develop_search_and_replace_OnSelectPrev ((valaDevelopSearchAndReplace*) self);
	return result;
}

gboolean
vala_develop_search_and_replace_OnSelectNext (valaDevelopSearchAndReplace* self)
{
	gboolean result = FALSE;
	GtkTextIter start = {0};
	GtkTextIter end = {0};
	GtkSourceBuffer* _tmp0_;
	GtkTextIter _tmp1_ = {0};
	GtkTextIter _tmp2_ = {0};
	gboolean _tmp3_;
	GtkTextIter matchStart = {0};
	GtkTextIter matchEnd = {0};
	gboolean wrapped = FALSE;
	GError* _inner_error0_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_buffer;
	_tmp3_ = gtk_text_buffer_get_selection_bounds ((GtkTextBuffer*) _tmp0_, &_tmp1_, &_tmp2_);
	start = _tmp1_;
	end = _tmp2_;
	if (!_tmp3_) {
		GtkSourceBuffer* _tmp4_;
		GtkSourceBuffer* _tmp5_;
		GtkTextMark* _tmp6_;
		GtkTextIter _tmp7_ = {0};
		_tmp4_ = self->priv->_buffer;
		_tmp5_ = self->priv->_buffer;
		_tmp6_ = gtk_text_buffer_get_insert ((GtkTextBuffer*) _tmp5_);
		gtk_text_buffer_get_iter_at_mark ((GtkTextBuffer*) _tmp4_, &_tmp7_, _tmp6_);
		start = _tmp7_;
	}
	{
		GtkSourceSearchContext* _tmp8_;
		_tmp8_ = self->priv->_searchContext;
		g_rec_mutex_lock (&self->priv->__lock__searchContext);
		{
			GtkSourceSearchContext* _tmp9_;
			GtkTextIter _tmp10_;
			GtkTextIter _tmp11_ = {0};
			GtkTextIter _tmp12_ = {0};
			gboolean _tmp13_ = FALSE;
			gboolean _tmp14_;
			_tmp9_ = self->priv->_searchContext;
			_tmp10_ = end;
			_tmp14_ = gtk_source_search_context_forward2 (_tmp9_, &_tmp10_, &_tmp11_, &_tmp12_, &_tmp13_);
			matchStart = _tmp11_;
			matchEnd = _tmp12_;
			wrapped = _tmp13_;
			if (_tmp14_) {
				GtkSourceBuffer* _tmp15_;
				GtkTextIter _tmp16_;
				GtkTextIter _tmp17_;
				GtkSourceView* _tmp18_;
				GtkTextIter _tmp19_;
				_tmp15_ = self->priv->_buffer;
				_tmp16_ = matchStart;
				_tmp17_ = matchEnd;
				gtk_text_buffer_select_range ((GtkTextBuffer*) _tmp15_, &_tmp16_, &_tmp17_);
				vala_develop_search_and_replace_UpdateResult (self, FALSE);
				_tmp18_ = self->priv->_view;
				_tmp19_ = matchStart;
				gtk_text_view_scroll_to_iter ((GtkTextView*) _tmp18_, &_tmp19_, (gdouble) 0, TRUE, 0.5, 0.5);
			}
		}
		__finally9:
		{
			GtkSourceSearchContext* _tmp20_;
			_tmp20_ = self->priv->_searchContext;
			g_rec_mutex_unlock (&self->priv->__lock__searchContext);
		}
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			gboolean _tmp21_ = FALSE;
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return _tmp21_;
		}
	}
	result = FALSE;
	return result;
}

static gboolean
_vala_develop_search_and_replace_OnSelectNext_gtk_widget_button_release_event (GtkWidget* _sender,
                                                                               GdkEventButton* event,
                                                                               gpointer self)
{
	gboolean result;
	result = vala_develop_search_and_replace_OnSelectNext ((valaDevelopSearchAndReplace*) self);
	return result;
}

static gboolean
string_contains (const gchar* self,
                 const gchar* needle)
{
	gboolean result = FALSE;
	gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (needle != NULL, FALSE);
	_tmp0_ = strstr ((gchar*) self, (gchar*) needle);
	result = _tmp0_ != NULL;
	return result;
}

static gboolean
vala_develop_search_and_replace_OnReplace (valaDevelopSearchAndReplace* self,
                                           GtkWidget* widget,
                                           GdkEventButton* event)
{
	gboolean result = FALSE;
	GtkTextIter start = {0};
	GtkTextIter end = {0};
	gchar* search = NULL;
	GtkEntry* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	const gchar* _tmp4_;
	gboolean _tmp7_ = FALSE;
	GtkSourceBuffer* _tmp8_;
	GtkTextIter _tmp9_ = {0};
	GtkTextIter _tmp10_ = {0};
	gboolean _tmp11_;
	GError* _inner_error0_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (widget != NULL, FALSE);
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = self->searchText;
	_tmp1_ = gtk_entry_get_text (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strdup (_tmp2_);
	search = _tmp3_;
	_tmp4_ = search;
	if (string_contains (_tmp4_, "\\t")) {
		const gchar* _tmp5_;
		gchar* _tmp6_;
		_tmp5_ = search;
		_tmp6_ = string_replace (_tmp5_, "\\t", "\t");
		_g_free0 (search);
		search = _tmp6_;
	}
	_tmp8_ = self->priv->_buffer;
	_tmp11_ = gtk_text_buffer_get_selection_bounds ((GtkTextBuffer*) _tmp8_, &_tmp9_, &_tmp10_);
	start = _tmp9_;
	end = _tmp10_;
	if (_tmp11_) {
		GtkSourceBuffer* _tmp12_;
		GtkTextIter _tmp13_;
		GtkTextIter _tmp14_;
		gchar* _tmp15_;
		gchar* _tmp16_;
		const gchar* _tmp17_;
		_tmp12_ = self->priv->_buffer;
		_tmp13_ = start;
		_tmp14_ = end;
		_tmp15_ = gtk_text_buffer_get_text ((GtkTextBuffer*) _tmp12_, &_tmp13_, &_tmp14_, FALSE);
		_tmp16_ = _tmp15_;
		_tmp17_ = search;
		_tmp7_ = g_strcmp0 (_tmp16_, _tmp17_) == 0;
		_g_free0 (_tmp16_);
	} else {
		_tmp7_ = FALSE;
	}
	if (_tmp7_) {
		{
			GtkSourceSearchContext* _tmp18_;
			_tmp18_ = self->priv->_searchContext;
			g_rec_mutex_lock (&self->priv->__lock__searchContext);
			{
				gchar* replace = NULL;
				GtkEntry* _tmp19_;
				const gchar* _tmp20_;
				const gchar* _tmp21_;
				gchar* _tmp22_;
				const gchar* _tmp23_;
				gboolean _tmp26_ = FALSE;
				GtkSourceSearchContext* _tmp27_;
				GtkTextIter _tmp28_;
				GtkTextIter _tmp29_;
				const gchar* _tmp30_;
				_tmp19_ = self->replaceText;
				_tmp20_ = gtk_entry_get_text (_tmp19_);
				_tmp21_ = _tmp20_;
				_tmp22_ = g_strdup (_tmp21_);
				replace = _tmp22_;
				_tmp23_ = replace;
				if (string_contains (_tmp23_, "\\t")) {
					const gchar* _tmp24_;
					gchar* _tmp25_;
					_tmp24_ = replace;
					_tmp25_ = string_replace (_tmp24_, "\\t", "\t");
					_g_free0 (replace);
					replace = _tmp25_;
				}
				_tmp27_ = self->priv->_searchContext;
				_tmp28_ = start;
				_tmp29_ = end;
				_tmp30_ = replace;
				_tmp26_ = gtk_source_search_context_replace2 (_tmp27_, &_tmp28_, &_tmp29_, _tmp30_, -1, &_inner_error0_);
				if (G_UNLIKELY (_inner_error0_ != NULL)) {
					_g_free0 (replace);
					goto __finally10;
				}
				if (_tmp26_) {
					GtkSourceBuffer* _tmp31_;
					_tmp31_ = self->priv->_buffer;
					gtk_text_buffer_set_modified ((GtkTextBuffer*) _tmp31_, TRUE);
					vala_develop_search_and_replace_OnSelectNext (self);
				}
				_g_free0 (replace);
			}
			__finally10:
			{
				GError* _inner_error1_ = NULL;
				GtkSourceSearchContext* _tmp32_;
				_tmp32_ = self->priv->_searchContext;
				g_rec_mutex_unlock (&self->priv->__lock__searchContext);
			}
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
				gboolean _tmp33_ = FALSE;
				_g_free0 (search);
				g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
				g_clear_error (&_inner_error0_);
				return _tmp33_;
			}
		}
	}
	vala_develop_search_and_replace_UpdateResult (self, FALSE);
	result = FALSE;
	_g_free0 (search);
	return result;
}

static gboolean
_vala_develop_search_and_replace_OnReplace_gtk_widget_button_release_event (GtkWidget* _sender,
                                                                            GdkEventButton* event,
                                                                            gpointer self)
{
	gboolean result;
	result = vala_develop_search_and_replace_OnReplace ((valaDevelopSearchAndReplace*) self, _sender, event);
	return result;
}

static gboolean
vala_develop_search_and_replace_OnReplaceAll (valaDevelopSearchAndReplace* self,
                                              GtkWidget* widget,
                                              GdkEventButton* event)
{
	gboolean result = FALSE;
	GError* _inner_error0_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (widget != NULL, FALSE);
	g_return_val_if_fail (event != NULL, FALSE);
	{
		GtkSourceSearchContext* _tmp0_;
		_tmp0_ = self->priv->_searchContext;
		g_rec_mutex_lock (&self->priv->__lock__searchContext);
		{
			gchar* replace = NULL;
			GtkEntry* _tmp1_;
			const gchar* _tmp2_;
			const gchar* _tmp3_;
			gchar* _tmp4_;
			const gchar* _tmp5_;
			guint replaced = 0U;
			GtkSourceSearchContext* _tmp8_;
			const gchar* _tmp9_;
			_tmp1_ = self->replaceText;
			_tmp2_ = gtk_entry_get_text (_tmp1_);
			_tmp3_ = _tmp2_;
			_tmp4_ = g_strdup (_tmp3_);
			replace = _tmp4_;
			_tmp5_ = replace;
			if (string_contains (_tmp5_, "\\t")) {
				const gchar* _tmp6_;
				gchar* _tmp7_;
				_tmp6_ = replace;
				_tmp7_ = string_replace (_tmp6_, "\\t", "\t");
				_g_free0 (replace);
				replace = _tmp7_;
			}
			_tmp8_ = self->priv->_searchContext;
			_tmp9_ = replace;
			replaced = gtk_source_search_context_replace_all (_tmp8_, _tmp9_, -1, &_inner_error0_);
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
				_g_free0 (replace);
				goto __finally11;
			}
			if (replaced > ((guint) 0)) {
				GtkSourceBuffer* _tmp10_;
				_tmp10_ = self->priv->_buffer;
				gtk_text_buffer_set_modified ((GtkTextBuffer*) _tmp10_, TRUE);
			}
			vala_develop_search_and_replace_UpdateResult (self, FALSE);
			_g_free0 (replace);
		}
		__finally11:
		{
			GError* _inner_error1_ = NULL;
			GtkSourceSearchContext* _tmp11_;
			_tmp11_ = self->priv->_searchContext;
			g_rec_mutex_unlock (&self->priv->__lock__searchContext);
		}
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			gboolean _tmp12_ = FALSE;
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return _tmp12_;
		}
	}
	result = FALSE;
	return result;
}

static gboolean
_vala_develop_search_and_replace_OnReplaceAll_gtk_widget_button_release_event (GtkWidget* _sender,
                                                                               GdkEventButton* event,
                                                                               gpointer self)
{
	gboolean result;
	result = vala_develop_search_and_replace_OnReplaceAll ((valaDevelopSearchAndReplace*) self, _sender, event);
	return result;
}

static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}

void
vala_develop_search_and_replace_UpdateResult (valaDevelopSearchAndReplace* self,
                                              gboolean withForward)
{
	gint matches = 0;
	GtkSourceSearchContext* _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	gchar* _tmp3_ = NULL;
	GtkLabel* _tmp9_;
	gboolean sensitive = FALSE;
	GtkEventBox* _tmp10_;
	GtkEventBox* _tmp11_;
	GtkEventBox* _tmp12_;
	GtkEventBox* _tmp13_;
	GtkEntry* _tmp14_;
	const gchar* _tmp15_;
	const gchar* _tmp16_;
	GtkEventBox* _tmp17_;
	GtkEntry* _tmp18_;
	const gchar* _tmp19_;
	const gchar* _tmp20_;
	g_return_if_fail (self != NULL);
	if (withForward) {
		vala_develop_search_and_replace_SearchForwardAsync (self);
	}
	_tmp0_ = self->priv->_searchContext;
	_tmp1_ = gtk_source_search_context_get_occurrences_count (_tmp0_);
	_tmp2_ = _tmp1_;
	matches = _tmp2_;
	if (matches > 0) {
		gchar* _tmp4_;
		gchar* _tmp5_;
		gchar* _tmp6_;
		_tmp4_ = g_strdup_printf ("%i", matches);
		_tmp5_ = _tmp4_;
		_tmp6_ = g_strconcat (_tmp5_, " matches", NULL);
		_g_free0 (_tmp3_);
		_tmp3_ = _tmp6_;
		_g_free0 (_tmp5_);
	} else {
		const gchar* _tmp7_;
		gchar* _tmp8_;
		_tmp7_ = string_to_string (_ ("Not found"));
		_tmp8_ = g_strconcat ("<span color=\"red\">", _tmp7_, "</span>", NULL);
		_g_free0 (_tmp3_);
		_tmp3_ = _tmp8_;
	}
	_tmp9_ = self->text;
	gtk_label_set_markup (_tmp9_, _tmp3_);
	sensitive = matches > 0;
	_tmp10_ = self->prevResult;
	gtk_widget_set_sensitive ((GtkWidget*) _tmp10_, sensitive);
	_tmp11_ = self->prevResult;
	gtk_widget_set_has_tooltip ((GtkWidget*) _tmp11_, TRUE);
	_tmp12_ = self->nextResult;
	gtk_widget_set_sensitive ((GtkWidget*) _tmp12_, sensitive);
	_tmp13_ = self->replaceEventBox;
	_tmp14_ = self->searchText;
	_tmp15_ = gtk_entry_get_text (_tmp14_);
	_tmp16_ = _tmp15_;
	gtk_widget_set_sensitive ((GtkWidget*) _tmp13_, g_strcmp0 (_tmp16_, "") != 0);
	_tmp17_ = self->replaceAllEventBox;
	_tmp18_ = self->searchText;
	_tmp19_ = gtk_entry_get_text (_tmp18_);
	_tmp20_ = _tmp19_;
	gtk_widget_set_sensitive ((GtkWidget*) _tmp17_, g_strcmp0 (_tmp20_, "") != 0);
	_g_free0 (_tmp3_);
}

valaDevelopSearchTypeEnum
vala_develop_search_and_replace_get_SearchType (valaDevelopSearchAndReplace* self)
{
	valaDevelopSearchTypeEnum result;
	valaDevelopSearchTypeEnum _tmp0_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_searchType;
	result = _tmp0_;
	return result;
}

void
vala_develop_search_and_replace_set_SearchType (valaDevelopSearchAndReplace* self,
                                                valaDevelopSearchTypeEnum value)
{
	valaDevelopSearchTypeEnum _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_searchType = value;
	_tmp0_ = self->priv->_searchType;
	switch (_tmp0_) {
		case VALA_DEVELOP_SEARCH_TYPE_ENUM_Find:
		{
			GtkFrame* _tmp1_;
			GtkFrame* _tmp2_;
			GtkFrame* _tmp3_;
			_tmp1_ = self->gotoLine;
			gtk_widget_set_visible ((GtkWidget*) _tmp1_, FALSE);
			_tmp2_ = self->replace;
			gtk_widget_set_visible ((GtkWidget*) _tmp2_, FALSE);
			_tmp3_ = self->search;
			gtk_widget_set_visible ((GtkWidget*) _tmp3_, TRUE);
			break;
		}
		case VALA_DEVELOP_SEARCH_TYPE_ENUM_Replace:
		{
			GtkFrame* _tmp4_;
			GtkFrame* _tmp5_;
			GtkFrame* _tmp6_;
			_tmp4_ = self->gotoLine;
			gtk_widget_set_visible ((GtkWidget*) _tmp4_, FALSE);
			_tmp5_ = self->replace;
			gtk_widget_set_visible ((GtkWidget*) _tmp5_, TRUE);
			_tmp6_ = self->search;
			gtk_widget_set_visible ((GtkWidget*) _tmp6_, TRUE);
			break;
		}
		case VALA_DEVELOP_SEARCH_TYPE_ENUM_Goto:
		{
			GtkFrame* _tmp7_;
			GtkFrame* _tmp8_;
			GtkFrame* _tmp9_;
			_tmp7_ = self->gotoLine;
			gtk_widget_set_visible ((GtkWidget*) _tmp7_, TRUE);
			_tmp8_ = self->replace;
			gtk_widget_set_visible ((GtkWidget*) _tmp8_, FALSE);
			_tmp9_ = self->search;
			gtk_widget_set_visible ((GtkWidget*) _tmp9_, FALSE);
			break;
		}
		default:
		break;
	}
	g_object_notify_by_pspec ((GObject *) self, vala_develop_search_and_replace_properties[VALA_DEVELOP_SEARCH_AND_REPLACE_SEARCH_TYPE_PROPERTY]);
}

static void
vala_develop_search_and_replace_class_init (valaDevelopSearchAndReplaceClass * klass,
                                            gpointer klass_data)
{
	vala_develop_search_and_replace_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &valaDevelopSearchAndReplace_private_offset);
	G_OBJECT_CLASS (klass)->get_property = _vala_vala_develop_search_and_replace_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_vala_develop_search_and_replace_set_property;
	G_OBJECT_CLASS (klass)->finalize = vala_develop_search_and_replace_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), VALA_DEVELOP_SEARCH_AND_REPLACE_SEARCH_TYPE_PROPERTY, vala_develop_search_and_replace_properties[VALA_DEVELOP_SEARCH_AND_REPLACE_SEARCH_TYPE_PROPERTY] = g_param_spec_enum ("SearchType", "SearchType", "SearchType", VALA_DEVELOP_TYPE_SEARCH_TYPE_ENUM, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/valaDevelop/findReplace.glade");
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "searchText", FALSE, G_STRUCT_OFFSET (valaDevelopSearchAndReplace, searchText));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "replaceText", FALSE, G_STRUCT_OFFSET (valaDevelopSearchAndReplace, replaceText));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "gotoText", FALSE, G_STRUCT_OFFSET (valaDevelopSearchAndReplace, gotoText));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "text", FALSE, G_STRUCT_OFFSET (valaDevelopSearchAndReplace, text));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "menu", FALSE, G_STRUCT_OFFSET (valaDevelopSearchAndReplace, menu));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "caseSensitive", FALSE, G_STRUCT_OFFSET (valaDevelopSearchAndReplace, caseSensitive));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "regexSearch", FALSE, G_STRUCT_OFFSET (valaDevelopSearchAndReplace, regexSearch));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "selectionSearch", FALSE, G_STRUCT_OFFSET (valaDevelopSearchAndReplace, selectionSearch));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "wholeWord", FALSE, G_STRUCT_OFFSET (valaDevelopSearchAndReplace, wholeWord));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "prevResult", FALSE, G_STRUCT_OFFSET (valaDevelopSearchAndReplace, prevResult));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "nextResult", FALSE, G_STRUCT_OFFSET (valaDevelopSearchAndReplace, nextResult));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "gotoEventBox", FALSE, G_STRUCT_OFFSET (valaDevelopSearchAndReplace, gotoEventBox));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "replaceEventBox", FALSE, G_STRUCT_OFFSET (valaDevelopSearchAndReplace, replaceEventBox));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "replaceAllEventBox", FALSE, G_STRUCT_OFFSET (valaDevelopSearchAndReplace, replaceAllEventBox));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "search", FALSE, G_STRUCT_OFFSET (valaDevelopSearchAndReplace, search));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "replace", FALSE, G_STRUCT_OFFSET (valaDevelopSearchAndReplace, replace));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "gotoLine", FALSE, G_STRUCT_OFFSET (valaDevelopSearchAndReplace, gotoLine));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "closeImage", FALSE, valaDevelopSearchAndReplace_private_offset + G_STRUCT_OFFSET (valaDevelopSearchAndReplacePrivate, closeImage));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "downImage", FALSE, valaDevelopSearchAndReplace_private_offset + G_STRUCT_OFFSET (valaDevelopSearchAndReplacePrivate, downImage));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "upImage", FALSE, valaDevelopSearchAndReplace_private_offset + G_STRUCT_OFFSET (valaDevelopSearchAndReplacePrivate, upImage));
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "on_key_press_event", G_CALLBACK(_vala_develop_search_and_replace_on_key_press_event_gtk_widget_key_press_event));
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "OnGoto", G_CALLBACK(_vala_develop_search_and_replace_OnGoto_gtk_widget_button_release_event));
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "OnClearEntry", G_CALLBACK(_vala_develop_search_and_replace_OnClearEntry_gtk_widget_button_release_event));
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "OnNextActivate", G_CALLBACK(_vala_develop_search_and_replace_OnNextActivate_gtk_entry_activate));
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "OnSearchClose", G_CALLBACK(_vala_develop_search_and_replace_OnSearchClose_gtk_widget_button_release_event));
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "OnGoToActivate", G_CALLBACK(_vala_develop_search_and_replace_OnGoToActivate_gtk_entry_activate));
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "OnIconRelease", G_CALLBACK(_vala_develop_search_and_replace_OnIconRelease_gtk_entry_icon_release));
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "CaseSensitiveToggle", G_CALLBACK(_vala_develop_search_and_replace_CaseSensitiveToggle_gtk_check_menu_item_toggled));
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "RegexSearchToggle", G_CALLBACK(_vala_develop_search_and_replace_RegexSearchToggle_gtk_check_menu_item_toggled));
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "SearchSelectionToggle", G_CALLBACK(_vala_develop_search_and_replace_SearchSelectionToggle_gtk_check_menu_item_toggled));
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "WholeWordToggle", G_CALLBACK(_vala_develop_search_and_replace_WholeWordToggle_gtk_check_menu_item_toggled));
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "OnReplaceChanged", G_CALLBACK(_vala_develop_search_and_replace_OnReplaceChanged_gtk_editable_changed));
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "OnTextChanged", G_CALLBACK(_vala_develop_search_and_replace_OnTextChanged_gtk_editable_changed));
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "OnSelectPrev", G_CALLBACK(_vala_develop_search_and_replace_OnSelectPrev_gtk_widget_button_release_event));
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "OnSelectNext", G_CALLBACK(_vala_develop_search_and_replace_OnSelectNext_gtk_widget_button_release_event));
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "OnReplace", G_CALLBACK(_vala_develop_search_and_replace_OnReplace_gtk_widget_button_release_event));
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "OnReplaceAll", G_CALLBACK(_vala_develop_search_and_replace_OnReplaceAll_gtk_widget_button_release_event));
}

static void
vala_develop_search_and_replace_instance_init (valaDevelopSearchAndReplace * self,
                                               gpointer klass)
{
	self->priv = vala_develop_search_and_replace_get_instance_private (self);
	g_rec_mutex_init (&self->priv->__lock__searchContext);
	gtk_widget_init_template (GTK_WIDGET (self));
}

static void
vala_develop_search_and_replace_finalize (GObject * obj)
{
	valaDevelopSearchAndReplace * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALA_DEVELOP_TYPE_SEARCH_AND_REPLACE, valaDevelopSearchAndReplace);
	_g_object_unref0 (self->searchText);
	_g_object_unref0 (self->replaceText);
	_g_object_unref0 (self->gotoText);
	_g_object_unref0 (self->text);
	_g_object_unref0 (self->menu);
	_g_object_unref0 (self->caseSensitive);
	_g_object_unref0 (self->regexSearch);
	_g_object_unref0 (self->selectionSearch);
	_g_object_unref0 (self->wholeWord);
	_g_object_unref0 (self->prevResult);
	_g_object_unref0 (self->nextResult);
	_g_object_unref0 (self->gotoEventBox);
	_g_object_unref0 (self->replaceEventBox);
	_g_object_unref0 (self->replaceAllEventBox);
	_g_object_unref0 (self->search);
	_g_object_unref0 (self->replace);
	_g_object_unref0 (self->gotoLine);
	_g_object_unref0 (self->priv->closeImage);
	_g_object_unref0 (self->priv->downImage);
	_g_object_unref0 (self->priv->upImage);
	_g_object_unref0 (self->priv->_view);
	_g_object_unref0 (self->priv->_buffer);
	_g_object_unref0 (self->priv->_searchSettings);
	g_rec_mutex_clear (&self->priv->__lock__searchContext);
	_g_object_unref0 (self->priv->_searchContext);
	G_OBJECT_CLASS (vala_develop_search_and_replace_parent_class)->finalize (obj);
}

GType
vala_develop_search_and_replace_get_type (void)
{
	static volatile gsize vala_develop_search_and_replace_type_id__volatile = 0;
	if (g_once_init_enter (&vala_develop_search_and_replace_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (valaDevelopSearchAndReplaceClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_develop_search_and_replace_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (valaDevelopSearchAndReplace), 0, (GInstanceInitFunc) vala_develop_search_and_replace_instance_init, NULL };
		GType vala_develop_search_and_replace_type_id;
		vala_develop_search_and_replace_type_id = g_type_register_static (gtk_box_get_type (), "valaDevelopSearchAndReplace", &g_define_type_info, 0);
		valaDevelopSearchAndReplace_private_offset = g_type_add_instance_private (vala_develop_search_and_replace_type_id, sizeof (valaDevelopSearchAndReplacePrivate));
		g_once_init_leave (&vala_develop_search_and_replace_type_id__volatile, vala_develop_search_and_replace_type_id);
	}
	return vala_develop_search_and_replace_type_id__volatile;
}

static void
_vala_vala_develop_search_and_replace_get_property (GObject * object,
                                                    guint property_id,
                                                    GValue * value,
                                                    GParamSpec * pspec)
{
	valaDevelopSearchAndReplace * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, VALA_DEVELOP_TYPE_SEARCH_AND_REPLACE, valaDevelopSearchAndReplace);
	switch (property_id) {
		case VALA_DEVELOP_SEARCH_AND_REPLACE_SEARCH_TYPE_PROPERTY:
		g_value_set_enum (value, vala_develop_search_and_replace_get_SearchType (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_vala_develop_search_and_replace_set_property (GObject * object,
                                                    guint property_id,
                                                    const GValue * value,
                                                    GParamSpec * pspec)
{
	valaDevelopSearchAndReplace * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, VALA_DEVELOP_TYPE_SEARCH_AND_REPLACE, valaDevelopSearchAndReplace);
	switch (property_id) {
		case VALA_DEVELOP_SEARCH_AND_REPLACE_SEARCH_TYPE_PROPERTY:
		vala_develop_search_and_replace_set_SearchType (self, g_value_get_enum (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

