/* source_create_file_dialog.c generated by valac UNKNOWN, the Vala compiler
 * generated from source_create_file_dialog.vala, do not modify */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <glib/gi18n-lib.h>
#include <gio/gio.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gee.h>

#define VALA_DEVELOP_TYPE_SOURCE_CREATE_FILE (vala_develop_source_create_file_get_type ())
#define VALA_DEVELOP_SOURCE_CREATE_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_SOURCE_CREATE_FILE, valaDevelopSourceCreateFile))
#define VALA_DEVELOP_SOURCE_CREATE_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_SOURCE_CREATE_FILE, valaDevelopSourceCreateFileClass))
#define VALA_DEVELOP_IS_SOURCE_CREATE_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_SOURCE_CREATE_FILE))
#define VALA_DEVELOP_IS_SOURCE_CREATE_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_SOURCE_CREATE_FILE))
#define VALA_DEVELOP_SOURCE_CREATE_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_SOURCE_CREATE_FILE, valaDevelopSourceCreateFileClass))

typedef struct _valaDevelopSourceCreateFile valaDevelopSourceCreateFile;
typedef struct _valaDevelopSourceCreateFileClass valaDevelopSourceCreateFileClass;
typedef struct _valaDevelopSourceCreateFilePrivate valaDevelopSourceCreateFilePrivate;
enum  {
	VALA_DEVELOP_SOURCE_CREATE_FILE_0_PROPERTY,
	VALA_DEVELOP_SOURCE_CREATE_FILE_NUM_PROPERTIES
};
static GParamSpec* vala_develop_source_create_file_properties[VALA_DEVELOP_SOURCE_CREATE_FILE_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE (vala_develop_overview_tree_store_get_type ())
#define VALA_DEVELOP_OVERVIEW_TREE_STORE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE, valaDevelopOverviewTreeStore))
#define VALA_DEVELOP_OVERVIEW_TREE_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE, valaDevelopOverviewTreeStoreClass))
#define VALA_DEVELOP_IS_OVERVIEW_TREE_STORE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE))
#define VALA_DEVELOP_IS_OVERVIEW_TREE_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE))
#define VALA_DEVELOP_OVERVIEW_TREE_STORE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_OVERVIEW_TREE_STORE, valaDevelopOverviewTreeStoreClass))

typedef struct _valaDevelopOverviewTreeStore valaDevelopOverviewTreeStore;
typedef struct _valaDevelopOverviewTreeStoreClass valaDevelopOverviewTreeStoreClass;
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef enum  {
	VALA_DEVELOP_ITEM_TYPE_None = 0,
	VALA_DEVELOP_ITEM_TYPE_Solution = 1,
	VALA_DEVELOP_ITEM_TYPE_Project = 2,
	VALA_DEVELOP_ITEM_TYPE_Resource = 4,
	VALA_DEVELOP_ITEM_TYPE_Source = 8,
	VALA_DEVELOP_ITEM_TYPE_Package = 16,
	VALA_DEVELOP_ITEM_TYPE_Directory = 32,
	VALA_DEVELOP_ITEM_TYPE_Vapi = 64
} valaDevelopItemType;

#define VALA_DEVELOP_TYPE_ITEM_TYPE (vala_develop_item_type_get_type ())
typedef enum  {
	VALA_DEVELOP_ITEM_BUILD_TYPE_None,
	VALA_DEVELOP_ITEM_BUILD_TYPE_Compile,
	VALA_DEVELOP_ITEM_BUILD_TYPE_Resource,
	VALA_DEVELOP_ITEM_BUILD_TYPE_Package,
	VALA_DEVELOP_ITEM_BUILD_TYPE_Executable,
	VALA_DEVELOP_ITEM_BUILD_TYPE_SharedObject
} valaDevelopItemBuildType;

#define VALA_DEVELOP_TYPE_ITEM_BUILD_TYPE (vala_develop_item_build_type_get_type ())

#define VALA_DEVELOP_TYPE_SYMBOL_FINDER (vala_develop_symbol_finder_get_type ())
#define VALA_DEVELOP_SYMBOL_FINDER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_SYMBOL_FINDER, valaDevelopSymbolFinder))
#define VALA_DEVELOP_SYMBOL_FINDER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_SYMBOL_FINDER, valaDevelopSymbolFinderClass))
#define VALA_DEVELOP_IS_SYMBOL_FINDER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_SYMBOL_FINDER))
#define VALA_DEVELOP_IS_SYMBOL_FINDER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_SYMBOL_FINDER))
#define VALA_DEVELOP_SYMBOL_FINDER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_SYMBOL_FINDER, valaDevelopSymbolFinderClass))

typedef struct _valaDevelopSymbolFinder valaDevelopSymbolFinder;
typedef struct _valaDevelopSymbolFinderClass valaDevelopSymbolFinderClass;

struct _valaDevelopSourceCreateFile {
	GtkDialog parent_instance;
	valaDevelopSourceCreateFilePrivate * priv;
};

struct _valaDevelopSourceCreateFileClass {
	GtkDialogClass parent_class;
};

struct _valaDevelopSourceCreateFilePrivate {
	GtkTreeView* sourceGroup;
	GtkTextView* sourceDescription;
	GtkEntry* sourceName;
	GtkButton* accept;
	GtkTreeIter _overviewTreeIter;
	GtkWidget* _parent;
};

static gint valaDevelopSourceCreateFile_private_offset;
static gpointer vala_develop_source_create_file_parent_class = NULL;
extern valaDevelopOverviewTreeStore* vala_develop_main_paned_overviewTreeModel;
extern GeeHashMap* vala_develop_main_paned__symbol_finder;

GType vala_develop_source_create_file_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (valaDevelopSourceCreateFile, g_object_unref)
#define VALA_DEVELOP_SOURCE_CREATE_FILE_empty_class "Class"
#define VALA_DEVELOP_SOURCE_CREATE_FILE_empty_enum "Enum"
#define VALA_DEVELOP_SOURCE_CREATE_FILE_empty_interface "Interface"
#define VALA_DEVELOP_SOURCE_CREATE_FILE_empty_struct "Struct"
#define VALA_DEVELOP_SOURCE_CREATE_FILE_empty_dialog "Dialog"
#define VALA_DEVELOP_SOURCE_CREATE_FILE_empty_widget "Widget"
#define VALA_DEVELOP_SOURCE_CREATE_FILE_empty_window "Window"
#define VALA_DEVELOP_SOURCE_CREATE_FILE_empty_plugin "PlugIn"
#define VALA_DEVELOP_SOURCE_CREATE_FILE_empty_dialog_resource "Dialog with Resource"
#define VALA_DEVELOP_SOURCE_CREATE_FILE_empty_widget_resource "Widget with Resource"
#define VALA_DEVELOP_SOURCE_CREATE_FILE_empty_window_resource "Window with Resource"
valaDevelopSourceCreateFile* vala_develop_source_create_file_new (GtkWidget* parent,
                                                                  GtkTreeIter* iter);
valaDevelopSourceCreateFile* vala_develop_source_create_file_construct (GType object_type,
                                                                        GtkWidget* parent,
                                                                        GtkTreeIter* iter);
static gboolean vala_develop_source_create_file_OnGroupSelected (valaDevelopSourceCreateFile* self,
                                                          GtkTreeSelection* selection,
                                                          GtkTreeModel* model,
                                                          GtkTreePath* path,
                                                          gboolean path_currently_selected);
static gboolean _vala_develop_source_create_file_OnGroupSelected_gtk_tree_selection_func (GtkTreeSelection* selection,
                                                                                   GtkTreeModel* model,
                                                                                   GtkTreePath* path,
                                                                                   gboolean path_currently_selected,
                                                                                   gpointer self);
static void __lambda80_ (valaDevelopSourceCreateFile* self);
static void ___lambda80__gtk_editable_changed (GtkEditable* _sender,
                                        gpointer self);
static void vala_develop_source_create_file_OnAccept (valaDevelopSourceCreateFile* self);
static void vala_develop_source_create_file_CreateSource (valaDevelopSourceCreateFile* self,
                                                   gint c);
static void vala_develop_source_create_file_CreateResource (valaDevelopSourceCreateFile* self,
                                                     gint r);
static void _vala_develop_source_create_file_OnAccept_gtk_button_clicked (GtkButton* _sender,
                                                                   gpointer self);
static void vala_develop_source_create_file_OnCancel (valaDevelopSourceCreateFile* self);
static void _vala_develop_source_create_file_OnCancel_gtk_button_clicked (GtkButton* _sender,
                                                                   gpointer self);
GType vala_develop_overview_tree_store_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (valaDevelopOverviewTreeStore, g_object_unref)
gchar* vala_develop_overview_tree_store_get_item_path (valaDevelopOverviewTreeStore* self,
                                                       GtkTreeIter* iter);
gchar* vala_develop_overview_tree_store_get_item_namespace (valaDevelopOverviewTreeStore* self,
                                                            GtkTreeIter* iter);
GtkTreeIter* vala_develop_overview_tree_store_get_project_iter_by_iter (valaDevelopOverviewTreeStore* self,
                                                                        GtkTreeIter* iter);
GtkTreeIter* vala_develop_overview_tree_store_get_resource_iter (valaDevelopOverviewTreeStore* self,
                                                                 GtkTreeIter* startIter);
void vala_develop_overview_tree_store_set_item_type (valaDevelopOverviewTreeStore* self,
                                                     GtkTreeIter* iter,
                                                     gint itemType);
GType vala_develop_item_type_get_type (void) G_GNUC_CONST;
void vala_develop_overview_tree_store_set_item_name (valaDevelopOverviewTreeStore* self,
                                                     GtkTreeIter* iter,
                                                     const gchar* name);
void vala_develop_overview_tree_store_set_item_resource_id (valaDevelopOverviewTreeStore* self,
                                                            GtkTreeIter* iter,
                                                            const gchar* resourceId);
void vala_develop_overview_tree_store_set_item_resource_compress (valaDevelopOverviewTreeStore* self,
                                                                  GtkTreeIter* iter,
                                                                  gboolean resourceCompress);
void vala_develop_overview_tree_store_set_item_resource_stripblanks (valaDevelopOverviewTreeStore* self,
                                                                     GtkTreeIter* iter,
                                                                     gboolean resourceStripBlanks);
void vala_develop_overview_tree_store_set_item_buildtype (valaDevelopOverviewTreeStore* self,
                                                          GtkTreeIter* iter,
                                                          gint itemBuildType);
GType vala_develop_item_build_type_get_type (void) G_GNUC_CONST;
void vala_develop_overview_tree_store_set_item_mimetype (valaDevelopOverviewTreeStore* self,
                                                         GtkTreeIter* iter,
                                                         const gchar* mimeType);
void vala_develop_overview_tree_store_set_item_pixbuf (valaDevelopOverviewTreeStore* self,
                                                       GtkTreeIter* iter,
                                                       GdkPixbuf* itemPixbuf);
gchar* vala_develop_overview_tree_store_get_item_name (valaDevelopOverviewTreeStore* self,
                                                       GtkTreeIter* iter);
GType vala_develop_symbol_finder_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (valaDevelopSymbolFinder, g_object_unref)
void vala_develop_symbol_finder_AddSourceFile (valaDevelopSymbolFinder* self,
                                               const gchar* source);
static void vala_develop_source_create_file_finalize (GObject * obj);

static inline gpointer
vala_develop_source_create_file_get_instance_private (valaDevelopSourceCreateFile* self)
{
	return G_STRUCT_MEMBER_P (self, valaDevelopSourceCreateFile_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static gboolean
_vala_develop_source_create_file_OnGroupSelected_gtk_tree_selection_func (GtkTreeSelection* selection,
                                                                          GtkTreeModel* model,
                                                                          GtkTreePath* path,
                                                                          gboolean path_currently_selected,
                                                                          gpointer self)
{
	gboolean result;
	result = vala_develop_source_create_file_OnGroupSelected ((valaDevelopSourceCreateFile*) self, selection, model, path, path_currently_selected);
	return result;
}

static void
__lambda80_ (valaDevelopSourceCreateFile* self)
{
	GtkButton* _tmp0_;
	GtkEntry* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	_tmp0_ = self->priv->accept;
	_tmp1_ = self->priv->sourceName;
	_tmp2_ = gtk_entry_get_text (_tmp1_);
	_tmp3_ = _tmp2_;
	gtk_widget_set_sensitive ((GtkWidget*) _tmp0_, g_strcmp0 (_tmp3_, "") != 0);
}

static void
___lambda80__gtk_editable_changed (GtkEditable* _sender,
                                   gpointer self)
{
	__lambda80_ ((valaDevelopSourceCreateFile*) self);
}

valaDevelopSourceCreateFile*
vala_develop_source_create_file_construct (GType object_type,
                                           GtkWidget* parent,
                                           GtkTreeIter* iter)
{
	valaDevelopSourceCreateFile * self = NULL;
	GtkWidget* _tmp0_;
	GtkWidget* _tmp1_;
	GtkWidget* _tmp2_;
	GtkTreeIter _tmp3_;
	GtkTreeStore* groupTreeStore = NULL;
	GType* _tmp4_;
	GType* _tmp5_;
	gint _tmp5__length1;
	GtkTreeStore* _tmp6_;
	GtkTreeStore* _tmp7_;
	GtkTreeViewColumn* c = NULL;
	GtkCellRendererText* _tmp8_;
	GtkCellRendererText* _tmp9_;
	GtkTreeViewColumn* _tmp10_;
	GtkTreeViewColumn* _tmp11_;
	GtkTreeView* _tmp12_;
	GtkTreeIter treeIter = {0};
	GtkTreeIter _tmp13_ = {0};
	GtkTreeIter _tmp14_;
	GValue _tmp15_ = {0};
	GtkTreeIter generalIter = {0};
	GtkTreeIter _tmp16_;
	GtkTreeIter _tmp17_ = {0};
	GtkTreeIter _tmp18_;
	GValue _tmp19_ = {0};
	GtkTreeIter _tmp20_;
	GtkTreeIter _tmp21_ = {0};
	GtkTreeIter _tmp22_;
	GValue _tmp23_ = {0};
	GtkTreeIter _tmp24_;
	GtkTreeIter _tmp25_ = {0};
	GtkTreeIter _tmp26_;
	GValue _tmp27_ = {0};
	GtkTreeIter _tmp28_;
	GtkTreeIter _tmp29_ = {0};
	GtkTreeIter _tmp30_;
	GValue _tmp31_ = {0};
	GtkTreeIter _tmp32_ = {0};
	GtkTreeIter _tmp33_;
	GValue _tmp34_ = {0};
	GtkTreeIter gtkIter = {0};
	GtkTreeIter _tmp35_;
	GtkTreeIter _tmp36_ = {0};
	GtkTreeIter _tmp37_;
	GValue _tmp38_ = {0};
	GtkTreeIter _tmp39_;
	GtkTreeIter _tmp40_ = {0};
	GtkTreeIter _tmp41_;
	GValue _tmp42_ = {0};
	GtkTreeIter _tmp43_;
	GtkTreeIter _tmp44_ = {0};
	GtkTreeIter _tmp45_;
	GValue _tmp46_ = {0};
	GtkTreeIter _tmp47_;
	GtkTreeIter _tmp48_ = {0};
	GtkTreeIter _tmp49_;
	GValue _tmp50_ = {0};
	GtkTreeIter _tmp51_ = {0};
	GtkTreeIter _tmp52_;
	GValue _tmp53_ = {0};
	GtkTreeIter gladeIter = {0};
	GtkTreeIter _tmp54_;
	GtkTreeIter _tmp55_ = {0};
	GtkTreeIter _tmp56_;
	GValue _tmp57_ = {0};
	GtkTreeIter _tmp58_;
	GtkTreeIter _tmp59_ = {0};
	GtkTreeIter _tmp60_;
	GValue _tmp61_ = {0};
	GtkTreeIter _tmp62_;
	GtkTreeIter _tmp63_ = {0};
	GtkTreeIter _tmp64_;
	GValue _tmp65_ = {0};
	GtkTreeView* _tmp66_;
	GtkTreeView* _tmp67_;
	GtkTreeView* _tmp68_;
	GtkTreeView* _tmp69_;
	GtkTreeSelection* _tmp70_;
	GtkEntry* _tmp71_;
	g_return_val_if_fail (parent != NULL, NULL);
	g_return_val_if_fail (iter != NULL, NULL);
	self = (valaDevelopSourceCreateFile*) g_object_new (object_type, NULL);
	_tmp0_ = _g_object_ref0 (parent);
	_g_object_unref0 (self->priv->_parent);
	self->priv->_parent = _tmp0_;
	_tmp1_ = self->priv->_parent;
	_tmp2_ = gtk_widget_get_toplevel (_tmp1_);
	gtk_window_set_transient_for ((GtkWindow*) self, G_TYPE_CHECK_INSTANCE_CAST (_tmp2_, gtk_window_get_type (), GtkWindow));
	_tmp3_ = *iter;
	self->priv->_overviewTreeIter = _tmp3_;
	_tmp4_ = g_new0 (GType, 1);
	_tmp4_[0] = G_TYPE_STRING;
	_tmp5_ = _tmp4_;
	_tmp5__length1 = 1;
	_tmp6_ = gtk_tree_store_newv (1, _tmp5_);
	_tmp7_ = _tmp6_;
	_tmp5_ = (g_free (_tmp5_), NULL);
	groupTreeStore = _tmp7_;
	_tmp8_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
	g_object_ref_sink (_tmp8_);
	_tmp9_ = _tmp8_;
	_tmp10_ = gtk_tree_view_column_new_with_attributes (_ ("Template"), (GtkCellRenderer*) _tmp9_, "text", 0, NULL);
	g_object_ref_sink (_tmp10_);
	_tmp11_ = _tmp10_;
	_g_object_unref0 (_tmp9_);
	c = _tmp11_;
	gtk_tree_view_column_set_sizing (c, GTK_TREE_VIEW_COLUMN_FIXED);
	gtk_tree_view_column_set_resizable (c, FALSE);
	gtk_tree_view_column_set_fixed_width (c, 200);
	_tmp12_ = self->priv->sourceGroup;
	gtk_tree_view_append_column (_tmp12_, c);
	gtk_tree_store_append (groupTreeStore, &_tmp13_, NULL);
	treeIter = _tmp13_;
	_tmp14_ = treeIter;
	g_value_init (&_tmp15_, G_TYPE_STRING);
	g_value_set_string (&_tmp15_, _ ("General"));
	gtk_tree_store_set_value (groupTreeStore, &_tmp14_, 0, &_tmp15_);
	G_IS_VALUE (&_tmp15_) ? (g_value_unset (&_tmp15_), NULL) : NULL;
	_tmp16_ = treeIter;
	gtk_tree_store_append (groupTreeStore, &_tmp17_, &_tmp16_);
	generalIter = _tmp17_;
	_tmp18_ = generalIter;
	g_value_init (&_tmp19_, G_TYPE_STRING);
	g_value_set_string (&_tmp19_, _ (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_class));
	gtk_tree_store_set_value (groupTreeStore, &_tmp18_, 0, &_tmp19_);
	G_IS_VALUE (&_tmp19_) ? (g_value_unset (&_tmp19_), NULL) : NULL;
	_tmp20_ = treeIter;
	gtk_tree_store_append (groupTreeStore, &_tmp21_, &_tmp20_);
	generalIter = _tmp21_;
	_tmp22_ = generalIter;
	g_value_init (&_tmp23_, G_TYPE_STRING);
	g_value_set_string (&_tmp23_, _ (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_enum));
	gtk_tree_store_set_value (groupTreeStore, &_tmp22_, 0, &_tmp23_);
	G_IS_VALUE (&_tmp23_) ? (g_value_unset (&_tmp23_), NULL) : NULL;
	_tmp24_ = treeIter;
	gtk_tree_store_append (groupTreeStore, &_tmp25_, &_tmp24_);
	generalIter = _tmp25_;
	_tmp26_ = generalIter;
	g_value_init (&_tmp27_, G_TYPE_STRING);
	g_value_set_string (&_tmp27_, _ (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_interface));
	gtk_tree_store_set_value (groupTreeStore, &_tmp26_, 0, &_tmp27_);
	G_IS_VALUE (&_tmp27_) ? (g_value_unset (&_tmp27_), NULL) : NULL;
	_tmp28_ = treeIter;
	gtk_tree_store_append (groupTreeStore, &_tmp29_, &_tmp28_);
	generalIter = _tmp29_;
	_tmp30_ = generalIter;
	g_value_init (&_tmp31_, G_TYPE_STRING);
	g_value_set_string (&_tmp31_, _ (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_struct));
	gtk_tree_store_set_value (groupTreeStore, &_tmp30_, 0, &_tmp31_);
	G_IS_VALUE (&_tmp31_) ? (g_value_unset (&_tmp31_), NULL) : NULL;
	gtk_tree_store_append (groupTreeStore, &_tmp32_, NULL);
	treeIter = _tmp32_;
	_tmp33_ = treeIter;
	g_value_init (&_tmp34_, G_TYPE_STRING);
	g_value_set_string (&_tmp34_, "Gtk");
	gtk_tree_store_set_value (groupTreeStore, &_tmp33_, 0, &_tmp34_);
	G_IS_VALUE (&_tmp34_) ? (g_value_unset (&_tmp34_), NULL) : NULL;
	_tmp35_ = treeIter;
	gtk_tree_store_append (groupTreeStore, &_tmp36_, &_tmp35_);
	gtkIter = _tmp36_;
	_tmp37_ = gtkIter;
	g_value_init (&_tmp38_, G_TYPE_STRING);
	g_value_set_string (&_tmp38_, _ (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_dialog));
	gtk_tree_store_set_value (groupTreeStore, &_tmp37_, 0, &_tmp38_);
	G_IS_VALUE (&_tmp38_) ? (g_value_unset (&_tmp38_), NULL) : NULL;
	_tmp39_ = treeIter;
	gtk_tree_store_append (groupTreeStore, &_tmp40_, &_tmp39_);
	gtkIter = _tmp40_;
	_tmp41_ = gtkIter;
	g_value_init (&_tmp42_, G_TYPE_STRING);
	g_value_set_string (&_tmp42_, _ (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_widget));
	gtk_tree_store_set_value (groupTreeStore, &_tmp41_, 0, &_tmp42_);
	G_IS_VALUE (&_tmp42_) ? (g_value_unset (&_tmp42_), NULL) : NULL;
	_tmp43_ = treeIter;
	gtk_tree_store_append (groupTreeStore, &_tmp44_, &_tmp43_);
	gtkIter = _tmp44_;
	_tmp45_ = gtkIter;
	g_value_init (&_tmp46_, G_TYPE_STRING);
	g_value_set_string (&_tmp46_, _ (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_window));
	gtk_tree_store_set_value (groupTreeStore, &_tmp45_, 0, &_tmp46_);
	G_IS_VALUE (&_tmp46_) ? (g_value_unset (&_tmp46_), NULL) : NULL;
	_tmp47_ = treeIter;
	gtk_tree_store_append (groupTreeStore, &_tmp48_, &_tmp47_);
	gtkIter = _tmp48_;
	_tmp49_ = gtkIter;
	g_value_init (&_tmp50_, G_TYPE_STRING);
	g_value_set_string (&_tmp50_, _ (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_plugin));
	gtk_tree_store_set_value (groupTreeStore, &_tmp49_, 0, &_tmp50_);
	G_IS_VALUE (&_tmp50_) ? (g_value_unset (&_tmp50_), NULL) : NULL;
	gtk_tree_store_append (groupTreeStore, &_tmp51_, NULL);
	treeIter = _tmp51_;
	_tmp52_ = treeIter;
	g_value_init (&_tmp53_, G_TYPE_STRING);
	g_value_set_string (&_tmp53_, "Glade");
	gtk_tree_store_set_value (groupTreeStore, &_tmp52_, 0, &_tmp53_);
	G_IS_VALUE (&_tmp53_) ? (g_value_unset (&_tmp53_), NULL) : NULL;
	_tmp54_ = treeIter;
	gtk_tree_store_append (groupTreeStore, &_tmp55_, &_tmp54_);
	gladeIter = _tmp55_;
	_tmp56_ = gladeIter;
	g_value_init (&_tmp57_, G_TYPE_STRING);
	g_value_set_string (&_tmp57_, _ (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_dialog_resource));
	gtk_tree_store_set_value (groupTreeStore, &_tmp56_, 0, &_tmp57_);
	G_IS_VALUE (&_tmp57_) ? (g_value_unset (&_tmp57_), NULL) : NULL;
	_tmp58_ = treeIter;
	gtk_tree_store_append (groupTreeStore, &_tmp59_, &_tmp58_);
	gladeIter = _tmp59_;
	_tmp60_ = gladeIter;
	g_value_init (&_tmp61_, G_TYPE_STRING);
	g_value_set_string (&_tmp61_, _ (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_widget_resource));
	gtk_tree_store_set_value (groupTreeStore, &_tmp60_, 0, &_tmp61_);
	G_IS_VALUE (&_tmp61_) ? (g_value_unset (&_tmp61_), NULL) : NULL;
	_tmp62_ = treeIter;
	gtk_tree_store_append (groupTreeStore, &_tmp63_, &_tmp62_);
	gladeIter = _tmp63_;
	_tmp64_ = gladeIter;
	g_value_init (&_tmp65_, G_TYPE_STRING);
	g_value_set_string (&_tmp65_, _ (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_window_resource));
	gtk_tree_store_set_value (groupTreeStore, &_tmp64_, 0, &_tmp65_);
	G_IS_VALUE (&_tmp65_) ? (g_value_unset (&_tmp65_), NULL) : NULL;
	_tmp66_ = self->priv->sourceGroup;
	gtk_tree_view_set_model (_tmp66_, (GtkTreeModel*) groupTreeStore);
	_tmp67_ = self->priv->sourceGroup;
	gtk_tree_view_columns_autosize (_tmp67_);
	_tmp68_ = self->priv->sourceGroup;
	gtk_tree_view_expand_all (_tmp68_);
	_tmp69_ = self->priv->sourceGroup;
	_tmp70_ = gtk_tree_view_get_selection (_tmp69_);
	gtk_tree_selection_set_select_function (_tmp70_, _vala_develop_source_create_file_OnGroupSelected_gtk_tree_selection_func, g_object_ref (self), g_object_unref);
	_tmp71_ = self->priv->sourceName;
	g_signal_connect_object ((GtkEditable*) _tmp71_, "changed", (GCallback) ___lambda80__gtk_editable_changed, self, 0);
	gtk_widget_show_all ((GtkWidget*) self);
	_g_object_unref0 (c);
	_g_object_unref0 (groupTreeStore);
	return self;
}

valaDevelopSourceCreateFile*
vala_develop_source_create_file_new (GtkWidget* parent,
                                     GtkTreeIter* iter)
{
	return vala_develop_source_create_file_construct (VALA_DEVELOP_TYPE_SOURCE_CREATE_FILE, parent, iter);
}

static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}

static gboolean
vala_develop_source_create_file_OnGroupSelected (valaDevelopSourceCreateFile* self,
                                                 GtkTreeSelection* selection,
                                                 GtkTreeModel* model,
                                                 GtkTreePath* path,
                                                 gboolean path_currently_selected)
{
	gboolean result = FALSE;
	GtkTreeIter iter = {0};
	GtkTreeIter _tmp0_ = {0};
	gboolean _tmp1_;
	GValue val = {0};
	GtkTreeIter _tmp2_;
	GValue _tmp3_ = {0};
	gchar* entry = NULL;
	GValue _tmp4_;
	gchar* _tmp5_;
	GtkTextView* _tmp6_;
	GtkTextBuffer* _tmp7_;
	GtkTextBuffer* _tmp8_;
	GtkEntry* _tmp9_;
	GtkTextIter startIter = {0};
	GtkTextView* _tmp10_;
	GtkTextBuffer* _tmp11_;
	GtkTextBuffer* _tmp12_;
	GtkTextIter _tmp13_ = {0};
	const gchar* _tmp14_;
	const gchar* _tmp15_;
	GQuark _tmp17_ = 0U;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (selection != NULL, FALSE);
	g_return_val_if_fail (model != NULL, FALSE);
	g_return_val_if_fail (path != NULL, FALSE);
	_tmp1_ = gtk_tree_model_get_iter (model, &_tmp0_, path);
	iter = _tmp0_;
	if (!_tmp1_) {
		result = FALSE;
		return result;
	}
	_tmp2_ = iter;
	gtk_tree_model_get_value (model, &_tmp2_, 0, &_tmp3_);
	G_IS_VALUE (&val) ? (g_value_unset (&val), NULL) : NULL;
	val = _tmp3_;
	_tmp4_ = val;
	_tmp5_ = g_strdup (g_value_get_string (&_tmp4_));
	entry = _tmp5_;
	_tmp6_ = self->priv->sourceDescription;
	_tmp7_ = gtk_text_view_get_buffer (_tmp6_);
	_tmp8_ = _tmp7_;
	g_object_set (_tmp8_, "text", "", NULL);
	_tmp9_ = self->priv->sourceName;
	gtk_entry_set_text (_tmp9_, "");
	_tmp10_ = self->priv->sourceDescription;
	_tmp11_ = gtk_text_view_get_buffer (_tmp10_);
	_tmp12_ = _tmp11_;
	gtk_text_buffer_get_start_iter (_tmp12_, &_tmp13_);
	startIter = _tmp13_;
	_tmp14_ = entry;
	_tmp15_ = _tmp14_;
	_tmp17_ = (NULL == _tmp15_) ? 0 : g_quark_from_string (_tmp15_);
	if (_tmp17_ == g_quark_from_string (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_class)) {
		switch (0) {
			default:
			{
				GtkEntry* _tmp18_;
				GtkTextView* _tmp19_;
				GtkTextBuffer* _tmp20_;
				GtkTextBuffer* _tmp21_;
				const gchar* _tmp22_;
				const gchar* _tmp23_;
				gchar* _tmp24_;
				gchar* _tmp25_;
				_tmp18_ = self->priv->sourceName;
				gtk_entry_set_text (_tmp18_, "Class");
				_tmp19_ = self->priv->sourceDescription;
				_tmp20_ = gtk_text_view_get_buffer (_tmp19_);
				_tmp21_ = _tmp20_;
				_tmp22_ = string_to_string (_ (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_class));
				_tmp23_ = string_to_string (_ ("Creates an empty class"));
				_tmp24_ = g_strconcat ("<b>", _tmp22_, "</b>\n", _tmp23_, ".", NULL);
				_tmp25_ = _tmp24_;
				gtk_text_buffer_insert_markup (_tmp21_, &startIter, _tmp25_, -1);
				_g_free0 (_tmp25_);
				break;
			}
		}
	} else if (_tmp17_ == g_quark_from_string (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_enum)) {
		switch (0) {
			default:
			{
				GtkEntry* _tmp26_;
				GtkTextView* _tmp27_;
				GtkTextBuffer* _tmp28_;
				GtkTextBuffer* _tmp29_;
				const gchar* _tmp30_;
				const gchar* _tmp31_;
				gchar* _tmp32_;
				gchar* _tmp33_;
				_tmp26_ = self->priv->sourceName;
				gtk_entry_set_text (_tmp26_, "Enumeration");
				_tmp27_ = self->priv->sourceDescription;
				_tmp28_ = gtk_text_view_get_buffer (_tmp27_);
				_tmp29_ = _tmp28_;
				_tmp30_ = string_to_string (_ (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_enum));
				_tmp31_ = string_to_string (_ ("Creates an empty enum"));
				_tmp32_ = g_strconcat ("<b>", _tmp30_, "</b>\n", _tmp31_, ".", NULL);
				_tmp33_ = _tmp32_;
				gtk_text_buffer_insert_markup (_tmp29_, &startIter, _tmp33_, -1);
				_g_free0 (_tmp33_);
				break;
			}
		}
	} else if (_tmp17_ == g_quark_from_string (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_interface)) {
		switch (0) {
			default:
			{
				GtkEntry* _tmp34_;
				GtkTextView* _tmp35_;
				GtkTextBuffer* _tmp36_;
				GtkTextBuffer* _tmp37_;
				const gchar* _tmp38_;
				const gchar* _tmp39_;
				gchar* _tmp40_;
				gchar* _tmp41_;
				_tmp34_ = self->priv->sourceName;
				gtk_entry_set_text (_tmp34_, "Interface");
				_tmp35_ = self->priv->sourceDescription;
				_tmp36_ = gtk_text_view_get_buffer (_tmp35_);
				_tmp37_ = _tmp36_;
				_tmp38_ = string_to_string (_ (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_interface));
				_tmp39_ = string_to_string (_ ("Creates an empty interface"));
				_tmp40_ = g_strconcat ("<b>", _tmp38_, "</b>\n", _tmp39_, ".", NULL);
				_tmp41_ = _tmp40_;
				gtk_text_buffer_insert_markup (_tmp37_, &startIter, _tmp41_, -1);
				_g_free0 (_tmp41_);
				break;
			}
		}
	} else if (_tmp17_ == g_quark_from_string (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_struct)) {
		switch (0) {
			default:
			{
				GtkEntry* _tmp42_;
				GtkTextView* _tmp43_;
				GtkTextBuffer* _tmp44_;
				GtkTextBuffer* _tmp45_;
				const gchar* _tmp46_;
				const gchar* _tmp47_;
				gchar* _tmp48_;
				gchar* _tmp49_;
				_tmp42_ = self->priv->sourceName;
				gtk_entry_set_text (_tmp42_, "Struct");
				_tmp43_ = self->priv->sourceDescription;
				_tmp44_ = gtk_text_view_get_buffer (_tmp43_);
				_tmp45_ = _tmp44_;
				_tmp46_ = string_to_string (_ (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_struct));
				_tmp47_ = string_to_string (_ ("Creates an empty struct"));
				_tmp48_ = g_strconcat ("<b>", _tmp46_, "</b>\n", _tmp47_, ".", NULL);
				_tmp49_ = _tmp48_;
				gtk_text_buffer_insert_markup (_tmp45_, &startIter, _tmp49_, -1);
				_g_free0 (_tmp49_);
				break;
			}
		}
	} else if (_tmp17_ == g_quark_from_string (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_dialog)) {
		switch (0) {
			default:
			{
				GtkEntry* _tmp50_;
				GtkTextView* _tmp51_;
				GtkTextBuffer* _tmp52_;
				GtkTextBuffer* _tmp53_;
				const gchar* _tmp54_;
				const gchar* _tmp55_;
				gchar* _tmp56_;
				gchar* _tmp57_;
				_tmp50_ = self->priv->sourceName;
				gtk_entry_set_text (_tmp50_, "Dialog");
				_tmp51_ = self->priv->sourceDescription;
				_tmp52_ = gtk_text_view_get_buffer (_tmp51_);
				_tmp53_ = _tmp52_;
				_tmp54_ = string_to_string (_ (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_dialog));
				_tmp55_ = string_to_string (_ ("Creates an Gtk.Dialog"));
				_tmp56_ = g_strconcat ("<b>", _tmp54_, "</b>\n", _tmp55_, ".", NULL);
				_tmp57_ = _tmp56_;
				gtk_text_buffer_insert_markup (_tmp53_, &startIter, _tmp57_, -1);
				_g_free0 (_tmp57_);
				break;
			}
		}
	} else if (_tmp17_ == g_quark_from_string (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_widget)) {
		switch (0) {
			default:
			{
				GtkEntry* _tmp58_;
				GtkTextView* _tmp59_;
				GtkTextBuffer* _tmp60_;
				GtkTextBuffer* _tmp61_;
				const gchar* _tmp62_;
				const gchar* _tmp63_;
				gchar* _tmp64_;
				gchar* _tmp65_;
				_tmp58_ = self->priv->sourceName;
				gtk_entry_set_text (_tmp58_, "Widget");
				_tmp59_ = self->priv->sourceDescription;
				_tmp60_ = gtk_text_view_get_buffer (_tmp59_);
				_tmp61_ = _tmp60_;
				_tmp62_ = string_to_string (_ (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_widget));
				_tmp63_ = string_to_string (_ ("Creates an Gtk.Widget"));
				_tmp64_ = g_strconcat ("<b>", _tmp62_, "</b>\n", _tmp63_, ".", NULL);
				_tmp65_ = _tmp64_;
				gtk_text_buffer_insert_markup (_tmp61_, &startIter, _tmp65_, -1);
				_g_free0 (_tmp65_);
				break;
			}
		}
	} else if (_tmp17_ == g_quark_from_string (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_window)) {
		switch (0) {
			default:
			{
				GtkEntry* _tmp66_;
				GtkTextView* _tmp67_;
				GtkTextBuffer* _tmp68_;
				GtkTextBuffer* _tmp69_;
				const gchar* _tmp70_;
				const gchar* _tmp71_;
				gchar* _tmp72_;
				gchar* _tmp73_;
				_tmp66_ = self->priv->sourceName;
				gtk_entry_set_text (_tmp66_, "Window");
				_tmp67_ = self->priv->sourceDescription;
				_tmp68_ = gtk_text_view_get_buffer (_tmp67_);
				_tmp69_ = _tmp68_;
				_tmp70_ = string_to_string (_ (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_window));
				_tmp71_ = string_to_string (_ ("Creates an Gtk.Window"));
				_tmp72_ = g_strconcat ("<b>", _tmp70_, "</b>\n", _tmp71_, ".", NULL);
				_tmp73_ = _tmp72_;
				gtk_text_buffer_insert_markup (_tmp69_, &startIter, _tmp73_, -1);
				_g_free0 (_tmp73_);
				break;
			}
		}
	} else if (_tmp17_ == g_quark_from_string (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_plugin)) {
		switch (0) {
			default:
			{
				GtkEntry* _tmp74_;
				GtkTextView* _tmp75_;
				GtkTextBuffer* _tmp76_;
				GtkTextBuffer* _tmp77_;
				const gchar* _tmp78_;
				const gchar* _tmp79_;
				gchar* _tmp80_;
				gchar* _tmp81_;
				_tmp74_ = self->priv->sourceName;
				gtk_entry_set_text (_tmp74_, "PlugIn");
				_tmp75_ = self->priv->sourceDescription;
				_tmp76_ = gtk_text_view_get_buffer (_tmp75_);
				_tmp77_ = _tmp76_;
				_tmp78_ = string_to_string (_ (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_plugin));
				_tmp79_ = string_to_string (_ ("Creates an plugin-interface and class"));
				_tmp80_ = g_strconcat ("<b>", _tmp78_, "</b>\n", _tmp79_, ".", NULL);
				_tmp81_ = _tmp80_;
				gtk_text_buffer_insert_markup (_tmp77_, &startIter, _tmp81_, -1);
				_g_free0 (_tmp81_);
				break;
			}
		}
	} else if (_tmp17_ == g_quark_from_string (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_dialog_resource)) {
		switch (0) {
			default:
			{
				GtkEntry* _tmp82_;
				GtkTextView* _tmp83_;
				GtkTextBuffer* _tmp84_;
				GtkTextBuffer* _tmp85_;
				const gchar* _tmp86_;
				const gchar* _tmp87_;
				gchar* _tmp88_;
				gchar* _tmp89_;
				_tmp82_ = self->priv->sourceName;
				gtk_entry_set_text (_tmp82_, "GladeDialog");
				_tmp83_ = self->priv->sourceDescription;
				_tmp84_ = gtk_text_view_get_buffer (_tmp83_);
				_tmp85_ = _tmp84_;
				_tmp86_ = string_to_string (_ (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_dialog_resource));
				_tmp87_ = string_to_string (_ ("Creates an Gtk.Dialog based on a glade file"));
				_tmp88_ = g_strconcat ("<b>", _tmp86_, "</b>\n", _tmp87_, ".", NULL);
				_tmp89_ = _tmp88_;
				gtk_text_buffer_insert_markup (_tmp85_, &startIter, _tmp89_, -1);
				_g_free0 (_tmp89_);
				break;
			}
		}
	} else if (_tmp17_ == g_quark_from_string (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_widget_resource)) {
		switch (0) {
			default:
			{
				GtkEntry* _tmp90_;
				GtkTextView* _tmp91_;
				GtkTextBuffer* _tmp92_;
				GtkTextBuffer* _tmp93_;
				const gchar* _tmp94_;
				const gchar* _tmp95_;
				gchar* _tmp96_;
				gchar* _tmp97_;
				_tmp90_ = self->priv->sourceName;
				gtk_entry_set_text (_tmp90_, "GladeWidget");
				_tmp91_ = self->priv->sourceDescription;
				_tmp92_ = gtk_text_view_get_buffer (_tmp91_);
				_tmp93_ = _tmp92_;
				_tmp94_ = string_to_string (_ (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_widget_resource));
				_tmp95_ = string_to_string (_ ("Creates an Gtk.Widget based on a glade file"));
				_tmp96_ = g_strconcat ("<b>", _tmp94_, "</b>\n", _tmp95_, ".", NULL);
				_tmp97_ = _tmp96_;
				gtk_text_buffer_insert_markup (_tmp93_, &startIter, _tmp97_, -1);
				_g_free0 (_tmp97_);
				break;
			}
		}
	} else if (_tmp17_ == g_quark_from_string (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_window_resource)) {
		switch (0) {
			default:
			{
				GtkEntry* _tmp98_;
				GtkTextView* _tmp99_;
				GtkTextBuffer* _tmp100_;
				GtkTextBuffer* _tmp101_;
				const gchar* _tmp102_;
				const gchar* _tmp103_;
				gchar* _tmp104_;
				gchar* _tmp105_;
				_tmp98_ = self->priv->sourceName;
				gtk_entry_set_text (_tmp98_, "GladeWindow");
				_tmp99_ = self->priv->sourceDescription;
				_tmp100_ = gtk_text_view_get_buffer (_tmp99_);
				_tmp101_ = _tmp100_;
				_tmp102_ = string_to_string (_ (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_window_resource));
				_tmp103_ = string_to_string (_ ("Creates an Gtk.Window based on a glade file"));
				_tmp104_ = g_strconcat ("<b>", _tmp102_, "</b>\n", _tmp103_, ".", NULL);
				_tmp105_ = _tmp104_;
				gtk_text_buffer_insert_markup (_tmp101_, &startIter, _tmp105_, -1);
				_g_free0 (_tmp105_);
				break;
			}
		}
	}
	result = TRUE;
	_g_free0 (entry);
	G_IS_VALUE (&val) ? (g_value_unset (&val), NULL) : NULL;
	return result;
}

static void
vala_develop_source_create_file_OnAccept (valaDevelopSourceCreateFile* self)
{
	GtkTreeModel* model = NULL;
	GtkTreeIter iter = {0};
	GtkTreeView* _tmp0_;
	GtkTreeSelection* _tmp1_;
	GtkTreeModel* _tmp2_ = NULL;
	GtkTreeIter _tmp3_ = {0};
	gboolean _tmp4_;
	GtkTreeModel* _tmp5_;
	GValue val = {0};
	GtkTreeModel* _tmp6_;
	GtkTreeIter _tmp7_;
	GValue _tmp8_ = {0};
	gchar* str = NULL;
	GValue _tmp9_;
	gchar* _tmp10_;
	const gchar* _tmp11_;
	const gchar* _tmp12_;
	GQuark _tmp14_ = 0U;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->sourceGroup;
	_tmp1_ = gtk_tree_view_get_selection (_tmp0_);
	_tmp4_ = gtk_tree_selection_get_selected (_tmp1_, &_tmp2_, &_tmp3_);
	_g_object_unref0 (model);
	_tmp5_ = _g_object_ref0 (_tmp2_);
	model = _tmp5_;
	iter = _tmp3_;
	if (!_tmp4_) {
		_g_object_unref0 (model);
		return;
	}
	_tmp6_ = model;
	_tmp7_ = iter;
	gtk_tree_model_get_value (_tmp6_, &_tmp7_, 0, &_tmp8_);
	G_IS_VALUE (&val) ? (g_value_unset (&val), NULL) : NULL;
	val = _tmp8_;
	_tmp9_ = val;
	_tmp10_ = g_strdup (g_value_get_string (&_tmp9_));
	str = _tmp10_;
	_tmp11_ = str;
	_tmp12_ = _tmp11_;
	_tmp14_ = (NULL == _tmp12_) ? 0 : g_quark_from_string (_tmp12_);
	if (_tmp14_ == g_quark_from_string (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_class)) {
		switch (0) {
			default:
			{
				vala_develop_source_create_file_CreateSource (self, 8);
				break;
			}
		}
	} else if (_tmp14_ == g_quark_from_string (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_enum)) {
		switch (0) {
			default:
			{
				vala_develop_source_create_file_CreateSource (self, 7);
				break;
			}
		}
	} else if (_tmp14_ == g_quark_from_string (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_interface)) {
		switch (0) {
			default:
			{
				vala_develop_source_create_file_CreateSource (self, 9);
				break;
			}
		}
	} else if (_tmp14_ == g_quark_from_string (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_struct)) {
		switch (0) {
			default:
			{
				vala_develop_source_create_file_CreateSource (self, 0);
				break;
			}
		}
	} else if (_tmp14_ == g_quark_from_string (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_dialog)) {
		switch (0) {
			default:
			{
				vala_develop_source_create_file_CreateSource (self, 4);
				break;
			}
		}
	} else if (_tmp14_ == g_quark_from_string (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_widget)) {
		switch (0) {
			default:
			{
				vala_develop_source_create_file_CreateSource (self, 5);
				break;
			}
		}
	} else if (_tmp14_ == g_quark_from_string (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_window)) {
		switch (0) {
			default:
			{
				vala_develop_source_create_file_CreateSource (self, 6);
				break;
			}
		}
	} else if (_tmp14_ == g_quark_from_string (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_plugin)) {
		switch (0) {
			default:
			{
				vala_develop_source_create_file_CreateSource (self, 10);
				break;
			}
		}
	} else if (_tmp14_ == g_quark_from_string (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_dialog_resource)) {
		switch (0) {
			default:
			{
				vala_develop_source_create_file_CreateResource (self, 2);
				vala_develop_source_create_file_CreateSource (self, 1);
				break;
			}
		}
	} else if (_tmp14_ == g_quark_from_string (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_widget_resource)) {
		switch (0) {
			default:
			{
				vala_develop_source_create_file_CreateResource (self, 1);
				vala_develop_source_create_file_CreateSource (self, 2);
				break;
			}
		}
	} else if (_tmp14_ == g_quark_from_string (VALA_DEVELOP_SOURCE_CREATE_FILE_empty_window_resource)) {
		switch (0) {
			default:
			{
				vala_develop_source_create_file_CreateResource (self, 3);
				vala_develop_source_create_file_CreateSource (self, 3);
				break;
			}
		}
	}
	gtk_dialog_response ((GtkDialog*) self, (gint) GTK_RESPONSE_ACCEPT);
	_g_free0 (str);
	G_IS_VALUE (&val) ? (g_value_unset (&val), NULL) : NULL;
	_g_object_unref0 (model);
}

static void
_vala_develop_source_create_file_OnAccept_gtk_button_clicked (GtkButton* _sender,
                                                              gpointer self)
{
	vala_develop_source_create_file_OnAccept ((valaDevelopSourceCreateFile*) self);
}

static void
vala_develop_source_create_file_OnCancel (valaDevelopSourceCreateFile* self)
{
	g_return_if_fail (self != NULL);
	gtk_dialog_response ((GtkDialog*) self, (gint) GTK_RESPONSE_CANCEL);
}

static void
_vala_develop_source_create_file_OnCancel_gtk_button_clicked (GtkButton* _sender,
                                                              gpointer self)
{
	vala_develop_source_create_file_OnCancel ((valaDevelopSourceCreateFile*) self);
}

static gchar*
string_replace (const gchar* self,
                const gchar* old,
                const gchar* replacement)
{
	gchar* result = NULL;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	GError* _inner_error0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	if ((*((gchar*) self)) == '\0') {
		_tmp1_ = TRUE;
	} else {
		_tmp1_ = (*((gchar*) old)) == '\0';
	}
	if (_tmp1_) {
		_tmp0_ = TRUE;
	} else {
		_tmp0_ = g_strcmp0 (old, replacement) == 0;
	}
	if (_tmp0_) {
		gchar* _tmp2_;
		_tmp2_ = g_strdup (self);
		result = _tmp2_;
		return result;
	}
	{
		GRegex* regex = NULL;
		gchar* _tmp3_;
		gchar* _tmp4_;
		GRegex* _tmp5_;
		GRegex* _tmp6_;
		gchar* _tmp7_ = NULL;
		GRegex* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		_tmp3_ = g_regex_escape_string (old, -1);
		_tmp4_ = _tmp3_;
		_tmp5_ = g_regex_new (_tmp4_, 0, 0, &_inner_error0_);
		_tmp6_ = _tmp5_;
		_g_free0 (_tmp4_);
		regex = _tmp6_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			if (_inner_error0_->domain == G_REGEX_ERROR) {
				goto __catch5_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return NULL;
		}
		_tmp8_ = regex;
		_tmp9_ = g_regex_replace_literal (_tmp8_, self, (gssize) -1, 0, replacement, 0, &_inner_error0_);
		_tmp7_ = _tmp9_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_regex_unref0 (regex);
			if (_inner_error0_->domain == G_REGEX_ERROR) {
				goto __catch5_g_regex_error;
			}
			_g_regex_unref0 (regex);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return NULL;
		}
		_tmp10_ = _tmp7_;
		_tmp7_ = NULL;
		result = _tmp10_;
		_g_free0 (_tmp7_);
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally5;
	__catch5_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		g_assert_not_reached ();
		_g_error_free0 (e);
	}
	__finally5:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return NULL;
	}
}

static void
vala_develop_source_create_file_CreateResource (valaDevelopSourceCreateFile* self,
                                                gint r)
{
	GError* _inner_error0_ = NULL;
	g_return_if_fail (self != NULL);
	{
		GtkTreeIter solutionIter = {0};
		valaDevelopOverviewTreeStore* _tmp0_;
		GtkTreeIter _tmp1_ = {0};
		gchar* solutionpath = NULL;
		valaDevelopOverviewTreeStore* _tmp2_;
		GtkTreeIter _tmp3_;
		gchar* _tmp4_;
		gchar* projectNamespace = NULL;
		valaDevelopOverviewTreeStore* _tmp5_;
		valaDevelopOverviewTreeStore* _tmp6_;
		GtkTreeIter _tmp7_;
		GtkTreeIter* _tmp8_;
		GtkTreeIter* _tmp9_;
		GtkTreeIter _tmp10_;
		gchar* _tmp11_;
		gchar* _tmp12_;
		gchar* path = NULL;
		valaDevelopOverviewTreeStore* _tmp13_;
		valaDevelopOverviewTreeStore* _tmp14_;
		GtkTreeIter _tmp15_;
		GtkTreeIter* _tmp16_;
		GtkTreeIter* _tmp17_;
		GtkTreeIter _tmp18_;
		gchar* _tmp19_;
		gchar* _tmp20_;
		gchar* _tmp21_ = NULL;
		GtkEntry* _tmp22_;
		const gchar* _tmp23_;
		const gchar* _tmp24_;
		gchar* file = NULL;
		gchar* _tmp33_;
		GFile* fullPath = NULL;
		const gchar* _tmp34_;
		GFile* _tmp35_;
		GFile* _tmp36_;
		const gchar* _tmp37_;
		GFile* _tmp38_;
		GFile* _tmp39_;
		const gchar* _tmp40_;
		GFile* _tmp41_;
		GFile* _tmp42_;
		GFile* source = NULL;
		gchar* _tmp43_;
		gchar* _tmp44_;
		gchar* _tmp45_;
		gchar* _tmp46_;
		GFile* _tmp47_;
		GFile* _tmp48_;
		GFileInputStream* _tmp49_ = NULL;
		GFile* _tmp50_;
		GFileInputStream* _tmp51_;
		GDataInputStream* dataInputStream = NULL;
		GDataInputStream* _tmp52_;
		GFileOutputStream* _tmp53_ = NULL;
		GFile* _tmp54_;
		GFileOutputStream* _tmp55_;
		GDataOutputStream* dataOutputStream = NULL;
		GDataOutputStream* _tmp56_;
		gchar* line = NULL;
		GDataInputStream* _tmp73_;
		GDataOutputStream* _tmp74_;
		GtkTreeIter tmpIter = {0};
		valaDevelopOverviewTreeStore* _tmp75_;
		valaDevelopOverviewTreeStore* _tmp76_;
		GtkTreeIter _tmp77_;
		GtkTreeIter* _tmp78_;
		GtkTreeIter* _tmp79_;
		GtkTreeIter _tmp80_ = {0};
		valaDevelopOverviewTreeStore* _tmp81_;
		GtkTreeIter _tmp82_;
		valaDevelopOverviewTreeStore* _tmp83_;
		GtkTreeIter _tmp84_;
		const gchar* _tmp85_;
		valaDevelopOverviewTreeStore* _tmp86_;
		GtkTreeIter _tmp87_;
		const gchar* _tmp88_;
		const gchar* _tmp89_;
		const gchar* _tmp90_;
		const gchar* _tmp91_;
		gchar* _tmp92_;
		gchar* _tmp93_;
		valaDevelopOverviewTreeStore* _tmp94_;
		GtkTreeIter _tmp95_;
		valaDevelopOverviewTreeStore* _tmp96_;
		GtkTreeIter _tmp97_;
		valaDevelopOverviewTreeStore* _tmp98_;
		GtkTreeIter _tmp99_;
		valaDevelopOverviewTreeStore* _tmp100_;
		GtkTreeIter _tmp101_;
		GdkPixbuf* _tmp102_ = NULL;
		GdkPixbuf* _tmp103_;
		valaDevelopOverviewTreeStore* _tmp104_;
		GtkTreeIter _tmp105_;
		GdkPixbuf* _tmp106_;
		GdkPixbuf* _tmp107_;
		_tmp0_ = vala_develop_main_paned_overviewTreeModel;
		gtk_tree_model_get_iter_first ((GtkTreeModel*) _tmp0_, &_tmp1_);
		solutionIter = _tmp1_;
		_tmp2_ = vala_develop_main_paned_overviewTreeModel;
		_tmp3_ = solutionIter;
		_tmp4_ = vala_develop_overview_tree_store_get_item_path (_tmp2_, &_tmp3_);
		solutionpath = _tmp4_;
		_tmp5_ = vala_develop_main_paned_overviewTreeModel;
		_tmp6_ = vala_develop_main_paned_overviewTreeModel;
		_tmp7_ = self->priv->_overviewTreeIter;
		_tmp8_ = vala_develop_overview_tree_store_get_project_iter_by_iter (_tmp6_, &_tmp7_);
		_tmp9_ = _tmp8_;
		_tmp10_ = *_tmp9_;
		_tmp11_ = vala_develop_overview_tree_store_get_item_namespace (_tmp5_, &_tmp10_);
		_tmp12_ = _tmp11_;
		_g_free0 (_tmp9_);
		projectNamespace = _tmp12_;
		_tmp13_ = vala_develop_main_paned_overviewTreeModel;
		_tmp14_ = vala_develop_main_paned_overviewTreeModel;
		_tmp15_ = self->priv->_overviewTreeIter;
		_tmp16_ = vala_develop_overview_tree_store_get_resource_iter (_tmp14_, &_tmp15_);
		_tmp17_ = _tmp16_;
		_tmp18_ = *_tmp17_;
		_tmp19_ = vala_develop_overview_tree_store_get_item_path (_tmp13_, &_tmp18_);
		_tmp20_ = _tmp19_;
		_g_free0 (_tmp17_);
		path = _tmp20_;
		_tmp22_ = self->priv->sourceName;
		_tmp23_ = gtk_entry_get_text (_tmp22_);
		_tmp24_ = _tmp23_;
		if (g_str_has_suffix (_tmp24_, ".glade")) {
			GtkEntry* _tmp25_;
			const gchar* _tmp26_;
			const gchar* _tmp27_;
			gchar* _tmp28_;
			_tmp25_ = self->priv->sourceName;
			_tmp26_ = gtk_entry_get_text (_tmp25_);
			_tmp27_ = _tmp26_;
			_tmp28_ = g_strdup (_tmp27_);
			_g_free0 (_tmp21_);
			_tmp21_ = _tmp28_;
		} else {
			GtkEntry* _tmp29_;
			const gchar* _tmp30_;
			const gchar* _tmp31_;
			gchar* _tmp32_;
			_tmp29_ = self->priv->sourceName;
			_tmp30_ = gtk_entry_get_text (_tmp29_);
			_tmp31_ = _tmp30_;
			_tmp32_ = g_strconcat (_tmp31_, ".glade", NULL);
			_g_free0 (_tmp21_);
			_tmp21_ = _tmp32_;
		}
		_tmp33_ = g_strdup (_tmp21_);
		file = _tmp33_;
		_tmp34_ = solutionpath;
		_tmp35_ = g_file_new_for_path (_tmp34_);
		_tmp36_ = _tmp35_;
		_tmp37_ = path;
		_tmp38_ = g_file_get_child (_tmp36_, _tmp37_);
		_tmp39_ = _tmp38_;
		_tmp40_ = file;
		_tmp41_ = g_file_get_child (_tmp39_, _tmp40_);
		_tmp42_ = _tmp41_;
		_g_object_unref0 (_tmp39_);
		_g_object_unref0 (_tmp36_);
		fullPath = _tmp42_;
		_tmp43_ = g_strdup_printf ("%i", r);
		_tmp44_ = _tmp43_;
		_tmp45_ = g_strconcat ("resource:///valaDevelop/resource", _tmp44_, ".glade", NULL);
		_tmp46_ = _tmp45_;
		_tmp47_ = g_file_new_for_uri (_tmp46_);
		_tmp48_ = _tmp47_;
		_g_free0 (_tmp46_);
		_g_free0 (_tmp44_);
		source = _tmp48_;
		_tmp50_ = source;
		_tmp51_ = g_file_read (_tmp50_, NULL, &_inner_error0_);
		_tmp49_ = _tmp51_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_object_unref0 (source);
			_g_object_unref0 (fullPath);
			_g_free0 (file);
			_g_free0 (_tmp21_);
			_g_free0 (path);
			_g_free0 (projectNamespace);
			_g_free0 (solutionpath);
			goto __catch4_g_error;
		}
		_tmp52_ = g_data_input_stream_new ((GInputStream*) _tmp49_);
		dataInputStream = _tmp52_;
		_tmp54_ = fullPath;
		_tmp55_ = g_file_create (_tmp54_, G_FILE_CREATE_PRIVATE, NULL, &_inner_error0_);
		_tmp53_ = _tmp55_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_object_unref0 (dataInputStream);
			_g_object_unref0 (_tmp49_);
			_g_object_unref0 (source);
			_g_object_unref0 (fullPath);
			_g_free0 (file);
			_g_free0 (_tmp21_);
			_g_free0 (path);
			_g_free0 (projectNamespace);
			_g_free0 (solutionpath);
			goto __catch4_g_error;
		}
		_tmp56_ = g_data_output_stream_new ((GOutputStream*) _tmp53_);
		dataOutputStream = _tmp56_;
		while (TRUE) {
			gchar* _tmp57_ = NULL;
			GDataInputStream* _tmp58_;
			gchar* _tmp59_;
			gchar* _tmp60_;
			const gchar* _tmp61_;
			GDataOutputStream* _tmp62_;
			const gchar* _tmp63_;
			const gchar* _tmp64_;
			gchar* _tmp65_;
			gchar* _tmp66_;
			GtkEntry* _tmp67_;
			const gchar* _tmp68_;
			const gchar* _tmp69_;
			gchar* _tmp70_;
			gchar* _tmp71_;
			GDataOutputStream* _tmp72_;
			_tmp58_ = dataInputStream;
			_tmp59_ = g_data_input_stream_read_line_utf8 (_tmp58_, NULL, NULL, &_inner_error0_);
			_tmp57_ = _tmp59_;
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
				_g_free0 (line);
				_g_object_unref0 (dataOutputStream);
				_g_object_unref0 (_tmp53_);
				_g_object_unref0 (dataInputStream);
				_g_object_unref0 (_tmp49_);
				_g_object_unref0 (source);
				_g_object_unref0 (fullPath);
				_g_free0 (file);
				_g_free0 (_tmp21_);
				_g_free0 (path);
				_g_free0 (projectNamespace);
				_g_free0 (solutionpath);
				goto __catch4_g_error;
			}
			_tmp60_ = _tmp57_;
			_tmp57_ = NULL;
			_g_free0 (line);
			line = _tmp60_;
			_tmp61_ = line;
			if (!(_tmp61_ != NULL)) {
				_g_free0 (_tmp57_);
				break;
			}
			_tmp62_ = dataOutputStream;
			_tmp63_ = line;
			_tmp64_ = projectNamespace;
			_tmp65_ = string_replace (_tmp63_, "{projectNamespace}", _tmp64_);
			_tmp66_ = _tmp65_;
			_tmp67_ = self->priv->sourceName;
			_tmp68_ = gtk_entry_get_text (_tmp67_);
			_tmp69_ = _tmp68_;
			_tmp70_ = string_replace (_tmp66_, "{filename}", _tmp69_);
			_tmp71_ = _tmp70_;
			g_data_output_stream_put_string (_tmp62_, _tmp71_, NULL, &_inner_error0_);
			_g_free0 (_tmp71_);
			_g_free0 (_tmp66_);
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
				_g_free0 (_tmp57_);
				_g_free0 (line);
				_g_object_unref0 (dataOutputStream);
				_g_object_unref0 (_tmp53_);
				_g_object_unref0 (dataInputStream);
				_g_object_unref0 (_tmp49_);
				_g_object_unref0 (source);
				_g_object_unref0 (fullPath);
				_g_free0 (file);
				_g_free0 (_tmp21_);
				_g_free0 (path);
				_g_free0 (projectNamespace);
				_g_free0 (solutionpath);
				goto __catch4_g_error;
			}
			_tmp72_ = dataOutputStream;
			g_data_output_stream_put_string (_tmp72_, "\n", NULL, &_inner_error0_);
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
				_g_free0 (_tmp57_);
				_g_free0 (line);
				_g_object_unref0 (dataOutputStream);
				_g_object_unref0 (_tmp53_);
				_g_object_unref0 (dataInputStream);
				_g_object_unref0 (_tmp49_);
				_g_object_unref0 (source);
				_g_object_unref0 (fullPath);
				_g_free0 (file);
				_g_free0 (_tmp21_);
				_g_free0 (path);
				_g_free0 (projectNamespace);
				_g_free0 (solutionpath);
				goto __catch4_g_error;
			}
			_g_free0 (_tmp57_);
		}
		_tmp73_ = dataInputStream;
		g_input_stream_close ((GInputStream*) _tmp73_, NULL, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_free0 (line);
			_g_object_unref0 (dataOutputStream);
			_g_object_unref0 (_tmp53_);
			_g_object_unref0 (dataInputStream);
			_g_object_unref0 (_tmp49_);
			_g_object_unref0 (source);
			_g_object_unref0 (fullPath);
			_g_free0 (file);
			_g_free0 (_tmp21_);
			_g_free0 (path);
			_g_free0 (projectNamespace);
			_g_free0 (solutionpath);
			goto __catch4_g_error;
		}
		_tmp74_ = dataOutputStream;
		g_output_stream_close ((GOutputStream*) _tmp74_, NULL, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_free0 (line);
			_g_object_unref0 (dataOutputStream);
			_g_object_unref0 (_tmp53_);
			_g_object_unref0 (dataInputStream);
			_g_object_unref0 (_tmp49_);
			_g_object_unref0 (source);
			_g_object_unref0 (fullPath);
			_g_free0 (file);
			_g_free0 (_tmp21_);
			_g_free0 (path);
			_g_free0 (projectNamespace);
			_g_free0 (solutionpath);
			goto __catch4_g_error;
		}
		_tmp75_ = vala_develop_main_paned_overviewTreeModel;
		_tmp76_ = vala_develop_main_paned_overviewTreeModel;
		_tmp77_ = self->priv->_overviewTreeIter;
		_tmp78_ = vala_develop_overview_tree_store_get_resource_iter (_tmp76_, &_tmp77_);
		_tmp79_ = _tmp78_;
		gtk_tree_store_append ((GtkTreeStore*) _tmp75_, &_tmp80_, _tmp79_);
		tmpIter = _tmp80_;
		_g_free0 (_tmp79_);
		_tmp81_ = vala_develop_main_paned_overviewTreeModel;
		_tmp82_ = tmpIter;
		vala_develop_overview_tree_store_set_item_type (_tmp81_, &_tmp82_, (gint) VALA_DEVELOP_ITEM_TYPE_Resource);
		_tmp83_ = vala_develop_main_paned_overviewTreeModel;
		_tmp84_ = tmpIter;
		_tmp85_ = file;
		vala_develop_overview_tree_store_set_item_name (_tmp83_, &_tmp84_, _tmp85_);
		_tmp86_ = vala_develop_main_paned_overviewTreeModel;
		_tmp87_ = tmpIter;
		_tmp88_ = projectNamespace;
		_tmp89_ = string_to_string (_tmp88_);
		_tmp90_ = file;
		_tmp91_ = string_to_string (_tmp90_);
		_tmp92_ = g_strconcat ("/", _tmp89_, "/", _tmp91_, NULL);
		_tmp93_ = _tmp92_;
		vala_develop_overview_tree_store_set_item_resource_id (_tmp86_, &_tmp87_, _tmp93_);
		_g_free0 (_tmp93_);
		_tmp94_ = vala_develop_main_paned_overviewTreeModel;
		_tmp95_ = tmpIter;
		vala_develop_overview_tree_store_set_item_resource_compress (_tmp94_, &_tmp95_, TRUE);
		_tmp96_ = vala_develop_main_paned_overviewTreeModel;
		_tmp97_ = tmpIter;
		vala_develop_overview_tree_store_set_item_resource_stripblanks (_tmp96_, &_tmp97_, TRUE);
		_tmp98_ = vala_develop_main_paned_overviewTreeModel;
		_tmp99_ = tmpIter;
		vala_develop_overview_tree_store_set_item_buildtype (_tmp98_, &_tmp99_, (gint) VALA_DEVELOP_ITEM_BUILD_TYPE_Resource);
		_tmp100_ = vala_develop_main_paned_overviewTreeModel;
		_tmp101_ = tmpIter;
		vala_develop_overview_tree_store_set_item_mimetype (_tmp100_, &_tmp101_, "application/x-glade");
		_tmp103_ = gdk_pixbuf_new_from_resource ("/valaDevelop/glade.svg.png", &_inner_error0_);
		_tmp102_ = _tmp103_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_free0 (line);
			_g_object_unref0 (dataOutputStream);
			_g_object_unref0 (_tmp53_);
			_g_object_unref0 (dataInputStream);
			_g_object_unref0 (_tmp49_);
			_g_object_unref0 (source);
			_g_object_unref0 (fullPath);
			_g_free0 (file);
			_g_free0 (_tmp21_);
			_g_free0 (path);
			_g_free0 (projectNamespace);
			_g_free0 (solutionpath);
			goto __catch4_g_error;
		}
		_tmp104_ = vala_develop_main_paned_overviewTreeModel;
		_tmp105_ = tmpIter;
		_tmp106_ = gdk_pixbuf_scale_simple (_tmp102_, 16, 16, GDK_INTERP_BILINEAR);
		_tmp107_ = _tmp106_;
		vala_develop_overview_tree_store_set_item_pixbuf (_tmp104_, &_tmp105_, _tmp107_);
		_g_object_unref0 (_tmp107_);
		_g_object_unref0 (_tmp102_);
		_g_free0 (line);
		_g_object_unref0 (dataOutputStream);
		_g_object_unref0 (_tmp53_);
		_g_object_unref0 (dataInputStream);
		_g_object_unref0 (_tmp49_);
		_g_object_unref0 (source);
		_g_object_unref0 (fullPath);
		_g_free0 (file);
		_g_free0 (_tmp21_);
		_g_free0 (path);
		_g_free0 (projectNamespace);
		_g_free0 (solutionpath);
	}
	goto __finally4;
	__catch4_g_error:
	{
		GError* e = NULL;
		GtkMessageDialog* messagedialog = NULL;
		GError* _tmp108_;
		const gchar* _tmp109_;
		GtkMessageDialog* _tmp110_;
		GtkMessageDialog* _tmp111_;
		GtkMessageDialog* _tmp112_;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp108_ = e;
		_tmp109_ = _tmp108_->message;
		_tmp110_ = (GtkMessageDialog*) gtk_message_dialog_new (NULL, GTK_DIALOG_MODAL, GTK_MESSAGE_ERROR, GTK_BUTTONS_OK, "%s", _tmp109_);
		g_object_ref_sink (_tmp110_);
		messagedialog = _tmp110_;
		_tmp111_ = messagedialog;
		gtk_dialog_run ((GtkDialog*) _tmp111_);
		_tmp112_ = messagedialog;
		gtk_widget_destroy ((GtkWidget*) _tmp112_);
		_g_object_unref0 (messagedialog);
		_g_error_free0 (e);
	}
	__finally4:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
}

static void
vala_develop_source_create_file_CreateSource (valaDevelopSourceCreateFile* self,
                                              gint c)
{
	GError* _inner_error0_ = NULL;
	g_return_if_fail (self != NULL);
	{
		GtkTreeIter solutionIter = {0};
		valaDevelopOverviewTreeStore* _tmp0_;
		GtkTreeIter _tmp1_ = {0};
		gchar* solutionpath = NULL;
		valaDevelopOverviewTreeStore* _tmp2_;
		GtkTreeIter _tmp3_;
		gchar* _tmp4_;
		gchar* projectNamespace = NULL;
		valaDevelopOverviewTreeStore* _tmp5_;
		valaDevelopOverviewTreeStore* _tmp6_;
		GtkTreeIter _tmp7_;
		GtkTreeIter* _tmp8_;
		GtkTreeIter* _tmp9_;
		GtkTreeIter _tmp10_;
		gchar* _tmp11_;
		gchar* _tmp12_;
		gchar* projectName = NULL;
		valaDevelopOverviewTreeStore* _tmp13_;
		valaDevelopOverviewTreeStore* _tmp14_;
		GtkTreeIter _tmp15_;
		GtkTreeIter* _tmp16_;
		GtkTreeIter* _tmp17_;
		GtkTreeIter _tmp18_;
		gchar* _tmp19_;
		gchar* _tmp20_;
		gchar* path = NULL;
		valaDevelopOverviewTreeStore* _tmp21_;
		GtkTreeIter _tmp22_;
		gchar* _tmp23_;
		gchar* _tmp24_ = NULL;
		GtkEntry* _tmp25_;
		const gchar* _tmp26_;
		const gchar* _tmp27_;
		gchar* file = NULL;
		gchar* _tmp36_;
		GFile* fullPath = NULL;
		const gchar* _tmp37_;
		GFile* _tmp38_;
		GFile* _tmp39_;
		const gchar* _tmp40_;
		GFile* _tmp41_;
		GFile* _tmp42_;
		const gchar* _tmp43_;
		GFile* _tmp44_;
		GFile* _tmp45_;
		GFile* source = NULL;
		gchar* _tmp46_;
		gchar* _tmp47_;
		gchar* _tmp48_;
		gchar* _tmp49_;
		GFile* _tmp50_;
		GFile* _tmp51_;
		GFileInputStream* _tmp52_ = NULL;
		GFile* _tmp53_;
		GFileInputStream* _tmp54_;
		GDataInputStream* dataInputStream = NULL;
		GDataInputStream* _tmp55_;
		GFileOutputStream* _tmp56_ = NULL;
		GFile* _tmp57_;
		GFileOutputStream* _tmp58_;
		GDataOutputStream* dataOutputStream = NULL;
		GDataOutputStream* _tmp59_;
		gchar* line = NULL;
		GDataInputStream* _tmp76_;
		GDataOutputStream* _tmp77_;
		GtkTreeIter tmpIter = {0};
		valaDevelopOverviewTreeStore* _tmp78_;
		GtkTreeIter _tmp79_;
		GtkTreeIter _tmp80_ = {0};
		valaDevelopOverviewTreeStore* _tmp81_;
		GtkTreeIter _tmp82_;
		valaDevelopOverviewTreeStore* _tmp83_;
		GtkTreeIter _tmp84_;
		const gchar* _tmp85_;
		valaDevelopOverviewTreeStore* _tmp86_;
		GtkTreeIter _tmp87_;
		valaDevelopOverviewTreeStore* _tmp88_;
		GtkTreeIter _tmp89_;
		GdkPixbuf* _tmp90_ = NULL;
		GdkPixbuf* _tmp91_;
		valaDevelopOverviewTreeStore* _tmp92_;
		GtkTreeIter _tmp93_;
		GdkPixbuf* _tmp94_;
		GdkPixbuf* _tmp95_;
		valaDevelopSymbolFinder* sf = NULL;
		GeeHashMap* _tmp96_;
		const gchar* _tmp97_;
		gpointer _tmp98_;
		valaDevelopSymbolFinder* _tmp99_;
		GFile* _tmp100_;
		gchar* _tmp101_;
		gchar* _tmp102_;
		_tmp0_ = vala_develop_main_paned_overviewTreeModel;
		gtk_tree_model_get_iter_first ((GtkTreeModel*) _tmp0_, &_tmp1_);
		solutionIter = _tmp1_;
		_tmp2_ = vala_develop_main_paned_overviewTreeModel;
		_tmp3_ = solutionIter;
		_tmp4_ = vala_develop_overview_tree_store_get_item_path (_tmp2_, &_tmp3_);
		solutionpath = _tmp4_;
		_tmp5_ = vala_develop_main_paned_overviewTreeModel;
		_tmp6_ = vala_develop_main_paned_overviewTreeModel;
		_tmp7_ = self->priv->_overviewTreeIter;
		_tmp8_ = vala_develop_overview_tree_store_get_project_iter_by_iter (_tmp6_, &_tmp7_);
		_tmp9_ = _tmp8_;
		_tmp10_ = *_tmp9_;
		_tmp11_ = vala_develop_overview_tree_store_get_item_namespace (_tmp5_, &_tmp10_);
		_tmp12_ = _tmp11_;
		_g_free0 (_tmp9_);
		projectNamespace = _tmp12_;
		_tmp13_ = vala_develop_main_paned_overviewTreeModel;
		_tmp14_ = vala_develop_main_paned_overviewTreeModel;
		_tmp15_ = self->priv->_overviewTreeIter;
		_tmp16_ = vala_develop_overview_tree_store_get_project_iter_by_iter (_tmp14_, &_tmp15_);
		_tmp17_ = _tmp16_;
		_tmp18_ = *_tmp17_;
		_tmp19_ = vala_develop_overview_tree_store_get_item_name (_tmp13_, &_tmp18_);
		_tmp20_ = _tmp19_;
		_g_free0 (_tmp17_);
		projectName = _tmp20_;
		_tmp21_ = vala_develop_main_paned_overviewTreeModel;
		_tmp22_ = self->priv->_overviewTreeIter;
		_tmp23_ = vala_develop_overview_tree_store_get_item_path (_tmp21_, &_tmp22_);
		path = _tmp23_;
		_tmp25_ = self->priv->sourceName;
		_tmp26_ = gtk_entry_get_text (_tmp25_);
		_tmp27_ = _tmp26_;
		if (g_str_has_suffix (_tmp27_, ".vala")) {
			GtkEntry* _tmp28_;
			const gchar* _tmp29_;
			const gchar* _tmp30_;
			gchar* _tmp31_;
			_tmp28_ = self->priv->sourceName;
			_tmp29_ = gtk_entry_get_text (_tmp28_);
			_tmp30_ = _tmp29_;
			_tmp31_ = g_strdup (_tmp30_);
			_g_free0 (_tmp24_);
			_tmp24_ = _tmp31_;
		} else {
			GtkEntry* _tmp32_;
			const gchar* _tmp33_;
			const gchar* _tmp34_;
			gchar* _tmp35_;
			_tmp32_ = self->priv->sourceName;
			_tmp33_ = gtk_entry_get_text (_tmp32_);
			_tmp34_ = _tmp33_;
			_tmp35_ = g_strconcat (_tmp34_, ".vala", NULL);
			_g_free0 (_tmp24_);
			_tmp24_ = _tmp35_;
		}
		_tmp36_ = g_strdup (_tmp24_);
		file = _tmp36_;
		_tmp37_ = solutionpath;
		_tmp38_ = g_file_new_for_path (_tmp37_);
		_tmp39_ = _tmp38_;
		_tmp40_ = path;
		_tmp41_ = g_file_get_child (_tmp39_, _tmp40_);
		_tmp42_ = _tmp41_;
		_tmp43_ = file;
		_tmp44_ = g_file_get_child (_tmp42_, _tmp43_);
		_tmp45_ = _tmp44_;
		_g_object_unref0 (_tmp42_);
		_g_object_unref0 (_tmp39_);
		fullPath = _tmp45_;
		_tmp46_ = g_strdup_printf ("%i", c);
		_tmp47_ = _tmp46_;
		_tmp48_ = g_strconcat ("resource:///valaDevelop/source", _tmp47_, ".vala", NULL);
		_tmp49_ = _tmp48_;
		_tmp50_ = g_file_new_for_uri (_tmp49_);
		_tmp51_ = _tmp50_;
		_g_free0 (_tmp49_);
		_g_free0 (_tmp47_);
		source = _tmp51_;
		_tmp53_ = source;
		_tmp54_ = g_file_read (_tmp53_, NULL, &_inner_error0_);
		_tmp52_ = _tmp54_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_object_unref0 (source);
			_g_object_unref0 (fullPath);
			_g_free0 (file);
			_g_free0 (_tmp24_);
			_g_free0 (path);
			_g_free0 (projectName);
			_g_free0 (projectNamespace);
			_g_free0 (solutionpath);
			goto __catch6_g_error;
		}
		_tmp55_ = g_data_input_stream_new ((GInputStream*) _tmp52_);
		dataInputStream = _tmp55_;
		_tmp57_ = fullPath;
		_tmp58_ = g_file_create (_tmp57_, G_FILE_CREATE_PRIVATE, NULL, &_inner_error0_);
		_tmp56_ = _tmp58_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_object_unref0 (dataInputStream);
			_g_object_unref0 (_tmp52_);
			_g_object_unref0 (source);
			_g_object_unref0 (fullPath);
			_g_free0 (file);
			_g_free0 (_tmp24_);
			_g_free0 (path);
			_g_free0 (projectName);
			_g_free0 (projectNamespace);
			_g_free0 (solutionpath);
			goto __catch6_g_error;
		}
		_tmp59_ = g_data_output_stream_new ((GOutputStream*) _tmp56_);
		dataOutputStream = _tmp59_;
		while (TRUE) {
			gchar* _tmp60_ = NULL;
			GDataInputStream* _tmp61_;
			gchar* _tmp62_;
			gchar* _tmp63_;
			const gchar* _tmp64_;
			GDataOutputStream* _tmp65_;
			const gchar* _tmp66_;
			const gchar* _tmp67_;
			gchar* _tmp68_;
			gchar* _tmp69_;
			GtkEntry* _tmp70_;
			const gchar* _tmp71_;
			const gchar* _tmp72_;
			gchar* _tmp73_;
			gchar* _tmp74_;
			GDataOutputStream* _tmp75_;
			_tmp61_ = dataInputStream;
			_tmp62_ = g_data_input_stream_read_line_utf8 (_tmp61_, NULL, NULL, &_inner_error0_);
			_tmp60_ = _tmp62_;
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
				_g_free0 (line);
				_g_object_unref0 (dataOutputStream);
				_g_object_unref0 (_tmp56_);
				_g_object_unref0 (dataInputStream);
				_g_object_unref0 (_tmp52_);
				_g_object_unref0 (source);
				_g_object_unref0 (fullPath);
				_g_free0 (file);
				_g_free0 (_tmp24_);
				_g_free0 (path);
				_g_free0 (projectName);
				_g_free0 (projectNamespace);
				_g_free0 (solutionpath);
				goto __catch6_g_error;
			}
			_tmp63_ = _tmp60_;
			_tmp60_ = NULL;
			_g_free0 (line);
			line = _tmp63_;
			_tmp64_ = line;
			if (!(_tmp64_ != NULL)) {
				_g_free0 (_tmp60_);
				break;
			}
			_tmp65_ = dataOutputStream;
			_tmp66_ = line;
			_tmp67_ = projectNamespace;
			_tmp68_ = string_replace (_tmp66_, "{projectNamespace}", _tmp67_);
			_tmp69_ = _tmp68_;
			_tmp70_ = self->priv->sourceName;
			_tmp71_ = gtk_entry_get_text (_tmp70_);
			_tmp72_ = _tmp71_;
			_tmp73_ = string_replace (_tmp69_, "{filename}", _tmp72_);
			_tmp74_ = _tmp73_;
			g_data_output_stream_put_string (_tmp65_, _tmp74_, NULL, &_inner_error0_);
			_g_free0 (_tmp74_);
			_g_free0 (_tmp69_);
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
				_g_free0 (_tmp60_);
				_g_free0 (line);
				_g_object_unref0 (dataOutputStream);
				_g_object_unref0 (_tmp56_);
				_g_object_unref0 (dataInputStream);
				_g_object_unref0 (_tmp52_);
				_g_object_unref0 (source);
				_g_object_unref0 (fullPath);
				_g_free0 (file);
				_g_free0 (_tmp24_);
				_g_free0 (path);
				_g_free0 (projectName);
				_g_free0 (projectNamespace);
				_g_free0 (solutionpath);
				goto __catch6_g_error;
			}
			_tmp75_ = dataOutputStream;
			g_data_output_stream_put_string (_tmp75_, "\n", NULL, &_inner_error0_);
			if (G_UNLIKELY (_inner_error0_ != NULL)) {
				_g_free0 (_tmp60_);
				_g_free0 (line);
				_g_object_unref0 (dataOutputStream);
				_g_object_unref0 (_tmp56_);
				_g_object_unref0 (dataInputStream);
				_g_object_unref0 (_tmp52_);
				_g_object_unref0 (source);
				_g_object_unref0 (fullPath);
				_g_free0 (file);
				_g_free0 (_tmp24_);
				_g_free0 (path);
				_g_free0 (projectName);
				_g_free0 (projectNamespace);
				_g_free0 (solutionpath);
				goto __catch6_g_error;
			}
			_g_free0 (_tmp60_);
		}
		_tmp76_ = dataInputStream;
		g_input_stream_close ((GInputStream*) _tmp76_, NULL, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_free0 (line);
			_g_object_unref0 (dataOutputStream);
			_g_object_unref0 (_tmp56_);
			_g_object_unref0 (dataInputStream);
			_g_object_unref0 (_tmp52_);
			_g_object_unref0 (source);
			_g_object_unref0 (fullPath);
			_g_free0 (file);
			_g_free0 (_tmp24_);
			_g_free0 (path);
			_g_free0 (projectName);
			_g_free0 (projectNamespace);
			_g_free0 (solutionpath);
			goto __catch6_g_error;
		}
		_tmp77_ = dataOutputStream;
		g_output_stream_close ((GOutputStream*) _tmp77_, NULL, &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_free0 (line);
			_g_object_unref0 (dataOutputStream);
			_g_object_unref0 (_tmp56_);
			_g_object_unref0 (dataInputStream);
			_g_object_unref0 (_tmp52_);
			_g_object_unref0 (source);
			_g_object_unref0 (fullPath);
			_g_free0 (file);
			_g_free0 (_tmp24_);
			_g_free0 (path);
			_g_free0 (projectName);
			_g_free0 (projectNamespace);
			_g_free0 (solutionpath);
			goto __catch6_g_error;
		}
		_tmp78_ = vala_develop_main_paned_overviewTreeModel;
		_tmp79_ = self->priv->_overviewTreeIter;
		gtk_tree_store_append ((GtkTreeStore*) _tmp78_, &_tmp80_, &_tmp79_);
		tmpIter = _tmp80_;
		_tmp81_ = vala_develop_main_paned_overviewTreeModel;
		_tmp82_ = tmpIter;
		vala_develop_overview_tree_store_set_item_type (_tmp81_, &_tmp82_, (gint) VALA_DEVELOP_ITEM_TYPE_Source);
		_tmp83_ = vala_develop_main_paned_overviewTreeModel;
		_tmp84_ = tmpIter;
		_tmp85_ = file;
		vala_develop_overview_tree_store_set_item_name (_tmp83_, &_tmp84_, _tmp85_);
		_tmp86_ = vala_develop_main_paned_overviewTreeModel;
		_tmp87_ = tmpIter;
		vala_develop_overview_tree_store_set_item_buildtype (_tmp86_, &_tmp87_, (gint) VALA_DEVELOP_ITEM_BUILD_TYPE_Compile);
		_tmp88_ = vala_develop_main_paned_overviewTreeModel;
		_tmp89_ = tmpIter;
		vala_develop_overview_tree_store_set_item_mimetype (_tmp88_, &_tmp89_, "text/x-vala");
		_tmp91_ = gdk_pixbuf_new_from_resource ("/valaDevelop/source.svg.png", &_inner_error0_);
		_tmp90_ = _tmp91_;
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			_g_free0 (line);
			_g_object_unref0 (dataOutputStream);
			_g_object_unref0 (_tmp56_);
			_g_object_unref0 (dataInputStream);
			_g_object_unref0 (_tmp52_);
			_g_object_unref0 (source);
			_g_object_unref0 (fullPath);
			_g_free0 (file);
			_g_free0 (_tmp24_);
			_g_free0 (path);
			_g_free0 (projectName);
			_g_free0 (projectNamespace);
			_g_free0 (solutionpath);
			goto __catch6_g_error;
		}
		_tmp92_ = vala_develop_main_paned_overviewTreeModel;
		_tmp93_ = tmpIter;
		_tmp94_ = gdk_pixbuf_scale_simple (_tmp90_, 16, 16, GDK_INTERP_BILINEAR);
		_tmp95_ = _tmp94_;
		vala_develop_overview_tree_store_set_item_pixbuf (_tmp92_, &_tmp93_, _tmp95_);
		_g_object_unref0 (_tmp95_);
		_tmp96_ = vala_develop_main_paned__symbol_finder;
		_tmp97_ = projectName;
		_tmp98_ = gee_abstract_map_get ((GeeAbstractMap*) _tmp96_, _tmp97_);
		sf = (valaDevelopSymbolFinder*) _tmp98_;
		_tmp99_ = sf;
		_tmp100_ = fullPath;
		_tmp101_ = g_file_get_path (_tmp100_);
		_tmp102_ = _tmp101_;
		vala_develop_symbol_finder_AddSourceFile (_tmp99_, _tmp102_);
		_g_free0 (_tmp102_);
		_g_object_unref0 (sf);
		_g_object_unref0 (_tmp90_);
		_g_free0 (line);
		_g_object_unref0 (dataOutputStream);
		_g_object_unref0 (_tmp56_);
		_g_object_unref0 (dataInputStream);
		_g_object_unref0 (_tmp52_);
		_g_object_unref0 (source);
		_g_object_unref0 (fullPath);
		_g_free0 (file);
		_g_free0 (_tmp24_);
		_g_free0 (path);
		_g_free0 (projectName);
		_g_free0 (projectNamespace);
		_g_free0 (solutionpath);
	}
	goto __finally6;
	__catch6_g_error:
	{
		GError* e = NULL;
		GtkMessageDialog* messagedialog = NULL;
		GError* _tmp103_;
		const gchar* _tmp104_;
		GtkMessageDialog* _tmp105_;
		GtkMessageDialog* _tmp106_;
		GtkMessageDialog* _tmp107_;
		e = _inner_error0_;
		_inner_error0_ = NULL;
		_tmp103_ = e;
		_tmp104_ = _tmp103_->message;
		_tmp105_ = (GtkMessageDialog*) gtk_message_dialog_new (NULL, GTK_DIALOG_MODAL, GTK_MESSAGE_ERROR, GTK_BUTTONS_OK, "%s", _tmp104_);
		g_object_ref_sink (_tmp105_);
		messagedialog = _tmp105_;
		_tmp106_ = messagedialog;
		gtk_dialog_run ((GtkDialog*) _tmp106_);
		_tmp107_ = messagedialog;
		gtk_widget_destroy ((GtkWidget*) _tmp107_);
		_g_object_unref0 (messagedialog);
		_g_error_free0 (e);
	}
	__finally6:
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return;
	}
}

static void
vala_develop_source_create_file_class_init (valaDevelopSourceCreateFileClass * klass,
                                            gpointer klass_data)
{
	vala_develop_source_create_file_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &valaDevelopSourceCreateFile_private_offset);
	G_OBJECT_CLASS (klass)->finalize = vala_develop_source_create_file_finalize;
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/valaDevelop/newSource.glade");
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "sourceGroup", FALSE, valaDevelopSourceCreateFile_private_offset + G_STRUCT_OFFSET (valaDevelopSourceCreateFilePrivate, sourceGroup));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "sourceDescription", FALSE, valaDevelopSourceCreateFile_private_offset + G_STRUCT_OFFSET (valaDevelopSourceCreateFilePrivate, sourceDescription));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "sourceName", FALSE, valaDevelopSourceCreateFile_private_offset + G_STRUCT_OFFSET (valaDevelopSourceCreateFilePrivate, sourceName));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "accept", FALSE, valaDevelopSourceCreateFile_private_offset + G_STRUCT_OFFSET (valaDevelopSourceCreateFilePrivate, accept));
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "OnAccept", G_CALLBACK(_vala_develop_source_create_file_OnAccept_gtk_button_clicked));
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "OnCancel", G_CALLBACK(_vala_develop_source_create_file_OnCancel_gtk_button_clicked));
}

static void
vala_develop_source_create_file_instance_init (valaDevelopSourceCreateFile * self,
                                               gpointer klass)
{
	self->priv = vala_develop_source_create_file_get_instance_private (self);
	gtk_widget_init_template (GTK_WIDGET (self));
}

static void
vala_develop_source_create_file_finalize (GObject * obj)
{
	valaDevelopSourceCreateFile * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALA_DEVELOP_TYPE_SOURCE_CREATE_FILE, valaDevelopSourceCreateFile);
	_g_object_unref0 (self->priv->sourceGroup);
	_g_object_unref0 (self->priv->sourceDescription);
	_g_object_unref0 (self->priv->sourceName);
	_g_object_unref0 (self->priv->accept);
	_g_object_unref0 (self->priv->_parent);
	G_OBJECT_CLASS (vala_develop_source_create_file_parent_class)->finalize (obj);
}

GType
vala_develop_source_create_file_get_type (void)
{
	static volatile gsize vala_develop_source_create_file_type_id__volatile = 0;
	if (g_once_init_enter (&vala_develop_source_create_file_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (valaDevelopSourceCreateFileClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_develop_source_create_file_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (valaDevelopSourceCreateFile), 0, (GInstanceInitFunc) vala_develop_source_create_file_instance_init, NULL };
		GType vala_develop_source_create_file_type_id;
		vala_develop_source_create_file_type_id = g_type_register_static (gtk_dialog_get_type (), "valaDevelopSourceCreateFile", &g_define_type_info, 0);
		valaDevelopSourceCreateFile_private_offset = g_type_add_instance_private (vala_develop_source_create_file_type_id, sizeof (valaDevelopSourceCreateFilePrivate));
		g_once_init_leave (&vala_develop_source_create_file_type_id__volatile, vala_develop_source_create_file_type_id);
	}
	return vala_develop_source_create_file_type_id__volatile;
}

