/* tab_header.c generated by valac UNKNOWN, the Vala compiler
 * generated from tab_header.vala, do not modify */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gdk/gdk.h>

#define VALA_DEVELOP_TYPE_TAB_HEADER (vala_develop_tab_header_get_type ())
#define VALA_DEVELOP_TAB_HEADER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_TAB_HEADER, valaDevelopTabHeader))
#define VALA_DEVELOP_TAB_HEADER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_TAB_HEADER, valaDevelopTabHeaderClass))
#define VALA_DEVELOP_IS_TAB_HEADER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_TAB_HEADER))
#define VALA_DEVELOP_IS_TAB_HEADER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_TAB_HEADER))
#define VALA_DEVELOP_TAB_HEADER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_TAB_HEADER, valaDevelopTabHeaderClass))

typedef struct _valaDevelopTabHeader valaDevelopTabHeader;
typedef struct _valaDevelopTabHeaderClass valaDevelopTabHeaderClass;
typedef struct _valaDevelopTabHeaderPrivate valaDevelopTabHeaderPrivate;

#define VALA_DEVELOP_TYPE_MAIN_PANED (vala_develop_main_paned_get_type ())
#define VALA_DEVELOP_MAIN_PANED(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_MAIN_PANED, valaDevelopMainPaned))
#define VALA_DEVELOP_MAIN_PANED_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_MAIN_PANED, valaDevelopMainPanedClass))
#define VALA_DEVELOP_IS_MAIN_PANED(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_MAIN_PANED))
#define VALA_DEVELOP_IS_MAIN_PANED_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_MAIN_PANED))
#define VALA_DEVELOP_MAIN_PANED_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_MAIN_PANED, valaDevelopMainPanedClass))

typedef struct _valaDevelopMainPaned valaDevelopMainPaned;
typedef struct _valaDevelopMainPanedClass valaDevelopMainPanedClass;
enum  {
	VALA_DEVELOP_TAB_HEADER_0_PROPERTY,
	VALA_DEVELOP_TAB_HEADER_LABEL_PROPERTY,
	VALA_DEVELOP_TAB_HEADER_FULL_PATH_PROPERTY,
	VALA_DEVELOP_TAB_HEADER_ACTIVE_PROPERTY,
	VALA_DEVELOP_TAB_HEADER_IMAGE_PROPERTY,
	VALA_DEVELOP_TAB_HEADER_NUM_PROPERTIES
};
static GParamSpec* vala_develop_tab_header_properties[VALA_DEVELOP_TAB_HEADER_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
enum  {
	VALA_DEVELOP_TAB_HEADER_CLOSE_CLICKED_SIGNAL,
	VALA_DEVELOP_TAB_HEADER_NUM_SIGNALS
};
static guint vala_develop_tab_header_signals[VALA_DEVELOP_TAB_HEADER_NUM_SIGNALS] = {0};

struct _valaDevelopTabHeader {
	GtkEventBox parent_instance;
	valaDevelopTabHeaderPrivate * priv;
};

struct _valaDevelopTabHeaderClass {
	GtkEventBoxClass parent_class;
};

struct _valaDevelopTabHeaderPrivate {
	GtkBox* _box;
	GtkLabel* _label;
	gboolean _modified;
	valaDevelopMainPaned* _parent;
	gchar* _full_path;
	gboolean _active;
	GtkImage* _image;
};

static gint valaDevelopTabHeader_private_offset;
static gpointer vala_develop_tab_header_parent_class = NULL;

GType vala_develop_tab_header_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (valaDevelopTabHeader, g_object_unref)
GType vala_develop_main_paned_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (valaDevelopMainPaned, g_object_unref)
valaDevelopTabHeader* vala_develop_tab_header_new (valaDevelopMainPaned* parent,
                                                   const gchar* text,
                                                   const gchar* fullPath);
valaDevelopTabHeader* vala_develop_tab_header_construct (GType object_type,
                                                         valaDevelopMainPaned* parent,
                                                         const gchar* text,
                                                         const gchar* fullPath);
static void vala_develop_tab_header_set_full_path (valaDevelopTabHeader* self,
                                            const gchar* value);
GdkPixbuf* vala_develop_globals_get_CloseImage (void);
static void vala_develop_tab_header_set_image (valaDevelopTabHeader* self,
                                        GtkImage* value);
GtkImage* vala_develop_tab_header_get_image (valaDevelopTabHeader* self);
static gboolean __lambda7_ (valaDevelopTabHeader* self,
                     GdkEventButton* evnt);
static gboolean ___lambda7__gtk_widget_button_release_event (GtkWidget* _sender,
                                                      GdkEventButton* event,
                                                      gpointer self);
static gboolean __lambda8_ (valaDevelopTabHeader* self,
                     gint x,
                     gint y,
                     gboolean keyboard_tooltip,
                     GtkTooltip* tooltip);
const gchar* vala_develop_tab_header_get_full_path (valaDevelopTabHeader* self);
static gboolean ___lambda8__gtk_widget_query_tooltip (GtkWidget* _sender,
                                               gint x,
                                               gint y,
                                               gboolean keyboard_tooltip,
                                               GtkTooltip* tooltip,
                                               gpointer self);
static gboolean __lambda9_ (valaDevelopTabHeader* self,
                     GdkEventCrossing* evnt);
static gboolean ___lambda9__gtk_widget_enter_notify_event (GtkWidget* _sender,
                                                    GdkEventCrossing* event,
                                                    gpointer self);
static gboolean __lambda10_ (valaDevelopTabHeader* self,
                      GdkEventCrossing* evnt);
GdkPixbuf* vala_develop_globals_get_ModifiedImage (void);
gboolean vala_develop_tab_header_get_active (valaDevelopTabHeader* self);
GdkPixbuf* vala_develop_globals_get_EmptyImage (void);
static gboolean ___lambda10__gtk_widget_leave_notify_event (GtkWidget* _sender,
                                                     GdkEventCrossing* event,
                                                     gpointer self);
gchar* vala_develop_tab_header_get_text (valaDevelopTabHeader* self);
void vala_develop_tab_header_UpdateModify (valaDevelopTabHeader* self,
                                           gboolean modified);
const gchar* vala_develop_tab_header_get_label (valaDevelopTabHeader* self);
void vala_develop_tab_header_set_active (valaDevelopTabHeader* self,
                                         gboolean value);
static void g_cclosure_user_marshal_VOID__OBJECT_BOXED (GClosure * closure,
                                                 GValue * return_value,
                                                 guint n_param_values,
                                                 const GValue * param_values,
                                                 gpointer invocation_hint,
                                                 gpointer marshal_data);
static void vala_develop_tab_header_finalize (GObject * obj);
static void _vala_vala_develop_tab_header_get_property (GObject * object,
                                                 guint property_id,
                                                 GValue * value,
                                                 GParamSpec * pspec);
static void _vala_vala_develop_tab_header_set_property (GObject * object,
                                                 guint property_id,
                                                 const GValue * value,
                                                 GParamSpec * pspec);

static inline gpointer
vala_develop_tab_header_get_instance_private (valaDevelopTabHeader* self)
{
	return G_STRUCT_MEMBER_P (self, valaDevelopTabHeader_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

static const gchar*
string_to_string (const gchar* self)
{
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}

static gboolean
__lambda7_ (valaDevelopTabHeader* self,
            GdkEventButton* evnt)
{
	gboolean result = FALSE;
	g_return_val_if_fail (evnt != NULL, FALSE);
	g_signal_emit (self, vala_develop_tab_header_signals[VALA_DEVELOP_TAB_HEADER_CLOSE_CLICKED_SIGNAL], 0, self, evnt);
	result = FALSE;
	return result;
}

static gboolean
___lambda7__gtk_widget_button_release_event (GtkWidget* _sender,
                                             GdkEventButton* event,
                                             gpointer self)
{
	gboolean result;
	result = __lambda7_ ((valaDevelopTabHeader*) self, event);
	return result;
}

static gboolean
__lambda8_ (valaDevelopTabHeader* self,
            gint x,
            gint y,
            gboolean keyboard_tooltip,
            GtkTooltip* tooltip)
{
	gboolean result = FALSE;
	const gchar* _tmp0_;
	g_return_val_if_fail (tooltip != NULL, FALSE);
	_tmp0_ = self->priv->_full_path;
	gtk_tooltip_set_markup (tooltip, _tmp0_);
	result = TRUE;
	return result;
}

static gboolean
___lambda8__gtk_widget_query_tooltip (GtkWidget* _sender,
                                      gint x,
                                      gint y,
                                      gboolean keyboard_tooltip,
                                      GtkTooltip* tooltip,
                                      gpointer self)
{
	gboolean result;
	result = __lambda8_ ((valaDevelopTabHeader*) self, x, y, keyboard_tooltip, tooltip);
	return result;
}

static gboolean
__lambda9_ (valaDevelopTabHeader* self,
            GdkEventCrossing* evnt)
{
	gboolean result = FALSE;
	GtkImage* _tmp0_;
	GdkPixbuf* _tmp1_;
	GdkPixbuf* _tmp2_;
	g_return_val_if_fail (evnt != NULL, FALSE);
	_tmp0_ = self->priv->_image;
	_tmp1_ = vala_develop_globals_get_CloseImage ();
	_tmp2_ = _tmp1_;
	g_object_set (_tmp0_, "pixbuf", _tmp2_, NULL);
	result = FALSE;
	return result;
}

static gboolean
___lambda9__gtk_widget_enter_notify_event (GtkWidget* _sender,
                                           GdkEventCrossing* event,
                                           gpointer self)
{
	gboolean result;
	result = __lambda9_ ((valaDevelopTabHeader*) self, event);
	return result;
}

static gboolean
__lambda10_ (valaDevelopTabHeader* self,
             GdkEventCrossing* evnt)
{
	gboolean result = FALSE;
	g_return_val_if_fail (evnt != NULL, FALSE);
	if (self->priv->_modified) {
		GtkImage* _tmp0_;
		GdkPixbuf* _tmp1_;
		GdkPixbuf* _tmp2_;
		_tmp0_ = self->priv->_image;
		_tmp1_ = vala_develop_globals_get_ModifiedImage ();
		_tmp2_ = _tmp1_;
		g_object_set (_tmp0_, "pixbuf", _tmp2_, NULL);
	} else {
		GdkPixbuf* _tmp3_ = NULL;
		gboolean _tmp4_;
		GtkImage* _tmp9_;
		_tmp4_ = self->priv->_active;
		if (_tmp4_) {
			GdkPixbuf* _tmp5_;
			GdkPixbuf* _tmp6_;
			_tmp5_ = vala_develop_globals_get_CloseImage ();
			_tmp6_ = _tmp5_;
			_tmp3_ = _tmp6_;
		} else {
			GdkPixbuf* _tmp7_;
			GdkPixbuf* _tmp8_;
			_tmp7_ = vala_develop_globals_get_EmptyImage ();
			_tmp8_ = _tmp7_;
			_tmp3_ = _tmp8_;
		}
		_tmp9_ = self->priv->_image;
		g_object_set (_tmp9_, "pixbuf", _tmp3_, NULL);
	}
	result = FALSE;
	return result;
}

static gboolean
___lambda10__gtk_widget_leave_notify_event (GtkWidget* _sender,
                                            GdkEventCrossing* event,
                                            gpointer self)
{
	gboolean result;
	result = __lambda10_ ((valaDevelopTabHeader*) self, event);
	return result;
}

valaDevelopTabHeader*
vala_develop_tab_header_construct (GType object_type,
                                   valaDevelopMainPaned* parent,
                                   const gchar* text,
                                   const gchar* fullPath)
{
	valaDevelopTabHeader * self = NULL;
	valaDevelopMainPaned* _tmp0_;
	GtkLabel* _tmp1_;
	GtkLabel* _tmp2_;
	GtkLabel* _tmp3_;
	GtkLabel* _tmp4_;
	GtkLabel* _tmp5_;
	const gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	GdkPixbuf* _tmp9_;
	GdkPixbuf* _tmp10_;
	GtkImage* _tmp11_;
	GtkImage* _tmp12_;
	GtkBox* _tmp13_;
	GtkBox* _tmp14_;
	GtkBox* _tmp15_;
	GtkLabel* _tmp16_;
	GtkBox* _tmp17_;
	GtkImage* _tmp18_;
	GtkBox* _tmp19_;
	GtkBox* _tmp20_;
	g_return_val_if_fail (parent != NULL, NULL);
	g_return_val_if_fail (text != NULL, NULL);
	g_return_val_if_fail (fullPath != NULL, NULL);
	self = (valaDevelopTabHeader*) g_object_new (object_type, NULL);
	_tmp0_ = _g_object_ref0 (parent);
	_g_object_unref0 (self->priv->_parent);
	self->priv->_parent = _tmp0_;
	vala_develop_tab_header_set_full_path (self, fullPath);
	_tmp1_ = (GtkLabel*) gtk_label_new (text);
	g_object_ref_sink (_tmp1_);
	_g_object_unref0 (self->priv->_label);
	self->priv->_label = _tmp1_;
	_tmp2_ = self->priv->_label;
	gtk_widget_set_name ((GtkWidget*) _tmp2_, "vdHeaderLabel");
	_tmp3_ = self->priv->_label;
	gtk_label_set_xalign (_tmp3_, (gfloat) 0);
	_tmp4_ = self->priv->_label;
	gtk_label_set_use_markup (_tmp4_, TRUE);
	_tmp5_ = self->priv->_label;
	_tmp6_ = string_to_string (text);
	_tmp7_ = g_strconcat ("<span size='smaller' weight='light'>", _tmp6_, "</span>", NULL);
	_tmp8_ = _tmp7_;
	gtk_label_set_markup (_tmp5_, _tmp8_);
	_g_free0 (_tmp8_);
	_tmp9_ = vala_develop_globals_get_CloseImage ();
	_tmp10_ = _tmp9_;
	_tmp11_ = (GtkImage*) gtk_image_new_from_pixbuf (_tmp10_);
	g_object_ref_sink (_tmp11_);
	_tmp12_ = _tmp11_;
	vala_develop_tab_header_set_image (self, _tmp12_);
	_g_object_unref0 (_tmp12_);
	_tmp13_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 10);
	g_object_ref_sink (_tmp13_);
	_g_object_unref0 (self->priv->_box);
	self->priv->_box = _tmp13_;
	_tmp14_ = self->priv->_box;
	gtk_widget_set_has_tooltip ((GtkWidget*) _tmp14_, TRUE);
	_tmp15_ = self->priv->_box;
	_tmp16_ = self->priv->_label;
	gtk_box_pack_start (_tmp15_, (GtkWidget*) _tmp16_, FALSE, FALSE, (guint) 0);
	_tmp17_ = self->priv->_box;
	_tmp18_ = self->priv->_image;
	gtk_box_pack_start (_tmp17_, (GtkWidget*) _tmp18_, FALSE, FALSE, (guint) 0);
	_tmp19_ = self->priv->_box;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp19_);
	g_signal_connect_object ((GtkWidget*) self, "button-release-event", (GCallback) ___lambda7__gtk_widget_button_release_event, self, 0);
	_tmp20_ = self->priv->_box;
	g_signal_connect_object ((GtkWidget*) _tmp20_, "query-tooltip", (GCallback) ___lambda8__gtk_widget_query_tooltip, self, 0);
	g_signal_connect_object ((GtkWidget*) self, "enter-notify-event", (GCallback) ___lambda9__gtk_widget_enter_notify_event, self, 0);
	g_signal_connect_object ((GtkWidget*) self, "leave-notify-event", (GCallback) ___lambda10__gtk_widget_leave_notify_event, self, 0);
	gtk_widget_show_all ((GtkWidget*) self);
	return self;
}

valaDevelopTabHeader*
vala_develop_tab_header_new (valaDevelopMainPaned* parent,
                             const gchar* text,
                             const gchar* fullPath)
{
	return vala_develop_tab_header_construct (VALA_DEVELOP_TYPE_TAB_HEADER, parent, text, fullPath);
}

gchar*
vala_develop_tab_header_get_text (valaDevelopTabHeader* self)
{
	gchar* result = NULL;
	GtkLabel* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_label;
	_tmp1_ = gtk_label_get_text (_tmp0_);
	_tmp2_ = g_strdup (_tmp1_);
	result = _tmp2_;
	return result;
}

void
vala_develop_tab_header_UpdateModify (valaDevelopTabHeader* self,
                                      gboolean modified)
{
	GdkPixbuf* _tmp0_ = NULL;
	GtkImage* _tmp9_;
	g_return_if_fail (self != NULL);
	self->priv->_modified = modified;
	if (modified) {
		GdkPixbuf* _tmp1_;
		GdkPixbuf* _tmp2_;
		_tmp1_ = vala_develop_globals_get_ModifiedImage ();
		_tmp2_ = _tmp1_;
		_tmp0_ = _tmp2_;
	} else {
		GdkPixbuf* _tmp3_ = NULL;
		gboolean _tmp4_;
		_tmp4_ = self->priv->_active;
		if (_tmp4_) {
			GdkPixbuf* _tmp5_;
			GdkPixbuf* _tmp6_;
			_tmp5_ = vala_develop_globals_get_CloseImage ();
			_tmp6_ = _tmp5_;
			_tmp3_ = _tmp6_;
		} else {
			GdkPixbuf* _tmp7_;
			GdkPixbuf* _tmp8_;
			_tmp7_ = vala_develop_globals_get_EmptyImage ();
			_tmp8_ = _tmp7_;
			_tmp3_ = _tmp8_;
		}
		_tmp0_ = _tmp3_;
	}
	_tmp9_ = self->priv->_image;
	g_object_set (_tmp9_, "pixbuf", _tmp0_, NULL);
}

const gchar*
vala_develop_tab_header_get_label (valaDevelopTabHeader* self)
{
	const gchar* result;
	GtkLabel* _tmp0_;
	const gchar* _tmp1_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_label;
	_tmp1_ = gtk_label_get_text (_tmp0_);
	result = _tmp1_;
	return result;
}

const gchar*
vala_develop_tab_header_get_full_path (valaDevelopTabHeader* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_full_path;
	result = _tmp0_;
	return result;
}

static void
vala_develop_tab_header_set_full_path (valaDevelopTabHeader* self,
                                       const gchar* value)
{
	g_return_if_fail (self != NULL);
	if (g_strcmp0 (value, vala_develop_tab_header_get_full_path (self)) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_full_path);
		self->priv->_full_path = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, vala_develop_tab_header_properties[VALA_DEVELOP_TAB_HEADER_FULL_PATH_PROPERTY]);
	}
}

gboolean
vala_develop_tab_header_get_active (valaDevelopTabHeader* self)
{
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_active;
	return result;
}

void
vala_develop_tab_header_set_active (valaDevelopTabHeader* self,
                                    gboolean value)
{
	g_return_if_fail (self != NULL);
	if (vala_develop_tab_header_get_active (self) != value) {
		self->priv->_active = value;
		g_object_notify_by_pspec ((GObject *) self, vala_develop_tab_header_properties[VALA_DEVELOP_TAB_HEADER_ACTIVE_PROPERTY]);
	}
}

GtkImage*
vala_develop_tab_header_get_image (valaDevelopTabHeader* self)
{
	GtkImage* result;
	GtkImage* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_image;
	result = _tmp0_;
	return result;
}

static void
vala_develop_tab_header_set_image (valaDevelopTabHeader* self,
                                   GtkImage* value)
{
	g_return_if_fail (self != NULL);
	if (vala_develop_tab_header_get_image (self) != value) {
		GtkImage* _tmp0_;
		_tmp0_ = _g_object_ref0 (value);
		_g_object_unref0 (self->priv->_image);
		self->priv->_image = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, vala_develop_tab_header_properties[VALA_DEVELOP_TAB_HEADER_IMAGE_PROPERTY]);
	}
}

static void
g_cclosure_user_marshal_VOID__OBJECT_BOXED (GClosure * closure,
                                            GValue * return_value,
                                            guint n_param_values,
                                            const GValue * param_values,
                                            gpointer invocation_hint,
                                            gpointer marshal_data)
{
	typedef void (*GMarshalFunc_VOID__OBJECT_BOXED) (gpointer data1, gpointer arg_1, gpointer arg_2, gpointer data2);
	register GMarshalFunc_VOID__OBJECT_BOXED callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 3);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__OBJECT_BOXED) (marshal_data ? marshal_data : cc->callback);
	callback (data1, g_value_get_object (param_values + 1), g_value_get_boxed (param_values + 2), data2);
}

static void
vala_develop_tab_header_class_init (valaDevelopTabHeaderClass * klass,
                                    gpointer klass_data)
{
	vala_develop_tab_header_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &valaDevelopTabHeader_private_offset);
	G_OBJECT_CLASS (klass)->get_property = _vala_vala_develop_tab_header_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_vala_develop_tab_header_set_property;
	G_OBJECT_CLASS (klass)->finalize = vala_develop_tab_header_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), VALA_DEVELOP_TAB_HEADER_LABEL_PROPERTY, vala_develop_tab_header_properties[VALA_DEVELOP_TAB_HEADER_LABEL_PROPERTY] = g_param_spec_string ("label", "label", "label", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), VALA_DEVELOP_TAB_HEADER_FULL_PATH_PROPERTY, vala_develop_tab_header_properties[VALA_DEVELOP_TAB_HEADER_FULL_PATH_PROPERTY] = g_param_spec_string ("full-path", "full-path", "full-path", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), VALA_DEVELOP_TAB_HEADER_ACTIVE_PROPERTY, vala_develop_tab_header_properties[VALA_DEVELOP_TAB_HEADER_ACTIVE_PROPERTY] = g_param_spec_boolean ("active", "active", "active", FALSE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), VALA_DEVELOP_TAB_HEADER_IMAGE_PROPERTY, vala_develop_tab_header_properties[VALA_DEVELOP_TAB_HEADER_IMAGE_PROPERTY] = g_param_spec_object ("image", "image", "image", gtk_image_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
	vala_develop_tab_header_signals[VALA_DEVELOP_TAB_HEADER_CLOSE_CLICKED_SIGNAL] = g_signal_new ("close-clicked", VALA_DEVELOP_TYPE_TAB_HEADER, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__OBJECT_BOXED, G_TYPE_NONE, 2, VALA_DEVELOP_TYPE_TAB_HEADER, gdk_event_get_type ());
}

static void
vala_develop_tab_header_instance_init (valaDevelopTabHeader * self,
                                       gpointer klass)
{
	self->priv = vala_develop_tab_header_get_instance_private (self);
}

static void
vala_develop_tab_header_finalize (GObject * obj)
{
	valaDevelopTabHeader * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALA_DEVELOP_TYPE_TAB_HEADER, valaDevelopTabHeader);
	_g_object_unref0 (self->priv->_box);
	_g_object_unref0 (self->priv->_label);
	_g_object_unref0 (self->priv->_parent);
	_g_free0 (self->priv->_full_path);
	_g_object_unref0 (self->priv->_image);
	G_OBJECT_CLASS (vala_develop_tab_header_parent_class)->finalize (obj);
}

GType
vala_develop_tab_header_get_type (void)
{
	static volatile gsize vala_develop_tab_header_type_id__volatile = 0;
	if (g_once_init_enter (&vala_develop_tab_header_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (valaDevelopTabHeaderClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_develop_tab_header_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (valaDevelopTabHeader), 0, (GInstanceInitFunc) vala_develop_tab_header_instance_init, NULL };
		GType vala_develop_tab_header_type_id;
		vala_develop_tab_header_type_id = g_type_register_static (gtk_event_box_get_type (), "valaDevelopTabHeader", &g_define_type_info, 0);
		valaDevelopTabHeader_private_offset = g_type_add_instance_private (vala_develop_tab_header_type_id, sizeof (valaDevelopTabHeaderPrivate));
		g_once_init_leave (&vala_develop_tab_header_type_id__volatile, vala_develop_tab_header_type_id);
	}
	return vala_develop_tab_header_type_id__volatile;
}

static void
_vala_vala_develop_tab_header_get_property (GObject * object,
                                            guint property_id,
                                            GValue * value,
                                            GParamSpec * pspec)
{
	valaDevelopTabHeader * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, VALA_DEVELOP_TYPE_TAB_HEADER, valaDevelopTabHeader);
	switch (property_id) {
		case VALA_DEVELOP_TAB_HEADER_LABEL_PROPERTY:
		g_value_set_string (value, vala_develop_tab_header_get_label (self));
		break;
		case VALA_DEVELOP_TAB_HEADER_FULL_PATH_PROPERTY:
		g_value_set_string (value, vala_develop_tab_header_get_full_path (self));
		break;
		case VALA_DEVELOP_TAB_HEADER_ACTIVE_PROPERTY:
		g_value_set_boolean (value, vala_develop_tab_header_get_active (self));
		break;
		case VALA_DEVELOP_TAB_HEADER_IMAGE_PROPERTY:
		g_value_set_object (value, vala_develop_tab_header_get_image (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_vala_develop_tab_header_set_property (GObject * object,
                                            guint property_id,
                                            const GValue * value,
                                            GParamSpec * pspec)
{
	valaDevelopTabHeader * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, VALA_DEVELOP_TYPE_TAB_HEADER, valaDevelopTabHeader);
	switch (property_id) {
		case VALA_DEVELOP_TAB_HEADER_FULL_PATH_PROPERTY:
		vala_develop_tab_header_set_full_path (self, g_value_get_string (value));
		break;
		case VALA_DEVELOP_TAB_HEADER_ACTIVE_PROPERTY:
		vala_develop_tab_header_set_active (self, g_value_get_boolean (value));
		break;
		case VALA_DEVELOP_TAB_HEADER_IMAGE_PROPERTY:
		vala_develop_tab_header_set_image (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

