/* wrong_location.c generated by valac 0.44.0, the Vala compiler
 * generated from wrong_location.vala, do not modify */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <glib.h>

#define VALA_DEVELOP_TYPE_WRONG_LOCATION (vala_develop_wrong_location_get_type ())
#define VALA_DEVELOP_WRONG_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), VALA_DEVELOP_TYPE_WRONG_LOCATION, valaDevelopWrongLocation))
#define VALA_DEVELOP_WRONG_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), VALA_DEVELOP_TYPE_WRONG_LOCATION, valaDevelopWrongLocationClass))
#define VALA_DEVELOP_IS_WRONG_LOCATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), VALA_DEVELOP_TYPE_WRONG_LOCATION))
#define VALA_DEVELOP_IS_WRONG_LOCATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), VALA_DEVELOP_TYPE_WRONG_LOCATION))
#define VALA_DEVELOP_WRONG_LOCATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), VALA_DEVELOP_TYPE_WRONG_LOCATION, valaDevelopWrongLocationClass))

typedef struct _valaDevelopWrongLocation valaDevelopWrongLocation;
typedef struct _valaDevelopWrongLocationClass valaDevelopWrongLocationClass;
typedef struct _valaDevelopWrongLocationPrivate valaDevelopWrongLocationPrivate;
enum  {
	VALA_DEVELOP_WRONG_LOCATION_0_PROPERTY,
	VALA_DEVELOP_WRONG_LOCATION_IMPORT_OPTION_PROPERTY,
	VALA_DEVELOP_WRONG_LOCATION_SAME4_ALL_PROPERTY,
	VALA_DEVELOP_WRONG_LOCATION_SAME4_ALL_VISIBLE_PROPERTY,
	VALA_DEVELOP_WRONG_LOCATION_NUM_PROPERTIES
};
static GParamSpec* vala_develop_wrong_location_properties[VALA_DEVELOP_WRONG_LOCATION_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef enum  {
	VALA_DEVELOP_IMPORT_OPTIONS_Use,
	VALA_DEVELOP_IMPORT_OPTIONS_Copy,
	VALA_DEVELOP_IMPORT_OPTIONS_Move,
	VALA_DEVELOP_IMPORT_OPTIONS_Link,
	VALA_DEVELOP_IMPORT_OPTIONS_Cancel
} valaDevelopImportOptions;

#define VALA_DEVELOP_TYPE_IMPORT_OPTIONS (vala_develop_import_options_get_type ())

struct _valaDevelopWrongLocation {
	GtkMessageDialog parent_instance;
	valaDevelopWrongLocationPrivate * priv;
};

struct _valaDevelopWrongLocationClass {
	GtkMessageDialogClass parent_class;
};

struct _valaDevelopWrongLocationPrivate {
	GtkRadioButton* _copy;
	GtkRadioButton* _move;
	GtkRadioButton* _link;
	GtkCheckButton* _same4all;
};

static gint valaDevelopWrongLocation_private_offset;
static gpointer vala_develop_wrong_location_parent_class = NULL;

GType vala_develop_wrong_location_get_type (void) G_GNUC_CONST;
valaDevelopWrongLocation* vala_develop_wrong_location_new (GtkWidget* parent);
valaDevelopWrongLocation* vala_develop_wrong_location_construct (GType object_type,
                                                                 GtkWidget* parent);
GType vala_develop_import_options_get_type (void) G_GNUC_CONST;
valaDevelopImportOptions vala_develop_wrong_location_get_ImportOption (valaDevelopWrongLocation* self);
gboolean vala_develop_wrong_location_get_Same4All (valaDevelopWrongLocation* self);
void vala_develop_wrong_location_set_Same4AllVisible (valaDevelopWrongLocation* self,
                                                      gboolean value);
static void vala_develop_wrong_location_finalize (GObject * obj);
static void _vala_vala_develop_wrong_location_get_property (GObject * object,
                                                     guint property_id,
                                                     GValue * value,
                                                     GParamSpec * pspec);
static void _vala_vala_develop_wrong_location_set_property (GObject * object,
                                                     guint property_id,
                                                     const GValue * value,
                                                     GParamSpec * pspec);

static inline gpointer
vala_develop_wrong_location_get_instance_private (valaDevelopWrongLocation* self)
{
	return G_STRUCT_MEMBER_P (self, valaDevelopWrongLocation_private_offset);
}

valaDevelopWrongLocation*
vala_develop_wrong_location_construct (GType object_type,
                                       GtkWidget* parent)
{
	valaDevelopWrongLocation * self = NULL;
	GtkWidget* _tmp0_;
	g_return_val_if_fail (parent != NULL, NULL);
	self = (valaDevelopWrongLocation*) g_object_new (object_type, NULL);
	_tmp0_ = gtk_widget_get_toplevel (parent);
	gtk_window_set_transient_for ((GtkWindow*) self, G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, gtk_window_get_type (), GtkWindow));
	gtk_widget_set_visible ((GtkWidget*) self, FALSE);
	return self;
}

valaDevelopWrongLocation*
vala_develop_wrong_location_new (GtkWidget* parent)
{
	return vala_develop_wrong_location_construct (VALA_DEVELOP_TYPE_WRONG_LOCATION, parent);
}

valaDevelopImportOptions
vala_develop_wrong_location_get_ImportOption (valaDevelopWrongLocation* self)
{
	valaDevelopImportOptions result;
	GtkRadioButton* _tmp0_;
	gboolean _tmp1_;
	gboolean _tmp2_;
	GtkRadioButton* _tmp3_;
	gboolean _tmp4_;
	gboolean _tmp5_;
	GtkRadioButton* _tmp6_;
	gboolean _tmp7_;
	gboolean _tmp8_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_copy;
	_tmp1_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_) {
		result = VALA_DEVELOP_IMPORT_OPTIONS_Copy;
		return result;
	}
	_tmp3_ = self->priv->_move;
	_tmp4_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp3_);
	_tmp5_ = _tmp4_;
	if (_tmp5_) {
		result = VALA_DEVELOP_IMPORT_OPTIONS_Move;
		return result;
	}
	_tmp6_ = self->priv->_link;
	_tmp7_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp6_);
	_tmp8_ = _tmp7_;
	if (_tmp8_) {
		result = VALA_DEVELOP_IMPORT_OPTIONS_Link;
		return result;
	}
	result = VALA_DEVELOP_IMPORT_OPTIONS_Use;
	return result;
}

gboolean
vala_develop_wrong_location_get_Same4All (valaDevelopWrongLocation* self)
{
	gboolean result;
	GtkCheckButton* _tmp0_;
	gboolean _tmp1_;
	gboolean _tmp2_;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_same4all;
	_tmp1_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp0_);
	_tmp2_ = _tmp1_;
	result = _tmp2_;
	return result;
}

void
vala_develop_wrong_location_set_Same4AllVisible (valaDevelopWrongLocation* self,
                                                 gboolean value)
{
	GtkCheckButton* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_same4all;
	gtk_widget_set_visible ((GtkWidget*) _tmp0_, value);
	g_object_notify_by_pspec ((GObject *) self, vala_develop_wrong_location_properties[VALA_DEVELOP_WRONG_LOCATION_SAME4_ALL_VISIBLE_PROPERTY]);
}

static void
vala_develop_wrong_location_class_init (valaDevelopWrongLocationClass * klass,
                                        gpointer klass_data)
{
	vala_develop_wrong_location_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &valaDevelopWrongLocation_private_offset);
	G_OBJECT_CLASS (klass)->get_property = _vala_vala_develop_wrong_location_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_vala_develop_wrong_location_set_property;
	G_OBJECT_CLASS (klass)->finalize = vala_develop_wrong_location_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), VALA_DEVELOP_WRONG_LOCATION_IMPORT_OPTION_PROPERTY, vala_develop_wrong_location_properties[VALA_DEVELOP_WRONG_LOCATION_IMPORT_OPTION_PROPERTY] = g_param_spec_enum ("ImportOption", "ImportOption", "ImportOption", VALA_DEVELOP_TYPE_IMPORT_OPTIONS, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), VALA_DEVELOP_WRONG_LOCATION_SAME4_ALL_PROPERTY, vala_develop_wrong_location_properties[VALA_DEVELOP_WRONG_LOCATION_SAME4_ALL_PROPERTY] = g_param_spec_boolean ("Same4All", "Same4All", "Same4All", FALSE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), VALA_DEVELOP_WRONG_LOCATION_SAME4_ALL_VISIBLE_PROPERTY, vala_develop_wrong_location_properties[VALA_DEVELOP_WRONG_LOCATION_SAME4_ALL_VISIBLE_PROPERTY] = g_param_spec_boolean ("Same4AllVisible", "Same4AllVisible", "Same4AllVisible", FALSE, G_PARAM_STATIC_STRINGS | G_PARAM_WRITABLE));
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/valaDevelop/wronglocation.glade");
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "_copy", FALSE, valaDevelopWrongLocation_private_offset + G_STRUCT_OFFSET (valaDevelopWrongLocationPrivate, _copy));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "_move", FALSE, valaDevelopWrongLocation_private_offset + G_STRUCT_OFFSET (valaDevelopWrongLocationPrivate, _move));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "_link", FALSE, valaDevelopWrongLocation_private_offset + G_STRUCT_OFFSET (valaDevelopWrongLocationPrivate, _link));
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "_same4all", FALSE, valaDevelopWrongLocation_private_offset + G_STRUCT_OFFSET (valaDevelopWrongLocationPrivate, _same4all));
}

static void
vala_develop_wrong_location_instance_init (valaDevelopWrongLocation * self,
                                           gpointer klass)
{
	self->priv = vala_develop_wrong_location_get_instance_private (self);
	gtk_widget_init_template (GTK_WIDGET (self));
}

static void
vala_develop_wrong_location_finalize (GObject * obj)
{
	valaDevelopWrongLocation * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, VALA_DEVELOP_TYPE_WRONG_LOCATION, valaDevelopWrongLocation);
	_g_object_unref0 (self->priv->_copy);
	_g_object_unref0 (self->priv->_move);
	_g_object_unref0 (self->priv->_link);
	_g_object_unref0 (self->priv->_same4all);
	G_OBJECT_CLASS (vala_develop_wrong_location_parent_class)->finalize (obj);
}

GType
vala_develop_wrong_location_get_type (void)
{
	static volatile gsize vala_develop_wrong_location_type_id__volatile = 0;
	if (g_once_init_enter (&vala_develop_wrong_location_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (valaDevelopWrongLocationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) vala_develop_wrong_location_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (valaDevelopWrongLocation), 0, (GInstanceInitFunc) vala_develop_wrong_location_instance_init, NULL };
		GType vala_develop_wrong_location_type_id;
		vala_develop_wrong_location_type_id = g_type_register_static (gtk_message_dialog_get_type (), "valaDevelopWrongLocation", &g_define_type_info, 0);
		valaDevelopWrongLocation_private_offset = g_type_add_instance_private (vala_develop_wrong_location_type_id, sizeof (valaDevelopWrongLocationPrivate));
		g_once_init_leave (&vala_develop_wrong_location_type_id__volatile, vala_develop_wrong_location_type_id);
	}
	return vala_develop_wrong_location_type_id__volatile;
}

static void
_vala_vala_develop_wrong_location_get_property (GObject * object,
                                                guint property_id,
                                                GValue * value,
                                                GParamSpec * pspec)
{
	valaDevelopWrongLocation * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, VALA_DEVELOP_TYPE_WRONG_LOCATION, valaDevelopWrongLocation);
	switch (property_id) {
		case VALA_DEVELOP_WRONG_LOCATION_IMPORT_OPTION_PROPERTY:
		g_value_set_enum (value, vala_develop_wrong_location_get_ImportOption (self));
		break;
		case VALA_DEVELOP_WRONG_LOCATION_SAME4_ALL_PROPERTY:
		g_value_set_boolean (value, vala_develop_wrong_location_get_Same4All (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_vala_develop_wrong_location_set_property (GObject * object,
                                                guint property_id,
                                                const GValue * value,
                                                GParamSpec * pspec)
{
	valaDevelopWrongLocation * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, VALA_DEVELOP_TYPE_WRONG_LOCATION, valaDevelopWrongLocation);
	switch (property_id) {
		case VALA_DEVELOP_WRONG_LOCATION_SAME4_ALL_VISIBLE_PROPERTY:
		vala_develop_wrong_location_set_Same4AllVisible (self, g_value_get_boolean (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

